### ISSUE TITLE
Watcher for Tomorrow / Hideaway does not put card in hand

### ISSUE THREAD

**Issue by VladFurman** [Card-Forge/forge#1005]
**Describe the bug**
Watcher for Tomorrow / Hideaway not working as intended.

**To Reproduce**
1. Cast Watcher for Tomorrow, exiling a card.
2. Watcher destroyed by damage on opponent's next turn.
3. Watcher's effect remains in command. Exiled card remains exiled.

**Expected behavior**
Watcher's effect triggers, putting card in exile into hand.

**Screenshots**
![image](https://user-images.githubusercontent.com/5605369/175893346-f55ecac7-842a-4b0d-ae16-33ce48395c3b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 21H2
 - Browser [e.g. chrome, safari] N/A
 - Version: 1.6.53

**Additional context**

**Comment by Hanmac** [comment]
watcher of tomorrow is known issue with "ExiledWith" which needs to be refactored in general

**Comment by Hanmac** [comment]
@tool4ever can you update the other cards that use ExileWith + Remember to use the ExiledWith Defined Cards method?

**Comment by tool4ever** [comment]
Yea
I'm trying to also fix #1122

do you have an idea for that?

I mean maybe there's a use case to have "ExiledWithOriginalSource" but it shouldn't be default?
