### ISSUE TITLE
Adventure Mode - Game Save/World Wide set or edition filter... not just a config file.

### ISSUE THREAD

**Issue by austeregrim** [Card-Forge/forge#1066]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I find cards or sets that really don't belong in normal gameplay in adventure mode.

**Describe the solution you'd like**
The ability to filter sets upon game world creation, instead of in a config file game wide.

**Describe alternatives you've considered**
Staring at the monitor until the pixels updated in a fashion I willed them to using only my mind... (it doesn't work.)

**Additional context**
I give you a heart in the discord if you do this.

For clarity; I'd like to see either a white list for sets at game/world creation, or the ability to create and manage planes in game (with whitelisting sets/editions), or the ability to edit and manage planes via configs (with ability to whitelist sets/editions). 
**NOT a universal filter for the entire game, and not a file that will be overwritten with an update which is how the current config file method is.**

**Comment by TrueFuFLeaderG** [comment]
It can be configured in config.json
made a wiki entry on how to [Configure-Planes](https://github.com/Card-Forge/forge/wiki/Configure-Planes)
What cards are you talking about? If it is editions like unset it would be easy to exclude those, but Commander cards for example are more difficult, I don't think that they have a property to filter them out.

**Comment by austeregrim** [comment]
Yeah, but the request is for specifically to have the settings editable in the start of the game and set per save. 
Or since you've got the config file as it is, should be able to add individual planes, or custom. I'd be happy to add core set planes to the config if it can be used to populate the plane selection at game start.

**Comment by austeregrim** [comment]
Especially with the trashcan editions coming out, I don't want to see fortnite cards ever...

**Comment by austeregrim** [comment]
There I updated my request to be clearer, I think it's time this gets added.

**Comment by austeregrim** [comment]
It can be plane based. But I'd like to have those planes editable in game, or at least the configs available so the planes cane be made and selected. That way I can start making planes either for myself or start contributing and make additional planes available. It's one of the major hurdles for me getting into adventure mode, there's just too many cards/sets/editions etc. where it would be nice to be able to flesh out a meta, in general, and then for each plane.

**Comment by austeregrim** [comment]
Right, I see I'm a dumb. I didn't realize the folder was the plane, not the entire game environment. Then I withdraw this request.
