### ISSUE TITLE
untilHostLeavesPlay must be done simultaneously

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1107]
> 610.3d If multiple one-shot effects are created this way immediately after one or more simultaneous
events, those one-shot effects are also simultaneous

> Example: Two Banisher Priests have each exiled a card. All creatures are destroyed at the same time by Day of Judgment. The two exiled cards are returned to the battlefield at the same time.

**Comment by tool4ever** [comment]
What about for now give Game a global `CardZoneTable untilHostLeavesPlayTriggerList`?
The GameCommand can then fill that one and whenever another `triggerChangesZoneAll` gets called by effects/SBA we can also call it on the global one, then clear it.

**Comment by Hanmac** [comment]
hm, i think it still should be done over the game command filling such table
