### ISSUE TITLE
Shandalar rebalance? Please discuss!

### ISSUE THREAD

**Issue by austeregrim** [Card-Forge/forge#1117]
**Is your feature request related to a problem? Please describe.**

- I'm always frustrated when Shandalar isn't how I remember it.
- Basically shandalar as it is currently is really open to all sets/editions etc. and a large number of enemies that don't reflect the original shandalar plane canon.

**Describe the solution you'd like**

- I'd like to see Shandalar plane moved to it's own plane with design trying to be closer to the original game Shandalar plane, limit legal editions to the first couple of releases and expansions (akin to original shandalar), limited enemies to the original enemy decks. (Some growth to provide our own "head canon" makes sense.) 
- A second plane that is more "wild" for game testing, and wider game play experience, and developmental?
- This would allow and provide more standardized design elements for newer planes, instead of design creeping shandalar to a point it's just a wild mess. 
- Allows for designing additional planes, Zendikar, Ravnica, Alara, etc. that might use their own block, sets, and enemies.
- Contributors can provide new enemies, and maps and dungeons, etc. to the more ephemeral "wild" plane.

**Describe alternatives you've considered**

- Letting a turtle walk across my keyboard to write most of this request. (I think Shellandra did pretty good, that's her name "Shellandra".)

**Additional context**

**Comment by austeregrim** [comment]
Comments in the discord:

Shii
`That said, a wild plane could be a good testing ground for new ideas.
Lastly, if a Shandalar plane does get implemented for those that would like it I'd still like a plane of how it is now with everything mixed together.  Hoping from plane to plane looking for cards would be rather annoying and as it stands the "Pull from Ether" is too expensive to pull cards one might want to make a deck work.`

DAS
`That'd be nice to limit the card pool and somehow balance player and AI decks. But Shandalar has also the most broken cards in magic. I'd prefer that player could progress through planes to assemble different decks while difficulty is increasing. So that Time Walks and Moxes are added on the last stages.`

I agree with limiting card pools per plane, and I think is a big thing that needs to be more "prevalent" or upfront about planes. I would like to start working on creating planes with enemy decks that aren't so wild or varied in meta as the shandalar plane is currently. I think this is more my point of this issue/request... if you can play any card from any edition, why would you play older cards? The power creep of editions makes original sets obsolete, and old decks easy to trump.

Instead of a "wild" plane, maybe calling it "unstable"? Move existing shandalar plane assets to this unstable plane. And start designing more stable planes. 

I know the concept of limiting editions is not widely accepted, considering what cards someone **wants to play** is only in the newest edition/set. But if you can progress from editions or blocks to newer editions, across the planes, that would be a more fulfilling game play and a real "adventure mode." Sure you might have to sell off older cards as you progress to newer planes, to make progress for newer cards and a more useful deck against the newer and changing metas across the ages of magic.

I want to see the game more fulfilling. so I'm sorry if this is sounded heavy handed and demanding, I don't intend to be... I'm just passionate about the concept. I wish I could write the code myself, but I'm trying to give ideas who can write the code.

**Comment by Agetian** [comment]
I fully support and agree with this idea, Austeregrim :)
In fact, this is one of the things that has, so far, sort of stopped me from playing Adventure actively. Having a more cohesive, period correct experience where cards from the said period make sense, sounds like a very good idea to me. Of course, this requires quite a bit of effort from plane designers (to design said planes, which can accomodate a wide range of both older and newer metas), which is quite possibly why it hasn't been done yet.

**Comment by Agetian** [comment]
Sounds like a good plan! :)

**Comment by Meerkov** [comment]
I always felt that the following sets would do well:
1) Each Plane
2) Each Standard rotation
3) Everything
4) User chooses a custom selection of sets.

Most discussion tends to revolve around 1 and 3.

But I think 2 actually would capture the feeling of shandalar best.

**Comment by austeregrim** [comment]
I don't disagree, actually that makes a lot of sense.
But each "plane" is somewhat ambiguous to what that means to the user, or
creator of the plane.
Standard rotation is good, but can that be configured programmatically,
without breaking existing decks/enemies. Or can enemies be
generated programmatically also based on the Std. Rotation limit?
Everything is probably good as an option.
and User chooses is also same issues with standard rotation... as I can
break the land shops with a limited set selection.

That would be awesome if all of those could be implemented as an option in
the game setup/starting options.
