### ISSUE TITLE
Abilities with some unpayable costs must still be allowed to be put on the stack

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#112]
> Activating mana abilities is done before paying costs when activating an ability. This means that if you control a creature which can be tapped for mana, such as Avacyn's Pilgrim, you may both tap it for mana and untap it to pay costs for Halo Fountain's activated abilities.

Currently Forge will not let you activate the ability without a tapped creature though, so you're forced to tap for mana first.

This matters because there might be triggers related to it that will then be on the stack before your ability, e.g.:

![grafik](https://user-images.githubusercontent.com/8506892/164464331-dd7fdecc-6a76-4649-84dc-a88fe6d1090d.png)

But you should be able to reach the opposite order as well if you so desire.

Another related example is _Bond of Agony_:
if you're at 1 life Forge will not let you choose X > 1. But maybe you want to cast it for X=2 because you can pay that part with _The Great Henge_.

**Comment by Hanmac** [comment]
Rules wise we need the following window:

* Put Card on the Stack
* Activate Mana Abilities (You would need to confirm that you are finished activating Mana Abilities)
* Pay the Cost (and do stuff like Convoke, Improvise and Delve), At this point you can't activate Mana Abilities anymore

**Comment by Hanmac** [comment]
it also related to the problem with CostPayment that we currently don't differ between the two steps of:

activating Mana Abilities and paying the Costs
