### ISSUE TITLE
Problem with ExiledWith Remember and Token

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#1122]
* Toluz, Clever Conductor on the field, it exiled some cards i discarded.
* make a token copy of it
* the token dies because of legend rule
* i somehow get the exiled cards back, but i shouldn't

**Comment by tool4ever** [comment]
@Hanmac 
found the problem here:
#1536

Since Toluz got updated with Remember it doesn't happen with him for now

**Comment by Hanmac** [comment]
Ah the OriginalHost is biting me in the butt.
Maybe for Clone Effects (and Token Copies), the OriginalHost should be the Clone for now?

I need to rewrite that for Linked Abilities anyway
