### ISSUE TITLE
ChangeXEffect: corner case with triggers using old value

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1134]
![image](https://user-images.githubusercontent.com/8506892/179396979-f7cf3887-85f3-4255-ae21-5574b98b74f6.png)

The Vial Smasher trigger will currently only deal 1 damage because it relies on `TriggerCount$CastSACMC`, but it should be 2.

My current idea is to just pass the AbilityKey as `MutableInt`, then we would only need to update it in one location and any other triggers would use that.

@Hanmac 
You ok with that approach?

**Comment by Hanmac** [comment]
or we might need to refactor/remove CastSACMC

in theory CastSA should always be a lki copy?

**Comment by tool4ever** [comment]
`AbilityKey.SpellAbility` will be a copy of castSA, however with real hostCard
changing the host to LKI wouldn't help us, then the CMC would be stored too early when the triggers get added to stack with the old value too

`TriggeredSpellAbility$Count$CardManaCost` would behave correctly in the example above, but once you counter the spell after doubling but before the damage trigger it would no longer count X :/

**Comment by Hanmac** [comment]
i think we need some LKI info for when a spell is removed from the stack
so that trigger can use that info instead
