### ISSUE TITLE
Circle of the Moon Druid Not Recognized as Elf

### ISSUE THREAD

**Issue by rtwormsy** [Card-Forge/forge#1137]
**Describe the bug**
Circle of the Moon Druid is not being recognized as an Elf for purposes of cards like Elvish Vanguard and Wolverine Riders. 

**To Reproduce**
Play Wolverine Riders/Elvish Vanguard
Play Circle of the Moon Druide
See that no health is gained or no +1/+1 counters are applied.

**Expected behavior**
He should be an elf. 

**Screenshots**
https://imgur.com/a/O4237FK
Note: The Elf Warrior Token just before in the Log shows proper behavior. 
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : N/A
 - Version: Downloaded Standalone 1.6.53 Java 8 Adventure Applet

**Additional context**

**Comment by tool4ever** [comment]
That's because of his ability:
> As long as it’s your turn, Circle of the Moon Druid is a Bear with base power and toughness 4/2.

When it ETB like that it will be a Bear only already.
