### ISSUE TITLE
Doublestrike Not Recognized with "Fight" Cards

### ISSUE THREAD

**Issue by rtwormsy** [Card-Forge/forge#1138]
**Describe the bug**
Creatures with Doublestrike are not properly doing first combat/"first strike" damage when a card with the "Target creature Fights another creature" mechanic. 

**To Reproduce**
Cast a creature with Doublestrike, e.g. Adorned Prowler, 1/1 Doublestrike
Have enemy cast creature that is also 1/1
Cast Titanic Brawl on your Prowler with enemy creature as target, both creatures die, rather than the Prowler winning the combat. 

**Expected behavior**
Doublestrike should provide "First Strike"/first combat damage in a "Fights other creature" mechanic. 

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/k2KZKlg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser N/A
 - Version 1.6.53

**Comment by kevlahnota** [comment]
Read MTG Comprehensive rules here: https://magic.wizards.com/en/rules

**701.12d The damage dealt when a creature fights isn’t combat damage.**

702.4a Double strike is a static ability that modifies the rules for the combat damage step. (See rule 510, “Combat Damage Step.”)

702.7a First strike is a static ability that modifies the rules for the combat damage step. (See rule 510, “Combat Damage Step.”)
