### ISSUE TITLE
Differ Between Control Untap Haste Effects

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#1157]
Most Effects does "Gain Control, do Untap, Gain Haste"

very few like "Blind with Anger" does Untap before Gain Control.

This would matter under which control the creature does untap for possible trigger.

**Comment by tool4ever** [comment]
The bigger problem here is even if `untap()` gets done before controller change in `ControlGainEffect` because of frozen stack a WaitingTrigger is created.

That means when after resolving `TriggerHandler` adds trigger to stack it still uses new host controller for it.

We might have to store controller in `TriggerWaiting` somehow or force it with `runWaitingTriggers()` directly afterwards but I'm not sure that's a good idea?

**Comment by Hanmac** [comment]
i would need to debug it

**Comment by tool4ever** [comment]
If we remove the param and script it with extra effect either before or after ControlGain it might be cleaner without engine workarounds?

**Comment by Hanmac** [comment]
> If we remove the param and script it with extra effect either before or after ControlGain it might be cleaner without engine workarounds?

technically yes, but it would make AI way more difficult

i would prefer if we have a parameter for `UntapBefore` and `UntapAfter` ?

wouldn't your idea also has the problem with waiting triggers?

**Comment by tool4ever** [comment]
Currently `AbilityUtils.resolveSubAbilities` should try and fill the WaitingTrigger from the previous events with the currently available ones

Would have to test it handles this interaction correctly though

**Comment by Hanmac** [comment]
> Currently `AbilityUtils.resolveSubAbilities` should try and fill the WaitingTrigger from the previous events with the currently available ones
> 
> Would have to test it handles this interaction correctly though

your problem was that while the waiting trigger are filled, when the trigger finally going to resolve and are put on the stack, the untap trigger might happen for the wrong controller

i think this might also be the problem if the cards were using extra script lines, because it isn't the problem of the effect, but the bigger problem of the TriggerHandler

**Comment by Hanmac** [comment]
@tool4ever @Northmoc while touching GainControl Effect, we might look into this issue again for Untap Trigger

**Comment by tool4ever** [comment]
I don't have a better idea besides refactoring such scripts into UntapEffect -> ControlGainEffect and storing the current controller while running `collectTriggerForWaiting`

**Comment by Hanmac** [comment]
@tool4ever what we could do is use LKI objects of the Trigger so it keeps the current Controller
