### ISSUE TITLE
Kalitas triggered ability occurred when he was no longer on the battlefield

### ISSUE THREAD

**Issue by daniel-morrison1** [Card-Forge/forge#1163]
**Describe the bug**
Kalitas died, but his zombie-producing triggered ability still worked the turn after.

**To Reproduce**
My side of the board consisted of Kalitas, one 2-2 zombie and some basic lands. Opponent hardcasted Fury targeting Kalitas which died. I untap with my zombie, cast Sudden Edict targeting my opponent who sacrifices Fury. Kalitas' ability then unexpectedly triggered giving me a second 2-2 zombie.

**Expected behavior**
Kalitas' ability should only trigger when he's on the battlefield

**Screenshots**
![image](https://user-images.githubusercontent.com/96431972/180151407-87180d8c-610f-4807-a6ae-d7ee5e3cdb06.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 1.6.53

**Comment by Hanmac** [comment]
it is an replacement effect that does replace dying so it does look back
> If Kalitas dies at the same time as creatures your opponents control, those creature cards will be exiled and you’ll get that many Zombies. (2016-01-22)

but it should better use of LastStateBattlefield there?

@tool4ever did you fixed that recently?

**Comment by tool4ever** [comment]
Yea it's caused by changeZoneLKIInfo messing up
But #1106 has fixed that too
