### ISSUE TITLE
Sword-Point Diplomacy interface issues (QoL/bug)

### ISSUE THREAD

**Issue by Agetian** [Card-Forge/forge#1177]
**Describe the bug**
When the opponent (AI) casts Sword-Point Diplomacy, the player isn't provided a clean intuitive view of which card he is currently being queried about (e.g. which card exactly you're asked to pay or not to pay 3 life for). You either have to memorize the order in which the cards were revealed, or you need to check the card detail view and check the Remembered/Imprinting info, which shows this information (but which is counter-intuitive, it's not immediately clear that that's where you have to look). This is especially confusing on Mobile Forge where you have to specifically enable the zoomed card view in card detail text mode in order to see the relevant information.

**To Reproduce**
1. Make the AI cast Sword-Point Diplomacy.
2. Go through the motions. See that you're not provided a clear view of the current card when you're asked about paying 3 life.

**Expected behavior**
The current card should be visualized in some way (e.g. in a pop-up window on mobile Forge and in the card image view box on desktop Forge).

**Comment by kevlahnota** [comment]
I'm on it but it needs testing since I just modified the vprompt to draw the card image in the background... I don't know how to add it on desktop so this is for mobile port only
![image](https://user-images.githubusercontent.com/9781539/180627222-f36dfa1b-76b1-445c-affe-1c485eb0b0ec.png)

**Comment by kevlahnota** [comment]
update, just manage an alternate version, I think this is better than previous one... 
![image](https://user-images.githubusercontent.com/9781539/180628133-2a3b93c1-ec7d-40c9-8d4a-8ac285e4ef8a.png)

**Comment by kevlahnota** [comment]
I think this is working on desktop too... 
![image](https://user-images.githubusercontent.com/9781539/180629457-613b3e9c-5ead-4590-8e31-09c0ae2dc1b5.png)
