### ISSUE TITLE
Information about illegal targets must still be provided by the engine in some cases

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1179]
When you cast _Searing Blaze_ targeting opponent + his creature, if he responds with _Blossoming Calm_, the creature should still be damaged after.
Currently the `Creature.ControlledBy ParentTarget` will also turn illegal because the player got removed.

https://twitter.com/Dunkatog/status/1439013991330680833

**Comment by Hanmac** [comment]
We probably should do illegal Targets as extra property so the original Targets arent't touched

But then we might need to check all other places where getTargets are returned ...
This might also only be set by the MagicStack, any other checks by the AI for maybe illegal targets should not alter them.

someone else has some ideas for this?

**Comment by tool4ever** [comment]
It could probably be fixed the same way I did _Yosei, the Morning Star_ with `RememberOriginalTargets$`

**Comment by tool4ever** [comment]
_Biomantic Mastery_ is another case
