### ISSUE TITLE
Wrong art returned for Tranquil Cove in J21 set

### ISSUE THREAD

**Issue by jman1865** [Card-Forge/forge#1223]
The art for Tranquil Cove from the J21 set returns the card art for Swords to Plowshares from the J21 set.  I have deleted the cached image multiple times (and restarting forge after doing so) and the temp card shows the correct card rules, but then it downloads the incorrect image.

Attached is a screenshot of what shows up for that card - the card text is correct, only the image appears to be incorrectly referenced.

![image](https://user-images.githubusercontent.com/47758247/181410415-6714ac74-75cd-4cca-85cd-45ed670a6632.png)

Windows 10 / Forge 1.6.53

**Comment by kevlahnota** [comment]
should be fixed on 1.6.54.730z.SNAPSHOT while using ImageFetcher (Automatically Download Missing Card Art).
