### ISSUE TITLE
Can't counter triggers from Effects

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1229]
Example: trying to _Stifle_ (opponents) Epic trigger

Using `ValidTgts$ Card,Effect` seems to fix it.

@Hanmac 

your opinion?

**Comment by Hanmac** [comment]
This might work, or can't we just make it target SA without the need for defining Card target?

**Comment by tool4ever** [comment]
I thought about just getting rid of TargetType completely, but I'll probably try to allow both variants because of something like
> target activated or triggered ability you control from an artifact source

- which still looks cleaner to me when written as `TargetType$ Activated.YouCtrl,Triggered.YouCtrl | ValidTgts$ Artifact`
- also slightly more efficient for the engine since it can check the host directly for the restriction part that's meant for it, avoiding running through all SA properties first

might need to tweak it a bit to get the defaults inserted nicely, the mapParams in AbilityFactory are currently unmodifiable

**Comment by tool4ever** [comment]
Well, this has gotten more complicated than I thought first:
- when the SA cares about source type (e.g. _Tawnos, Urza's Apprentice_) it will fail because effect hosts don't have any
  - so for some cards like _Acidic Dagger_ maybe EffectSource can be checked instead
  - rewriting into DelayedTriggerEffect might help a bit, but probably can't be done for all because of some other limitation and would also take a long time
- "normal" delayed triggers are also not fully correct, their LKI host means if you resolve _Carrier Pigeons_ ETB trigger, then turn them into artifact with _Memnarch_ ➡️  Tawnos still can't target it on upkeep

**Comment by Hanmac** [comment]
> Well, this has gotten more complicated than I thought first:
>     * "normal" delayed triggers are also not fully correct, their LKI host means if you resolve _Carrier Pigeons_ ETB trigger, then turn them into artifact with _Memnarch_ ➡️  Tawnos still can't target it on upkeep

this one i am not sure if that's correct? i mean it wasn't an Artifact when the delayed trigger was created?

**Comment by Hanmac** [comment]
hm i need to think about the delayed trigger thing:
> 603.7e If an activated or triggered ability creates a delayed triggered ability, the source of that delayed triggered ability is the same as the source of that other ability. The controller of that delayed triggered ability is the player who controlled that other ability as it resolved.

so for example,
* the delayed trigger is created,
* then something turns it into an artifact
* then the bird gets removed
* now the delayed trigger happens, should it use LKI from the battlefield?

**Comment by Hanmac** [comment]
this is probably related to my game timestamp problem:

because Card has an id (that stays on zone change) and a timestamp (that is changes on zone change) and it needs a different timestamp for layers.

now the problem: the Rules only care about the GameTimestamp

so we need something like https://guava.dev/releases/28.0-jre/api/docs/com/google/common/base/Equivalence.html
when talking about getting LKI from an Card last state on the battlefield

**Comment by tool4ever** [comment]
> > 603.7e If an activated or triggered ability creates a delayed triggered ability, the source of that delayed triggered ability is the same as the source of that other ability. The controller of that delayed triggered ability is the player who controlled that other ability as it resolved.

With that rule the use of `getCardState` seems just too problematic there as it might set up the the trigger on the wrong object:

Currently you can Flicker stuff like _Crumbling Colossus_ with its attack trigger on the stack and the new object will still be sacrificed.
(Otherwise we need to fix such cards with `RememberObjects$ Self` and `DelayTriggerRememberedLKI` again)

But I think if we can make it work without LKICopy host, that might be cleanest?
Then if the host LTB for some reason we should try and just treat the Card as LKI (because GameAction will make a copy as the new real Card for the destination zone anyway)

**Comment by Hanmac** [comment]
i think we should store the controller of the trigger inside extra variable, so we may not need the lki for delayed trigger

**Comment by tool4ever** [comment]
The `spawningAbility` is a copy, maybe we can just use `getActivatingPlayer()` from there
