### ISSUE TITLE
Crown of Doom acts as a mana drain (Commander)

### ISSUE THREAD

**Issue by cpoll23** [Card-Forge/forge#1313]
When given to an AI opponent, they will continuously drain their mana every turn they have the crown:

Crown of Doom (26) - [Couldn't add to stack, failed to target] - {2}: *crown of doom ability description*

This will repeat in the log until they drain themselves, every turn.

**Comment by kevlahnota** [comment]
if you check the card script, Crown of Doom has `AI:RemoveDeck:All` it means the card is not supported by AI.

**Comment by cpoll23** [comment]
Just to be clear, what I'm referring to is when I cast Crown of Doom and then use it's active to give it to an AI.

It is at this point in which they start draining themselves, so no AI started with the card in their deck.

Also curious if your explanation implies that Crown of Doom not working with AI is intended? Or if it's just one of many things on an endless to-do list you have, thanks!

**Comment by kevlahnota** [comment]
> Just to be clear, what I'm referring to is when I cast Crown of Doom and then use it's active to give it to an AI.
> 
> It is at this point in which they start draining themselves, so no AI started with the card in their deck.
> 
> Also curious if your explanation implies that Crown of Doom not working with AI is intended? Or if it's just one of many things on an endless to-do list you have, thanks!

Try using latest 812 snapshots, AI shouldn't mill itself anymore. Anyway cards with `AI:RemoveDeck:All` means Forge will not include those on Random Generated Decks and Draft and on latest snapshots it will not considered to be played since they are known to have issues with the AI due to missing AI logic how to handle them properly.
