### ISSUE TITLE
Update cards checking for color words without oracle

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#134]
cards like `Opal Titan` needs to be rewritten so they don't use Color Words in their effect because their oracle doesn't use them.

that causes them to be affected by Card Text Changes when they should not

maybe some investigation if there are more cards like this

**Comment by Northmoc** [comment]
- `All Suns' Dawn`
- `Rogues' Gallery`

**Comment by Hanmac** [comment]
All Suns Dawn and Rogues Gallery are fixed imo and can't be done better:
> You choose the color each target must be when you choose it as a target, so if the card you targeted as a blue card is red when All Suns’ Dawn resolves, the card is an illegal target, even if the spell doesn’t target another red card. 

While Opal Titan might can be tweaked getting the Colors from the TriggeredSpell
