### ISSUE TITLE
Adventure Custom Planes Folder

### ISSUE THREAD

**Issue by austeregrim** [Card-Forge/forge#1340]
**Is your feature request related to a problem? Please describe.**

- I'm always frustrated when ... Res Updates delete my mods, as we have no location for mods to reside for adventure mode.
- Creating a copy of shandalar in the /res/adventure folder creates a custom plane that can be modded, but this gets deleted whenever a res update happens. Forge hangs when the settings file is set for and looking for the modded plane.

**Describe the solution you'd like**

- Provide a location in /data/custom/adventure/ where modded planes can reside, for testing or personal preference of plane design.
- /data/custom/adventure/ravnica could be a custom plane and enumerated at the same time /res/adventure/shandalaer is.

**Describe alternatives you've considered**

**Additional context**

**Comment by TrueFuFLeaderG** [comment]
#1560
