### ISSUE TITLE
Henzie "Toolbox" Torre

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#137]
Toolbox from Streets Commander Set grants Spells Blitz on the Stack, but only if their mana value is >= 4

Problems:
* It is not a zone allow
* it bypasses Jailer which would remove the ability in the graveyard
* it is especially problematic for cards that has X in their ManaCost because it might stop you from casting when X is too low.

So again we need to check what the object would be on the stack, adding a check with that the ManaValue needs to be 4+ and then stop and revert the cast if X < 4

other alternative costs also may function while on the stack like Dash? but they shouldn't be affected by this

**Comment by Hanmac** [comment]
in addition to other getAlternateHost, this check needs to add the new Card onto the stack so see it would gain any Keyword.

**Comment by Hanmac** [comment]
i tried to get it working, i managed to cast the spell but it didn't had blitz anymore while on the field

the problem: while it affected the stack, it didn't affected the card anymore when it hit the field.

trying to copy the card when it goes to the battlefield caused StackOverflow Errors

**Comment by Northmoc** [comment]
> i tried to get it working, i managed to cast the spell but it didn't had blitz anymore while on the field

> the problem: while it affected the stack, it didn't affected the card anymore when it hit the field.

> trying to copy the card when it goes to the battlefield caused StackOverflow Errors

Instead of copying the card, could the keyword be added again?

Maybe some kind of check... if a card is cast with Blitz, but doesn't have the keyword on ETB, apply the keyword?

I don't know. Probably a bad idea but sometimes bad ideas spark good ones.
