### ISSUE TITLE
Mobile vs. Desktop Commander Deck

### ISSUE THREAD

**Issue by austeregrim** [Card-Forge/forge#1383]
**Describe the bug**

- Mobile commander deck creation enforces an unknown rule of "legendary creatures can only be a commander."
- Desktop commander deck creation allows legendary creatures to not be only the commander.
- There is no rule that specifies this to be enforced.

**To Reproduce**

1. Build commander deck.
2. Try to put legendary creatures in main deck.

**Expected behavior**

- I expect legendary creatures to be allowed in both mobile and desktop deck creation, unless there is a rule for it. mtgcommander.com does not clarify.
- If there is a rule for it, then both mobile and desktop should handle it the same and prevent legendary creatures in main deck.

**Screenshots**

<img width="1680" alt="Screenshot 2022-08-21 at 10 00 25 PM" src="https://user-images.githubusercontent.com/1243145/185842773-16324988-e619-410a-b4de-f4123bcab279.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by austeregrim** [comment]
In the same vain, desktop doesn't enforce singles only on commander decks.

**Comment by kevlahnota** [comment]
@tool4ever seems like user error... Don't have problem with deck building a commander. Some rulings..

```
903. Commander

903.1. In the Commander variant, each deck is led by a legendary creature designated as that deck’s commander. The Commander variant was created and popularized by fans; an independent rules committee maintains additional resources at MTGCommander.net. The Commander variant uses all the normal rules for a Magic game, with the following additions.

903.2. A Commander game may be a two-player game or a multiplayer game. The default multiplayer setup is the Free-for-All variant with the attack multiple players option and without the limited range of influence option. See rule 806, “Free-for-All Variant.”

903.3. Each deck has a legendary creature card designated as its commander. This designation is not a characteristic of the object represented by the card; rather, it is an attribute of the card itself. The card retains this designation even when it changes zones.
Example: A commander that’s been turned face down (due to Ixidron’s effect, for example) is still a commander. A commander that’s copying another card (due to Cytoshape’s effect, for example) is still a commander. A permanent that’s copying a commander (such as a Body Double, for example, copying a commander in a player’s graveyard) is not a commander.
```

**Comment by austeregrim** [comment]
Thanks. It was user error on my part. I didn't think about color identity limiting card selection.
