### ISSUE TITLE
Shield Counter Replacement Effects

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#142]
> 122.1c A shield counter on a permanent creates one replacement effect and one prevention effect that protect the permanent. These effects are “If this permanent would be destroyed as the result of an effect, instead remove a shield counter from it” and “If damage would be dealt to this permanent, prevent that damage and remove a shield counter from it.” See rule 614, “Replacement Effects,” and rule 615, “Prevention Effects.”

But Jess said: https://twitter.com/Hanmac10/status/1518659638312554502
> No, they are not abilities of the permanent, and those effects will still apply if the permanent loses its abilities.

meaning i need to find a way to add them as Effect that is somehow connected to the card.
That is especially important if the player somehow left the game, and they wasn't the owner of the card.

and if possible i don't want to pollute the CommandZone with Effect objects

The ReplaceDestroy needs to check if it was by an Effect. This excludes Destroy by State Based Action.

Example:
So if Unpreventable damage is dealt to a creature with 2 or more shield counters,
then the Damage ReplacementEffect would kick in and still remove the Counter. (see Polukranos, Unchained or Phantom Cards)
Then if the creature has lethal damage, the State Based Action would kill the creature while it still has shield counter on them.
(need to ask Judges)

**EDIT:**
One idea is to hijack the getReplacements method and add them *after* the Ability Layer removed the other abilities

**Comment by Northmoc** [comment]
Possibly you could Animate (or your new equivalent) the replacement and prevention effects onto them with some kind of `Duration$` to avoid using Effects in the Command Zone?

**Comment by Hanmac** [comment]
Animate is a nono because these would be affected by Cards losing their abilities

And Extra Effect object would be ugly

**Comment by Northmoc** [comment]
Makes sense

The ability is on the counter, not sure why WotC doesn't just say that
