### ISSUE TITLE
Vigilance as Static Ability

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#1423]
in the work of cleanup the Attack Assign for Optional Attack Cost (Enlist and Exert),
Vigilance and the Effect from Johan should use a StaticAbility instead of a hidden keyword.

Should probably be done before #1354

**Comment by tool4ever** [comment]
I wonder if this should be refactored into Untap replacement to avoid extra check

**Comment by Hanmac** [comment]
@tool4ever "Untap"? doesn't you mean "Tap" Replacement?

and having CantHappen Tap Replacement might be ugly?

**Comment by tool4ever** [comment]
oops yes

you already added it a year later because of *Ood Sphere* (that's what I mean with extra check now)

so it would be sort of like *Archon of Coronation* instead
