### ISSUE TITLE
forge .command files not delivered with +x permissions

### ISSUE THREAD

**Issue by austeregrim** [Card-Forge/forge#1443]
**Describe the bug**

both ".Command" files for forge is not delivered with executable permission, not allowing the script to run on Mac OS systems. Preventing new users from being able to start it up. 

Also the command file should use /bin/bash not /bin/sh 

And it appears the command file is stored with windows hard returns not Linux/Unix compatible ones, so it might not run on even with the corrections.

**Comment by CrimsnRoc** [comment]
adventure mode can launch, but trying to go to "adventure" just hangs on the gray map background screen on desktop snapshot 1.6.54.905

**Comment by austeregrim** [comment]
Thats not the same issue.
