### ISSUE TITLE
Yurlok of Scorch Thrash and Leyline of Abundance producing too much Mana

### ISSUE THREAD

**Issue by AbonShell** [Card-Forge/forge#1472]
**Describe the bug**
When Yurlok of Scorch Thrash is tapped while a Leyline of Abundance is under your control, it adds an additional 3 green mana.

**To Reproduce**
Have both Yurlok of Scorch Thrash and Leyline of Abundance under your control.
Use Yurlok's ability to add a Black, Red, Green, and an extra Green from the Leyline.
See that it added an additional 3 Green.

**Expected behavior**
A total of 4 mana should be in the pool, instead it is 7.

**Screenshots**
![image](https://user-images.githubusercontent.com/20672472/188515491-43041ef6-f894-44f9-8430-41698e53181c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.54 Snapshot- 9/5/2022

**Comment by Simisays** [comment]
How many opponents did you have ?

**Comment by AbonShell** [comment]
Four opponents.

**Comment by Simisays** [comment]
Ah I see, I tested it againt 1 opponent and it gave me 1 mana too much. I'll try to fix Leyline of Abundance

**Comment by Northmoc** [comment]
I highly doubt the issue is in Leyline of Abundance script... I think it has to do with the TapsForMana trigger going off for each player that gets mana from Yurlok. Makes sense because Yurlok is the only card templated with `Each player adds`...
