### ISSUE TITLE
True-Name Nemesis should not be a Modern card

### ISSUE THREAD

**Issue by daniel-morrison1** [Card-Forge/forge#1483]
**Describe the bug**
True-Name Nemesis appears in the deckbuilder when filtering by format: modern, despite the fact that it is not a modern-legal card.

**To Reproduce**
1. Go to the constructed deckbuilder
2. Add the filter "Format: Modern"
3. Search for True-Name Nemesis
4. It appears despite not being a legal card in Modern

**Expected behavior**
TNN should not show up in the search results when the modern filter is applied

**Screenshots**
![image](https://user-images.githubusercontent.com/96431972/188752744-dc0d182f-86a6-4fea-8cd2-d631a6f4b839.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.53

**Comment by tool4ever** [comment]
@paulsnoops 
something we can't fix nicely without removing the whole set I guess?

**Comment by paulsnoops** [comment]
@tool4ever correct however TSR is the problematic set here. I have no problem removing it from Modern, it's probably an oversight on my part when re-doing the formats. This set as a whole should really only be legal in Vintage and Legacy. Will push a PR fix now.

**Comment by paulsnoops** [comment]
Well actually, I guess it's the Old Frame Bonus Sheet cards that shouldn't be in Modern but yeah I can just remove the set. It's just a reprint set anyway.
