### ISSUE TITLE
Dominaria United Draft Pool allows too many lands

### ISSUE THREAD

**Issue by CrimsnRoc** [Card-Forge/forge#1503]
**Describe the bug**
Booster draft pool for Dominaria United packs frequently contain more than one dual land card

**To Reproduce**
1. Go to booster draft
2. Click on Dominaria United
3. Open packs
4. See multiple packs showing 2+ dual land cards

**Expected behavior**
Packs can contain one dual land, but only two if one of them is foil. Never more than that. Couldn't find definitive MTG source showing this, but almost zero chance of more than one common dual land in a pack.

**Screenshots**
Multiple packs early in a draft showing excessive dual lands:

![rd2 pack 4](https://user-images.githubusercontent.com/113217785/189459955-f16814f9-ddc9-4197-99b5-b28fbd54ddee.jpg)
![pack1](https://user-images.githubusercontent.com/113217785/189459956-d909a988-e6ba-46cf-aaad-61b7a94b189f.jpg)
![pack7](https://user-images.githubusercontent.com/113217785/189459957-c99982f7-7bd9-4783-a68f-53e1a9ea6de5.jpg)
![rd2 pack 6](https://user-images.githubusercontent.com/113217785/189459958-85b70fe0-f429-4896-b82d-78fcb8f1567a.jpg)
![rd2 pack 5](https://user-images.githubusercontent.com/113217785/189459959-7bdf68b3-4764-445d-b619-b44f54f836f1.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [NA]
 - Version [snapshot 1.6.54.905]

**Additional context**
This makes drafting the set unrealistic to the point where it's not worth it. Very often there will be 2-3 lands in the pack.

**Comment by tehtmi** [comment]
Real DMU draft packs can absolutely have multiple common duals. Without checking super carefully, US/Belgian packs probably won't have more than 2 (barring weirdness), but 2 is not particularly unusual. Japanese packs should be able to have up to 4 without weirdness, although this would be quite unlikely. I've seen 3 (though this is also rare).

(Don't know how Forge models packs, but IRL print runs probably tend to reduce variance in this number versus a more random model, so a random model may give 0 and 2+ packs more often.) (Also, no idea if Forge is doing things correctly anyway, just saying what real packs are like.)

**Comment by CrimsnRoc** [comment]
![toomanylands](https://user-images.githubusercontent.com/113217785/192098212-826f6241-eb3d-453d-8327-3d12b1008912.jpg)
It's just too extreme right now without some sort of limiting logic when populating the card pool. Perhaps the code could work in phases where it rolls how many common dual lands will be in the pack (1 or 2) and THEN populates the rest of the commons?
