### ISSUE TITLE
40K: Ravenous Keyword

### ISSUE THREAD

**Issue by paulsnoops** [Card-Forge/forge#1507]

**Comment by Hanmac** [comment]
@paulsnoops 

> 702.156a Ravenous is a keyword found on some creature cards with {X} in their mana cost. Ravenous represents both a replacement effect and a triggered ability. “Ravenous” means “This permanent enters the battlefield with X +1/+1 counters on it” and “When this permanent enters the battlefield, if X is 5 or more, draw a card.” See rule 107.3m.

The X Trigger is separate and not a delayed trigger inside the replacement effect

**Comment by Northmoc** [comment]
On it
