### ISSUE TITLE
Adventure Mode: Enemy Drop * Difficulty Multiplier 

### ISSUE THREAD

**Issue by TheSAguy** [Card-Forge/forge#1511]
**Is your feature request related to a problem? Please describe.**

I'm playing on Hard and am still getting amazing drops. Sometimes several rares per enemy drop. I feel that the "Grind" to improve your deck, especially if you choose to play on Hard is part of the fun/challenge. 
If I can easily get the best cards from a few key enemies, the challenge quickly dissipates. If I'm not mistaken, drops currently has nothing to do with difficulty settings...

**Describe the solution you'd like**

Add a multiplier to the rewards code. It could be on 
"probability" * difficulty or "addMaxCount" * difficulty, if not both.

Difficulty can be something like:
Easy: 1.5
Normal: 1
Hard: 0.5

As a side note, drop rates could be one of the race perks, when you implement starting race specific attributes

**Describe alternatives you've considered**

Create a Hard+ or Insane difficulty setting and make it brutal...

**Additional context**

This is related to topic: [#1115](https://github.com/Card-Forge/forge/issues/1115)

**Comment by TrueFuFLeaderG** [comment]
#1560
added insane difficulty, added drop multiplier for rewards (only for drops that have a range), added "Pile" as mode where you start with just a pile of cards

**Comment by TheSAguy** [comment]
Just wanted to say thanks!
