### ISSUE TITLE
Order of cost reductions can sometimes matter

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1519]
If you control _Tezzeret, Betrayer of Flesh_ + _Heartstone_ you should be able to activate _Burnished Hart_ for {0}.

Currently it can still be {1} if the Stone ETB after Tezzeret.

But rules say:
> If multiple cost reductions apply, the player may apply them in any order.

@Hanmac 
Always choosing order might be annoying? What you think about just sorting them so those with `MinMana$` are always done first?

**Comment by Hanmac** [comment]
We need to find the Corner Case where such thing matters.

* as far as i know, MinMana only happens for reducing the Cost of Activated abilities. 
* most of them reduce only for cards on the battlefield
* stuff that reduces outside are far more rare. like Embalmer's Tools for GY.

having multiple without MinMana is no problem, while having multiple with MinMana is also no problem.

the case should only be needed to ask the player if there is at minimum one with MinMana and one without MinMana?

**Comment by tool4ever** [comment]
My search resulted in no other cases.

But I found this commit of yours: 40b1f89c8fd647f917a39aad3cbb09d10356735e
which stopped the combination with `ReduceCost$` also from allowing it.

Example (Ability always costs {1}):
![image](https://user-images.githubusercontent.com/8506892/190395618-f4bbfa6c-3e12-4961-adee-47f46513e7df.png)
Unless I'm missing something it shouldn't be treated differently?

Also somewhat related:
> If an effect (such as the one from Lodestone Golem) imposes an additional generic mana cost to casting Khalni Hydra, the Hydra’s ability will reduce it too. It’ll reduce the amount of green mana you need to spend first, though. 

Currently not working (will always be at least {1})

**Comment by Hanmac** [comment]
ugh, more stupid corner cases ...
* Edgewalker, Ragemonger, Morophon, the Boundless, Bard Class explicit says that they do not remove generic mana
* Khalni Hydra seems to be the only one that can

**Comment by Hanmac** [comment]
Found the rules:
> 118.7b If a cost is reduced by an amount of colored or colorless mana, but the cost doesn’t require mana of that type, the cost is reduced by that amount of generic mana.
> 118.7c If a cost is reduced by an amount of colored mana that exceeds its mana component of that color, the cost’s mana component of that color is reduced to nothing and the cost’s generic mana component is reduced by the difference.

but most of them have a restriction to not reduce generic mana
