### ISSUE TITLE
make LandAbility work for ValidSA

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#165]
i really need to make LandAbility work for ValidSA

_Originally posted by @Hanmac in https://github.com/Card-Forge/forge/pull/162#discussion_r860794151_

This would be great for streamlining Ziatora's Envoy

==
* LandAbility should probably be created by CardFactory when reading the CardFace in a similar way how Spell Permanent is created.
* this might cleanup other mayPlay stuff

* If Enchant Keyword is updated, Spell Permanent would needs to be updated for Auras too

**Comment by Hanmac** [comment]
@tool4ever maybe i look into this first 

this should be as simple as this in CardFactory
```java
SpellAbility sa = new LandAbility(c);
sa.setCardState(c.getCurrentState());
c.addSpellAbility(sa);
```
