### ISSUE TITLE
Cards with "may"(be able to) text force an action from the user

### ISSUE THREAD

**Issue by rodriggit** [Card-Forge/forge#1669]
This happens for example with The Trickster-God's Heist(You may exchange control of two target creatures) or Electropotence enchanments. User is forced to perform the action depicted in the card when it should be optional. Even when is not possible to do it resulting in a dead end.

Play a normal game with one of the given Enchanments

**Expected behavior**
It should be given a clear option or command to skip the usage of the card effects

**Desktop (please complete the following information):**
 - Windows 11

**Comment by Hanmac** [comment]
@rodriggit the rules say you still need to target 2 creatures when the ability is put on the stack, before you choose if you want to exchange control on resolution.

@tool4ever @Northmoc can you debug it if it still works?

**Comment by tool4ever** [comment]
Yes, nothing is broken here

**Comment by rodriggit** [comment]
> @rodriggit the rules say you still need to target 2 creatures when the ability is put on the stack, before you choose if you want to exchange control on resolution.
> 
> @tool4ever @Northmoc can you debug it if it still works?

The problem is that if there are no creatures or noncreature/nonbasic  permanents(second step) on play the ability triggers anyway and the game seems to be stucked.  Thanks for the quick response!

**Comment by tool4ever** [comment]
Ah I see what you mean now, thanks for reporting
