### ISSUE TITLE
Card error: Underdark Beholder exiles revealed cards

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#1682]
I got Underdark Beholder in a Quest run, and all revealed cards were exiled from its attack trigger. These cards should never leave the library (apart from one, if it was cast) and be shuffled away.

**Comment by tool4ever** [comment]
I found _Amplifire_ with the same issue, might want to check if more affected too

**Comment by Samthere** [comment]
Thanks! It's working now on the snapshot. However, it looks like it still puts the card into the exile zone while it executes and then shuffles them all back in. Is this going to trigger corner cases like Stonebinder's Familiar?

**Comment by tool4ever** [comment]
Hmn, no I don't observe that now
