### ISSUE TITLE
Can't activate morph ability after casting from exile

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#1684]
I'm playing Quest, and in two games now I've cast Bane of the Living as a morph creature after Tectonic Giant sent it to exile. However, once that's done, the morph creature can't be activated to turn face up.

(Windows Desktop GUI 1.6.53)

**Comment by paulsnoops** [comment]
Works fine here as you can see in the step-by-step images below. Make sure you've cast it from exile and then try to morph on a main phase. If it's not working try the latest snapshot: https://downloads.cardforge.org/dailysnapshots/

![java_z4y1JFSCoZ](https://user-images.githubusercontent.com/18243520/195852151-d56be203-9ff9-4cc0-be7b-d4fbb2a3c39b.png)
![java_T9IsFzJG3J](https://user-images.githubusercontent.com/18243520/195852311-af9c85a9-d594-45a8-b5f0-33cc7243afec.png)
![java_S5RfHC9G9l](https://user-images.githubusercontent.com/18243520/195852443-383b604e-3eba-4afe-88cb-372ea8da7005.png)
![java_mguUGFE34G](https://user-images.githubusercontent.com/18243520/195852615-e24c0ec2-7933-4b69-b451-1364a02e9fcc.png)

**Comment by Samthere** [comment]
Yep, thanks, it's working in the snapshot!
