### ISSUE TITLE
Bugs with some adventure cards

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [Card-Forge/forge#1692]
**Describe the bug**
Sapphire Dragon and Giant Killer are going to graveyard instead of exile after their adventure is cast successfully and
Dread Linnorm should have creature type "Snake Dragon" but has type "Giant" instead.

**To Reproduce**
1. Start a Game.
2. Play the adventures of sapphire dragon and giant killer.
3. Look into your graveyard.
4. Go to the deck editor and search for dread linnorm.
5. compare the creature type on his image with the type in the box above.

**Expected behavior**
Sapphire Dragon and Giant Killer should go to exile after their adventure is cast and should be playable as creature from exile.
Dread Linnorm should have type "Snake Dragon".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.6.54.1015 - SNAPSHOT

**Additional context**
I found the wrong creature type on Dread Linnorm because i had in on the battlefield and it did not get destroyed by the adventure of Realm-Cloaked Giant.

**Comment by tool4ever** [comment]
Those adventures seem to work fine for me
were you testing this with a specific Deck maybe? If you used Dev Mode try with basic lands only or posting your gamestate could help

**Comment by Terandox-The-Pineapple** [comment]
I tried this in Commander with an Adventures Tribal Deck... It happens nearly every time i play with this deck and with a lot of other adventure cards like Crystal Dragon too.

**Comment by Terandox-The-Pineapple** [comment]
Is Dread Linnorm also a Giant on your end?
On mine it is...

**Comment by Terandox-The-Pineapple** [comment]
https://imgur.com/a/AUnhMBA

**Comment by tool4ever** [comment]
I did fix the creature type but your deck behaves fine for me

**Comment by Terandox-The-Pineapple** [comment]
It happens not every time and not always with the same creatures... i don't know what is causing this.
It happens most of the time in late game.

**Comment by Terandox-The-Pineapple** [comment]
I tested a bit more and finaly found out what is causing this weird behavior.
If you cast an adventure like Giant Killer on a target, copy it with lucky clover and cast the copy on the same target so it leaves the battlefield before the original adventure resolves, the adventure goes to grave instead of exile

**Comment by tool4ever** [comment]
Well in that case it's not a bug because if the adventure doesn't resolve it's not exiled:

> If all its targets, for every instance of the word "target," are now illegal, the spell or ability doesn't resolve. It's removed from the stack and, if it's a spell, put into its owner's graveyard.
