### ISSUE TITLE
Threads Undetected does not work the way it should

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [Card-Forge/forge#1697]
**Describe the bug**
Threads Undetected should normaly let you pick 4 creatures with different powers from your deck and then let you pick 1 opponent who picks 2 of them to shuffle back into your library while the rest goes into your hand. Instead it lets you pick 4 creatures with different powers from your deck and an opponent who separates the choosen cards into 2 piles and lets you pick one pile that goes to the top of your library and the rest goes to your hand.

**To Reproduce**
1. Activate Threads Undetected.
2. Choose 4 Creatures.
3. Choose an opponent.
4. Wonder why the game lets you pick a pile.
5. Play any card that draws 2 cards.

**Expected behavior**
Threads Undetected should normaly let you pick 4 creatures with different powers from your deck and then let you pick 1 opponent who picks 2 of them to shuffle back into your library while the rest goes into your hand.

**Desktop:**
 - OS: Windows 10
 - Version 1.6.54.1016 - SNAPSHOT

**Additional context**
This is strange...

**Comment by tool4ever** [comment]
Can probably be done like _Realms Uncharted_ without TwoPiles...
