### ISSUE TITLE
Collective Voyage is using the Artwork from Bearscape...

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [Card-Forge/forge#1712]
**Describe the bug**
One version of Collective Voyage is using the artwork of Bearscape.

**To Reproduce**
1. Go to Deckeditor
2. Search for Collective Voyage
3. Look at the card image of the third version

**Expected behavior**
It should use its own artwork instead of an artwork from another card

**Screenshots**
https://ibb.co/YcRVp6J

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.6.54.1018 - SNAPSHOT

**Comment by paulsnoops** [comment]
@tool4ever I think it's @kevlahnota for the images ftp. The edition file is correct.

**Comment by paulsnoops** [comment]
Fix has been pushed. After the next snapshot delete your image and it should download correctly.
