### ISSUE TITLE
Threads Undetected still not shuffling the deck

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [Card-Forge/forge#1714]
**Describe the bug**
Threads Undetected says in its text that the cards choosen by your opponent are shuffled into your library, but they get just placed ontop of your library instead.

**To Reproduce**
1. Play Threads Undetected.
2. Play any spell that draws 2 cards.

**Expected behavior**
The cards choosen by your opponent should be shuffled into your library.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.6.54.1018 - SNAPSHOT

**Comment by tool4ever** [comment]
Thanks for checking!
