### ISSUE TITLE
Conspiracy Breaks Quest Tournament

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#1721]
I'm on the 1.6.54 snapshot current as of today, and I started a Conspiracy draft in Quest mode. The draft went fine, but I'm unable to start the actual match due to Conspiracies in my sideboard/deck.

When pressing start, the error says Deck Invalid: Deck contains the nonexisting card Muzzio's Preparations. I'm able to quit the tournament, but not remove them from the deck pool to play with the cards I have.

**Comment by kevlahnota** [comment]
how did you add non existing/not supported cards to your deck? I think you are not supposed to add any invalid cards or it will corrupt your save file.

**Comment by Samthere** [comment]
The format was available to be picked using a token and the conspiracies were included in the draft. It hasn't crashed anything, just meant that retiring was the only available option as the offending cards couldn't be removed.

**Comment by Samthere** [comment]
I've just checked now and the conspiracies weren't added to my main quest card pool after conceding, it must handle that.

**Comment by Samthere** [comment]
So I was later able to play this as a saved draft. Muzzio's Preparations, Immediate Action and Secrets of Paradise. However, trying again now (different install but up to date) it's unable to start a game in either context, saying that Immediate Action is a nonexistent card (possibly focused on this one because it was the first conspiracy I drafted).

**Comment by Samthere** [comment]
Okay I restarted and applied a new snapshot and this seems to be working again for the Conspiracy one cards! Will look again and close if appropriate.

**Comment by Samthere** [comment]
Ah, I think I see what the specific issue is. In booster draft mode with a saved deck, the conspiracy cards can be added to the "conspiracy" deck segment, and they work from there. In quest tournament, there are no alternative boards, just sideboard and deck, so the conspiracies are stuck there where they're considered nonexisting cards.

This also means that if you've drafted conspiracies, you're forced to use them all for the game to be playable - either they're in the conspiracy section meaning they're in effect, or they're in the sideboard and the game won't work.

**Comment by Serrasmurf** [comment]
Issue is still there.

I'm on the 1.6.62 snapshot  and I started a Conspiracy draft in Quest mode. The draft went fine, but I'm unable to start the actual match due to Conspiracies in my sideboard/deck.

When pressing start, the error says Deck Invalid: Deck contains the nonexisting card Adriana's Valor. I'm able to quit the tournament, but not remove them from the deck pool to play with the cards I have.
