### ISSUE TITLE
Moved replacement causing wrong ChangesZoneAll trigger

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1733]
![image](https://user-images.githubusercontent.com/8506892/197491886-040a3bf1-cb39-43d4-94fc-ed5843bb4ae4.png)

When you destroy the Griffin _Welcoming Vampire_ will trigger.
This is because the RiP RE only changes the zone of the copied card, so the `ChangeZoneTable` will be `{Battlefield={Battlefield=[Abbey Griffin]}}`

@Hanmac 
my current idea is to just return `game.getCardState(c)` here:
https://github.com/Card-Forge/forge/blob/e7f6b3371a2642ce625abce01c8b2bab21c2c368/forge-game/src/main/java/forge/game/GameAction.java#L382

or at the very least update the zone of c with the new one?

Edit:
probably not good enough, that would still cause `triggerChangesZoneAll` twice, once from RE ChangeZoneEffect and second from DestroyEffect

**Comment by Hanmac** [comment]
imo what should be done is that RIP does Replace and Update the Destination / zoneTo

**Comment by tool4ever** [comment]
Yea that's probably needed, it will also fix the splitting of simultaneous events into multiple, e.g. in this example _Ranar_ should only trigger once but currently it's twice:

![image](https://user-images.githubusercontent.com/8506892/205458102-d302ff0f-6b87-4dfa-b564-2065ea6c8b30.png)

**Comment by tool4ever** [comment]
Fixing this will also avoid UntilHostLeavesPlay being dropped

**Comment by Hanmac** [comment]
@tool4ever what we could try is pasting the change Zone Table as Replacement parameter to fill

with that, the outer Destroy Effect creates the Table
and the inner Effect notices that its inside a Move Replacement Effect and just updates the data in the Table (with keeping old lki in tact?)
