### ISSUE TITLE
Spined Sliver ability does not calculate number of blockers on resolution

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#1776]
I blocked Spined Sliver and sacced the blocking creature while its trigger was on the stack. However, it resolved and still gave it +1/+1. This is wrong as even though it was blocked, there were 0 blocking creatures at resolution.

I came up against a quest deck with a bunch of similar abilities, so it may not be only for Spined Sliver, but I only observed this case.

**Comment by Hanmac** [comment]
@Northmoc @tool4ever we probably need to remove "TriggerCount$NumBlockers" or something like that

and yeah, it would affect way more cards
