### ISSUE TITLE
Convert is just another word for Transform (//tableflip)

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#1807]
![image](https://user-images.githubusercontent.com/103371817/200148650-bf73a753-f0cc-4cf5-a240-77c54a5cbf5d.png)

I don't want to do it 😬

**Comment by Hanmac** [comment]
or does someone else want to do that?

**Comment by Hanmac** [comment]
Copy from the release notes: https://magic.wizards.com/en/news/feature/the-brothers-war-release-notes

>Convert notes:
>* The convert keyword action functions the same way as the transform keyword action found on some other cards; to convert a permanent on the battlefield, turn it over so that its other face is up.
>* The mana value of a converted permanent on the battlefield is equal to the mana value of the card's front face, no matter which face is up.
>* Converting a permanent doesn't affect any Auras or Equipment that are attached to it. Similarly, any counters on the permanent will remain on that permanent after it converts. Any continuous effects from a resolved spell or ability will continue to affect it. Any spells or abilities on the stack that target a permanent continue to do so after that permanent converts.
>* Any triggered ability of another card that triggers whenever a permanent transforms will also trigger whenever a permanent converts.
>* Similarly, an ability of another card that instructs you to "transform" one of these cards will cause you to convert it, even if that ability doesn't use the word "convert."
