### ISSUE TITLE
Cabaretti Confluence [NCC] - 3rd Ability does not work after selection.

### ISSUE THREAD

**Issue by seryous** [Card-Forge/forge#1839]
**Describe the bug**
The 3rd ability "Creatures target player controls get +1/+1 and gain first strike until end of turn" does not function. The selection of Target Player doesn't activate, ergo no creatures get +1/+1 nor first strike. 

**To Reproduce**
1. Cast Cabaretti Confluence
2. Choose 3rd option "Creatures target player controls get +1/+1 and gain first strike until end of turn" as one of your 3 picks.

**Expected behavior**
Option to choose target player to apply +1/+1 and first strike to creatures owned by player upon selecting 3 functions. 

_6:52 PM, T12.M1: Seryous casts [Cabaretti Confluence](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Cabaretti%20Confluence) [2e8] (mode 2) targeting [Double Vision](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Double%20Vision) [3ef] (mode 3)
6:52 PM, T12.M1: Seryous moves [Double Vision](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Double%20Vision) [3ef] from battlefield to the exile zone (source: [Cabaretti Confluence](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Cabaretti%20Confluence) [2e8])
6:52 PM, T12.M1: Seryous moves [Lightning Greaves](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Lightning%20Greaves) [526] from battlefield to the exile zone (source: [Cabaretti Confluence](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Cabaretti%20Confluence) [2e8])
6:52 PM, T12.M1: Seryous puts [Cabaretti Confluence](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Cabaretti%20Confluence) [2e8] from stack into their graveyard_

**Comment by kevlahnota** [comment]
logs are xmage marking this invalid
