### ISSUE TITLE
Phabine, Boss's Confidant - Only getting 1/1 Tokens and Not +1/+1 for Nonlands.

### ISSUE THREAD

**Issue by seryous** [Card-Forge/forge#1840]
**Describe the bug**
When Phabine, Boss's Confidant's ability triggers, 1/1 tokens are being created when Non-Lands are revealed, instead of controlled creatures getting +1/+1 until end of turn. 

**To Reproduce**
Cast card, Trigger ability when combat phase starts. 

**Expected behavior**
1/1 tokens should be generated when Lands are revealed, otherwise Creatures player controls should get +1/+1 until end of turn. 

**Screenshots**
_7:10 PM, T12.BC: Seryous - Ability triggers: [Phabine, Boss's Confidant](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Phabine,%20Boss's%20Confidant) [aa1] - Parley — At the beginning of combat on your turn, each player reveals the top card of their library. For each land card revealed this way, you create a 1/1 green and white Citizen creature token. Then creatures you control get +1/+1 until end of turn for each nonland card revealed this way. Then each player draws a card.
7:10 PM, T12.BC: Seryous creates a [Citizen Token](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Citizen%20Token) [5f7] token
7:10 PM, T12.BC: Seryous draws a card
7:10 PM, T12.BC: Seryous creates a [Citizen Token](https://github.com/Card-Forge/forge/issues/new?assignees=&labels=&template=bug_report.md&title=#Citizen%20Token) [b1e] token
7:10 PM, T12.BC: Computer 2 reveals **Rite of the Raging Storm**
7:10 PM, T12.BC: Seryous reveals **Awakening Zone**
7:10 PM, T12.BC: Computer 2 draws a card_

**Desktop (please complete the following information):**
 - OS: Win 11
 - Beta Client 1.4.52-V1

**Comment by kevlahnota** [comment]
There is no Forge Beta Client.
Are you using xmage? this is Forge github... you might want to report your issue here: https://github.com/magefree/mage/issues
