### ISSUE TITLE
(A)Ochre Jelly doesn't create copies if it's not in the battlefield anymore

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#1868]
My (A)Ochre Jelly died during an end step. Before its death trigger resolved, I reanimated it with Nim Deathmantle. When the delayed trigger resolved, it did nothing.

**Comment by tool4ever** [comment]
`timestampCheck` problem. we should probably skip LKI cards?

**Comment by Hanmac** [comment]
@tool4ever The card probably needs to be updated to propably use LKI

or is the problem the DelayedTrigger Effect?

timestampCheck needs to be updated which each effect that is updated to handle LKI objects correct
and if it is all of them, could finally be removed

**Comment by tool4ever** [comment]
It already uses `TriggeredCardLKICopy` but the problem is if the card leaves the zone before the delayed trigger gets created

I think I found a workaround for now though

**Comment by Hanmac** [comment]
You need to extend noTimestampCheck

**Comment by tool4ever** [comment]
you mean make it skip LKI?
Hmn...

**Comment by Hanmac** [comment]
No, i mean noTimestampCheck needs DelayedTrigger in the list
