### ISSUE TITLE
Moved replacement chain can sometimes lead to incorrect result

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#1880]
![image](https://user-images.githubusercontent.com/8506892/201516676-1a92904c-2f75-4c83-bd76-f4a2e6994d61.png)

When you run the intrinsic RE first the chain will look like this:

- Play Land `changeZone`
- ETBReplacement for tapped (this is `ReplacementResult.Updated`)
- sacrifice RE (this is full `Replaced`)

Now the problem is while `ReplacementHandler` does store the most recent result here:
https://github.com/Card-Forge/forge/blob/350690ebf5b351a24a7ff75eb63b7df976bc1043/forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java#L314

it still returns the possibly wrong old one which then gets used for the switched logics.

This means _if you choose the same land for the sacrifice choice_ the engine thinks the `LandAbility` should continue and you will end up with the card existing in two zones.

@Hanmac 
As possible fix I just added this at the line above:
`res = result;`

Anything else to consider? 🤔

**Comment by Hanmac** [comment]
@tool4ever i think you should try to see if an Update -> Replaced can make the outer return Replaced too
