### ISSUE TITLE
Commander not respecting Universes Within/Universes Beyond 

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#1927]
When deck building in Commander (and I assume other formats as well) the game doesn't seem to be able to tell that the Universes Within cards are the same as the Universes Beyond ones for name purposes. Example: Chief Jim Hopper and Sophina, Spearsage Deserter are considered the same card, but the game allows both to be in the same Commander deck.

**Comment by paulsnoops** [comment]
Yeah we haven't set that up yet unfortunately
