### ISSUE TITLE
BOT cards not available in a new quest

### ISSUE THREAD

**Issue by corwin72** [Card-Forge/forge#1981]
**Describe the bug**
When Starting a new quest with commander subformat and Starting pool unrestricted, Allow Duplicate Cards, and start with all cards in selected sets, the BOT cards are not included in this pool.

**To Reproduce**
Quest Mode>Start Quest:
Click check marks for Novice, Fantasy Mode, Commander Subformat, Allow duplicate cards, and Start with all cards in selected sets.
Click Embark!
Enter the quest name. Click ok.
Click Build a New Deck
BOT cards are not included in the Quest Inventory

**Expected behavior**
When you create a new deck there will be 4 copies of all BOT cards available to add to a deck.

**Screenshots**
Attached is a screen shot of a search for Prime that should include Optimus Prime, Hero.
![image](https://user-images.githubusercontent.com/65971977/204296001-8ffb80a5-889e-4d34-8fcf-5e65a656a2cd.png)

**Desktop (please complete the following information):**
 Windows 10

**Additional context**
There have been newer sets added and I feel like this omission is an issue not a feature request.

**Comment by kevlahnota** [comment]
@Hanmac to enable promos, the user needs to change it's quest preference to enable promo cards...
![image](https://user-images.githubusercontent.com/9781539/204386059-bbb5ea6e-3ef3-4822-ba9f-bac40dbcced8.png)

**Comment by corwin72** [comment]
I flipped that flag to 1 and restarted forge then started a new quest with above values and BOT cards were not included. Ryu, World Warrior is included in the new quest. I would consider this the same type of Promo.

**Comment by corwin72** [comment]
I also did a clean install and started a new quest and received the same result. Can you duplicate creating a new quest with all cards shows Bot cards available to add to a quest deck?

**Comment by corwin72** [comment]
Has anyone thought of a reason that BOT cards are not showing up in the initial all cards but can be won as rewards?
