### ISSUE TITLE
Illegal access concerns

### ISSUE THREAD

**Issue by eight85** [Card-Forge/forge#2007]
**Describe the bug**
Starting the forge.sh script gives the following in terminal 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/eightbitbang/Games/forge-gui-desktop-1.6.53/forge-gui-desktop-1.6.53-jar-with-dependencies.jar) to field java.util.EnumMap.keyType
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**To Reproduce**
1. run the forge.sh script

**Expected behavior**
Illegal access should not be happening

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.10

**Additional context**

**Comment by kevlahnota** [comment]
what JDK version do you use? try using java 17 or higher. you can disable illegal access permit by editing the forge.sh but your quest save will stop working since xstream uses reflection which needs this.
