### ISSUE TITLE
Six-Sided Die not working

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#2012]
I cast Six-Sided Die and rolled a 3, but nothing happened. Not sure if all or any of the other options are broken as well, or if it defaulted to 1 regardless of the roll which I wouldn't be able to tell.

**Comment by kevlahnota** [comment]
seems to work fine... could you be more specific? what card and what forge version?

https://user-images.githubusercontent.com/9781539/205470918-2c10d10f-260a-4b16-a5fe-2c5d7251c0aa.mp4

**Comment by Samthere** [comment]
Specifically the spell, Six-Sided Die (https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=580661) which has different outcomes based on the result of a die roll.
I'm playing on Windows, in Quest, on the current Snapshot.

**Comment by kevlahnota** [comment]
seems to work on 1202 snapshots... 

https://user-images.githubusercontent.com/9781539/205471279-43c15536-703d-4921-8fb6-406760721281.mp4

**Comment by Samthere** [comment]
Hmm not sure, I'll keep an eye on it!

**Comment by kevlahnota** [comment]
well it returned.. seems the bug is introduce when playing cards from dev mode...
