### ISSUE TITLE
Missing images for getting started with IntelliJ IDE

### ISSUE THREAD

**Issue by JStatnekov** [Card-Forge/forge#2018]
On this page [https://github.com/Card-Forge/forge/wiki/IntelliJ-setup](https://github.com/Card-Forge/forge/wiki/IntelliJ-setup) that outlines the steps for configuring the project  for doing development in IntelliJ, the images are not available. This makes the setup considerably harder for simpletons like myself who are bad at following directions without a visual aid.

**Comment by kevlahnota** [comment]
fixed.. check latest revision.. https://github.com/Card-Forge/forge/wiki/IntelliJ-setup

**Comment by JStatnekov** [comment]
Most excellent, thank you!
