### ISSUE TITLE
cipher card

### ISSUE THREAD

**Issue by gek92** [Card-Forge/forge#2043]
I play a card with **cipher** like Stolen Identity. The problem occures when the encoded effect triggers on a combat damage resolving moment.
The game copy the encoded card and it resolves with a new cipher trigger, but the problem is that: IRL when the copy goes to exile, it stops to exist and it doesn't trigger the new encoding. IN FORGE it continues to exist and during another damage step it triggers another additional time. and so on.

![Stolen-Identity](https://user-images.githubusercontent.com/120029732/206195799-ddb0167a-bc0e-49fc-ba26-2630e7f7e5dd.jpg)

sorry for my english

**Comment by tool4ever** [comment]
Can't reproduce, your version might be outdated
