### ISSUE TITLE
GY replacement effects mess up LKI

### ISSUE THREAD

**Issue by asvitkine** [Card-Forge/forge#2096]
Example repro:
  1. Have Marath on the field.
  2. Have Bow of Nylea, giving Marath deathtouch when attacking
  3. Attack and remove all remaining counters from Marath to deal damage to a creature that has more toughness

Expected: Marath dies due to all counters being removed, but damage still goes through as deathtouch, via LKI.
Actual:
1. The above is true if there is no replacement effect for the GY.
2. If Marath is your commander and you put it into command zone, the replacement effect messes up LKI and the creature survives.
3. Similarly, if Marath is not your commander, but Anafenza, the Foremost is on the field, the GY effect also results in damage not being dealt as deathtouch.

Some repro states set up in dev mode:
1. Attacking into Anafenza 
[state_marath.txt](https://github.com/Card-Forge/forge/files/10224782/state_marath.txt)
2. Attacking into some other 4-toughness creatures
[state_marath2.txt](https://github.com/Card-Forge/forge/files/10224784/state_marath2.txt)

(Normally, it would happen when removing last 1/1 counter, but for the purpose of the game states, just remove all 3.)

**Comment by asvitkine** [comment]
@tool4ever I saw you have a PR related to LKI fixes. Any idea on this one?

**Comment by tool4ever** [comment]
Thanks for the states

Yea, this is a bigger engine problem that would most likely require an extended rework to fully address all corner cases

I won't be taking that on anytime soon but maybe I'll be able to make a small fix so the current solution becomes somewhat more reliable
