### ISSUE TITLE
Commander precons should be stored in commanderprecons dir, not precons.

### ISSUE THREAD

**Issue by fechmistrz** [Card-Forge/forge#2104]
**Is your feature request related to a problem? Please describe.**
Some commander decks are stored in precons/ directory, which makes them visible even when playing non-commander game (like Vintage or Legacy).

**Describe the solution you'd like**
Move commander decks to commanderprecons directory.

**Describe alternatives you've considered**
In GUI, hide decks containing commander section when Commander tick box is not selected on the top (in main window, where players and decks are selected)

**Additional context**
Entries with "wrong directory" could be moved right away. Entries with "duplicated" require minor changes.
```
forge/forge-gui/res/quest/precons for i in *; do if ! grep -q 'commander' "$i"; then continue; fi; if [[ -f "../commanderprecons/$i" ]]; then echo "Duplicated: $i"; else echo "Wrong directory: $i"; fi; done | sort 
Duplicated: Built from Scratch.dck
Duplicated: Counterpunch.dck
Duplicated: Devour for Power.dck
Duplicated: Eternal Bargain.dck
Duplicated: Evasive Maneuvers.dck
Duplicated: Forged in Stone.dck
Duplicated: Guided by Nature.dck
Duplicated: Heavenly Inferno.dck
Duplicated: Mind Seize.dck
Duplicated: Mirror Mastery.dck
Duplicated: Nature of the Beast.dck
Duplicated: Peer Through Time.dck
Duplicated: Political Puppets.dck
Duplicated: Power Hungry.dck
Duplicated: Sworn to Darkness.dck
Wrong directory: Arcane Maelstrom.dck
Wrong directory: Arm for Battle.dck
Wrong directory: Aura of Courage.dck
Wrong directory: Buckle Up.dck
Wrong directory: Coven Counters.dck
Wrong directory: Draconic Rage.dck
Wrong directory: Dungeons of Death.dck
Wrong directory: Elven Empire.dck
Wrong directory: Enhanced Evolution.dck
Wrong directory: Faceless Menace.dck
Wrong directory: Heads I Win, Tails You Lose.dck
Wrong directory: Land's Wrath.dck
Wrong directory: Lorehold Legacies.dck
Wrong directory: Merciless Rage.dck
Wrong directory: Mystic Intellect.dck
Wrong directory: Phantom Premonition.dck
Wrong directory: Planar Portal.dck
Wrong directory: Primal Genesis.dck
Wrong directory: Prismari Performance.dck
Wrong directory: Quantum Quandrix.dck
Wrong directory: Reap the Tide.dck
Wrong directory: Ruthless Regiment.dck
Wrong directory: Silverquill Statement.dck
Wrong directory: Sneak Attack.dck
Wrong directory: Spirit Squadron.dck
Wrong directory: Symbiotic Swarm.dck
Wrong directory: Timeless Wisdom.dck
Wrong directory: Undead Unleashed.dck
Wrong directory: Upgrades Unleashed.dck
Wrong directory: Vampiric Bloodline.dck
Wrong directory: Witherbloom Witchcraft.dck
```

Example of minor changes:
```
forge/forge-gui/res/quest/precons diff Sworn\ to\ Darkness.dck ../commanderprecons/Sworn\ to\ Darkness.dck 
3,13c3,5
< [shop]
< WinsToUnlock=0
< Credits=5000
< MinDifficulty=0
< MaxDifficulty=5
< Description=Ob Nixilis of the Black Oath is a ruthless tyrant who will stop at nothing to achieve his aims. This planeswalker commander saps his oppenents strength, summons powerful demons to the battlefield, and compels the dead to rise and fight again.
< Set=C14
< Image=sworn_to_darkness.png
< [commander]
< 1 Ob Nixilis of the Black Oath+|C14
< [main]
---
> [Commander]
> 1 Ob Nixilis of the Black Oath|C14
> [Main]
71c63,66
< 32 Swamp|C14
---
> 8 Swamp|C14|1
> 8 Swamp|C14|2
> 8 Swamp|C14|3
> 8 Swamp|C14|4
81a77,78
> [Sideboard]
> 
```

**Comment by fechmistrz** [comment]
Small update: greps above should be invoked with -i flag because sometimes it's written commander and sometimes Commander.

**Comment by Fulgur14** [comment]
It seems that the commanderprecons has all the decks that it should -- so it's just deleting the commander decks from precons?

**Comment by tool4ever** [comment]
the list is probably outdated now but this should lead to no loss of metadata

**Comment by Fulgur14** [comment]
On the other hand, these precons have quest information and such. All seem to have the same ones, but still. And the descriptions. Perhaps the solution would be to put them in a subdirectory or such, and only access them when the quest allows commander play? I don't play the quest mode, so I have no idea how that works.

**Comment by tool4ever** [comment]
yea they live there because of the additional metadata
but that is simply ignored when used in other gamemodes
so there is should be no reason to duplicate them

**Comment by Fulgur14** [comment]
So I should replace the precons in the commanderprecons folder with these? I don't really want to do that. Right now they all have the same format, same name structure... I don't want some to differ. I'd prefer to have commander precons used for quests separate, then they could be perhaps edited for better AI compatibility or such.

**Comment by tool4ever** [comment]
not replace, merge...
if that means aligning some names that's perfectly fine 🤷‍♂️

**Comment by Fulgur14** [comment]
What's the difference?

**Comment by tool4ever** [comment]
not flooding our assets with duplicates

**Comment by Fulgur14** [comment]
I think I still don't really understand this.

Take Adaptive Enchantment, for example. The version in precons has header

[metadata]
Name=Adaptive Enchantment
[shop]
WinsToUnlock=0
Credits=3600
MinDifficulty=0
MaxDifficulty=5
Description=Estrid wears many faces, only occasionally wearing her own. Her arsenal of enchanted masks lets her shift seamlessly between the powers and fighting styles of countless creatures to adapt to enemy tactics.
Set=C18
Image=adaptive_enchantment.jpg

The one in commanderprecons has header

[metadata]
Name=Adaptive Enchantment [C18] [2018]
Set=C18

So you want to copy the [shop] information from commander decks in precons to those in commanderprecons to preserve that info, and delete all commander decks from precons?

**Comment by tool4ever** [comment]
the same logic is already used by normal precons
and more decks are already getting duplicated by adventure planes now: #11211

though I really thought `commanderprecons` was also hooked up in quest mode
but it's starting to look like that subdirectory was chosen rather randomly 🤦‍♂️
so we probably need to fix that first :/

**Comment by Fulgur14** [comment]
OK. I'm sorry to have so many comments, and I know you marked this as an issue for newbies, but my programming knowledge is stuck in the 1990's. I'm happy enough to work on those parts of Forge I can understand :)

**Comment by tool4ever** [comment]
Yea I'll try to look into the code, though not a huge priority for me

then after you or someone else can sort out the assets

**Comment by Fulgur14** [comment]
OK

**Comment by tool4ever** [comment]
A few decks also have the Description,Set,Image fields in shop section, but they belong to metadata.
