### ISSUE TITLE
Rock Hydra's replacement effect doesn't prevent damage

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#2126]
My 8/8 Rock Hydra got killed in combat by two 2/2s! It seems like the replacement effect is removing the counter but not preventing the damage, resulting in it dying twice as easily.

For example, this buddy here took a damage, had a counter removed, but still has a damage marked on it:

![image](https://user-images.githubusercontent.com/29505281/208243037-7330027f-d04d-43a1-b284-e11699498a39.png)

**Comment by tool4ever** [comment]
Tricky card, I think I got it fixed but maybe you will prove me wrong again :)
