### ISSUE TITLE
AI with Bow of Nylea will keep targeting a dead creature repeatedly

### ISSUE THREAD

**Issue by asvitkine** [Card-Forge/forge#2133]
**Describe the bug**
AI with Bow of Nylea will keep targeting a dead creature repeatedly (to deal 2 dmg to a flying creature).

Once the creature dies, each turn the AI controlling Bow of Nylea will activate it, with target illegally set to the creature in the graveyard. Debugging the cause, it's because we're not resetting the target in `damageChoosingTargets()` which was introduced by this commit:
https://github.com/Card-Forge/forge/commit/0ca0458656a2982925a7dcb02c817b9e0435094a

If I remove the if statement around `resetTargets()`, like it was before, the bug goes away.
@Agetian do you remember the details of that change? Why do we need to not reset the targets for Domri's Ambush?

**Comment by tool4ever** [comment]
Fixed by #2670
