### ISSUE TITLE
Allow easy handling of custom skins

### ISSUE THREAD

**Issue by gbraad** [Card-Forge/forge#2142]
I used to be able to place my own dark/bright skins in the `/res/skins/` folder:

  * https://github.com/gbraad/cardforge-skin-night
  * https://github.com/gbraad/cardforge-skin-day

... but this does not seem to work on more recent versions. Would it be possible to allow skins to be loaded from the user data folder?

Note: the bright skin was made for use on an Eink tablet. The current theme shows way too much gradients/colors to be correctly drawn.

**Comment by paulsnoops** [comment]
Custom skins can be put in: C:/Users/<your username>/Application Data/Local/Forge/Cache/skins

**Comment by gbraad** [comment]
Got it working on Android and desktop. Quite confusing on some platforms as on Android it can either be in `Android/obb` or external storage.
