### ISSUE TITLE
Sixth Sense (forge-gui-desktop-1.6.53)

### ISSUE THREAD

**Issue by Cernelius** [Card-Forge/forge#2173]
**Describe the bug**
"Sixth Sense" gives the controller of the creature to which it is attached the possibility of drawing a card.

**To Reproduce**
Attach "Sixth Sense" to a creature controlled by an opponent.
The opponent gets the card instead of you.

**Expected behavior**
The card drawing should always be offered to the controller of the enchantment.

**Desktop (please complete the following information):**
Windows 10
Edge

**Comment by Cernelius** [comment]
Why is there the option of opening the issue as "Bug report" or "Feature request" if nothing related seems to show? Or does it?

Anyway, this is a bug report.

Please fix. Thank you.

**Comment by tool4ever** [comment]
No, you are mistaken

The trigger is granted to the creature, so the "You" refers to its current controller
