### ISSUE TITLE
AI Cast Warlord's Elite with 3 basic lands and an artifact

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#2177]
The AI had 2 forests, a plains and a Goblin Firebomb (artifact) out, but managed to cast Warlord's Elite. It failed when I tried to do it myself, but the AI could!

**Comment by Samthere** [comment]
Seen it a few more times now - looks like the AI ignores the tapping cost or taps the lands it's using anyway!

**Comment by 8BitAvenger** [comment]
This continues to be an issue. AI (haven't tested on the player side) ignores the additional cost of Warlord's elite. "
As an additional cost to cast this spell, tap two untapped artifacts, creatures, and/or lands you control." They have cast it multiple times vs me without fulfilling any of the additional costs.

**Comment by RyushoYosei** [comment]
![image](https://github.com/user-attachments/assets/95622c3b-62ef-40ff-b1e8-00c4daa6188f)

This is still an issue, even now. IT just did it to me.
