### ISSUE TITLE
S21 Ultra landscape mode issue

### ISSUE THREAD

**Issue by derekR14** [Card-Forge/forge#2183]
**Describe the bug**
On my S21 Ultra I can't get the game to run in landscape mode. It runs fine in portrait mode but it's not the best layout for playability. Even when I check the settings box for Landscape mode it still stays in portrait. 

Maybe there are config/xml settings I could change to get it to work I'm open to that. 

**To Reproduce**
1. Open App with phone in portrait or landscape orientation 

**Expected behavior**
Open the App and it runs in landscape mode. 

**Smartphone (please complete the following information):**
 - Device: S21 Ultra 
 - OS: Android 12
 - Versions: 3 versiond tested: 1.6.54.1220 Snapshot. 1.6.54.1227 Snapshot. 1.6.53.001

**Additional context**

**Comment by kevlahnota** [comment]
Did you try opening classic mode, then aettings, then check landscape mode and restart. Adventure mode settings is known not applying some settings.

**Comment by derekR14** [comment]
I did not try that thank you! That allows it to run in landscape. Just didn't know thats the way it needed to be changed. Thanks again.
