### ISSUE TITLE
Can't respond if no valid blockers / no block declared 

### ISSUE THREAD

**Issue by 420BlazeItFaggot** [Card-Forge/forge#2196]
If this is intentional game design that has always been a part of mtg than I'm sorry and will delete, but I've been playing this game for literally years and that's how we've always played everywhere (pre-release, fnm, commander playgroups).
Before damage is distributed during combat player can respond, example:
Lightning Reaver: 3/3 fear (rest unimportant) attacks
No valid blockers
I want to cast teferi protection before damage is distributed
I used to do exactly that in paper mtg. Before damage is distributed I would cast teferi protection (or respond in some other way) in paper magic and in forge it seems you can't do any response if you entered combat but had no valid blockers.
Another example: 
being attacked let's say by a 1/1 flyer token
no valid blockers again, I have condemn on my hand (and mana to cast it)
Forge won't give me an option to cast condemn and I will get hit by it
One more example:
Being attacked by a 4/4 creature  (no other abilities, no trample)
declare block with my 1/3 bottled gnomes
before damage is distributed I want to sacrifice bottled gnomes to gain 3 life (since he's gonna die anyway might as well get 3 life)
Once again forge doesnt give me the option to do that. There is no prompt before damage distribution
I wanted to post this on discord but you require phone verification which I'm not gonna do.
Aside from that forge's been great so far so I'm hoping there is a hidden option in the menu I can't find.
And seriously, I'm in the barenstien bears demension if I got the rules wrong all of the sudden

**Comment by kevlahnota** [comment]
did you enable phase stop before combat damage?

**Comment by 420BlazeItFaggot** [comment]
wow thanks a lot man
