### ISSUE TITLE
"Can't enter" effects (Moved Prevent$) mess up ChangedState

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#2197]
Examples with _Grafdigger's Cage_ in play:
- Cast _Ever After_ on _Abbey Griffin_. You now have a Zombie Griffin in your graveyard
- Try to return artifact creature that got Unearth from _Ghost Ark_. It now lost Unearth
- _Startled Awake_ will transform and then stay in the graveyard, but it should be allowed to ETB

Also combined with _Containment Priest_ Forge allows you to order both so you could make it exile which seems wrong too.

They should probably be done as statics?

**Comment by Hanmac** [comment]
@tool4ever 
> 614.17. Some effects state that something can’t happen. These effects aren’t replacement effects, but follow similar rules.

**Comment by Hanmac** [comment]
we might even turn more Cant Statics into Replacement effects
