### ISSUE TITLE
Error: Forge is missing some JVM options for reflective access

### ISSUE THREAD

**Issue by Archargelod** [Card-Forge/forge#2221]
**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04 aarch64
 - Forge: 1.6.54.SNAPSHOT-2023.1.8
 - Java: openjdk 17.0.5 2022-10-18

**Describe the bug**
When starting forge adventure mode with a shell script - it fails to load, showing a javaVM white error screen (see screenshot).

**To Reproduce**
1. extract snapshot archive
2. open terminal
3. convert script to unix format: `dos2unix forge-adventure.sh`  to fix [#2220](https://github.com/Card-Forge/forge/issues/2220)
4. make script executable: `sudo chmod +x forge-adventure.sh`
5. run the script with `./forge-adventure.sh`
6. See error

**Expected behavior**
Forge-adventure app starts and loads atleast to a menu.

**Screenshots**
![java error](https://user-images.githubusercontent.com/60652075/211259962-b547f0e8-ea24-4db5-8953-dee55a4acb5a.png)

**Affected files**
https://github.com/Card-Forge/forge/blob/master/forge-gui-mobile-dev/src/main/config/forge-adventure.sh
https://github.com/Card-Forge/forge/blob/master/forge-adventure/src/main/config/forge-adventure-editor.sh

**Fix proposed by [kevlanhota](https://github.com/kevlahnota) on [slightly-magic forum](https://www.slightlymagic.net/forum/viewtopic.php?p=254261#p254261)**
I tested it and it fixes the problem.
```
#!/bin/sh
cd $(dirname "${0}")
java -Xmx4096m --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/javax.swing.border=ALL-UNNAMED --add-opens java.desktop/javax.swing.event=ALL-UNNAMED --add-opens java.desktop/sun.swing=ALL-UNNAMED --add-opens java.desktop/java.awt.image=ALL-UNNAMED --add-opens java.desktop/java.awt.color=ALL-UNNAMED --add-opens java.desktop/sun.awt.image=ALL-UNNAMED --add-opens java.desktop/javax.swing=ALL-UNNAMED --add-opens java.desktop/java.awt=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -Dfile.encoding=UTF-8 -jar $project.build.finalName$
```

**Comment by tehdiplomat** [comment]
Can you just push a PR rather than an issue that lists the files and the solution?

**Comment by Archargelod** [comment]
To be honest, I'm not a developer, so:
1. I have no idea if it will break anything
2. I've almost no experience with git (apart from simple cloning or actions available on website)
3. with my shitty internet it'd take me hours to even clone the repo
4. it's not my solution and it was given by an active developer, so I assumed it was a known issue.
