### ISSUE TITLE
Adding companion to commander deck?

### ISSUE THREAD

**Issue by invalidCards** [Card-Forge/forge#2235]
I've searched high and low through the deck editor but I can't find any way to add a companion to a commander deck. Is this currently implemented at all? Am I missing something blindingly obvious? Please assist :stuck_out_tongue:

**Comment by kevlahnota** [comment]
did you try adding the companion card to sideboard? then start the game. It should ask which companion to use at the start of the game.

**Comment by invalidCards** [comment]
Yup, works like a charm. No idea why I didn't think of that before :sweat_smile: thanks!
