### ISSUE TITLE
Cost merging needs additional logic

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#2244]
If _Drought_ affects a spell with multiple black shards the resulting sacrifices should happen simultaneously (e.g. a single ChangesZoneAll trigger for _Nefarious Imp_).

 - But what about a spell like _Corpse Cobble_ that has another sacrifice cost? Their types aren't compatible, will that lead to two triggers instead then?
 - In either case sacrificing a manland for the Drought part should probably not increase the total power of the new token

**Comment by Hanmac** [comment]
* _Rescue from the Underworld_ for example is something where the additional cost matters

**Comment by Hanmac** [comment]
One idea: have the outer Cost class itself handle the bigger Trigger Lists

so the CostParts doesn't need to be merged, the All Trigger still works
and we could differ with the Paid lists if the Costs was paid using the cards own abilities (like the AddionalCost from cards like Rescue of the Underworld) or from other Cards like Drought

**Comment by tool4ever** [comment]
A lot of the merging is for exotic cumulative upkeep.
I think I'll try to refactor that so it creates the full cost directly.

**Comment by tool4ever** [comment]
Some AI parts also expect the merging to make better decisions.
E.g. multiple _Cultist of the Absolute_ causing Ward life payments

**Comment by Hanmac** [comment]
hm maybe we need two different functions for merging costs? an extra one for ai?

**Comment by tool4ever** [comment]
I found this:
![grafik](https://user-images.githubusercontent.com/8506892/228782517-82f89dd3-55a1-4c07-8ea9-c63f19c282d0.png)

So following that reasoning nothing seems to contradict these results:
- {B} or {BB} SA with Drought -> 1 ChangesZoneAll trigger
- Corpse Cobble with Drought -> 2 ChangesZoneAll

Therefore I am considering to close this after Part 2.
