### ISSUE TITLE
Assemble the Team tutors up 1/3 of my deck instead of just 1 card

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [Card-Forge/forge#2246]
**Describe the bug**
Assemble the Team lets me select multiple cards and gives me all cards selected to my hand instead of just 1 card

**To Reproduce**
1. Activate the card 'Assemble the Team'
2. Select a card
3. Select a card
4. Select a card
5. Select a card
6. Select a card
7. ...

**Expected behavior**
You should only be able to select 1 card and get only that card to your hand

**Desktop (please complete the following information):**
 - OS: Ubuntu (Linux)
 - Version: 1.6.54.SNAPSHOT-2023.1.14

**Additional context**
Why is this always happening to me :rofl: :rofl: :rofl:

**Comment by Simisays** [comment]
Thanks should be an easy fix
