### ISSUE TITLE
Lukka, Bound to Ruin

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#2250]
>  [-4]: Lukka deals X damage divided as you choose among any number of target creatures and/or planeswalkers, where X is the greatest power among creatures you controlled **as you activated this ability**. 

Compare with _Monstrous Onslaught_ and:
> where X is the greatest power among creatures you control **as you cast this spell**.

imo it should be more hard-coded for DividedAsYouChoose stuff ... so it doesn't change after the Spell/Ability was put on the Stack?

**Comment by Hanmac** [comment]
@tool4ever can you look at this too? technically it doesn't need to set SVar variables, or check the MinMax of the Targets again after the "divided as you choose" values are set?

**Comment by tool4ever** [comment]
I did a few quick tests on _Monstrous Onslaught_ without the trigger and it seemed to work fine

So maybe this card won't need changes
