### ISSUE TITLE
Witch's Cottage entered tapped but still triggered

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#2260]
I played Witch's Cottage (ELD) off of Siphon Insight (MID). It correctly entered tapped, but still triggered the ability for entering untapped.

**Comment by Samthere** [comment]
The same thing happened when I played Idyllic Grange from their hand with Sen Triplets!

**Comment by tool4ever** [comment]
Should have been fixed by #2259
Please retry on upcoming snapshot

**Comment by Samthere** [comment]
Yep, looks like it's working now, thanks!
