### ISSUE TITLE
Churning Reservoir

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#2267]
>  Churning Reservoir {R}
> Artifact
> At the beginning of your upkeep, put an oil counter on another target nontoken artifact or creature you control.
> {2}, {T}: Create a 1/1 red Phyrexian Goblin creature token. **Activate only if an oil counter was removed from a permanent you controlled this turn or a permanent with an oil counter on it was put into a graveyard this turn.**

do we already have a Table to check for "CountersRemoved" from Permanent you controlled?

**Comment by tool4ever** [comment]
No

We only have `Game.countersAddedThisTurn`

if we mirror that LKI needs to be created everytime that happens 😭 

maybe wait for rest of spoilers if it can be cheated with a boolean? 🤔

**Comment by Hanmac** [comment]
hm we need to check if you controlled the Permanent at the moment when you removed the oil counter
That might happen either as Cost OR as Effect

so we probably need to keep LKI infos about that (for a Turn)

**Comment by Hanmac** [comment]
Updated Official Oracle

it only checks that you controlled the Permanent that got the counter removed.
it doesn't care WHO removed the counter. That is good for us.

**Comment by Hanmac** [comment]
i will probably use `ArrayListMultimap<CounterType, Pair<Card, Integer>>` to implement that so i can better store the LKI of Card

**Comment by Hanmac** [comment]
Engine works, Card Still missing
