### ISSUE TITLE
Expand the Sphere

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#2278]
> Expand the Sphere
> 3G
> Sorcery
> Look at the top six cards of your library. Put up to two lands onto the  battlefield tapped. Put the rest on the bottom of your library in a  random order. If you didn't put a land onto the battlefield, **proliferate a number of times equal to the difference**.

Extend Proliferate Effect using a Num Parameter for looping. The Proliferate Trigger should still be inside

**Comment by tool4ever** [comment]
A bit short on time currently and I def want to finish Enlist first

mb @Northmoc can take a shot at it?

**Comment by Hanmac** [comment]
checkout other Effects that uses `Num$` like ScryEffect

Use ReplacementEffect first to get the updated number. (ReplacementResult.Updated)

then use the Number to loop around CountersProliferateEffect.

all the stuff with CountersTable and ProliferateTrigger should be inside the loop

**Comment by Northmoc** [comment]
Sure, I should be able to take a look!

Thanks as always for the leads @Hanmac 😁
