### ISSUE TITLE
Vanish Into Eternity and similar

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#2284]
Improve static ability condition checks to be more like spell ability condition checks for this card an similar –

              shouldn't it be easier way to code this? I know that the other cards are like this too

but shouldn't be a Condition Present work too?

_Originally posted by @Hanmac in https://github.com/Card-Forge/forge/pull/2281#discussion_r1082253455_

**Comment by Hanmac** [comment]
imo ValidTarget$ should work already

_Originally posted by @tool4ever in https://github.com/Card-Forge/forge/pull/2281#discussion_r1082550364_

**Comment by squee1968** [comment]
Fixed Vanish in my PR
