### ISSUE TITLE
Something about Thirst for Knowledge and similar cards. 

### ISSUE THREAD

**Issue by cicoa** [Card-Forge/forge#2299]
Hello.  If I want to discard two artifact cards for discard effect of "Thirst for knowledge"(or two basic land cards for Thirst for discover), what shall I do? Thanks for your efforts.

**Comment by tool4ever** [comment]
> You can discard either one artifact card or two cards which may or may not be artifacts. If you really want to, you can discard two artifact cards. 

Seems this was handled incorrectly, thanks for the report.
