### ISSUE TITLE
 Feather, the Redeemed - stack not processed correctly

### ISSUE THREAD

**Issue by root-as** [Card-Forge/forge#2302]
**Describe the bug**
Feather deals no damage to an opponent if Feather triggers.
Other effects that come at the end of stack also don't work: ex. lifelink

**To Reproduce**
1. Cast Feather
2. Attack with Feather
3. Cast instant and target feather ex. +3/+3 (Brute Force)
4. Stack is processed but no damage is being dealt.

**Expected behavior**
Damage should be dealt.

**Desktop (please complete the following information):**
 - OS: WIN 11

**Additional context**
Forge Version: forge-gui-desktop-1.6.54.SNAPSHOT-2023.1.23

**Comment by tool4ever** [comment]
Can't reproduce
There must be another card in play that prevents it

**Comment by root-as** [comment]
> Can't reproduce There must be another card in play that prevents it

Issue can be deleted

I was mistakenly already in CD phase. Sorry for wasting your time and opening this issue, but many thanks for clearing it up.
