### ISSUE TITLE
Can't choose order of actions for Pulmonic Sliver when there's a board wipe.

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#2307]
I had a bunch of slivers out, including Pulmonic Sliver, and the opponent board wiped with Kindred Dominance. The game chose the order of destruction, which limited what I could do with choosing what goes on top and in what order.

It also didn't give me the option for creatures after Pulmonic Sliver was put away. I think this is wrong, because the slivers all died with that ability, so each should have the option to replace itself regardless of when it went. Not 100% sure on that though.

Windows 1.6.54.SNAPSHOT-2023.1.23

**Comment by Hanmac** [comment]
@tool4ever the Replacement Effect of Pulmonic Sliver should have used LastStateBattlefield?

**Comment by tool4ever** [comment]
Probably difficult to fix cleanly...

We only have the "CheckSelfLKIZone$" workaround for such cases but it seems since this RE is granted by static ability the other slivers are currently losing it too early when it gets recalculated :/

**Comment by Hanmac** [comment]
Leave the Battlefield Replacement Effects should better use LastStateBattlefield, so CheckSelfLKIZone should not be needed

**Comment by tool4ever** [comment]
@Samthere 
after the fix lands for now you also need this setting:
![grafik](https://user-images.githubusercontent.com/8506892/215075672-165f615a-f4e8-447a-af74-d537b5688aa6.png)
