### ISSUE TITLE
A bug about puzzle mode

### ISSUE THREAD

**Issue by cicoa** [Card-Forge/forge#2309]
Some puzzles begin at opponent's Combat phase, and opponent have declared attackers. So these puzzles should begin at Declare attacker step and I should have priority before declaring blockers. 

But when I play these puzzles in forge, I begin at Declare blocker step. But I need do something before declaring blocker to solve these puzzles. So I can't solve them in forge.

e.g. PC_012612.pzl 

Thanks for your efforts

**Comment by kevlahnota** [comment]
Did you try enable phase stop on all combat steps involved and reload the puzzle?

**Comment by cicoa** [comment]
> Did you try enable phase stop on all combat steps involved and reload the puzzle?

Oh, my bad. I don't let it stop at declare attacker step. Thank you.
