### ISSUE TITLE
Card Selection Visual Bug - Greyed out colors

### ISSUE THREAD

**Issue by Sub-Lockdown** [Card-Forge/forge#2365]
**Describe the bug**
When using the Deck Builder, Quest Deck Builder, and Spell Shop, the right hand pane is greyed although it roughly works. There also a checked pattern across the tabs of that location, preventing from switching tabs.

**To Reproduce**
1. Go to Deck Builder, Quest Deck Builder, or Spell Shop
2. See error

**Expected behavior**
This used to be clear

**Screenshots**
![image](https://user-images.githubusercontent.com/9663170/216190330-d9e169a3-9c47-42b4-9c51-243ece74fd10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave 
 - Version: v1.47.186

**Additional context**
This issue occurred with Forge 1.6.53 and then I downloaded 1.6.54 and the issue persisted.

**Comment by kevlahnota** [comment]
Did you try to reset the layout in the settings?

**Comment by Sub-Lockdown** [comment]
This did it for me, not sure what started it but it now looks good, thanks!
