### ISSUE TITLE
mothdust changeling flying does not seem to work for blocking

### ISSUE THREAD

**Issue by protective1** [Card-Forge/forge#2378]
Opponent attacks with flying creature. [Mothdust changeling card](https://gatherer.wizards.com/pages/Card/Details.aspx?multiverseid=143333)  says tapping another creature will allow mothdust to fly.  While selecting blockers, I click on mothdust to use this flying ability, but still can't block flying creature with mothdust changeling.  Instead of blocking, tapping mothdust changeling again causes prompt to tap yet another creature to make mothdust fly.  I thought flying mothdust should now be able to block flying creature, but this doesn't work properly.

**Comment by tool4ever** [comment]
You must do it before blockers are declared or it's too late

**Comment by protective1** [comment]
Thanks for explaining
