### ISSUE TITLE
Jace, the Perfected Mind can use multiple planeswalker abilities in a turn.

### ISSUE THREAD

**Issue by corwin72** [Card-Forge/forge#2385]
Jace, the Perfected Mind is currently not functioning correctly. 
When it is on the battlefield you can use the +1 ability then use the -2 or -x ability as well.
Expected behavior is to use one ability per turn.

This issue was found in"
1.6.55.SNAPSHOT-2023.2.3

**Comment by Simisays** [comment]
Thanks will be fixed
