### ISSUE TITLE
The Ruinous Powers card not causing loss of life.

### ISSUE THREAD

**Issue by Pumatyger** [Card-Forge/forge#2400]
**Describe the bug**
Card "The Ruinous Powers" last ability is not causing the owner to lose life when casting the exiled card.

**To Reproduce**
1. Have Ruinous Powers in play on your side
2. Exile a card with a CMC of 1 or more
3. Cast the Exile card

**Expected behavior**
Owner of the exiled card should lose life equal to the converted casting cost.

**Screenshots**
https://i.imgur.com/jx65Nki.jpeg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: forge-gui-desktop-1.6.54.SNAPSHOT-2023.1.16

**Comment by tool4ever** [comment]
@Simisays 
can you try to reproduce? It seemed to work fine for me 🤷‍♂️

**Comment by Simisays** [comment]
@tool4ever Same it seems to work fine.
![image](https://user-images.githubusercontent.com/67333662/216821058-13161d25-7c8c-4df3-b7c3-22b5ec54f55c.png)

**Comment by Pumatyger** [comment]
Same result for me, no life loss, and even updated to the latest version of forge

forge-gui-desktop-1.6.55.SNAPSHOT-2023.2.5

https://i.imgur.com/yb79AeY.png

**Comment by kevlahnota** [comment]
> Same result for me, no life loss, and even updated to the latest version of forge
> 
> forge-gui-desktop-1.6.55.SNAPSHOT-2023.2.5
> 
> https://i.imgur.com/yb79AeY.png

I just tested latest snapshots and it's working fine too. Did you extract snapshots to different folder?

https://user-images.githubusercontent.com/9781539/216852003-27ddc0b0-22b5-40bf-a99b-c195d5088118.mp4

**Comment by Pumatyger** [comment]
I extracted to a completely new folder, I updated Java and Forge to the latest and it still doesn't work

https://user-images.githubusercontent.com/42071139/216856667-077b9597-c87f-4a79-a18e-22d920a79407.mp4

**Comment by kevlahnota** [comment]
> I extracted to a completely new folder, I updated Java and Forge to the latest and it still doesn't work
> 
>  20230205183616-1.mp4

I can't reproduce the issue, there maybe a card that's buggy that affects the card. Can you share your deck and the opponent's deck...

https://user-images.githubusercontent.com/9781539/216859558-b38c434b-5228-4814-9002-933900a53b0a.mp4

**Comment by Pumatyger** [comment]
[Decks.zip](https://github.com/Card-Forge/forge/files/10661366/Decks.zip)

Here are the decks, they are commander decks
"Z - Prosper low power VS" is the one I was piloting
"Z - TESTING" is the one the AI is using

**Comment by Simisays** [comment]
@Pumatyger Tested it with your deck and it seems to work fine, really weird 
![image](https://user-images.githubusercontent.com/67333662/216939702-cb4d7e77-71e5-454c-a8d0-7bd2e712f82b.png)

**Comment by Pumatyger** [comment]
and it caused the loss of life?

That's really weird that it's not workin for me

**Comment by tool4ever** [comment]
The problem is related to the effect cleanup
Most likely it can only be encountered by using mana abilities while paying

**Comment by Pumatyger** [comment]
@tool4ever is correct, if I generate the mana before playing the card ruinous powers works correctly.

However, if I select the card from their exile BEFORE generating the mana the effect seems to not work correctly.
