### ISSUE TITLE
AI improvements required for card "Inverter of Truth"

### ISSUE THREAD

**Issue by maicomstoppa** [Card-Forge/forge#2426]
On "Adventure Mode", the "Eldrazi" NPC used the card "Inverter of Truth" on turn 4, with an empty graveyard, milling itself and losing the match.

Android, 1.6.55.SNAPSHOT-2023.2.7

**Comment by Hanmac** [comment]
Possible AI Logic:
* Cast only if GY > Library?
* And/Or Cast only if Library < 5 ?

Probably should be marked as Bad Reanimation Target?

**Comment by Simisays** [comment]
Strange that card should show up in the AI deck since it has the tag AI:RemoveDeck:Random. Maybe these tags are not taken into account with the Adventure deckbuilder ?
