### ISSUE TITLE
Unable to play/cast spells exiled with Praetor's Grasp

### ISSUE THREAD

**Issue by Pumatyger** [Card-Forge/forge#2487]
**Describe the bug**
After exiling a non-land card facedown, it is unable to be selected to be played

**To Reproduce**
1. Exile non-land card via Praetor's Grasp
2. Try to click on the card from the opponent's exile -or- your flashback zone

**Expected behavior**
Should be able to cast the card

**Screenshots**
https://i.imgur.com/AEFIqS9.jpeg

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version forge-gui-desktop-1.6.55.SNAPSHOT-2023.2.16

**Comment by tool4ever** [comment]
Hmn, a quick try seemed to work fine

Nothing on your board should prevent it either

I'll see if I can find something that could cause it

**Comment by Pumatyger** [comment]
Here's a video of what I'm seeing and the deck I'm using. (You'll have to rename the txt to dck)
https://user-images.githubusercontent.com/42071139/219658901-3378c1c5-1694-49ce-9bcb-c3675822caea.mp4

[Z - Prosper low power VS.txt](https://github.com/Card-Forge/forge/files/10766916/Z.-.Prosper.low.power.VS.txt)

**Comment by Pumatyger** [comment]
Still not working in the latest desktop snapshot, it works on the mobile version.
