### ISSUE TITLE
Trigger ability of Magnanimous Magistrate

### ISSUE THREAD

**Issue by cicoa** [Card-Forge/forge#2495]
When a creature dies, the trigger ability of Magnanimous Magistrate triggers. 

But when this ability resolves, there is no prompt that asks me if removing the reprieve counters to return that creature to battlefield.  And then nothing happened. I don't know whether it is my fault. 

P.S. The trigger ability of  Magnanimous Magistrate: Whenever another nontoken creature you control dies, if its mana value was 1 or greater, you may remove that many reprieve counters from Magnanimous Magistrate. If you do, return that card to the battlefield under its owner's control.

**Comment by Simisays** [comment]
Seems to work fine, though a costdescription woudn't hurt 
![image](https://user-images.githubusercontent.com/67333662/219855510-9c9e8f42-5a9e-4716-834c-2dd73ad58364.png)

Are you on the latest version, since this card was fixed beginning of december ?

**Comment by cicoa** [comment]
> Seems to work fine, though a costdescription woudn't hurt ![image](https://user-images.githubusercontent.com/67333662/219855510-9c9e8f42-5a9e-4716-834c-2dd73ad58364.png)
> 
> Are you on the latest version, since this card was fixed beginning of december ?

Oh, thank you for testing. This happened when I play the puzzle PS_J221. And I know why this bug happen with your help. 

The puzzle file of PS_J221 give Magnanimous Magistrate 5 REPRIEVE counters. But it should be REPR counters. I will correct this. Thank you.
