### ISSUE TITLE
Add support for Pi-Apps - app store for Raspberry Pi / ARM computers

### ISSUE THREAD

**Issue by Archargelod** [Card-Forge/forge#2501]
We can publish Forge on [Pi-Apps appstore.](https://github.com/Botspot/pi-apps)
Supported systems:
- Raspberry Pi OS
- Switchroot L4T Ubuntu Bionic
- Raspberry Pi Ubuntu, Raspberry Pi Pop_OS!
- Nvidia Jetson, Pine64, Orange Pi, Radxa, Bananna Pi, Khadas, Inovato, Libre Computer, and other ARM Debian/Ubuntu Based Devices

I already made a necessary script to install java and latest snapshot from FTP server on arm devices, see [pi-apps/#2264](https://github.com/Botspot/pi-apps/issues/2264)

But, 
> https://downloads.cardforge.org/dailysnapshots/ does not include previous days snapshots. so this app will break every day. this is not suitable for pi-apps, we need old versions to be cached as we only update apps weekly and users are not expected to always have the latest app versions on their local pi-apps installs.

Can we provide, let's say, up to 10 previous snapshots on ftp server or move snapshots to pre-releases?

_As an alternative, I also set up this repo - https://github.com/Archargelod/forge-snapshot-archive with a simple workflow that archives every snapshot and publishes it as release, daily._ - but it's a very janky solution, I'd like to avoid.

**Comment by Hanmac** [comment]
For Releases we could get the Releases on Github working

for snapshots i don't know, are Beta Releases too much?

**Comment by Archargelod** [comment]
Essentially, pi-apps updates link to latest snapshot weekly and they want to have this snapshot be available under said link for a week.

If you're concerned about cluttering the releases page : 
1. Github separates pre-releases and actual releases. For example, "latest release" will always be "release" and not a snapshot.
3. We can use [delete releases action](https://github.com/marketplace/actions/delete-older-releases) or something similar to keep only N number of previous snapshots (filtered by tags).

**Comment by tool4ever** [comment]
I understand users want the newest cards asap but one of the reasons we only offer one snapshot at a time is helping our workload tbh
It's difficult to get an accurate estimate for this, but things will break and in that case people possibly falling back to 7 days old ones or even more this way doesn't sound great to me 🤔 

That said with the current approach we try hard to get the release schedule back to quicker intervals

**Comment by tehdiplomat** [comment]
We already have releases here: https://github.com/Card-Forge/forge/releases ?

Also we have old releases on our ftp: https://releases.cardforge.org/forge/forge-gui-desktop/

**Comment by Archargelod** [comment]
@tehdiplomat I didn't know about that second link.

**Comment by Archargelod** [comment]
@tehdiplomat , I didn't know about that second link, thank you.
I wanted to specifically support snapshot version because it has less bugs, more features and support. Both on Github and Discord I see encouragements to use snapshot version and use releases as a fallback. Also, Adventure mode wasn't fully implemented in release version until last week.

But if releases will be more frequent, as @tool4ever said, I think that's fine.

**Comment by tehdiplomat** [comment]
We were encouraging that because the tooling had broken and the main dev that ran manual releases had been busy with life stuff. Now that (at least PC) releases are on github-actions. I expect to run that much more often. 

I'm not sure I would say snapshot has less bugs, it just has different ones. And potentially worse ones.
