### ISSUE TITLE
CLB: Choose Background + Background Type

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#251]
From what is leaked, Background works as similar to Partner in a way like Oath Breaker.

You can have a Legendary with "Choose a Background" as Commander
and a Legendary Enchantment - Background as second Commander

from what it looks like, the choice isn't flexible, but done like Partner Commander while Deck Building

GUI wise the CanBeCommander checks needs to be extended to allow for secondary choices.
Meaning you need to first choose a Commander with "Choose a Background", then you need to choose the Background card

**Comment by Northmoc** [comment]
I was not planning to do serious work on this until done with NCC. Or do you guys think we should shelve NCC and punch this out first?

**Comment by tool4ever** [comment]
don't think there's need for rush while rules are still missing anyway
