### ISSUE TITLE
New Card Set (e.g., Dominaria United, Brothers' War) for Android 

### ISSUE THREAD

**Issue by Silverback-Ren** [Card-Forge/forge#2515]
I am new to MTG Forge in Android. I really appreciate it as a good app to test and play decks. Just wondering if there's a way to update the new Card Set since 1.6.53.001 version does not have Dominaria United and Brothers' War sets in the list. Here is the snapshot of my card sets. 

![image](https://user-images.githubusercontent.com/89775899/220267032-d94354c3-d1ac-49ee-b934-031b8a6f6450.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A31
 - OS: Android Version 12

Thanks in advance. 

Warm regards

**Comment by kevlahnota** [comment]
download snapshot apk to have sets up to Phyrexia: All Will Be One (ONE) here: https://downloads.cardforge.org/dailysnapshots/

**Comment by Silverback-Ren** [comment]
Will check, thanks a lot.

**Comment by Silverback-Ren** [comment]
This is working perfectly. Thanks a lot.
