### ISSUE TITLE
Compleated doesn't interact with counter doubling properly

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#2519]
I had Vorinclex, Monstrous Raider out and cast Tamiyo, Compleated Sage with the life payment. I was given the option to apply the normal planeswalker loyalty or Compleated reduction first, but not Vorinclex's doubling. Thus I ended up with 6 loyalty, but I should be able to choose between 6 or 8 via ordering.

**Comment by tool4ever** [comment]
Duplicate of #2481
