### ISSUE TITLE
Card Images downloader skips some images

### ISSUE THREAD

**Issue by BrashSmash** [Card-Forge/forge#2528]
**Describe the bug**
The downloader for card images skips about 3 to5 hundred or so pictures when downloading. No forum has given me a solve.

**To Reproduce**
download card images, 
attempt to downloaded skipped images
images skip again

**Expected behavior**
all the rest of the images download

**Screenshots**
![Screenshot_20230221_034942](https://user-images.githubusercontent.com/126024875/220466776-e1c8713a-a4c4-4cba-b822-f260b02a2e43.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version Feb 2022 latest version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Necromancyfan** [comment]
I have a similar problem, just that it skips 33625 out of 33625 every time after it took hours to download :(
