### ISSUE TITLE
CLB: Venture into Undercity

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#254]
Venture Effect needs to be extended to set a Specific Dungeon (Undercity). Going into that Dungeon is part of #252

And this Dungeon can't be get into unless specific defined.

**Comment by Northmoc** [comment]
I think I can tackle this one if that's OK with you

**Comment by Hanmac** [comment]
shouldn't be that complicated,  just make a `UnderCity$ True` param or something

**Comment by Hanmac** [comment]
> Venture into [quality] is a variant of venture into the dungeon. If a player is instructed to “venture into [quality]” while they don’t own a dungeon card in the command zone, they choose a dungeon card they own from outside the game with the indicated quality and put it into the command zone. 

meaning we should treat Undercity in the Venture Effect as a Subtype.

for this, CardType needs to be update to not collide with "Dungeon Master"

**Comment by Northmoc** [comment]
I did begin to modify Venture Effect to look at subtypes for the new param instead of looking at the card name, but the Dungeon Master issue shut me down.

I am slammed right now but hope to get some time to go after it later this week.

Thanks for the insight and pertinent rulings
