### ISSUE TITLE
Double faced cards appear black on front side in adventure rewards and shop screens

### ISSUE THREAD

**Issue by LtLukoziuzU** [Card-Forge/forge#2551]
The card does show up correctly in deck manager. This does happen both when getting card as a reward for winning a duel, and when visiting a shop.

Playing on Win 10, 1.6.56-SNAPSHOT-02.23

**Comment by LtLukoziuzU** [comment]
![IMG_20230224_113809233](https://user-images.githubusercontent.com/55747413/221145746-aab540ce-62ac-444e-994f-e1067beb24b9.jpg)
![IMG_20230224_113814257](https://user-images.githubusercontent.com/55747413/221145756-ddab9d44-4055-4769-a04c-a1043fc013be.jpg)
Forgot to attach images

**Comment by kevlahnota** [comment]
this is known if you use HQ images and the amount texture to hold is at its limit. What specs you have? RAM? GPU? Java version?

**Comment by LtLukoziuzU** [comment]
![image](https://user-images.githubusercontent.com/55747413/221184920-ebb7740a-ce71-4330-8921-e36a5cdaf2c4.png)
![image](https://user-images.githubusercontent.com/55747413/221184975-415fbfb3-9991-4cc5-a903-f7eb78e9839e.png)
![image](https://user-images.githubusercontent.com/55747413/221185209-9adff9e3-047d-4031-b493-f65abc8375c0.png)


It does load successfully if I revisit the shop, I've noticed after making the report, so I can at least check those cards (but for rewards, do have to go and look it up in manager).

**Comment by kevlahnota** [comment]
> ![image](https://user-images.githubusercontent.com/55747413/221184920-ebb7740a-ce71-4330-8921-e36a5cdaf2c4.png) ![image](https://user-images.githubusercontent.com/55747413/221184975-415fbfb3-9991-4cc5-a903-f7eb78e9839e.png) ![image](https://user-images.githubusercontent.com/55747413/221185209-9adff9e3-047d-4031-b493-f65abc8375c0.png)
> 
> It does load successfully if I revisit the shop, I've noticed after making the report, so I can at least check those cards (but for rewards, do have to go and look it up in manager).

How do you run Forge adventure? If you have Java 64 bits installed (Java 11 or above is recommended) Try editing forge-adventure.sh, replace the line Xmx4096m to Xmx8192m since you have tons of RAM, save it, then run forge-adventure.sh (double click it)

**Comment by LtLukoziuzU** [comment]
> How do you run Forge adventure? 

Double-clicking 'forge-adventure.exe'. I will try doing the memory trick though, see if that fixes it,

**Comment by LtLukoziuzU** [comment]
First visit:
![image](https://user-images.githubusercontent.com/55747413/221210181-28850626-9ee7-4e69-ba1f-10209872a98c.png)
Second visit:
![image](https://user-images.githubusercontent.com/55747413/221210286-d81778ef-fa5e-4ee5-becb-6649c2b81685.png)

**Comment by kevlahnota** [comment]
Does it happen when downloading cards? Or everytime you open the reward/shop the image automatically fails to load? If it fails then revisiting fixes the issue, it seems the image is not loaded properly after download and requires delay to reload properly.

**Comment by LtLukoziuzU** [comment]
Yeah, that is likely to be an issue, failing to show immediately after download. Requires a bit of luck though to enter a new shop to find the card I already downloaded before (or spend several hours downloading every art through in-game options I noticed exist on classic side), I'll try to confirm it through my adventuring, but I think this can be closed unless something can be improved about the load process.

**Comment by LtLukoziuzU** [comment]
Just leaving a comment that the fix did help ;)
