### ISSUE TITLE
AI used Pearlspear Courier on itself

### ISSUE THREAD

**Issue by LtLukoziuzU** [Card-Forge/forge#2552]
![IMG_20230224_132255569](https://user-images.githubusercontent.com/55747413/221167380-cd6dcaf7-5889-427e-a65e-b5e38e4d1435.jpg)

It probably should have some check not to self tap, because otherwise it just spends 3 mana to pseudoremove itself

Normal Difficulty (if that matters), 1.6.56-SNAPSHOT-02.23

**Comment by Hanmac** [comment]
@Agetian card like "You may choose not to untap CARDNAME during your untap step." might need extra logic
