### ISSUE TITLE
Treasure tokens with counter instead of separate cards

### ISSUE THREAD

**Issue by JohnnyTest91** [Card-Forge/forge#2556]
![Screenshot_20230225_014644_Forge](https://user-images.githubusercontent.com/52100676/221328753-dd7722e8-db46-41b1-92c5-7b00bcdb7bbe.jpg)
As you can see in the screenshot above, I was at over 300 treasure tokens at this point. I tried to get another combat step but the game froze. The additional combat would have put me to something close to 4000 treasures. I wouldn't even know how the game should display all those as separate tokens. A possible solution could be that if you get over a certain amount of treasures, instead of separate tokens, it just displays one treasure token with a counter of how many tokens you have.

**Comment by Hanmac** [comment]
doesn't work, Ruleswise they need to be separate

**Comment by JohnnyTest91** [comment]
> doesn't work, Ruleswise they need to be separate

Ah that's unfortunate, didn't know that. Could there be another solution?

**Comment by betamatt** [comment]
Arena gives you a handful stacked up to interact with and beyond that adds a counter (x35) to indicate the total number that are actually there. There's an option click to attack with the whole stack so if you have 400 you can select the stack (and then remove a few individuals) or just select a few individuals.
