### ISSUE TITLE
AI using Tempered Veteran's more expensive ability even though creature already had +1/+1 counters

### ISSUE THREAD

**Issue by LtLukoziuzU** [Card-Forge/forge#2563]
![image](https://user-images.githubusercontent.com/55747413/221361199-163c4a01-87a4-4126-96dc-2732aef721c6.png)

Could have spent just W and had another pump from Anointed Chorister itself (not that it matterd much thanks to Kor Haven from me), but instead it just dumped all its mana for that one counter.

Win 10, 1.6.56-SNAPSHOT-02.23, Insane Difficulty Adventure Mode

**Comment by Hanmac** [comment]
@tool4ever can you look at this when you already touched the CountersPutAi?
