### ISSUE TITLE
PLEASE READ! Few questions regarding the sprites

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#2610]
So, I've been creating a skin template and mapping out the coordinates for the sprites so it's easier to create custom themes. I have a couple of questions though, and I'm sorry about asking through here, but your discord won't allow me to join since you demand a cell phone number... 

Anywho, two questions I have are: 
1.) What exactly is the attached symbol? It's labeled as "costreserved" in the code, but what does that even mean?
![costreserved](https://user-images.githubusercontent.com/92389638/222898062-5854e754-df2f-40c1-8a9b-0f9c7478cd8b.png)

2.) What are the extra two coordinates in the Attack, Defend, Summon Sick, Phasing, Cost Reserved for? 
Example: Attack image coordinates are (160, 320, 80, 80, 32, 32)
I understand that it's (Top X, Top Y, Width, Height). So is it safe to assume that the extra two coordinates are also width and height, but at a scale of 32x32 instead of 80x80?

**Comment by TheLastNarwhal** [comment]
Okay, the name threw me and it'd been awhile since I actively paid attention to the icons, but it seems like the "costreserved" icon is just the thing that pops up when you're dealing with attacking creatures or things of that nature. That's the first question sorta answered. The second one remains unanswered though.

Also, I have a new question and I sincerely hope that someone will actually answer it...

So far anything that I replace in the sprite_icons.png file is respected and it shows correctly when using my custom theme. However, when I try to change the flipcard image in the sprite_icons.png it refuses to show it. After some swapping of files (changing the default sprite_icons in the default skins folder with my custom one) it finally uses my custom flipcard image. Why does forge **only** take the flipcard image from the sprite_icons.png found inside the default skins folder? That seems very strange...

**Comment by Hanmac** [comment]
List for Icons, the name for this is "sacrifice"

https://github.com/Card-Forge/forge/blob/a96827a8071b8341a5295ece7472b5111b0031d5/forge-gui-desktop/src/main/java/forge/view/arcane/CardPanel.java#L539-L542

https://github.com/Card-Forge/forge/blob/1b655458e792af1e055879dfe8ca6db9239bfcc7/forge-gui-mobile/src/forge/card/CardRenderer.java#L773-L776

the isUsedToPay check is for cards that are highlighted, probably chosen for some kind of effect or cost?

**Comment by TheLastNarwhal** [comment]
In the FSkins.java it was just called costreserved... XD

Do you have any idea about the new question regarding the flipcard image?

**Comment by Hanmac** [comment]
i don't do images

@kevlahnota can you look at the flipcard question?

**Comment by kevlahnota** [comment]
I mostly modify for the mobile version. Regarding the flipcard, the  high resolution flip card in the default skin is exclusive to mobile version. The old implementation for the desktop version is still the same as before inside the sprite icons file.

**Comment by TheLastNarwhal** [comment]
Yes, but it will only take the flipcard image from the default sprite_icons file, even if I add my own custom flipcard image to my custom sprite_icons file.

**Comment by kevlahnota** [comment]
> Yes, but it will only take the flipcard image from the default sprite_icons file, even if I add my own custom flipcard image to my custom sprite_icons file.

Try replacing your flipcard image with opaque rectangle image (no transparency) in your custom sprite, if it loads then the check fails when detecting the sprite region since it compares the origin (middle x,y coordinates) of the sprite, if it has color..

**Comment by TheLastNarwhal** [comment]
Hmm... Okay, that's weird. If I replace it with a black square it shows up when using my custom theme. The really weird thing is that if I replace the default sprite_icons file found in the default skins folder with my own custom sprite_icons file that has my flipcard image, it is able to properly detect the new arrows.

**Comment by TheLastNarwhal** [comment]
This is forge taking from my custom sprite_icons.png file that is in **.cache/forge/skins/**:
![custom flipcard image - in custom theme folder](https://user-images.githubusercontent.com/92389638/223743524-766fe515-6ad8-4f67-88d8-5c5552f79557.png)

This is forge taking the same image, from the same location, but with a black square:
![custom flipcard image - black square](https://user-images.githubusercontent.com/92389638/223744145-a532c392-3e54-41a0-823b-b57086617bf2.png)

This is forge properly detecting the flipcard image from my custom sprite_icons.png, but from the **res/skins/default** location:
![custom flipcard image - in default folder](https://user-images.githubusercontent.com/92389638/223744348-f1cfd0e2-2097-4458-a3f3-0409df2b7df7.png)

**Comment by TheLastNarwhal** [comment]
Actually, thinking on it. I guess that makes sense. Since it probably isn't checking anything if you're using the default skin and it just cuts whatever is there and displays it. Do you know how I can fix the image so that forge can detect this and display it instead of the default image?

**Comment by TheLastNarwhal** [comment]
> > Yes, but it will only take the flipcard image from the default sprite_icons file, even if I add my own custom flipcard image to my custom sprite_icons file.
> 
> Try replacing your flipcard image with opaque rectangle image (no transparency) in your custom sprite, if it loads then the check fails when detecting the sprite region since it compares the origin (middle x,y coordinates) of the sprite, if it has color..

Okay, thanks for pointing out how the detection was most likely failing. I just added a small "detection node" and made it essentially transparent to the naked eye, but not the computer, and now the flipcard icon shows up. I appreciate the help with this. Thank you.
