### ISSUE TITLE
Android: Adventure Mode freezes when selecting from side menu.

### ISSUE THREAD

**Issue by SirDidds** [Card-Forge/forge#2656]
**Describe the bug**
Adventure Mode freezes when attempting to view/edit decks, change equipment, save game, et cetera.

**To Reproduce**
1. Enable landscape mode. (Bug does not effect vertical mode.)
2. Start a new game of Adventure Mode while on an Android device.
3. If the menu on the right side is not visible, double-tap portrait to enable it.
4. Select any option on the menu.
5. The game freezes.

**Expected behavior**
Instead of freezing, the menu should display the proper submenu/screen.

**Screenshots**
![Screenshot_20230310-210243](https://user-images.githubusercontent.com/127575711/224462231-7b40fff0-0ff5-4888-abaf-6eb017df4dfc.png)
![Screenshot_20230310-210310](https://user-images.githubusercontent.com/127575711/224462234-5510ead8-e122-4e68-816d-bda00a784f82.png)

**Smartphone**
 - Device: motorola edge 5G UW (2021)
 - Android 12
 - Google Chrome (Unsure how this effects issue?)
 - Chrome 107.0.5304.141

**Additional context**
Menu titles are unreadable, may be related to the issue.

**Comment by kevlahnota** [comment]
Forge version? Did you try to update or reinstall the latest snapshot version?
