### ISSUE TITLE
Contractual Safeguard

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#266]

**Comment by Hanmac** [comment]
i think that's currently not easy to code because you first need to choose a creature with a counter and then you need to choose a counter on it.

and currently that can't be done as one effect i think

**Comment by Northmoc** [comment]
> i think that's currently not easy to code because you first need to choose a creature with a counter and then you need to choose a counter on it.
> 
> and currently that can't be done as one effect i think

What did you think of the CountersPutEffect tweak?
