### ISSUE TITLE
Error run forge.sh 

### ISSUE THREAD

**Issue by ChristiamMB** [Card-Forge/forge#2669]
hello, 
when you try to run the .sh executable on linux or mac. you get this error:

./forge.sh
zsh: ./forge.sh: bad interpreter: /bin/bash^M: no such file or directory

Solution:
modify the forge.sh file in the beginning looks like this
```
#!/bin/bash
 
# returns the JDK version.
# 8 for 1.8.0_nn, 9 for 9-ea etc, and "no_java" for undetected
# Based on the code from this source: https://eed3si9n.com/detecting-java-version-bash
jdk_version() {

```
change to:

```
#!/bin/bash
jdk_version() {
  local result
```

as far as I have been able to see there is a wrong space and that's why the execution fails

**Comment by Hanmac** [comment]
@ChristiamMB the problem is the line ending, For some reason the file has the windows encoding but shouldn't

**Comment by Hanmac** [comment]
@tehdiplomat can you look why it somehow has wrong endings?

**Comment by ChristiamMB** [comment]
it could also be due to a bug in one of the last updates because this has been happening for 3-4 days now, before everything was perfect

**Comment by tehdiplomat** [comment]
I dunno. File hasn't changed in a year. Is this for only full releases, or snapshots too? 

Full releases are running on an ubuntu box, I have no reason to expect it to convert the git pull to windows line endings?

**Comment by ChristiamMB** [comment]
in the stable version everything is correct, where it is failing right now is in the snapshop.

**Comment by tehdiplomat** [comment]
@kevlahnota Any chance your git pulls are converting line endings during snapshots?

**Comment by kevlahnota** [comment]
could be, is there any settings so it's always LF?

**Comment by Hanmac** [comment]
@kevlahnota it should be possible in the git attributes to define the line ending for the sh files as always LF

https://git-scm.com/docs/gitattributes
