### ISSUE TITLE
CantCounter Rework

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#2688]
* `CardFactoryUtil.isCounterable` should probably be removed in favor of isCounterableBy
* `CardFactoryUtil.isCounterableBy` should either be moved and/or extended
if it only checking the ReplacementList, moved to AI?
* Remove this keywords:
  * "CARDNAME can't be countered."
  * "This spell can't be countered."
  * "CantBeCounteredBy"
* Currently it is done as CantHappen Replacement Effect, is this the right way or are our StaticAbility better?
Should we prefer CantHappen if an event is available?
  * For "CantBeCounteredBy", the Replacement Effect should probably get new Parameter to handle
* CounterEffect should be changed to use CantHappen result

**Comment by tool4ever** [comment]
Not sure about the CantHappen vs. Static yet

- from Rules perspective the Layer could model it with less overhead
- but with static last time I checked it seemed the engine could test it pretty early and so maybe easier, especially in case a true replacement for it already exists (but which is only run after some other stuff happens first)

**Comment by Hanmac** [comment]
my current point is that we might prefer CantHappen if we have already an Replacement Event for this

otherwise, StaticAbility are fine

for stuff that ignore stuff (can attack as if it doesn't has defender), static are better
