### ISSUE TITLE
Yavimaya, Cradle of Growth broken

### ISSUE THREAD

**Issue by AcornTwigs** [Card-Forge/forge#2700]
**Describe the bug**
Yavimaya, Cradle of Growth on my side
AI had 5 plains
AI Blocked and killed my Elvish Champion 
Enduring Angel deals 3 damage to Elvish Champion 

**To Reproduce**
1. Have Yavimaya, Cradle of Growth (Each land is a Forest in addition to its other land types.) on your side 
2. Have Elvish Champion that grants forestwalk. (They can’t be blocked as long as defending player controls a Forest.)
3. Attack
4. Be blocked even though opponent has forest from Yavimaya 

**Expected behavior**
Expected to not be blocked

**Comment by tool4ever** [comment]
You need to read the card closely, Elvish Champion doesn't work on itself

**Comment by AcornTwigs** [comment]
Just realized that, tested and saw that Infobox has Forestwalk listed on other creatures, thank you.
