### ISSUE TITLE
Dennick, Pious Apprentice disturb issue

### ISSUE THREAD

**Issue by Athanasiosdk** [Card-Forge/forge#2701]
**Describe the bug**
Dennick, Pious Apprentice returns as its front side when returned from the graveyard using its disturb ability. 

**To Reproduce**
1. Start a game, make it to a gamestate where Dennick, Pious Apprentice is in your graveyard and you have the ability to pay 2WU. 
2. Click on Dennick, Pious Apprentice in your graveyard. 
3. Pay 2WU
4. Dennick's ability goes on the stack
5. Dennick returns as "Pious Apprentice" instead of "Pious Apparition".

There is no error associated with this interaction that I have encountered. 

**Expected behavior**
Dennick, Pious Apprentice should return to the battlefield as "Dennick, Pious Apparition".

**Screenshots**
1. https://imgur.com/B8zrzdg
2. https://imgur.com/bzvDyo0
3. https://imgur.com/L4MRpgs
4. https://imgur.com/Njefw7w

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.6.55

**Comment by Hanmac** [comment]
@tool4ever can you debug it? with current master, i see it returning on the right face, but some visual bugs?

**Comment by tool4ever** [comment]
Looks good on my end, unfortunately the Disturb fix didn't make it into the last release

**Comment by Hanmac** [comment]
@tool4ever please check with disabled image, while I got the right stats and keywords, the card still looks wrong

**Comment by tool4ever** [comment]
![image](https://user-images.githubusercontent.com/8506892/226101185-35d6f028-a892-43f5-8bad-c67ac192d040.png)

**Comment by Hanmac** [comment]
![Bildschirmfoto vom 2023-03-18 12-27-49](https://user-images.githubusercontent.com/225553/226102622-9c737ba0-8fde-4fb6-9c0d-56173aabdc60.png)
![Bildschirmfoto vom 2023-03-18 12-28-27](https://user-images.githubusercontent.com/225553/226102627-58a1f66c-fcac-43bb-a1af-1cdc4aef4c74.png)

Desktop snapshot
look how it doesn't match the stuff ?

**Comment by tool4ever** [comment]
![image](https://user-images.githubusercontent.com/8506892/226103486-d3dc3aac-c707-40af-ae4f-fb707c0af4a0.png)

I think that can happen if you accidentally try to add it as backside to the zone with Dev Mode directly
