### ISSUE TITLE
Achievements - Need for Speed adjustment

### ISSUE THREAD

**Issue by jarodium** [Card-Forge/forge#2707]
**Describe the bug**
In MTG is impossible to achieve 'Need for Speed' Mythic achievement since there is no turn 0 in MTG

**To Reproduce**
1. Go to Game Settings > Achievements

**Expected behavior**
Expect a review of the achievement criteria

**Screenshots**
![image](https://user-images.githubusercontent.com/1470446/226196481-b4e8e9cc-5a4f-4b36-aea1-d9dbce9d0dd0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser brave
 - Version 1.49

**Comment by tool4ever** [comment]
This refers to your own turn number, not the whole game
So while it's of course pretty hard there are ways
See e.g. https://www.reddit.com/r/magicTCG/comments/h0tt52/how_does_a_turn_zero_win_work/
