### ISSUE TITLE
StackOverflow from Master Chef Replacement

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#2749]
Because the static is not connected to a KW the card will always get a new RE (with different ID)

1. Reverting https://github.com/Card-Forge/forge/pull/2449/commits/4734b02c0 works

2. another way would be doing ``newCopy.setStoredReplacementEffects(in.getStoredReplacementEffects())`` in `getLKICopy` and then also later when the Affected is updated

**Comment by tool4ever** [comment]
One thing I don't like for performance after 1. is that now all other LKI also needs to always make deep copies of the `storedKeywords` when it shouldn't be needed?

My idea:
- Have `setStoredKeywords()` check if it can find the right instance in `changedCardKeywords` first because those would already be copied before in most cases

@Hanmac what you think?

**Comment by Hanmac** [comment]
@tool4ever the problem, Master Chef aren't keywords that's why your idea has no effect
