### ISSUE TITLE
Phyrexian Purge bug

### ISSUE THREAD

**Issue by Capamerica805** [Card-Forge/forge#2769]
![image](https://user-images.githubusercontent.com/125170572/228064194-674b0e34-a98d-4126-9a94-6261abaf464e.png)

Has anyone else seen this issue with Phyrexian Purge not adding to stack and just failing to resolve?

**Comment by tool4ever** [comment]
That was from AI right?

**Comment by Capamerica805** [comment]
Correct, that was the log from playing against the AI when i tried to use Phyrexian Purge.

**Comment by Hanmac** [comment]
@Capamerica805 the question was if AI was trying to cast this spell or if it was you

**Comment by Capamerica805** [comment]
I was trying to cast the spell.
