### ISSUE TITLE
MOM: Backup Mechanic

### ISSUE THREAD

**Issue by paulsnoops** [Card-Forge/forge#2774]

**Comment by Hanmac** [comment]
it should probably only care about intrinsic abilities

**Comment by Hanmac** [comment]
from the https://magic.wizards.com/en/news/feature/march-of-the-machine-mechanics article

> On a few creatures, abilities that wouldn't make much sense to have another creature gain until end of turn, such as flash or landcycling, are printed above backup. Creatures that are the targets of backup abilities don't gain any abilities printed above backup.

means we need to be careful how to make the abilities be gained or not

for now we can do something like this: `K:Backup:1:AnimateSub`
with AnimateSub being a SubAbility that does animating the right keywords and abilities manually

in the long run, we might change how the abilities are stored on the card, like in a generic `cardtraits` property which does keep the order of the abilities

**Comment by zzo38** [comment]
Like other new things, I think that it would be better to wait for the new version of the Comprehensive Rules to be released.
