### ISSUE TITLE
Planescape Chaos Ensues

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#2829]
* "roll for Chaos" needs to be changed into a Chaos (Ensues) Trigger
* Chaos also needs to be an Effect so that it can be called by SpellAbility (better make it a function in Game?)
* Rolling Chaos on the PlanarDie makes it ensue Chaos (no extra Trigger, should be in Game)

`Stairs to Infinity` Updated Oracle:
> Whenever you roll the planar die, draw a card.
> Whenever chaos ensues, reveal the top card of your planar deck. You may put it on the bottom of your planar deck

We still need `TriggerType.PlanarDice` for this,

**Comment by Hanmac** [comment]
> if a resolving spell or ability says that chaos ensues, or if a resolving spell or ability states that chaos ensues for a particular object. In the last case, the chaos ability can trigger even if that plane card is still in the planar deck but revealed.

This Rule Matters for:
>  The Fertile Lands of Saulvinia
> Plane — Antausia
> Whenever a player taps a land for mana, that player adds one mana of any type that land produced.
> Whenever chaos ensues, reveal cards from the top of your planar deck until you reveal a plane card. **Chaos ensues on that plane.** Then put all cards revealed this way on the bottom of your planar deck in an order.

meaning we would need to make the Chaos Ensures Trigger Zone Check Depend on if the Trigger gets a Specific Object or not?

@tehdiplomat this probably is messing with ActiveTriggers for Chaos

**Comment by tehdiplomat** [comment]
Just FYI. It's "Chaos Ensues" not "Chaos Ensures"

**Comment by tehdiplomat** [comment]
Yea I don't like that rule. We'd have to fire a trigger to a specific game object which bypasses specific conditions. Maybe thats how we should consider it? If the trigger param runs with some type of BypassConditions argument, then we skip the conditions check?

```
Params ->
Mode=PlanarDie
Result=Chaos
AddConditionals=ValidCard$ Card.IsRemembered
IgnoreConditionals=Zones
```

**Comment by Hanmac** [comment]
also for `The Fertile Lands of Saulvinia`  **Chaos ensues on that plane** doesn't cause their own `Whenever chaos ensues` to trigger

so we need to handle the Special cases with Triggered Object anyway in the Ensures Trigger

**Comment by tehdiplomat** [comment]
Yep for sure. Needs to be limited to only the thing we care about
