### ISSUE TITLE
MOM: Any targeting include Battles

### ISSUE THREAD

**Issue by tehdiplomat** [Card-Forge/forge#2833]
Currently, Forge expands damage dealing SpellAbilities that say "any target" to `ValidTgts$ Creature, Planeswalker, Player` once Battles are available, we would need to expand each of these "Any target" phrasing targets to include Battles. Obviously we could just take Battle into the list, but ideally we should make it more aligned with how the comprehensive rules treat the "any target" keyword. If we're able to define it using `Any` this also simplifies the TgtPrompt we need to have on all of these scripts. 

Old:
```
A:SP$ DealDamage | ValidTgts$ Creature,Battle,Player,Planeswalker | TgtPrompt$ Select any target | NumDmg$ 2 | SpellDescription$ CARDNAME deals 2 damage to any target.
```

Potentially?
```
A:SP$ DealDamage | ValidTgts$ Any | NumDmg$ 2 | SpellDescription$ CARDNAME deals 2 damage to any target.
```

One concern is that the phrase "Any" only means `Creature,Battle,Player,Planeswalker` when it comese to damage dealing targeting context, so is there a way to tackle that concern but also simplify the script I think that would be a win win.

**Comment by Hanmac** [comment]
second part of the Question:
* Should the Parser split `Any` into `Creature,Battle,Player,Planeswalker` when the TargetRestrictions are built? then it might not be extendable? like `Any.nonCreature` ?
* or should GameEntity.isValid work with `Any` ?

**Comment by zzo38** [comment]
It might be worth to wait for the new version of the Comprehensive Rules to be released before attempting to implement battles; at least, that would be my opinion.

I think that `Damageable` would be better than `Any`, and then any cards that use "any target" should use `Damageable`. (My own unofficial rules and cards use "target damageable" as the wording, but the meaning is exactly the same as "any target".) `Damageable` should be usable anywhere that a criteria for selecting objects/players is required, including targeting, enchant, etc.

About being possible to write `Any.nonCreature` (or `Damageable.nonCreature`), I think that being able to combine criteria is helpful for many purposes, and not only this one. Being able to combine arbitrary criteria with AND, OR, and NOT would be helpful.

**Comment by tool4ever** [comment]
The chosen implementation requires additional updates in multiple places.
Most important probably the functions like `canTgtPlayer` which would otherwise degrade AI quality because it relies heavily on it and some engine logic parts also use it.

**Comment by Hanmac** [comment]
@tool4ever the most easy way would be to add `canTgtAny` and then use it for `canTgtPlayer` and the other functions
