### ISSUE TITLE
Oblivion Ring does not return permanent to play.

### ISSUE THREAD

**Issue by astaderini** [Card-Forge/forge#2854]
**Describe the bug**
AI cast Oblivion Ring and exiles a permanent (Mox Ruby). I destroy Oblivion Ring with Force of Vigor. Permanent (Mox Ruby) remains exiled. All happened during match with AI.

**Expected behavior**
Permanent should return to play under its owner's control.

**Additional context**

**Comment by tool4ever** [comment]
Can't reproduce
Make sure your engine and scripts are in sync

**Comment by astaderini** [comment]
I'm using release 1.6.55 (21 feb.). DO I need to copile source?

**Comment by tool4ever** [comment]
It got fixed after, you can use snapshot if you want
