### ISSUE TITLE
Transforming Copy Token

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#2866]
> This change will also apply to tokens that are created as copies of other transforming double-faced permanents or as copies of transforming double-faced cards in zones other than the battlefield. For example, if you control a Flame Channeler and an effect creates a token that's a copy of it, the resulting permanent is a transforming double-faced token that is a copy of Flame Channeler. It enters the battlefield with its front face up, and it can transform. If it does, it will become an Embodiment of Flame, the back face of Flame Channeler. Similarly, if you controlled an Embodiment of Flame and created a token that is a copy of it, the token would be the same transforming double-faced token, but it would enter with its back face up.

That means ONLY for CopyPermanent should the Transforming Backside be copied.
For TDFC Clones entering as Copy of another TDFC, the Backside should not be copied.

not sure how that is for Spells that enter as token of TDFC Spells (when the spell is copied on the stack)

**Comment by Hanmac** [comment]
some of it got accidentally commited into master

@tool4ever you probably should use this ticket to document errors you find with this

**Comment by tool4ever** [comment]
Sure, I'll test some more later

Here's the crash after https://github.com/Card-Forge/forge/commit/bb3709ebad509a316df0ccaffec4546082764d67:
```
Game-3 > java.lang.NullPointerException: Cannot invoke "forge.game.card.CardState.getStateName()" because "originalState" is null
    at forge.game.card.CardFactory.getCloneStates(CardFactory.java:812)
    at forge.game.ability.effects.CopyPermanentEffect.getProtoType(CopyPermanentEffect.java:285)
    at forge.game.ability.effects.CopyPermanentEffect.resolve(CopyPermanentEffect.java:247)
```

**Comment by tool4ever** [comment]
Bug: I defeated _Invasion of Amonkhet_ and copied the backside spell with _Lithoform Engine_

The new token looked ok but somehow still got 4 defense counters

(Not affected by #3095)

**Comment by tool4ever** [comment]
Copied permanent spells don't seem to be able to transform at all, not sure why yet

**Comment by Hanmac** [comment]
> Copied permanent spells don't seem to be able to transform at all, not sure why yet

i did only Copy Token yet, not Copy Spell

**Comment by Hanmac** [comment]
@tool4ever @Agetian i need to look at `copySpellHost` and `copyCopiableCharacteristics`
Specially `copyCopiableCharacteristics` is only used on one location, and might need to be cleaned up too

**Comment by Hanmac** [comment]
@tool4ever i think this Issue can be closed? i think we have done all cases there?

**Comment by tool4ever** [comment]
There's something for the future here:
https://github.com/Card-Forge/forge/pull/3146#pullrequestreview-1464879129

but it's probably another issue
