### ISSUE TITLE
Other property missing timestamp check

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#2871]
With _Charmed Stray_ ETB trigger on the stack, flicker it. Because it is now a new object it should get a counter.

There are a lots of cards like that.

@Hanmac
I don't think we can make `equalsWithTimestamp` default or it will break other cards that use it when finding cards during zone change.

So probably need to update scripts with a `StrictlyOther` or you got a better idea?

**Comment by Hanmac** [comment]
StrictlyOther sounds okay for now, until we do a bitter change with Timestamps
