### ISSUE TITLE
The translated text cannot be displayed in its entirety

### ISSUE THREAD

**Issue by herolulu** [Card-Forge/forge#290]
**Describe the bug**

The translated text cannot be displayed in its entirety

**To Reproduce**

Fully translated card descriptions can be displayed in the deck editor. Card descriptions cannot be displayed in full during a match.

**Expected behavior**

I hope the translated content can be displayed normally.

**Screenshots**

https://i.imgur.com/jH5O5BM.jpeg

**Desktop (please complete the following information):**

windows10

**Smartphone (please complete the following information):**

**Additional context**

I created a card. This card can be used normally, but the translation information of the card cannot be displayed normally. I edited the Chinese text in the cardnames-zh-CN.txt file in Forge_pc\res\languages. Viewing the card text in the deck editor is displayed in full Chinese, but in the battle with AI, the card text is displayed in half Chinese and half English. I found that if the content after SpellDescription$ in the card TXT is in English, even if the Chinese is edited in cardnames-zh-CN.txt, there is a certain probability that it will still be displayed in English. 
K:Indestructible
K:Exalted
Statements like the above also often do not display translated text.

**Comment by y12345e** [comment]
the reason is here [java code](https://github.com/Card-Forge/forge/blob/ac05891bf5c17ff3e77cb86cbea0649d2b2ae491/forge-game/src/main/java/forge/game/keyword/Keyword.java)
