### ISSUE TITLE
Yorion shouldn't be allowed as a companion in EDH

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#2980]
**Describe the bug**
Title says it all. Right now Yorion is allowed to be a companion in a commander deck, when it shouldn't since it can never meet the requirements as a commander deck can never have more than 100 cards.

**Comment by tehdiplomat** [comment]
Looks like the GameType is being set as a variant, but when we go see what the deck size is, we don't check if any of the variants change the deck size...
