### ISSUE TITLE
GUI project: disentangle frontend from backend

### ISSUE THREAD

**Issue by allentiak** [Card-Forge/forge#2982]
The classes in the forge-gui project mixin frontend and backend responsibilities.
Eventually, this project should be broken up into those two parts.

Of course, this will take very long. But I have already started to work on this.

As a first step, back in March 2021, I started grouping classes together w.r.t. what they do.
_(Check the commits around https://github.com/Card-Forge/forge/commit/0a29d6794be96bcff2110787c68c5215b9aadd56.)_
Now, I'm starting to segregate the frontend from the backend (and from what needs to be disentangled).
Once this is done, it will become possible to start actually disentangling the code, so it becomes testable, and easier to change.

For those interested in the particulars of the process, I strongly suggest you check the introductory chapters of "Working effectively with Legacy Code", by Michael C. Feathers. _(BTW: If you only have time to pick one of those chapters, I strongly suggest you start with Chapter 4)._

You can [read many reviews at GoodReads](https://www.goodreads.com/book/show/44919.Working_Effectively_with_Legacy_Code).
Moreover, you can even [get the book free of charge at the Internet Archive](https://archive.org/details/working-effectively-with-legacy-code).

## Phases

- [x] 1.Organize classes functionally.
_(MR data lost in the migration from GitLab.
Check my commits around https://github.com/Card-Forge/forge/commit/0a29d6794be96bcff2110787c68c5215b9aadd56.)_

- [ ] 2. Segregate frontend classes from backend classes (WIP)
  - #2981

- [ ] 3. Disentangle functionality, class by class.
_(See my WEwLC mention in this PR's description.)_

**Comment by Hanmac** [comment]
Question: what kind of frontend/backend difference do you mean?

i mean is backend for you gui-less? if yes, stuff without GUI should be part of Game module?

**Comment by allentiak** [comment]
As I mentioned in the description, the problem is that there are plenty of
classes that mix frontend and backend responsibilities. Eventually, the
responsibilities from this last group will have to be (somehow) refactored
into the other two.

As this is just the first step into separating those three groups of
responsibilities into three clear hierarchies, it is too soon to know the
exact final destination for each of those to-be-refactored classes. It
could be "game", or it could be somewhere else. This will depend on what
the refactored hierarchy ends up looking like.

Have I answered your question?
