### ISSUE TITLE
Vogar, Necropolis Tyrant

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#2985]
**Describe the bug**
Vogar, Necropolis Tyrant's description in forge, as well as the scripted effect is currently: "Whenever another creature **you control** dies during your turn, put a +1/+1 counter on Vogar, Necropolis Tyrant."

It should be: "Whenever another creature dies during your turn, put a +1/+1 counter on Vogar, Necropolis Tyrant."

https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=582588

**Comment by tool4ever** [comment]
thanks fixed
