### ISSUE TITLE
Ratchet, Field Medic Missing Lifelink

### ISSUE THREAD

**Issue by dwetuski** [Card-Forge/forge#3010]
**Describe the bug**
In the deck editor, Ratchet, Field Medic has lifelink... but in games, it does not.

**To Reproduce**
1. Start a constructed game.
2. Get Ratchet, Field Medic in hand.
3. Observe Card Detail for Ratchet.

**Screenshots**
![Ratchet](https://user-images.githubusercontent.com/4153921/234259620-613f459a-4b40-4924-ae55-daf6551b558f.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Forge: 1.6.55
 - Java: 8

**Additional context**
Attacking is also confirmed to not increase life.

**Comment by Simisays** [comment]
This is fixed on the latest snapshot
