### ISSUE TITLE
Forge.exe not working... at all...

### ISSUE THREAD

**Issue by Terandox-The-Pineapple** [Card-Forge/forge#3036]
**Describe the bug**
Every time i try to start forge.exe i get an error pointing out, that forge.exe needs java 11.0.1
The Problem is, that i actually already have java 11.0.19 installed and active (I checken it in cmd with: java -version)

**To Reproduce**
1. Install Java 11.0.19
2. Try to start forge.exe
3. Be depressed

**Expected behavior**
It should start

**Screenshots**
![image](https://user-images.githubusercontent.com/79146211/235299212-77f36ff1-f62b-459a-8c2d-959de98a4814.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.6.56

**Comment by kevlahnota** [comment]
can you try to uninstall java (all java installed) and install java 11 or higher. then redownload latest snapshot (1.6.56 release version will not load properly if you have old/existing quest saves). https://downloads.cardforge.org/dailysnapshots/

**Comment by kevlahnota** [comment]
Seems the OP is nit interested in fixing this.. Gonna close this issue.
