### ISSUE TITLE
Filigree Vector missing entirely (not added or accidentally removed)

### ISSUE THREAD

**Issue by Glorax** [Card-Forge/forge#3037]
The issue: Despite every other card from March of the Machine Commander seemingly having been added, and the projects section saying that Filigree Vector is merged, Filigree Vector isn't present at all in the client, as of the most recent snapshot. Nor is it present in the files when I unzip the cards folder.

To reproduce: Search for it in the client, and also check the unzipped card folder under "F".

The expected behaviour: Filigree Vector should be present in the client, and I should be able to add it to decks and draft it, since the March of the Machine Commander project has ostensibly been completed, and is marked as such, and the card script itself is marked as completed and merged. Either it was never merged, or it was accidentally removed somehow in a subsequent snapshot.

Desktop:
• OS: Not relevant
• Forge: 1.6.57 - Snapshot 04.29
• Java: Not relevant

**Comment by kevlahnota** [comment]
refer here: https://github.com/orgs/Card-Forge/projects/25
- https://github.com/Card-Forge/forge/pull/2989
