### ISSUE TITLE
Invasion of Innistrad enters the battlefield with 4 defense counters instead of 5

### ISSUE THREAD

**Issue by tjtillman** [Card-Forge/forge#3046]
**Describe the bug**
Invasion of Innistrad enters the battlefield with 4 defense counters instead of 5

**Expected behavior**
Invasion of Innistrad enters the battlefield with 5 defense counters

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Snapshot 1.6.57 05-01

**Comment by tool4ever** [comment]
thanks fixed
