### ISSUE TITLE
LTR: The Ring mechanic

### ISSUE THREAD

**Issue by paulsnoops** [Card-Forge/forge#3064]
https://magic.wizards.com/en/news/feature/the-lord-of-the-rings-tales-of-middle-earth-mechanics

**Comment by Hanmac** [comment]
Some Info about some cards:

* `the Ring tempts you. Then if CARDNAME is your Ring-bearer`
This should be by Remember
* `Whenever the Ring tempts you, if you chose a creature other than CARDNAME as your Ring-bearer`
Trigger Param `ValidPlayer$ You` and `ValidBearer$ Card.Other`
* `Whenever you choose a creature as your Ring-bearer`
I Think do similar to `Whenever the Ring tempts you`, just with `ValidBearer$ Card`
