### ISSUE TITLE
Calix Triggers while in the Deck

### ISSUE THREAD

**Issue by m-iken** [Card-Forge/forge#3084]
**Describe the bug**
Every instance of Calix in the deck and on the battlefield react to combat damage triggers.

**To Reproduce**
1. Draft a deck with Calix, Guided by Fate
2. Deal combat damage to an opponent with either Calix or an enchanted creature.
3. Calix triggers will go on the stack for each instance of Calix in the deck and the battlefield.

**Expected behavior**
Only Calix creatures on the battlefield should trigger from combat damage.

**Screenshots**
The triggers going on the stack. The face-down cards are the Calix cards in the deck.
![image](https://github.com/Card-Forge/forge/assets/26942009/4a242d04-ea78-475c-a2c5-bf91c3cf6db7)
The combat log showing the triggers from an enchanted creature dealing combat damage.
![image](https://github.com/Card-Forge/forge/assets/26942009/c1f8f77a-2b8e-4ec0-9c1d-b91bb9b655d4)
The battlefield state, showing a single Calix creature card on the battlefield.
![image](https://github.com/Card-Forge/forge/assets/26942009/1360f630-f9e0-4d7d-833f-1a9cf46dfaa6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: forge-gui-desktop-1.6.57-SNAPSHOT-05.09

**Comment by tool4ever** [comment]
Fixed by #3085
