### ISSUE TITLE
AI crashes when attacking the player and a battle is on the board

### ISSUE THREAD

**Issue by Nerdmaster** [Card-Forge/forge#3100]
**Describe the bug**

The AI seems to be unable to attack after it has a battle on the board. I am not 100% certain if this is the only situation or if it's always in this situation, but I've seen it multiple times and it's always been battle-related.

It tends to go something like this:

- AI drops a battle on the board
- AI doesn't attack for a few turns (I think this is just because of my board presence, but I'm not certain; sometimes it seems like AI could safely attack earlier)
- When AI finally attacks, I get a null pointer error that "defender" is null, implying the AI is attacking but couldn't choose what to attack.

The error looks like this:

```
[AI Preferences] AI profile Default was chosen for the lobby player Michael.
[AI Preferences] AI profile Default was chosen for the lobby player Ava.
Game-0 > java.lang.NullPointerException: Cannot invoke "forge.game.card.Card.getController()" because "defender" is null
        at forge.ai.AiAttackController.declareAttackers(AiAttackController.java:754)
        at forge.ai.AiController.declareAttackers(AiController.java:1458)
        at forge.ai.PlayerControllerAi.declareAttackers(PlayerControllerAi.java:652)
        at forge.game.phase.PhaseHandler.declareAttackersTurnBasedAction(PhaseHandler.java:545)
        at forge.game.phase.PhaseHandler.onPhaseBegin(PhaseHandler.java:322)
        at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1110)
        at forge.game.GameAction.startGame(GameAction.java:2088)
        at forge.game.Match.startGame(Match.java:90)
        at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:255)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

**To Reproduce**

1. Start a sealed or draft game using March of the Machines as the set (sealed and draft may not be mandatory, but these are the places I see the bug)
2. Build your deck, fight all AIs in gauntlet mode (I haven't tried one vs. one, maybe the bug is there, too)
3. Play until the AI puts out a battle. Give them a moment to prepare for the attack
4. On their turn, when the Declare Attackers step happens, the game dies with the above exception

**Expected behavior**

The AI should be able to choose a defender, not crash.

**Screenshots**

This is my latest game state where a crash occurred. Note the AI's battle in the top right. I don't know if it matters, but I also had battles on the board.

![image](https://github.com/Card-Forge/forge/assets/330040/c8d86b80-084d-4b85-aaef-f3cea41539a7)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser: Firefox
 - Version: copied and pasted from `forge.cmd` startup, see below

```
Forge v.1.6.56 (forge.GuiDesktop@689604d9)
Windows 11 (10.0 amd64)
Language 'en-US' loaded successfully.
(ThreadUtil first call): Running on a machine with 16 cpu core(s)
Read cards: 25803 archived files in 1149 ms (25 parts) using thread pool
Read cards: 589 files in 35 ms (5 parts) using thread pool
```

**Comment by Agetian** [comment]
I tried a few things and couldn't make the AI exactly crash that way so far (tried with various Battles on my side and on the AI side), but I noticed that the AI basically never attacks its own Battle cards to try to trigger them, even if I have literally no way of defending them.
I'll try to investigate, but may need a bit of time, sadly. Could use some help with this one.

**Comment by Agetian** [comment]
In fact, indeed, the battle-related branch (at AiAttackController:725 in chooseDefender) never actually chooses anything

**Comment by Agetian** [comment]
I tried adding some mockup code for the AI to actually choose a battle when able, e.g.:

```
        List<Card> battleDefending = c.getDefendingBattles();
        battleDefending = CardLists.filter(battleDefending, Predicates.or(CardPredicates.isControlledByAnyOf(ai.getAllies()), CardPredicates.isController(ai)));
        Card bestBattle = null;
        if (!battleDefending.isEmpty()) {
            // Get the battle that is the closest to triggering
            int defCounters = Integer.MAX_VALUE;
            for (Card battle : battleDefending) {
                if (battle.getCounters(CounterEnumType.DEFENSE) < defCounters) {
                    defCounters = battle.getCounters(CounterEnumType.DEFENSE);
                    bestBattle = battle;
                }
            }
            if (bestBattle != null) {
                return bestBattle;
            }
        }

```

This works at that point (the battle is chosen as a defender), but the AI then bails and chooses not to attack at all (neither the battle nor the player). The relevant code where it happens is around AiAttackController:837 where the AI determines requirements for the attack, and the battles always end up with the value being set to 0. Then the AI ignores the opportunity to attack and simply attacks no one with anything.

The relevant code is pretty tangled, I definitely need some help to fix this. @tool4ever , what do you think?

Here's an example game state where this is relevant.
[BattleAI_Test.txt](https://github.com/Card-Forge/forge/files/11469144/BattleAI_Test.txt)

**Comment by Agetian** [comment]
It looks like it actually miscalculates around AiAttackController.java:1017, assuming that it will block its own attacking creatures when trying to attack its own Battle (?), and calculates the possible so-called "blocking creatures" as potential opponent's attritional forces, too.

**Comment by Agetian** [comment]
Potentially, it misunderstands "defender" and "defendingOpponent", e.g. in refreshCombatants, it wrongly assigns AI's own creatures to the potential oppList (opponent creatures list) since the owner of the attacked card is the actual AI, not the opponent (which makes the AI confused).

**Comment by Agetian** [comment]
So yeah, by the looks of it, there's currently next to zero AI support for Battles. The AI doesn't attack its own Battles to try to activate them, and it looks like the AI also won't try to prevent the human player from attacking his own Battles either, completely ignoring their existence and potentially miscalculating in quite a few places as to what's going on (which, I guess, could potentially lead to crashes in certain corner cases as well, though I wasn't successful in reproducing the crash mentioned in the original issue).

We need to at least make the AI correctly account for Battles and write some simple algorithms to attack and defend Battles. Any help in coding this is much appreciated, as currently I've exhausted my available spare time, sadly, and will have to get back to investigating this much later.

**Comment by tool4ever** [comment]
Thanks for the hints, I was already afraid the way battles are controlled will be tricky for our AI
I probably fixed the crashes in my last PR for them but making it really work also seemed like a pretty complex task to me
Ideally we'll work towards a Draft that can clean up these outdated assumptions in the code (I was kind of hoping to come up with at least some heuristics when it should still prefer to attack a player outside of assaulting or it might be too predictable?)

**Comment by Agetian** [comment]
Yes, I agree about that. Would also eventually benefit from additional heuristics for sure 😊

**Comment by Agetian** [comment]
An interesting additional side investigation: it looks like the current implementation of Battles (not only AI, the actual mechanics) is somewhat sketchy when it comes to blocking. It looks like there is no way to actually defend the battle (if the AI attacks its Battle (I added some code to simulate that), the human player has no way of defending it even if the human is chosen to be the defender of the battle; the reason is that the chooseBlockers code is never called during the Declare Blockers phase in the case where a player attacks its own card, that doesn't seem to trip the state-based action code that actually calls the relevant method in the player controller, whether it's a human or AI).

**Comment by Nerdmaster** [comment]
Sweet, thanks so much!
