### ISSUE TITLE
Feature Request: Remove Ashnod's Altar/Phyrexian Altar from autotapper

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3156]
**Is your feature request related to a problem? Please describe.**
Most of the time, since I'm aware of the issue, I try to manually tap for mana when I have either Ashnod's Altar or Phyrexian Altar out, but sometimes (often) you just forget... The sac'ing of creatures when other options are *always* better is really bad, like: "I have to exit the game bad, 'cause Forge just ended my board." 

The most egregious just happened a few days ago, which is what prompted me to try to ask for this in the first place. I had a very strong board and six treasures ready to be tapped, plus Phyrexian Altar. I, thinking that surely Forge would be smart enough to tap and sac the obvious SIX treasures for mana when I cast a 6CMC card, didn't even think about being warry of the autotapper... The game sac'd all six of my creatures to Phyrexian Altar instead of using the six treasures. I had to quit.

**Describe the solution you'd like**
Just completely remove Ashnod's Altar and Phyrexian Altar from any kind of autotapping solution. Just don't allow it. If you don't allow it, then Forge can't kill your creatures due to a user's innocent "error" when other much better options are present. 

I know I can't be the only person who has had this issue, so why not just resolve this once and for all? I don't know how hard it would be, maybe very hard, but leaving an obvious problem in and just saying "it's your fault for not tapping manually" is kinda not cool.

Anywho, I really, really do love Forge and I use it a lot. I understand that this is all volunteer and no one gets paid for this project of love, but it *is* a project of love, so maybe show a little bit more love and fix this frustration/rage inducing interaction?

**Comment by Hanmac** [comment]
imo the Autotapper should prefer to sacrifice (non-creature) treasure token before trying to sacrifice creatures

**Comment by TheLastNarwhal** [comment]
Agreed. I also want to say that I've had the autotapper sacrifice creatures instead of tapping pain lands like Mana Confluence. This is another instance where sometimes you just have to quit, because, in my case, it sac'd the creature I was trying to combo with. All in all, if possible, these two cards should really be taken off the menu for the autotapper.
