### ISSUE TITLE
Feature request: Move location of windows user and image cache folder

### ISSUE THREAD

**Issue by Lykrast** [Card-Forge/forge#3167]
**Is your feature request related to a problem? Please describe.**
My C: drive where windows is installed is a small SSD where I just want windows, and I have a separate HDD with tons of space. Currently, the user folder as well as all the card and token images are thrown into AppData (on the C: drive) and I couldn't find any way to move that.

**Describe the solution you'd like**
I would like some option to change where my user data and card images are stored, so that I can put them on my D: drive HDD with tons of space instead of the C: drive SSD with much less space.

While I technically have enough space for it, there are a lot of programs who refuse to be elsewhere than the C: drive for some reason (hate that) so I would like to trim off what I can.

**Describe alternatives you've considered**
I don't really know what a good alternative fix for that issue would be.

**Additional context**
The forge image cache on my computer is currently around 3.5 GB (I take set pictures) so it's still manageable for now.

**Comment by kevlahnota** [comment]
Open forge.profile.properties.example (on your Forge install folder) with notepad or any text editor and read instructions there. It should solve you're issue.

**Comment by Lykrast** [comment]
Oooooooh thanks! Didn't know about that file!
