### ISSUE TITLE
Option to switch from whole cards to just card art squares for battlefield and hand.

### ISSUE THREAD

**Issue by fluorescently** [Card-Forge/forge#3236]
**Is your feature request related to a problem? Please describe.**
There is little point to displaying whole cards on the battlefield and hand they waste lots of screen space. Because cards are so small there their effects become blurry and hard to read.

**Describe the solution you'd like**
There should be an option to show just the square card art on the battlefield and hand - we already have card overlays like power/toughness, abilities, card names every other information about the card could be known by hovering over the card kinda how shandalar or magic arena does it.

**Additional context**
![630418195_orig-3178147492](https://github.com/Card-Forge/forge/assets/134939867/cb461d18-b8bb-416d-b669-5dd903ed0d1c)
![maxresdefault-1507737680](https://github.com/Card-Forge/forge/assets/134939867/9fd166cc-6d1c-45d3-941c-da977fb38c2e)

**Comment by zlyfire** [comment]
Problem with that approach here is card variants. All the cards are single pictures, which is just a scan of the card essentially. There's no knowledge of the art vs the card.
You can get the card art and put it into the card art folder, and that could be an option, but it would require getting all that art available for download as well.
