### ISSUE TITLE
Forge fizzles mass token creation

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3268]
**Describe the bug**
I'm not sure what's happening here, but I assume Forge runs out of some kind of memory. I wanted to test the Esix, Fractal Bloom + Mercurial Transformation combo on a Doubling Season. So I made quite a few Doubling Seasons via that interaction and then attacked with Ancient Gold Dragon to create some more tokens. It pops up the prompt for effect order and I select Esix first and then select all of the Doubling Season triggers. I can choose about 25 or so (maybe a few more) until Forge just fizzles the effect and nothing is created. No error from what I can see is recorded in the *.forge/forge.log*.

**To Reproduce**
1. Have Esix on the field with over 25 Doubling Seasons. (I had 80 on the field.)
2. Cast/Attack with a token producer while another creature is on the field. (I used Ancient Gold Dragon.)
3. Order the effects until Forge fizzels the whole thing.

**Expected behavior**
Forge creates enough tokens to probably cause me to just close the now unresponsive program, but it's at least creating the tokens.

**Comment by Hanmac** [comment]
you probably caused an integer overflow, i think the num token are stored as Integer, where the max is 32bit which = "2 147 483 647"

as soon as you try to create more token, it would fail

**Comment by TheLastNarwhal** [comment]
Ah, well that makes sense then. I didn't even think of that being an issue, I was just thinking I'd stacked too many triggers for forge to take. Thanks.

**Comment by kevlahnota** [comment]
> you probably caused an integer overflow, i think the num token are stored as Integer, where the max is 32bit which = "2 147 483 647"
> 
> as soon as you try to create more token, it would fail

can we control the max limit so it will still produce tokens?

**Comment by tool4ever** [comment]
It's hard to prevent but if this value turns negative it happened:
https://github.com/Card-Forge/forge/blob/5b219bbc64b187c9dbce9e323cf7b8b070e057f6/forge-game/src/main/java/forge/game/ability/effects/ReplaceTokenEffect.java#LL57C24-L57C24

But should we raise it back to Integer.MAX_VALUE?

One could argue that no tokens is better than Forge certainly consuming all memory so if it gets changed at all maybe only a smaller default

Might make a fun achievement though

**Comment by kevlahnota** [comment]
How does MTGO or MTGA handle those big amount? Maybe limit it to safe values and just notify the player via log etc..

**Comment by Ampersandnz** [comment]
MTGA just stops creating tokens at all once you have 250
