### ISSUE TITLE
Possible bug with Witch-king, Bringer of Ruin

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3290]
**Describe the bug**
Witch-King says that when it attacks the defending player sacrifices the creature with the least power among creatures they control. I would assume that if they only control a single creature that they would have to sacrifice it, since it's the creature with the least power on their board. That doesn't seem to be happening.

The trigger came and went, and yet their creature still remains.
![Screenshot_20230617_175336](https://github.com/Card-Forge/forge/assets/92389638/3b7531df-7daf-494b-86fd-acdb198302b6)

Maybe I'm just fundamentally misunderstanding how this card works though...

**Comment by TheLastNarwhal** [comment]
I figured it was just the inversion of Crackling Doom, which I have in this deck and it works just like you would assume when the opponent only has a single creature, that creature gets sacrificed.

**Crackling Doom**: *Crackling Doom deals 2 damage to each opponent. Each opponent sacrifices a creature with the greatest power among creatures that player controls.*

**Comment by tool4ever** [comment]
Fixed by #3281
