### ISSUE TITLE
Forge on Android (Samsung ZFold 4) issue with touch mapping. When touching the screen, it always registers above your finger.

### ISSUE THREAD

**Issue by DigaumSpider** [Card-Forge/forge#3315]
**Describe the bug**

Hello, I'm running Forge (always the latest versions) on Android (Samsung ZFold 4) .
I'm running on adventure mode and I have an issue with touch mapping. When I touch the screen, Forge always registers above where my finger touched.
For example: in my hand or menus, etc, I always have to deliberately touch about 1/4 of an inch below where I actually want the touch to register.

**To Reproduce**
1. Enter Adventure mode
2. Initiate a fight with anyone.
3. When selecting the cards to play, or buttons (do you want to go first or not, etc?) click on the button or card itself
4. The "click" will register about 1/4 inch above where you touched/clicked.

**Expected behavior**
Pretty self explanatory. I'd like the touch to register where I actually touched/clicked 😄 

**Screenshots**
Sorry, screenshots can't help here :(

**Smartphone (please complete the following information):**
 - Device: 
Android (Samsung ZFold 4) - I'm always playing Forge using the "tablet" mode where the phone flip is in an open state.
 Android v 13, Samsung One UI v 5.1 (all latest)
Not using browser
 v 1.6.57-SNAPSHOT-06.18
 
**Additional context**
The only thing I might suspect could be causing the app to behave badly here is that the screen size is more akin to a tablet than a phone, although I've been using every single application under the Sun (games and productivity apps included) in the large screen and they're all mapped correctly, so I'm not quite sure.
I also have been having this issue ever since I started playing Forge, about a month or 2 ago. Been through multiple updates so far, but the issue still remains.

Thank you all for the fantastic application, superb experience and attention to detail. You all rock!

**Comment by kevlahnota** [comment]
landscape mode or portrait mode? did you try both if those have same issue?

**Comment by DigaumSpider** [comment]
> landscape mode or portrait mode? did you try both if those have same issue?

Thanks for the reply. Forge only runs in landscape mode on my Z fold 4 when launching it, so I'm not sure how to test it in portrait at all.
Thanks again.

**Comment by kevlahnota** [comment]
> > landscape mode or portrait mode? did you try both if those have same issue?
> 
> Thanks for the reply. Forge only runs in landscape mode on my Z fold 4 when launching it, so I'm not sure how to test it in portrait at all. Thanks again.

Try to change in the classic settings.. go to classic mode, settings and change orientation.

**Comment by DigaumSpider** [comment]
> Try to change in the classic settings.. go to classic mode, settings and change orientation.

Thank you! I had never used Classic mode before and had no idea these settings could be changed.
I just changed it and it all works perfectly fine, now. I in fact prefer the layout as the cards are organized better in my opinion, and the click "mapping" is spot on, no issues.

To those who are using it on landscape mode, though, it's still worth investigating the issue, perhaps.

Thanks!
