### ISSUE TITLE
Peregrin Took Bug

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3339]
**Describe the bug**
Peregrin Took is supposed to create an additional food token whenever one or more tokens (in general) are created under your control. It seems to only create an additional food token if one or more food tokens are created instead.

**Expected behavior**
I would expect an additional food token to be created whether I create a food, treasure, creature, etc. token.

**Comment by tool4ever** [comment]
Fixed by #3335
