### ISSUE TITLE
Possible bug with how additional/replacement tokens are created

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3344]
**Describe the bug**
I have Gala Greeters on field alongside Peregrin Took. I cast a creature and create a tapped treasure token, as well as a food token, but the food token also comes in tapped. Is this the correct behavior? I would've assumed that the food token would come in untapped.

**Comment by TheLastNarwhal** [comment]
Another possible bug, well, it definitely is one. I had Peregrin Took on the field, Academy Manufactor and Ghalta and Mavren. I attacked with a creature and created a tapped and attacking Dinosaur. Due to the creation of a token I also created a food from Peregrin Took, which proc'd Academy Manufactor to create a food, treasure and clue, however all of these tokens came in tapped... and attacking. I had to select an opponent for each of these noncreature tokens.

**Comment by tool4ever** [comment]
> The additional Food tokens won't have any abilities the other tokens were created with. Anything else specified in the effect creating the token (such as tapped or "Exile that token at end of combat") applies to both the original tokens and the Food.

For the attacking I'll need to check a few things before fixing

**Comment by TheLastNarwhal** [comment]
Gotcha. Wasn't sure about the coming in tapped, could've gone either way.

**Comment by Hanmac** [comment]
> > The additional Food tokens won't have any abilities the other tokens were created with. Anything else specified in the effect creating the token (such as tapped or "Exile that token at end of combat") applies to both the original tokens and the Food.
> 
> For the attacking I'll need to check a few things before fixing

probably extra check for "isCreature" when Attacking?
