### ISSUE TITLE
A.I. cheating with Nils, Discipline Enforcer

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3350]
**Describe the bug**
Nils, Discipline Enforcer says: *"At the beginning of your end step, for each player, put a +1/+1 counter on up to one target creature that player controls."* The A.I. ignores this and places a counter on each of its creatures.

**Expected behavior**
To not place a counter on more than one of its creatures.

**Screenshots**
![Screenshot_20230627_180710](https://github.com/Card-Forge/forge/assets/92389638/32c88388-d2b1-4969-8703-7fd9b18c9a75)

**Comment by Ampersandnz** [comment]
Same thing happens with Shadrix Silverquill - it chooses itself twice instead of two different players. Seems like some of these restrictions on multi-target abilities are being ignored

**Comment by Ampersandnz** [comment]
I've also just seen this happen with Elminster's Simulacrum - AI player chose targets equal to the number of opponents, but they were all controlled by the same player
