### ISSUE TITLE
4K 150% scaling issue with GUI deck viewer

### ISSUE THREAD

**Issue by warlock00** [Card-Forge/forge#3380]
**Describe the bug**
On Home screen. double click a deck to bring up pop up deck viewer window. This window is larger than my screen resolution. Cannot resize this window, and there is no way to press button at bottom of window (off screen).
This occurs because I am on a 4K monitor running at 150% scaling.
If I set scaling to 100% then the deck viewer window size is fine. 

**To Reproduce**
On 4K screen set scaling to 150%
Then bring up pop up deck viewer window.

**Expected behavior**
Able to see entire window.

**Screenshots**
<img width="1920" alt="image" src="https://github.com/Card-Forge/forge/assets/11534905/4697f82a-83c5-4611-8e7c-c6a300b760cd">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.57

**Additional context**
Annoying because I cannot click the button at the bottom of the window.
Microsoft windows lists 300% scaling as the recommended setting.

**Comment by warlock00** [comment]
Anyone want to have a crack at this?
4K monitors have been out for over 5 years. 4K is amazing for card games online.

**Comment by Black616Angel** [comment]
If someone on Linux has the same issue, do the follwoing:
open the Forge.sh file and add this to the line ` -Dsun.java2d.uiScale=2` (match the number to your liking)
