### ISSUE TITLE
Bug with Rhys, the Redeemed and autopay creating fake mana

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3400]
**Describe the bug**
I have Rhys, the Redeemed on the field and can tap to activate his first effect. I only have access to two mana through Elvish Harbinger and an Arcane Signet. Just in case it matters I also have an untapped Eladamri, Lord of Leaves and an untapped, but summon sick Elvish Archdruid.

I am able to attempt to activate Rhys's effect even though I only have two mana. I can activate it, pay for two and then click autopay. The first autopay click ~~doesn't do anything, but a second will somehow magically pay for the Rhys ability as well as depositing a single white mana into my pool.~~ magically adds GW to my mana pool.

I did this on a following turn as well by tapping all sources of mana except two, and then advancing to a new phase to drain the pool. It produced the same result. Somehow I'm able to make the token with only two mana and then get a magical white and green mana in my pool.

**Steps to reproduce**
1. Have Rhys, the Redeemed, Elvish Harbinger (or maybe another mana dork), and Arcane Signet on the field.
2. Having access to only two mana activate Rhys's first effect.
3. Clicking autopay will generate two mana in the pool, could be GW or WW depending on which color you used to pay for the ability.

**Expected behavior**
For the ability to *not* work if I don't have three mana to pay for said ability.

**Screenshots**
Screen of boardstate before activating ability.
![pre-ability](https://github.com/Card-Forge/forge/assets/92389638/a5747ab2-119e-4c7f-92a7-4945de538fdb)

Screen of boardstate on starting payment of ability.
![beginning-payment](https://github.com/Card-Forge/forge/assets/92389638/50e9926c-0f81-4e37-9214-d7f478348329)

Screen of all real sources of mana used for ability.
![all-real-sources-of-mana-tapped](https://github.com/Card-Forge/forge/assets/92389638/fbfa4a56-5c35-4105-accc-ee930bcb9b94)

Screen of GW appearing after clicking autopay.
![1g-1w-magically-appear](https://github.com/Card-Forge/forge/assets/92389638/1c56c57b-adad-4dd4-99e5-9069fb3e7a84)

**Comment by tool4ever** [comment]
I can't reproduce with your boardstate
Autopay is never offered
Are you using a recent snapshot?

**Comment by TheLastNarwhal** [comment]
> I can't reproduce with your boardstate Autopay is never offered Are you using a recent snapshot?

Yes, I'm using forge-gui-desktop-1.6.57-SNAPSHOT-07.02. I feel like I remember stumbling upon this issue with Rhys years ago, but this was before I ever joined github or the forum, so I never reported it.

**Comment by TheLastNarwhal** [comment]
Maybe it has to do with Rhys being the commander? I can instantly set up a game and with Rhys + a mana dork + Arcane Signet and nothing else tap Rhys and have the autopay available and magic up some mana using it.

**Comment by TheLastNarwhal** [comment]
![Screenshot_20230704_062927](https://github.com/Card-Forge/forge/assets/92389638/189b2d05-0dbc-4b75-9d44-52b5fa6a3f1c)

**Comment by tool4ever** [comment]
That seems to be related, I can get it to happen now

**Comment by TheLastNarwhal** [comment]
I wonder if it has something to do with him and the ability both being hybrid mana...?
