### ISSUE TITLE
Mana disappearing into the aether during complex boardstates

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3411]
**Describe the bug**
I have noticed that when you have floating mana in the pool and an overly large boardstate that it seems like Forge will just dump it (mana). It happens when you cast a spell, or possibly use an ability, but definitely during the casting of a spell. The A.I. will go into its thinking mode and then your mana will flicker between 0 and the amount that you floated before going away. There have even been occasions where this flickering will actually allow you to preserve mana between phases.

**Expected behavior**
To either keep your floating mana, or in the case of moving to a new phase, lose it.

**Screenshots**
This is the type of board state where it can happen.

![Screenshot_20230705_054539](https://github.com/Card-Forge/forge/assets/92389638/41d1c834-b4ab-4482-98cc-627e0419a96d)

![Screenshot_20230705_054553](https://github.com/Card-Forge/forge/assets/92389638/39c5a430-c77b-42f8-b117-ac6296ab0ab9)

![Screenshot_20230705_054605](https://github.com/Card-Forge/forge/assets/92389638/5ce5a7d5-89b7-4fd3-a694-bf9c9aaaf04a)

I floated 2w and 2g in the main phase, then moved to combat. The A.I. went into it's normal tanking on a decision mode and then when I arrived in the combat phase I still had the four mana I floated. During this time it was flickering in between the amount floated and 0, before settling on 2w and 2g (the floated amount).

![Screenshot_20230705_055122](https://github.com/Card-Forge/forge/assets/92389638/538514a6-f4e1-44de-912d-8563b69e2b49)

![Screenshot_20230705_055206](https://github.com/Card-Forge/forge/assets/92389638/8e6c0ae9-3d6b-4668-9ecf-0ced2f848866)

**Comment by tool4ever** [comment]
That seems rather weird, though I don't doubt it as all your reports have been pretty accurate so far ;)
But it does sound like pretty hard to reproduce again, can you also upload a gamestate next time you happen on it?
There's also a chance it is just a GUI update problem, did you try if the mana was really available to pay?

**Comment by TheLastNarwhal** [comment]
> That seems rather weird, though I don't doubt it as all your reports have been quite accurate so far ;) But it does sound like pretty hard to reproduce again, can you also upload a gamestate next time you happen on it? There's also a chance it is just a GUI update problem, did you try if the mana was really available to pay?

I thought that it could be a GUI issue as well, so I did in fact make sure to test that it was real mana. I cast Akroma's Will with the mana after the declare attackers step, so it survived two separate phase changes. I'll attempt to recreate it again and grab a gamestate. I think I probably have  a good chance to do it since this isn't the first time I've come across this weird issue.

**Comment by TheLastNarwhal** [comment]
Recreating this gamestate is proving to be rather difficult. Which, I suppose, shouldn't be too surprising considering that out of the thousands of games I've played over the years only a handful have had this bug. I imagine it has something to do with the additional mana provided by cards like Mirari's Wake or Mana Reflection, but intentionally getting to this perfect storm of complex boards and A.I. decisions, to lag(?) the game into keeping or killing the mana is, I now realize, near impossible.

I guess I'll just go back to playing normally and if this ever happens again I'll try to remember to save the gamestate and upload it.

~~This is such an extreme edge case that I almost wonder if it's worth it, or if it can even *be* fixed...~~

**Comment by TheLastNarwhal** [comment]
So, I unintentionally managed to get a gamestate into a place where mana could be floated across phases, so that's good. I also quit Forge and reloaded from the saved state and it still floats the mana. It's not easy to get it to happen, and it will correctly empty the pool most of the time, but there are times, especially when going from main to begin combat that the mana will float through and be usable.

In this saved state if you manage to get the mana through a phase you can use Ulvenwald Tracker to confirm that the mana is real, or I suppose you could also spawn an instant in hand. You won't be successful with floating the mana the first time unless you're incredibly lucky, but it will happen eventually, or at least it does on my computer - which I suppose could be the difference if my computer is less powerful?

[state3.txt](https://github.com/Card-Forge/forge/files/11974963/state3.txt)

@tool4ever
