### ISSUE TITLE
Phyrexian Devourer cloned via Volrath's Shapeshifter causes infinite Sacrifice triggers

### ISSUE THREAD

**Issue by Gamekeeper** [Card-Forge/forge#3414]
When Phyrexian Devourer reaches >=7 power, Forge stacks infinite instances of the sacrifice trigger.

According to the current Oracle rulings, the sacrifice ability only triggers once.

The current handling of this card makes it impossible to execute any devourer combos within Forge.  This is a fairly popular win condition in Premodern and it would be nice to actually be able to resolve it in this program.

**Comment by Agetian** [comment]
What version of the game are you on? I tested this in upstream master and I can't reproduce it, it only triggers once for me.

**Comment by Gamekeeper** [comment]
> What version of the game are you on? I tested this in upstream master and I can't reproduce it, it only triggers once for me.

I am on 1.6.46 for Windows

**Comment by Agetian** [comment]
1.6.46 sounds like a very old version. The current numbered version here on Github is 1.6.56, and even that is quite dated by now (April 2023), quite a lot of things were changed and patched since then...

**Comment by Gamekeeper** [comment]
Ah apologies for posting an issue with such an outdated version.  I have updated to 1.6.56.  I also neglected to mention that the issue occurs specifically with Volrath's Shapeshifter copying Phyrexian Devourer on top of the graveyard.  This situation still causes infinite sacrifice triggers in 1.6.56.

**Comment by Agetian** [comment]
I reproduced this issue with the following game state (if you activate the Phyrexian Devourer cloned via Volrath's Shapeshifter three times so it gets 7 counters, it'll cause infinite Sacrifice triggers to appear:
[phyrexian_devourer_cloned.txt](https://github.com/Card-Forge/forge/files/11985180/phyrexian_devourer_cloned.txt)

Not sure how to properly debug or solve this. @Hanmac @tool4ever , do you have any ideas here?

**Comment by tool4ever** [comment]
The problem is the trigger gets recreated (with a new ID) on each run of `checkStaticAbilities` 🤔

**Comment by Agetian** [comment]
Alright, so what seems to happen is that applyContinuousAbility copies the trigger with a new ID every time the ability is applied (in the Text layer, I guess), which causes the loop. Setting the "lki" parameter to "true" on line 649 seems to fix the issue, but I don't know if it'll have any other unwanted effects somewhere else, and if maybe there's a better and more appropriate solution to this problem. Most likely we don't want/need LKI there as such, but we don't want a new trigger ID either?... At any rate, this is something to think about. I'm not the best at figuring out mechanical subtleties, sadly, so I'd need some advice/help on this one :/

**Comment by Hanmac** [comment]
I will take a look soon when i finished the other ones

What I'm going to do:
similar to the AddAbilties Layer, it needs to store the old Trigger ID so the Text layer only copies the card traits once

**Comment by Agetian** [comment]
Alrighty, sounds good! 👍
