### ISSUE TITLE
Hermit Druid

### ISSUE THREAD

**Issue by Gamekeeper** [Card-Forge/forge#3415]
When resolving the ability of Hermit Druid, Forge does not prompt graveyard order.

By the rules of Magic, the controller of the Hermit Druid ability gets to decide the order in which the revealed cards go to the graveyard.

"Naughty" or "Angry" Hermit is a fairly common combo in Premodern to win by putting your whole library into your graveyard and it would be nice if it worked appropriately in Forge.

**Comment by Agetian** [comment]
There's an option to order the graveyard in the game settings (you can set it to "Always" so that you're always prompted to order your graveyard if you're playing with a relevant deck).
