### ISSUE TITLE
Feature Request: The ability to deselect a spell's/trigger's targets

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3420]
I don't know how hard this would be, or maybe it already exists and I'm just stupid, but if it doesn't already exist, would it be at all possible to add to Forge the ability to "deselect" a target when you're selecting targets? There have been plenty of times where I either clicked a creature, or some other permanent/player by accident or just changed my mind, but couldn't remove that selection. If I clicked it again it would just add the thing to the targeted list once more, whereas normally one would assume that clicking it another time would remove it from the targets list.

I feel like the list of targets shouldn't be final until I click "ok."

As an example I just had an instance where Lathiel, the Bounteous Dawn triggered and I was selecting the creatures. I initially clicked one of my creatures, but then changed my mind and didn't want to distribute counters to that particular target, but alas I was not allowed to change my mind. Forge said: "*You made your bed, now lie in it.*"

**Comment by Hanmac** [comment]
@Agetian we need to remove from GUI that targets try to be added more than once

**Comment by Agetian** [comment]
I'm pretty sure this used to work a while back, not sure what exactly happened. Probably best solved by someone who is good at the GUI part of Forge though ^^;

**Comment by Hanmac** [comment]
@Agetian i think that happened when we separated the divisionValues from the targetDepth values

https://github.com/Card-Forge/forge/blob/master/forge-gui/src/main/java/forge/gamemodes/match/input/InputSelectTargets.java

currently you can try targetDepth should only hold the target collection, and division will be done alter

**Comment by Agetian** [comment]
Alrighty, sounds good! Thanks! :)

**Comment by Agetian** [comment]
Btw, not sure if it's the same issue or a different one, but I noticed I could target the same thing over and over again with the same ability in certain cases (instead of removing the target)... Can't tell off the top of my head what it was exactly that I was trying to do, but if I see it again, I'll let you know.

**Comment by TheLastNarwhal** [comment]
> Btw, not sure if it's the same issue or a different one, but I noticed I could target the same thing over and over again with the same ability in certain cases (instead of removing the target)... Can't tell off the top of my head what it was exactly that I was trying to do, but if I see it again, I'll let you know.

Yeah, this is what I was talking about. When selecting targets, if you're able to select multiple ones, you can continuously select the same target, but you can't *unselect* that target. Obviously with a spell that you're casting you can just click cancel and redo all the targets, but with a trigger ability if you select the wrong target or change your mind, you're pretty much out of luck.

**Comment by TheLastNarwhal** [comment]
Now this is a good example. Here I cast Nethroi for its mutate and then started to select creatures in the graveyard to bring back. At first I jumped at Thalia and the Gitrog Monster, but then I thought better and decided to target The Gitrog Monster and Ramunap Excavator, but I can't unselect Thalia...

![Screenshot_20230711_030352](https://github.com/Card-Forge/forge/assets/92389638/9d0acb7f-5852-498a-9422-c26d64abb8de)
