### ISSUE TITLE
Feature Request: Quest Mode - Spell Shop - "Sell all extras" button

### ISSUE THREAD

**Issue by Spiggy73** [Card-Forge/forge#3425]
The button "Sell all extras" works the way, that it sells all but **1 of each** cards (except basic lands). This works well, if I am playing in the Commander subformat.

I started another quest with normal 4-of rules. In this case I expected the button to sell all but **4 of each** cards. But it still sells all but 1 although the mouseover says "Sell unneeded extra copies". In non-Commander MTG I'd like to keep 4 of each ;-)

2 possible solutions (I guess):
- two different buttons (sell all but 1 / sell all but 4)
- the button behaves differently regarding the format you are playing

would be nice if you can implement this. thanks :-)

**Comment by Samthere** [comment]
Just a note, you can fix this in the Quest Preferences - the "Playset Size" parameter determines how many copies of a card the game will keep when you sell all extras. Maybe starting a commander quest defaulted it to 1 and it never changed back.

**Comment by Spiggy73** [comment]
oh wow... I'm dumb. TY, didnt ever notice that
