### ISSUE TITLE
Bug with Hurl Through Hell

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3433]
**Describe the bug**
I am unable to cast the spell exiled with Hurl Through Hell.

**Hurl Through Hell**: *Exile target creature. Until the end of your next turn, you may cast that card and you may spend mana as though it were mana of any color to cast that spell.*

**To Reproduce**
1. Cast Hurl Through Hell.
2. Attempt to cast the creature exiled with Hurl Through Hell.
3. Become sad that your super cool play isn't gonna happen.

**Expected behavior**
To be able to cast the creature exiled with Hurl Through Hell using any color mana.

**Comment by tool4ever** [comment]
Probably fixed by #3426

**Comment by TheLastNarwhal** [comment]
Yes, it appears to be working on the latest snapshot (forge-gui-desktop-1.6.57-SNAPSHOT-07.08x) now. I'll just close this since a fix was already in the works.
