### ISSUE TITLE
Banding can fail in multiplayer if creature can't attack first defender

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#3460]
There's probably another related corner case with cards like _Weathered Sentinels_ hiding there, if you feel so inclined:
because the restriction is dependent on specific defender, you might not be able to band because InputAttack only initializes the boolean that toggles it once

_Originally posted by @tool4ever in https://github.com/Card-Forge/forge/issues/1665#issuecomment-1275814102_

**Comment by Agetian** [comment]
Not sure if I understand how to fix this, would likely need help with this one ...
