### ISSUE TITLE
Amethyst Dragon // Explosive Crystal: Explosive Crystal Not Working

### ISSUE THREAD

**Issue by etphonehome73** [Card-Forge/forge#3465]
**You must change code to this. Now working!**

Name:Amethyst Dragon
ManaCost:4 R R
Types:Creature Dragon
PT:4/4
K:Flying
K:Haste
AlternateMode:Adventure
Oracle:Flying, haste

ALTERNATE

Name:Explosive Crystal
ManaCost:4 R
Types:Sorcery Adventure
**A:SP$ DealDamage | ValidTgts$ Any| ValidTgts$ Any | TgtPrompt$ Select any number of targets to distribute damage to | NumDmg$ 4 | TargetMin$ 0 | TargetMax$ 4 | DividedAsYouChoose$ 4 | SpellDescription$ CARDNAME deals 4 damage divided as you choose among any number of targets.**
Oracle:Explosive Crystal deals 4 damage divided as you choose among any number of targets.

BEFORE:

**A:SP$ DealDamage | ValidTgts$ _Any to distribute damage to_ | NumDmg$ 4 | TargetMin$ 0 | TargetMax$ 4 | DividedAsYouChoose$ 4 | SpellDescription$ CARDNAME deals 4 damage divided as you choose among any number of targets.**

WRONG CODE:

 **| ValidTgts$ _Any to distribute damage to_ |**

**Comment by tool4ever** [comment]
Already fixed by e242003
