### ISSUE TITLE
Loose control of keyboard

### ISSUE THREAD

**Issue by aknight2015** [Card-Forge/forge#3485]
'm running the Linux version, I'm using Pop!_OS (Ubuntu/Debian distro). My Java Version is openjdk 11.0.19 2023-04-18. Forge version is 1.5.56.

Whenever I use Forge, I can't use my backspace key, enter key, delete key, most of the letters on my keyboard. I have to log out and log back in to get control.

**Comment by TheLastNarwhal** [comment]
I used to run into this issue all the time. It would basically bork all my programs and my computer would behave as if I were always using hotkeys. I found that it occured when I used any of the download buttons in the *Content Downloaders* section. I don't do that anymore, and as a result it doesn't seem to cause system instability.

This is the error report post from back when it used to happen: https://www.slightlymagic.net/forum/viewtopic.php?f=26&t=31106&p=251894&hilit=manjaro#p251894

**Comment by Jetz72** [comment]
Also using Pop_OS - I experience this periodically, but I assumed it was a rare quirk of alt tabbing. Don't remember if I was using the content downloading at the time. Even after Forge closes, every other application behaves as though the alt-key is held down until logging out and back in. Pressing either alt key or any other modifier key doesn't reset it. 

I wouldn't know which specific component of the operating system is being broken by this bug, but it seems like this should be reported there as well. I feel like it shouldn't be possible for an already terminated process to have a permanent effect on user inputs like this.

**Comment by aknight2015** [comment]
I think it has to do with Java. Call it a hunch.

**Comment by TheLastNarwhal** [comment]
> Also using Pop_OS - I experience this periodically, but I assumed it was a rare quirk of alt tabbing. Don't remember if I was using the content downloading at the time. Even after Forge closes, every other application behaves as though the alt-key is held down until logging out and back in. Pressing either alt key or any other modifier key doesn't reset it.
> 
> I wouldn't know which specific component of the operating system is being broken by this bug, but it seems like this should be reported there as well. I feel like it shouldn't be possible for an already terminated process to have a permanent effect on user inputs like this.

I was using Manjaro at the time, I'm using Kubuntu (ubuntu) right now. And yeah, even after closing the Forge program my system would remain in this broken state until I rebooted. I may have been using Java 11, at the time, but I don't recall. I know for sure that I am using Java 17 right now though.

**Comment by aknight2015** [comment]
As far as I know, it still affects Java. I have the most up to date version for my distro.

**Comment by aknight2015** [comment]
This issue is continuing. Any sort of idea if this issue is capable of being addressed?

**Comment by aknight2015** [comment]
This is still an issue. It hasn't gone away.
