### ISSUE TITLE
Feature Request: Ability to use restricted mana independently of non-restricted mana

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3494]
**Is your feature request related to a problem? Please describe.**
Admittedly, this is a fairly niche issue, but when it arises it is frustrating. As an example, right now I have a game where I have Karn, Legacy Reforged on the field and a Grim Monolith. I have 12 colorless mana in the pool with the restriction that it can't be used to cast nonartifact spells. I want to tap Grim Monolith for its restrictionless mana and then pay its untap cost with only the restricted mana. This is all so I can cast a large Blue Sun's Zenith. Right now this is impossible to do though...

**Describe the solution you'd like**
Ideally, when you have a mixture of restricted mana and non-restricted mana in your pool and you go to cast a spell or use an ability a prompt of some kind would pop up, then you would be able to select which kind and how much of that kind you wanted to use.

I can imagine that it is probably fairly difficult to implement something like this, but it would be an amazing QoL upgrade to this program.

**Additional context**
I've also had this issue with things like Castle Garenbrig where the creature restricted mana would get mixed up with the non-restricted mana and end up not allowing me to cast my non-creature spells. I would count the correct mana needed for two spells and have it in the pool, but since I don't have control over what is used the non-restricted mana would end up being used on the creature spell, leaving the restricted mana for the non-creature spell.

**Comment by tool4ever** [comment]
Fixed by #10051
