### ISSUE TITLE
DoctorWho: Time Travel N Times

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#3503]
New Effect:

> For each suspended card you own and each permanent you control with a time counter on it, you may add or remove a time counter.

AI might need some logic on when it is better to add a time counter to a suspended card
normally it should do this:
* suspended Card: remove time counter
* Card in play: add time counter

The Effect probably should be designed like proliferate 

> To time travel, look at each permanent you control with a time counter on it and each card you own in exile with a time counter on it. For each of them, you choose whether you want to put a time counter on that card or permanent, remove a time counter from it, or do neither. Then those changes all happen simultaneously.

the rules say, you should check for each card if you want: Add/Remove/None, but imo its more clear if you select them first

**Comment by tool4ever** [comment]
I think `CountersPutOrRemoveEffect` can already handle it

**Comment by Hanmac** [comment]
> I think `CountersPutOrRemoveEffect` can already handle it

The Thing is the `N Times` and how it's handled with Triggers
