### ISSUE TITLE
Possible bug with Vedalken Shackles and Teferi's Protection

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3511]
**Describe the bug**
I honestly don't know if this is a bug, but it seems like it would be to me.

I have Vedalken Shackles and it is tapped and controlling an opponent's creature. I cast Teferi's Protection phasing everything out. Vedalken Shackles never becomes untapped, yet the opponent's creature goes back to the owner's battlefield. During my upkeep when everything phases back in, I choose *not* to untap Vedalken Shackles, but the opponent's creature is still on their battlefield and it is phased out, it phases back in during their turn under their control.

**To Reproduce**
1. Have Vedalken Shackles tapped controlling an opponent's monster.
2. Cast Teferi's Protection.
3. Creature controlled by Vedalken Shackles returns to it's owner's control.

**Expected behavior**
I would assume since Vedalken Shackles never becomes untapped that I would retain control of the opponent's creature.

**Comment by kevlahnota** [comment]
maybe this: https://blogs.magicjudges.org/ftw/returning-mechanics-review/phasing/ 
![image](https://github.com/Card-Forge/forge/assets/9781539/1982592f-45e0-4880-a625-6234ee19da51)

**Comment by TheLastNarwhal** [comment]
I suppose that makes sense. 

One thing though, if the game can no longer see the cards, then how does it know to return the phased out creature that Vedalken Shackles is stealing to its owners control? I don't doubt that you have it right, wasn't sure it was a bug to begin with, I just want to understand the reasoning since both cards are phased out.

**Comment by TheLastNarwhal** [comment]
Nevermind. I don't know why I couldn't find this before I posted this question/report. Guess I just didn't ask google the right question. The second half of the rule is the same as what you posted, but the first half explains why a phased out creature would revert control to its owner.

**702.25e:** *Continuous effects that affect a phased-out permanent may expire while that permanent is phased out. If so, they will no longer affect that permanent once it’s phased in. In particular, effects with “for as long as” durations that track that permanent (see rule 611.2b) end when that permanent phases out because they can no longer see it.*
