### ISSUE TITLE
Localized Effects might break AI checks

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#3522]
Effect Unique$ doesn't seems to be used anymore 

https://github.com/Card-Forge/forge/blob/8f1d8ce265fe265cc53c165619d24208cf608098/forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java#L138-L140

The Translations in createEffect would break isCardInCommand checks used also by the AI
https://github.com/Card-Forge/forge/blob/8f1d8ce265fe265cc53c165619d24208cf608098/forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java#L500-L524

i don't know if isCardInPlay is also affected, but i think for Real Cards, the getTranslatedName should be different?

Also for the Emblem check, should we use extra Emblem flag instead of checking the Name?

**Comment by kevlahnota** [comment]
- #3524
