### ISSUE TITLE
Wrong sequence for some discard choices

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#3526]
Matters for some cards, e.g. _Borderland Explorer_:
> Players decide whether or not they’re discarding a card in turn order. Each player will know if previous players are discarding, but not what they are discarding. All cards to be discarded are set aside, then revealed and discarded simultaneously. Similarly, all basic land cards searched for are set aside, then revealed simultaneously.

Ugly idea:
- ChooseGeneric on all players with Pump sub to remember each who wants to discard first

**Comment by Northmoc** [comment]
I had a branch started for this! Github calm down

**Comment by tool4ever** [comment]
@Northmoc
maybe Repeat isn't actually needed because I kind of forgot my previous work on this: https://github.com/Card-Forge/forge/commit/4effb02

**Comment by Northmoc** [comment]
What other cards are currently wrong?

**Comment by tool4ever** [comment]
So far I only found:
- Ruin Grinder
