### ISSUE TITLE
UI_DISABLE_REBALANCED_CARDS=true doesn't currently catch all alchemy cards

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#3551]
I don't really want these alchemy cards to ever appear in my games, partly because I don't want to deal with fake cards, and also those images are always blurry and I don't care for the way those cards look. It seems like the YONE, YDMU, YBRO, and HBG stuff is always allowed even under **UI_DISABLE_REBALANCED_CARDS=true**.

**Describe the solution you'd like**
Ideally there would be a box you could check in game that would disable all these ~~unwanted and fake~~ cards, but at the very least I would like it so that when you manually change the preferences file that these cards don't just slip through.

**Comment by kevlahnota** [comment]
that option is only usable on snapshot version and it is experimental. Do you use snapshot?
