### ISSUE TITLE
Adventure Mode: Duel sometimes fails to init

### ISSUE THREAD

**Issue by jumpinjackie** [Card-Forge/forge#3559]
**Describe the bug**

Sometimes when beginning a duel with an enemy, the UI fails to init somehow and no initial hand is drawn and the places where the keep or mulligan buttons normally reside, are now empty. Once in this state, you cannot get out if it without force quitting forge.

See attached screenshot

**To Reproduce**

Unfortunately, I cannot find a way to reliably reproduce this. I guess fight enough duels in Adventure Mode and it eventually happens? Seems to happen when I'm in a dungeon/building/cave/etc, I haven't yet observed this when I'm dueling an enemy in the overworld.

**Expected behavior**

I expect an initial hand to be drawn and be prompted to keep or mulligan

**Screenshots**

![2023-07-30 04_44_49-](https://github.com/Card-Forge/forge/assets/563860/139d94aa-9a57-4198-9a5b-4527c77fa05d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version 1.6.58-SNAPSHOT-07.29

**Additional context**

**Comment by kevlahnota** [comment]
if you encounter the error again can you upload forge.log? it seems your opponent is missing a deck? did you extract the snapshot to new folder?

**Comment by jumpinjackie** [comment]
> if you encounter the error again can you upload forge.log? 

Sure, will keep an eye out

> it seems your opponent is missing a deck? did you extract the snapshot to new folder?

Everytime I download a new snapshot build, I wipe the existing snapshot install folder first before extracting the new snapshot build tarball into it, so I guess that's a yes.
