### ISSUE TITLE
Storm cards with target player such as brain freeze and tendrils of agony dont work

### ISSUE THREAD

**Issue by vheren** [Card-Forge/forge#3590]
**Describe the bug**
Storm cards such as brain freeze and tendrils of agony have no way to select targets on the copied spells from the storm trigger. It has you stack the triggers but there is no way to select the target player on the copies, instead the copies have no target and nothing happens when the triggers resolve

**To Reproduce**
cast either of the cards with with a storm count

**Expected behavior**
select targets for each trigger or at least use the same target as the original spell

**Screenshots**
![help](https://github.com/Card-Forge/forge/assets/76803745/bcffbd4a-69d6-4071-a888-9fcd32983adc)
![help2](https://github.com/Card-Forge/forge/assets/76803745/323e763f-9e67-4c2a-b8d8-699dd6838ac5)

**Desktop (please complete the following information):**
windows 10

**Comment by kevlahnota** [comment]
Can you update to latest snapshot. I can't reproduce the error.

**Comment by vheren** [comment]
> Can you update to latest snapshot. I can't reproduce the error.

i dont know how to do that, the version is the lord of the rings one in the releases

**Comment by kevlahnota** [comment]
> > Can you update to latest snapshot. I can't reproduce the error.
> 
> i dont know how to do that, the version is the lord of the rings one in the releases

read user guide: https://github.com/Card-Forge/forge/wiki/User-Guide#downloads

**Comment by vheren** [comment]
> > > Can you update to latest snapshot. I can't reproduce the error.
> > 
> > 
> > i dont know how to do that, the version is the lord of the rings one in the releases
> 
> read user guide: https://github.com/Card-Forge/forge/wiki/User-Guide#downloads

it works 100% on the latest snapshot, ty!
