### ISSUE TITLE
Start Game from command line

### ISSUE THREAD

**Issue by L3v3L** [Card-Forge/forge#3601]
**Is your feature request related to a problem? Please describe.**
none

**Describe the solution you'd like**
Would be great if you could start a game from a command line, Feeding in a gamestate text file and then game results were logged out also.
This would open up people developing other apps (just like the adventure mode) that could use forge for the card playing part.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by tehdiplomat** [comment]
@L3v3L you mean like this? https://github.com/Card-Forge/forge/wiki/ai#ai-matches-from-command-line

**Comment by L3v3L** [comment]
@tehdiplomat yes, just not headless, and let the user play.
