### ISSUE TITLE
Adventure - Zombie Town Spawns Demoncaller in Solid Object

### ISSUE THREAD

**Issue by andrewc42** [Card-Forge/forge#3623]
https://github.com/Card-Forge/forge/blob/626a8bf02098bd17cbaadd67886c2d9276677bd1/forge-gui/res/adventure/common/maps/map/hostiletown/zombietown.tmx#L129-L134

The pentagram summoning circle is a solid object and this spawns the demon caller enemy in it. I assume the summoning circle sprite should not be solid, but I'm not sure which line controls that.

To complete the quest for this town, I had to shift the x location of the demon caller and reload so I could fight him.

**Comment by Simisays** [comment]
Thanks I'll get it fixed
