### ISSUE TITLE
Advanced Filtering in Spell Shop

### ISSUE THREAD

**Issue by Spiggy73** [Card-Forge/forge#3635]
Is it possible to add "Qty" in the advanced filtering in Spell Shop? 
This would be helpful to me when I try to complete a set as I can see which cards I still have <4 copies of.

Thank you
Stefan

**Comment by Goddfrey** [comment]
You can sort it by "owned" ascending, and once you see the first 4 you are done checking. Something like in the screenshot.

![owned-sort](https://github.com/Card-Forge/forge/assets/49716936/328cc647-6c85-4510-8ac8-ebfbaa0e7740)

**Comment by Spiggy73** [comment]
> You can sort it by "owned" ascending, and once you see the first "4" in the column, you are done buying for that iteration. Something like in the screenshot.
> 
> ![owned-sort](https://user-images.githubusercontent.com/49716936/261839483-328cc647-6c85-4510-8ac8-ebfbaa0e7740.png)

yes, I know about this possibility. But my situation is the following: there are ~20 cards with <4 copies from one edition an I grind some drafts to pick up the missing ones. So my plan would be to only show those cards (filtering qty<4 and the desired set) and then sort those by CN.

When I am in the reward splash screen to pick up one rare or mythic this list is sorted by CN. So it is 1:1 comparable to my view in the spell shop, making it easier for me to remember which card I need. (I cannot switch back to Spell Shop when the splash screen is up)

I feel so old when I just described this :D
