### ISSUE TITLE
Adventure mode: Always show card names in $LANG in shop

### ISSUE THREAD

**Issue by jumpinjackie** [Card-Forge/forge#3639]
Version: 1.6.58-SNAPSHOT-08.10 Android

**Is your feature request related to a problem? Please describe.**

Occasionally, when I visit a shop in Adventure mode, I see a card for sale but the card image is in Japanese instead of English. Unless the card is popular/well-known enough, I generally don't have an idea what the card actually is and may be skipping over on a potentially useful card due to a different language card image being shown and not knowing the card art intimately enough to jump over the language barrier.

![Screenshot_20230815-233633_Forge](https://github.com/Card-Forge/forge/assets/563860/9b6a5e25-406e-4237-a2ac-fef0cd98cd6e)

**Describe the solution you'd like**

Replace $LANG below with English or whatever currently-configured language if forge supports i18n card names (IDK if this is the case)

Just like the duel UI, show the $LANG card name overlaid on top of each card in the shop and provide the ability to swipe up when looking at a card in detail to see the full $LANG card name and oracle text, irrespective of the card image shown.

The swipe up to see oracle text is a "nice to have" just showing the $LANG card name is sufficient for me to do a Gatherer/Scryfall lookup as a workaround.

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by Hanmac** [comment]
the problem there is that this is a special print of the card, that only exist in Japanese that's why it can't show them in your language.

@kevlahnota might look into it if the card name can be shown over the card as overlay

**Comment by jumpinjackie** [comment]
@Hanmac The duel UI seems to know that my JP print of "Karn, the Great Creator" that I'm using is indeed "Karn, the Great Creator"

![forge_game](https://github.com/Card-Forge/forge/assets/563860/bf040dd3-352d-45e1-9860-e55927ba5a0b)

![karn_jp](https://github.com/Card-Forge/forge/assets/563860/f272f31a-525d-47ff-97a9-ba1d290b22b1)

Could this not also be done for the Shop UI?

**Comment by Hanmac** [comment]
yeah, that's exactly what i mean with Overlay the White Card name on top of the image

but I'm neither GUI nor Adventure (Shop) Developer, so i don't know how difficult that would be too add

**Comment by kevlahnota** [comment]
I have a working draft, looks fine.. But it needs character alignment and some sort of custom BG to see the text clearly.. Need to figure it though.. 
![image](https://github.com/Card-Forge/forge/assets/9781539/d6aa416f-eb50-4eb0-926f-f0e84deb5b9e)
