### ISSUE TITLE
Revealed cards in the opponent's had should stay revealed

### ISSUE THREAD

**Issue by Goddfrey** [Card-Forge/forge#3642]
When any effect reveals card(s) in opponent's hand they should stay revealed just like MtG Arena does. Of course we can write them down and track it when they leave hand manually but that's not what computers are for :)

Edit: hand, not had :)

**Comment by Hanmac** [comment]
imo no, Arena there isn't following the rules

technically cards in hand should stay hidden when they aren't revealed anymore

**Comment by Goddfrey** [comment]
> imo no, Arena there isn't following the rules
> 
> technically cards in hand should stay hidden when they aren't revealed anymore

The only practical difference is a player has to write them down. Which is a permitted and go to method in sanctioned tournaments in real life. I can see the reason behind it with physical cards but I see no reason for this inconvenience when using computers. Neither did WotC judging by Arena implementation.

**Comment by Hanmac** [comment]
The difference there is for Forge, you may see which (physical) card is which by their ID

the moment when opponent draws the same as the revealed card again and plays another one, you could see by their ID if it was the same card or not

Arena for example hides the revealed card if you play the other one

**Comment by Goddfrey** [comment]
All right that does make the difference. I guess notepad it is then :(
