### ISSUE TITLE
Wastes dont count as basic lands

### ISSUE THREAD

**Issue by Tiwega** [Card-Forge/forge#3649]
While playing a commander game with my Urza's Liberator deck, I couln'd search for Wastes with any such cards, i.e. Evolving Wilds, Fabled Passage or Sword of the Animist.

**Comment by tool4ever** [comment]
Can't reproduce, need more details or a gamestate
![grafik](https://github.com/Card-Forge/forge/assets/8506892/b96bdcf7-495e-4fb2-82dd-afaa20c29807)
