### ISSUE TITLE
Quest Mode balance issue: Shandalar fat packs price is ludicrous

### ISSUE THREAD

**Issue by Goddfrey** [Card-Forge/forge#3662]
**Describe the bug**
The price of every and any fat pack in Shandalar's world is exactly 2365, I assume it misses at least a couple of zeroes at the end, given the expected average value of Antiquities, Revised, Alpha, Beta and Unlimited fat packs.  For comparison, Antiquities just one booster costs 10k, i.e. five times more than a whole pack of boosters. And something like Mishra's Workshop from Antiquities can sell for 58k+, covering expenses for roughly 29 Fat Packs. And dont get me started on how many A/B/R/U Fat Packs you can buy if you sell just one Mox, or Black Lotus from them. I was not sure maybe they don't have as good card chances as single booster pack does so I did some testing and after roughly 30 mins of Shandalar farming I'm swimming in credits and power cards making whole Quest mode trivial.

Now sometimes cards don't sell for more than 1k no matter what, in the early game, but later I seem to be able to sell them without this cap. But even with the cap in place, price is still absurd in relation to single booster pack's price and the expected value is still higher than that :)

**To Reproduce**
Travel to Shandalar in Quest mode. Check the Spell Shop

**Expected behavior**
Increase the price appropriately please :)

**Screenshots**
![fat pack price](https://github.com/Card-Forge/forge/assets/49716936/bf464a07-6c95-4826-a7ed-c6ee59b1f470)

**Desktop (please complete the following information):**
 - Windows 10
 - Forge 1.6.58-SNAPSHOT-08.19, card prices downloaded via ingame content downloader.

**Edit**: when you play _without_ a pricelist, the default fat pack price is exactly the same. So the problem might be not so much a typo in price as just missing price for the fat pack in the pricelist, so the app falls back to default. Maybe.

**Comment by OrphanStomper** [comment]
Unfortunately this is not limited to shandalaar. At all. 
The economy of *any* quest game with irl prices which includes reserved list sets is prone to periodically tempt the player with fat packs that *absolutely* break it in half. 
Even as someone who only plays on the main world, I will hit one in the shop every 5-10 refreshes, allowing me to amass a majority of the cards in the game before I even hit 50 wins.
Having to deny myrself these to preserve any feeling of an economy kinda ruins the fun. Drafts present the same issue, but you have to actively seek those out, they are more easily avoided.
I came here to bring up the same exact issue, **I believe there should be a change to calculate the price of any fat pack in a "real prices" playthrough as `price of an individual booster * number of boosters in product` if no real world price is available.**

**Comment by OrphanStomper** [comment]
Actually that suggestion was somewhat ignorant, just changing the prices manually is the best fix ig (changing the prices that download automatically that is).
@Goddfrey In the meanwhile you can just edit the product price yourself, booster-prices.txt in the res folder.
