### ISSUE TITLE
AI flaws

### ISSUE THREAD

**Issue by Goddfrey** [Card-Forge/forge#3674]
So I understand coding AI is very hard especially for a game like MtG, and it's not gonna play anywhere near as good as humans unless you get Alpha Zero's team working on it. Forge's AI is already _much_ better than that of Arena's or Shandalar's and is the main reason I play Forge. That said, some of it's flaws are so game breaking I believe they do qualify as bugs.

* I've never seen AI to not pay cumulative upkeep even when it's detrimental to them. Even if the upkeep is paid in life, AI will just happily go ahead and suicide. If it's mana, they will lock themselves out of casting anything and just pay CU for the useless crap.
* Similarly, as far as I noticed AI always uses "you may" triggers during the upkeep. I.e. it never stops adding counters on Aether Vial way past the point of the CMC of the most expensive creature in their deck, rendering the card useless. _(as of 1.6.57)_
* AI doesn't understand effects like "_when a creature becomes target of a spell or ability first time in a turn, counter it_", or "_counter the first spell played each turn_". It will still play a spell even if it costs all the mana AI has and _will_ get countered by the effect already in play.
* AI doesn't understand "when this is dealt damage, deals the same amount to target player" type of effects and happily burns such permanents even when it means immediate game loss for it.  (as of 1.6.58-SNAPSHOT-08.23x)
* AI keeps casting spells during it's own upkeep whenever it can, for no reason, not as bad as other problems but still a very detrimental strategy to say the least.
* Having to choose between two of the same legendary AI seems to prefer keeping in play the newer one. Which breaks certain "Play against Vintage deck" Quest Challenge. AI plays Oath of Druids -> Emrakul combo, a few copies of Emrakul being the only creatures in deck apparently, since AI gets one every turn. And keeps the new one every turn, not the one who already has no summoning sickness. And since Emrakul has no haste it never attacks. (as of 1.6.58-SNAPSHOT-08.23x)
* AI keeps using more removal than necessary if you do anything in response to their removal. i.e. it casts STP on Kenrith, The Returned King. You activate any of Kenrith's abilities while STP is on stack, say draw a card. AI immediately casts another STP while the rest is on stack even if the first one would kill it just fine. It's just one example I've seen similar pattern numerous times. Once it just suicided using too many removal spells in response to each other on Bonecrusher Giant, taking 2 damage each time. As of 1.6.58-SNAPSHOT-09.03

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 1.6.58-SNAPSHOT-08.19, unless stated otherwise.

**Edit**: added a couple more
**Edit**: and one more

**Comment by MorihiroS** [comment]
> AI keeps casting spells during it's own upkeep whenever it can, for no reason, not as bad as other problems but still a very detrimental strategy to say the least.

Agree! For example, AI sacrifice Sakura-Tribe Elder immediately after it's summoned, not using it as a blocker on its opponent's turn. Even the bot from the tutorial for Ninth Edition could pull this off with Bottle Gnomes.

**Comment by amishtal** [comment]
Regarding the "You may..." effects, it seems to always choose yes even for things that are directly against its best interests. Livio, Oathsworn Sentinel allows me to target a creature, and then it's controller may choose to exile it with an aegis counter (another ability of the creature returns all exiled creatures with aegis counters onto the battlefield under their owner's control). The AI will happily let me exile all their creatures (it's a 2 mana activated ability that doesn't tap Livio).

**Comment by myyk** [comment]
Adding on:
* I noticed AI seems to not always know how to use sacrificial cards like "Black Lotus" for example. AI seems to always play and sacrifice it even if they don't intend to spend the mana for anything. It would be better if they could understand that it's mana that there's value in it being on board but not used. But maybe that it's less than playing something.
