### ISSUE TITLE
Forge Adventure Mode Fails to Start

### ISSUE THREAD

**Issue by Itude** [Card-Forge/forge#3678]
**Describe the bug**
Starting the Adventure Executable, leads to the expected Configuration Interface.  But the World itself fails to load; just hangs indefinitely.

**To Reproduce**
1. Start Forge via Forge Adventure Mode.
2. Click on Adventure Mode.
3. Select New Game.
4. Click Start.
5. Wait..
6. Wait indefinitely..
7. Stuck on 'Generating World' Screen.

**Expected behavior**
Adventure Mode should start.

**Screenshots**
![image](https://github.com/Card-Forge/forge/assets/14318963/b413126d-1457-4362-94ab-c5fe5c2c1d67)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Forge 1.6.58 Snapshot 08.19 .. Java (JRE) Version 8 Update 381 (1.8.0_381-b09) .. JDK 20.0.2

**Additional context**

**Comment by kevlahnota** [comment]
can you attach forge.log, also did you extract the snapshots to new folder? if not follow this guide: https://github.com/Card-Forge/forge/wiki/User-Guide
