### ISSUE TITLE
First fetchland from graveyard with Serra Paragon without exile

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3696]
**Describe the bug**

When a player play his first fetchland from his graveyard with a Serra Paragon under his control, the angel's ability appears on the stack. At that moment, you can sacrifice fetchland in response. Fetchland goes to the graveyard, not exiled, and can be played again next turn. On future tries everything works correctly, only when it happens for the first time in the game.

**To Reproduce**
1. Cast Serra Paragon
2. Play fetchland (for example, Windswept Heath) from graveyard first time in game.
3. See Serra Paragon's ability in stack
4. Sacrifice fetchland
5. See fetchland at graveyard

**Expected behavior**
Fetchland is exiled after sacrifice and the player gains 2 life. Ideally, Serra Paragon's own abilify should not appear on the stack

**Desktop:**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.58-SNAPSHOT-08.26

![bug 1](https://github.com/Card-Forge/forge/assets/115870280/4eb897c1-b9ca-474e-bde4-7ee07571847c)
![bug 4](https://github.com/Card-Forge/forge/assets/115870280/e19a12f7-8dd0-4e71-883f-5724abc0731b)

**Comment by Hanmac** [comment]
@tool4ever Serra Paragon probably should not be a trigger (or be a static one)

**Comment by MorihiroS** [comment]
Hi, @tool4ever, is it real to fix?
