### ISSUE TITLE
Osgir, the Reconstructor's tap ability randomly stops functioning

### ISSUE THREAD

**Issue by Uthred** [Card-Forge/forge#3703]
**Describe the bug**
Osgir, the Reconstructor's tap ability ("Variable Colorless, Tap, Exile an artifact card with mana value X from your graveyard: Create two tokens that are copies of the exiled card. Activate only as a sorcery.") randomly stops functioning. Usually it will work once or twice at the start of the match and then it will be constantly greyed out.

**To Reproduce**
1. Make a Commander deck with Osgir as the Commander
2. Use his tap ability, try to use it again on subsequent turns or after untapping

**Expected behavior**
His ability should work as long as he's untapped and no other cards are actively preventing it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest release version

**Comment by kevlahnota** [comment]
I think this is fixed on latest snapshot version...

https://github.com/Card-Forge/forge/assets/9781539/f2a26bf9-4904-4861-90c7-16a1cc360424
