### ISSUE TITLE
Several problems recently encountered

### ISSUE THREAD

**Issue by stormcat664** [Card-Forge/forge#3710]
**Describe the bug**
1. Barrow-Blade is not Legendary.
2. Desecrate Reality's Adamant ability should only refer to owner's graveyard.
3. CR:800.4i does not seem to be reflected.
e.g. When I kept copying and looping Strefan, Maurer Progenitor's ability, Blood tokens generated were also reduced if my opponent lost in the process.

**To Reproduce**
3. The number of players is varied before resolving an ability that refers to the number of players.

**Expected behavior**
3. Memorize the number of players who fulfill the conditions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] forge-gui-desktop-1.6.58-SNAPSHOT-08.28

**Additional context**
I'm not confident in my English because of the complicated explanation.

**Comment by Hanmac** [comment]
Barrow-Blade fixed

**Comment by tool4ever** [comment]
For the player LKI the problem is _Stefran_ doesn't have a ruling.

I thought the rule made sense like this:
> At the beginning of your postcombat main phase, you may pay X life, where X is the number of opponents that were dealt combat damage this turn.
- > If a player was dealt combat damage and subsequently lost the game, Tymna’s triggered ability counts that player to determine the value of X. 

But the newer printed:
> When Moonshae Pixie enters the battlefield, draw cards equal to the number of opponents who were dealt combat damage this turn.
- > Moonshae Pixie's triggered ability counts only players who are still in the game. If an opponent was dealt damage but then left the game, that player isn't counted.

I see no real templating or rules change that would explain the different rulings. 😕

**Comment by Hanmac** [comment]
@tool4ever can you check out Stefan?

**Comment by tool4ever** [comment]
After more research I think the templating with "for each [player] ..." only refers to the the current game state.

This is also consistent with even more similar wording of _Gnoll War Band_:
> This spell costs {1} less to cast for each opponent who was dealt damage this turn.

which provides the relevant ruling
>  Opponents who have left the game will not be counted when determining how many opponents have been dealt damage this turn.

**Comment by stormcat664** [comment]
Strefan counts the number of players, not the number of opponents, so I think the behavior is strictly different.

Gnoll War Band↓
702.125b Players who have left the game are not counted when determining how many opponents
you have

Strefan↓
800.4i If an effect requires information about a specific player, the effect uses the current
information about that player if they are still in the game; otherwise, the effect uses the last
known information about that player before they left the game. If an effect requires information
from the game about actions players have taken, the effect can find actions that were taken by a
player who has left the game.

**Comment by tool4ever** [comment]
Alright, I still think you can't use LKI because it's not really a specific player in this case but I will try and ask judges soon

**Comment by Hanmac** [comment]
@tool4ever have you checked the Rules for Stephan yet?

**Comment by tool4ever** [comment]
Oh right I did and the answer wasn't that reassuring:
https://www.reddit.com/r/askajudge/comments/16w719d/strefan_maurer_progenitor_and_player_lki/
I will leave it alone unless better information can be provided.
