### ISSUE TITLE
AI activates Grist without a target

### ISSUE THREAD

**Issue by Triquetra** [Card-Forge/forge#3728]
**Describe the bug**
AI activates Grist, the Hunger Tide's -2 ability ("You may sacrifice a creature. When you do, destroy target creature or planeswalker.") when it has no creature to sacrifice. The net effect is merely the loss of loyalty on Grist with no value to AI.

**Expected behavior**

1. Generally, AI should not activate planeswalker abilities which do not provide value.
2. Specifically for Grist, AI should not activate the -2 ability unless it has a creature to sacrifice. Preferably, the AI should evaluate whether it is of more value to keep the potential sacrifice victim or if it would be better to remove an opponent's creature or planeswalker.

**Screenshots**
![2023-09-02 12_31_19-Forge_ 1 6 58-SNAPSHOT-08 28](https://github.com/Card-Forge/forge/assets/195027/0e316bef-6884-4dc0-92f1-8775d666e7c6)

**Desktop (please complete the following information):**
- OS: Windows 11
- Java Version: JRE 8.0.381
- Forge Version: 1.6.58-SNAPSHOT-08.28

**Comment by tool4ever** [comment]
Fixed by #3737
