### ISSUE TITLE
Urza's Saga doesnt want to undo

### ISSUE THREAD

**Issue by Nemesis666first** [Card-Forge/forge#3745]
Im stuck in a moment in the M1 phase where : Urza's Saga got his Lore counter, and nothing happend.
I turned Urza's Saga to create a token, but I had only one mana available.
The game is now stuck...

**Comment by kevlahnota** [comment]
Can you provide more details, screenshot, forge version.

**Comment by tool4ever** [comment]
Honestly all three issues sound like user error
Gonna close them soon if no clarifications get provided...
