### ISSUE TITLE
The +1 of Wrenn and Realmbreaker seems to not working

### ISSUE THREAD

**Issue by Nemesis666first** [Card-Forge/forge#3750]
This Planeswalker seems to have an issue. When I select it +1, it asks to select a land, then... nothing.

**Comment by tool4ever** [comment]
The card works fine. We've asked you to provide at the minimum screenshots already before

**Comment by Nemesis666first** [comment]
A screenshot would shows nothing.
Maybe there were an Immortal Sun and I didnt see it, this is the only thing I can think about. But if it's the case, why the soft allows me to select a skill from a Planeswalker.
