### ISSUE TITLE
Developing custom AI: is it possible?

### ISSUE THREAD

**Issue by gcoter** [Card-Forge/forge#3756]
Hi there! I have tried to look for documentation or existing issues on this topic but I could not find anything apart from this issue which is now closed for inactivity: https://github.com/Card-Forge/forge/issues/3062

I would like to experiment with creating an AI for Magic the Gathering using Machine Learning (as it is my field of expertise and because I think it would be fun). To do this, I essentially need two things:
1. It must be possible for me to implement a custom AI that is compatible with a rules engine (as yours). That means that at some point there is a method in which I can implement my own logic to decide what to do next (from the list of all legal moves) and I can access all the information available to the current player about the current (and past) game state.
2. I need to be able to "simulate" games programmatically, for instance having an AI fight another AI with random decks and repeat this thousands of times. That way I can benchmark AIs and also collect data (which assumes that I can record the game logs). Another usage of such "simulation" feature would be for an AI to simulate the game several moves ahead to find the best option.

So my question is: is it possible using forge? Or at least some parts of these things? I see that you already have an AI player so I assume that some part of it already exists. I would be interested to know more about it :slightly_smiling_face:

**Comment by tool4ever** [comment]
Hey

our documentation is suboptimal but most of your requirements are handled in some way :)

- rudimentary command line support see https://github.com/Card-Forge/forge/wiki/AI
- standard AI is pretty hardcoded effect API but you can enable simulation extension which will perform MCTS-like approach with simple boardstate scoring function
- rudimentary test framework supports running specific game steps, see e.g. #3669 for application

**Comment by gcoter** [comment]
Hey @tool4ever, than you for your response :slightly_smiling_face: I have some additional question if you don't mind:
- The command line corresponds indeed to what I had in mind, is it possible to save the logs in a structured format?
- Could you give some pointers to the files/classes I should look at? In particular, let's say I want to extend your AI with a MCTS approach, as you said, where should I start?
- I see a lot of ongoing works/issues about your AI and in your documentation you mention that you would prefer a trained AI if possible, so I assume it was already discussed. Are there people working on that currently?

**Comment by gcoter** [comment]
For what it's worth, in case it might interest you, for the last few months I have been working with a friend on a re-implementation of the game in Python and I have started to train some AI in a very restricted version of the game (no abilities, only basic land and creatures, no MCTS yet):
- Project: https://github.com/gcoter/magic-the-gathering-python
- Experiments: https://github.com/gcoter/magic-the-gathering-python/blob/minimal-creatures-and-lands-only-no-abilities/docs/experiments.md

The problem is that it is actually quite difficult to implement Magic and in fact most of our efforts up to now went into implementing the rules. So if it was possible to use your engine instead and focus more on the AI part, it would be great :slightly_smiling_face:

**Comment by tool4ever** [comment]
- I assume logs will be stored, you'll just have to see if you need to adjust the structure
- understand the (simulation) code I guess? we have different `PlayerController` classes that provide many entry points for interactions based on what rules events are happening
- Not really. I don't see any constraints on what you train for though, I'm not sure e.g. an unlimited card pool would result in anything reasonably smart 🤔

**Comment by gcoter** [comment]
Hi @tool4ever, thank you for your answers :slightly_smiling_face: I will take a look at the code, try to run it and see what I can do depending on the data that is available and the different entry points that are available. As up to now I was using a very simplified version of the game, it is more than likely that the strategy I used for training needs to be adjusted.

**Comment by Hanmac** [comment]
right now we have some different AI Profiles to make the AI more reckless

**Comment by marthinwurer** [comment]
The main issue blocking a more robust tree-search AI like AlphaZero is having a more robust single-step system where the AI can copy the game state that it's given, get a list of all possible choices for the current player, and apply them to modify their copy of the game state, then evaluate that modified copy. The current simulation code is effectively a reimplementation of a good chunk of the engine, and isn't very stable. My changes in #3669 are a step towards using the core engine for simulation.

**Comment by gcoter** [comment]
Hi @marthinwurer, thank you for your remark! Indeed, I was making the assumption that it is possible to copy the current state and explore different "action paths"
