### ISSUE TITLE
Double Fires of Invention mess up adventure casting options

### ISSUE THREAD

**Issue by Goddfrey** [Card-Forge/forge#3766]
**Describe the bug**
With a single Fires of Invention I get the 4 options: cast adventure, cast creature, cast adventure via FoI, cast creature via FoI. With double FoI in play I also get 4 options but they seem to be the first 4 or random 4 out of the 6 intended to display. So I can get "cast as adventure" twice, one for each FoI presumably, but don't get "cast as creature via FoI" at all. See the screenshot.

I did try to find a way to maybe scroll the list but there seems to be none, it's a complete list displayed. Also I did try keyboard; to click 5 or 6, does not do anything, while 1 through 4 do work.

**Expected behavior**
I can think of no reason to display separate set of options for each Fires of Invention that are in play, I don't think MtG rules require it, you are not "activating" FoI and you are not required to tell which one of them you are using as you cast the spell. You simply have an option to cast it without paying mana. So we should get the same amount of options no matter how many FoI are in play.

But if I am wrong then obviously full set of options should be displayed, 2 normal (adventure and creature) + 2 per FoI.

**Screenshots**
![fires-of-invention-2](https://github.com/Card-Forge/forge/assets/49716936/96e891f5-3daf-4739-b49a-911e2476aa1c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.58-SNAPSHOT-09.10, Java 8

**Comment by tool4ever** [comment]
You don't have 7 lands to pass the restriction on the creature part.

In theory it might not matter which one you use in this scenario but for other cards it's more important.

**Comment by Goddfrey** [comment]
Damn I must have had a brainfart. Sorry :)
