### ISSUE TITLE
Tanglespan Lookout triggering from the library

### ISSUE THREAD

**Issue by IMNOTACROOK22** [Card-Forge/forge#3769]
**Describe the bug**
Tanglespan Lookout's ability triggers even when it is not on the battlefield.

**To Reproduce**
1. Have Tanglespan Lookout in your library. 
2. Cast an Aura or put an Aura into play (roles). 
(I have yet to test to see if it occurs in other zones i.e. exile or graveyard)

**Expected behavior**
Tanglespan Lookout should only trigger when it is in play. 

**Screenshots**
![Tanglespan trigger going on stack despite not being on the battlefield.](https://i.imgur.com/7VgJueD.png)

**Desktop:**
 - OS: Windows
 - Version 11

**Comment by tool4ever** [comment]
ALready fixed by c92e892
