### ISSUE TITLE
Cascade bug

### ISSUE THREAD

**Issue by zyval** [Card-Forge/forge#3777]
**Describe the bug**
Android. Cascade spells show a notification but nothibg happens afterward.

**To Reproduce**
1. Cast a spell with cascade

**Expected behavior**
Show cards from library until a spell with less cmc is shown and offer to cast that spell

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11 lite
 - OS: latest android 

**Additional context**
Only tested in android

**Comment by kevlahnota** [comment]
> **Describe the bug** Android. Cascade spells show a notification but nothibg happens afterward.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Cast a spell with cascade
> 
> **Expected behavior** Show cards from library until a spell with less cmc is shown and offer to cast that spell
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Xiaomi 11 lite
> * OS: latest android
> 
> **Additional context** Only tested in android

This should be fixed on latest snapshot version.
