### ISSUE TITLE
AI sacrifice Sakura-Tribe Elder immediately

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3780]
**Describe the bug**
AI sacrifice Sakura-Tribe Elder immediately after cast. He doesn't wait until the end of his opponent's turn to use Sakura-Tribe Elder as a blocker. This is characteristic of all four types of AI! Even the AI from the tutorial disc for 9th Edition knew how to sacrifice Bottle Gnomes after declaring them blockers.

**To Reproduce**
1. AI cast Sakura-Tribe Elder
2. AI sacrifice Sakura-Tribe Elder immediately

**Expected behavior**
AI will sacrifice Sakura-Tribal Elder at the end of an opponent's turn, after declaring it as a blocker or in response to a spell or ability that targets Sakura-Tribal Elder.

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.58-SNAPSHOT-09.16

**Additional context**
I think the same problem applies to creatures like Dawntreader Elk or Diligent Farmhand.

**Screenshots**
![bug sakura (def)](https://github.com/Card-Forge/forge/assets/115870280/7ff6eda9-75cd-4d96-9f02-947940035293)

**Comment by MorihiroS** [comment]
The problem hasn't been solved
Forge Version: 1.6.59-SNAPSHOT-10.19

**Comment by MorihiroS** [comment]
@Agetian, AI understands how to deal with Bottle Gnomes, sacrificing them after letal blocking. I think it's realistic to give the AI a similar pattern of action with Sakura-Tribe Elder, but on the condition that it sacrifices Sakura-Tribe Elder before the start of its turn.
Again, it's worth considering the presence of Amulet of Vigor on the battlefield

![bottle](https://github.com/Card-Forge/forge/assets/115870280/037a9ff7-1ed7-42f4-a4f0-399b02c279b2)

**Comment by Agetian** [comment]
I'll see what I can do when I next have a window opportunity for some debugging/coding ;)
