### ISSUE TITLE
Disturb mechanic not working for double-faced creatures

### ISSUE THREAD

**Issue by kenizl86** [Card-Forge/forge#3782]
**Describe the bug**
Creatures with Disturb that come back as a back-faced creatures don't come back as the correct creature, they instead come back as their front face. Built a deck of all Disturb cards, only the ones that don't come back as creatures work properly (ex: Binding Geist // Spectral Binding). Chaplain of Alms was the card I was playing with when I discovered the bug during a match.

**To Reproduce**
1. Play any deck with a creature with Disturb that comes back as a creature
2. Once it's in the graveyard, activate Disturb

**Expected behavior**
They should be coming back as their back-face. Example: Chaplain of Alms should come back as Chapel Shieldgeist.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit
 - Version: 1.6.55 (Java edition?)

**Additional context**
 I know I'm running an older version of Forge; however, as a test I did compare the cardsfolder files for Chaplain of Alms from my version with what is here on GitHub, and they're still both the same. So the problem should still persist to the newest version.

**Comment by tool4ever** [comment]
no, this is already fixed in newer engine
