### ISSUE TITLE
AI uses Roiling Vortex ability multiple times

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3810]
**Describe the bug**
AI uses Roiling Vortex ability multiple times just for no reason, not in response to player actions, and does so for all the possible mana. 

**To Reproduce**
1. AI cast Roiling Vortex and have untapped lands
2. Player heal himself with, for example, Bubbling Cauldron
3. AI uses Roiling Vortex ability multiple times

**Expected behavior**
AI uses Roiling Vortex ability only in response to player actions or triggers that can heal the player. 

**Additional context**
AI type: experimental

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.58-SNAPSHOT-09.23

**Screenshots**
![vortex](https://github.com/Card-Forge/forge/assets/115870280/4175b108-49c5-4266-bcf7-05afb511cdfc)

**Comment by Hanmac** [comment]
@Agetian AI needs logic for the Effect to check if the Opponent already can't gain life
