### ISSUE TITLE
White area Dungeon with Caracal and Lions has z-order issues

### ISSUE THREAD

**Issue by developingedan** [Card-Forge/forge#3820]
**Describe the bug**
There is a dungeon in the white area that was populated with lions and caracals. Desert with a central redoubt. All of the sand tiles near the plateau are over the creature/player sprites

**To Reproduce**
1. Go to cat/lion dungeon
2. Walk near plateau
3. You will go under the sand tiles

**Expected behavior**
Landscape tiles should be below sprites

**Screenshots**
Map
![image](https://github.com/Card-Forge/forge/assets/2677858/d7d5ebfd-08c0-4bba-bba8-4099dbae7a00)
Overland dungeon icon
![image](https://github.com/Card-Forge/forge/assets/2677858/d9c28112-3de3-457a-9cd3-47bee777fa58)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser adventure.exe
 - Version 1.6.59-SNAPSHOT-09.23

**Comment by Simisays** [comment]
I'll take a look thanks
