### ISSUE TITLE
Adventure Mode: Sliver dungeon (skep) is extremely laggy

### ISSUE THREAD

**Issue by jumpinjackie** [Card-Forge/forge#3830]
**Describe the bug**

The sliver dungeon (skep) in Adventure mode is extremely laggy. It didn't used to be like this.

**To Reproduce**

Enter the sliver dungeon and try to navigate around.

**Expected behavior**

It should be smooth like other dungeons

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Device: Galaxy S9
OS: Android 10
Browser: N/A
Version: 1.6.59-SNAPSHOT-09.29

**Additional context**

**Comment by Simisays** [comment]
>  It didn't used to be like this.

When was that ? a few updates ago or before the skep got revamped ?

**Comment by jumpinjackie** [comment]
> When was that ? a few updates ago or before the skep got revamped ?

Sorry for the lack of details on that front, if I recall the last time I ventured into skep in an Adventure mode playthrough would've been around late June / early July, so whatever [git master / snapshot build] was around at that time I suppose.

**Comment by jumpinjackie** [comment]
UPDATE: As of `1.6.59-SNAPSHOT-10.13` this dungeon is now longer slideshow-tier laggy, but is still more sluggish than the overworld or other dungeons
