### ISSUE TITLE
Adventure Mode: No reward from legionnaire after defeating sliver queen

### ISSUE THREAD

**Issue by jumpinjackie** [Card-Forge/forge#3831]
**Describe the bug**

When you enter the sliver dungeon (skep) and talk to the legionnaire NPC, he hints at a reward if you defeat the sliver queen. But after defeating the sliver queen and talking to the legionnaire NPC again, there is no reward and the conversation is the same as before.

**To Reproduce**

1. Enter the sliver dungeon (skep)
2. Talk to the legionnaire about rewards for defeating the sliver queen
3. Defeat the sliver queen (after defeating the 3 "lieutenants" beforehand as a requirement for entering her cave)
4. Talk to the legionnaire again about your reward.

**Expected behavior**

I get a reward for defeating the sliver queen as promised. But instead I get the same conversation tree from step 2.

**Screenshots**

This is the legionnaire I'm talking to

![Screenshot_20230929-205647_Forge](https://github.com/Card-Forge/forge/assets/563860/b48edce1-d42d-4313-9135-5194a0b0e798)

This is the reward I'm supposed to get if I defeat the sliver queen.

![Screenshot_20230929-205707_Forge](https://github.com/Card-Forge/forge/assets/563860/1694d1a1-ee61-4729-943c-b4b94ae0e792)

**Smartphone (please complete the following information):**

Device: Galaxy S9
OS: Android 10
Browser: N/A
Version: 1.6.59-SNAPSHOT-09.29

**Additional context**

**Comment by Simisays** [comment]
Yeah, I'm still working on the aftermath of the Sliver Queen defeat. (Item and the Sliver's becoming friendly). Should be expected in the next few weeks. 

Also did you like the fight against the queen ?
