### ISSUE TITLE
Creatures owned by opponent that die and then ETB under my control don't trigger ETB effects.

### ISSUE THREAD

**Issue by amishtal** [Card-Forge/forge#3832]
**Describe the bug**

Ardarkar Valkyrie allows me to choose a target creature and return in to the battlefield under my control when it dies. By using this on an opponent's creature and then destroying it, I gain control of it. Since this involves the creature dying and returning to the battlefield, I would expect it trigger ETB effects. This is the case when my own creatures are targeted by Ardarkar Valkyrie and then die, but doesn't occur with creatures I don't own.

**To Reproduce**
1. Have an ETB effect source in play.
2. Use one or more abilities to remove a creature you don't own or control from the battlefield and return it under your control.

In my case,  Ardarkar Valkyrie provided the means of returning the creature to the battlefield under my control, a Cavalier of Dawn entering the battlefield provided the destroy effect to cause the creature to die, and there were several ETB triggers in play:
- Preston, the Vanisher
- Distinguished Conjurer (x4)
- Ajani's Welcome
- Angelic Chorus

**Expected behavior**
Creatures that enter the battlefield under my control should trigger effects that are triggered by creatures entering the battlefield under my control.

**Screenshots**
I'm not sure if any pictures would help with this.

**Smartphone (please complete the following information):**
 - Device: Galaxy Note 10+
 - OS: Android 12
 - Version 1.6.58-SNAPSHOT-9.20

**Additional context**

**Comment by kevlahnota** [comment]
Can you try to update to latest snapshot? Just tested here on android and it works fine..

https://github.com/Card-Forge/forge/assets/9781539/314b8945-2de9-43c7-8f89-a8bbc489f85f

**Comment by amishtal** [comment]
Interesting, I just updated so I will try to get a similar board state again.

For some more details about the instance I experienced, the creature in question was a Relentless Rat. I also had Lifeline out, but resolved the Ardarkar Valkyrie effect first. I had a Cathars' Crusade in play as well, and noticed the rats I stole earlier in the course of going through the stack didn't get +1/+1 counters, even though they were on the battlefield and under my control when thr Cathars' Crusade effect resolved.

**Comment by amishtal** [comment]
It's still not working like it should, updated to 1.6.59-SNAPSHOT-09.29. The creature enters the battlefield without triggering any of the ETB effects. 

This is what happens when one of my creatures enters:

![Screenshot_20230929-205052_Forge](https://github.com/Card-Forge/forge/assets/680891/6f7f29e5-c15f-4dcb-b9d5-a6ba4df8b6cf)


And here's a sequence of images showing what happens when I steal one of their creatures:

![Screenshot_20230929-204603_Forge](https://github.com/Card-Forge/forge/assets/680891/b55634d3-aea7-487b-9577-fbd7040f83d8)
![Screenshot_20230929-204658_Forge](https://github.com/Card-Forge/forge/assets/680891/e990b8d7-e48f-4f66-a4e9-76de14cdd5a7)
![Screenshot_20230929-204716_Forge](https://github.com/Card-Forge/forge/assets/680891/d6b03c83-29c8-42b8-ae77-7288d670df55)
![Screenshot_20230929-204730_Forge](https://github.com/Card-Forge/forge/assets/680891/c30cf46c-cbcc-4e03-972b-ee70f94dbce5)

**Comment by kevlahnota** [comment]
can you be specific what doesn't work on your screenshot? the cards you mentioned earlier doesn't trigger likt in the original report.. but on your screenshot it triggers. Does it trigger but not resolved? what particular card didn't trigger that should trigger?

**Comment by amishtal** [comment]
The several abilities that trigger on a creature entering the battlefield under my control are what have been the issue, not Ardarkar Valkyrie's ability. Sorry if that wasn't clear.

The first picture shows what the stack looks like when I flicker one of my creature. When the effect resolves, it triggers Distinguished Conjurer, Ajani's Welcome, and Preston, the Vanisher. This is what I would expect the stack to look like whenever any nontoken creature enters the battlefield under my control by some means other than casting.

The other four pictures show me going through the steps of using Ardarkar Valkyrie to mark a target creature owned by my opponent (second picture), then killing it by having it block (third picture). The effect from Ardarkar Valkyrie triggers correctly (fourth picture), but then it resolves and none of the ETB effects I have are triggered (fifth picture) even though it is a nontoken creature entering the battlefield under my control from the graveyard without being cast. The fifth picture should look the same as the the fourth picture, but with the zone changer being [Relentless Rats (338)] instead of [Ardarkar Valkyrie (30)].

**Comment by amishtal** [comment]
I'm noticing the same thing happening with creatures I own now. Twice I've used Gilraen, Dunedain Protector to flicker a creature (I chose to return it immediately both times) without it triggering any ETB effects that aren't on the returning card itself. Both times I used the dev menu to untap Gilraen and flicker again and it works fine.
