### ISSUE TITLE
Workshop Elders unable to animate treasure token

### ISSUE THREAD

**Issue by Triquetra** [Card-Forge/forge#3837]
**Describe the bug**
I was playing a commander gauntlet against the AI. The AI was playing Tinker Time precon. The AI played Workshop Elders and then tried to animate a treasure token it had created. But the ability did nothing. The token did not become a creature.

**Expected behavior**
When a treasure token is targeted by Workshop Elders' triggered ability, it should become a 0/0 creature with 4 1/1 counters on it.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.6.59-SNAPSHOT-09.29

**Comment by tool4ever** [comment]
It can do that since it's optional though the scenarios that make that the better decision are probably more uncommon

**Comment by kevlahnota** [comment]
> It can do that since it's optional though the scenarios that make that the better decision are probably more uncommon

tried adding ailogic always, seems to work.. (though a better ailogic would be best)
```
SVar:TrigAnimate:DB$ Animate | ValidTgts$ Artifact.nonCreature+YouCtrl | TgtPrompt$ Select noncreature artifact | AILogic$ Always | Power$ 0 | Toughness$ 0 | Types$ Artifact,Creature | Duration$ Permanent | SubAbility$ DBPutCounter
```
