### ISSUE TITLE
Immobilizer Eldrazi rulings not correctly applied

### ISSUE THREAD

**Issue by fgoncalves** [Card-Forge/forge#3886]
**Describe the bug**
According to the [rulings](https://gatherer.wizards.com/pages/card/Details.aspx?multiverseid=407607) `Immobilizer Eldrazi`'s ability should check for power and toughness when you declare blockers however it seems to check it as the ability resolves.

**To Reproduce**
1. Begin the puzzle `Perplexing Chimera (GatheringMagic.com) 012616 - Sucker Punch`
2. You should be in the attack phase of your opponent
3. During the attack phase of your opponent do the following:
      a. Cast `Sweep Away` using `1UR` targetting opponent's attacking `Mountain` and choosing to put it into their library.
      b. Cast `Dimensional Infiltrator` using `U`. Before it resolves cast `Abstruse Interference` using `U` and `Hedron Crawler`'s ability targetting the `Dimensional Infiltrator`.
      c. Let `Kozilek's Sentinel` trigger resolve so it becomes a `2/4`.
      d. Let `Abstruse Interference` resolve but pay `R` so `Dimensional Infiltrator` doesn't get counter.
      e. Let `Kozilek's Sentinel` trigger resolve so it becomes a `3/4`.
      f. Finally let `Dimensional Infiltrator` resolve.
      g. Using `R` and `Cultivator Drone`'s ability, activate `Dimensional Infiltrator`'s ability. The card on top of your opponent's library is a `Mountain` and we can return `Dimensional Infiltrator` to our hand.
      h. Finally, cast `Dimensional Infiltrator` again and let everything resolve. Your `Kozilek's Sentinel` should now be a `4/4`.
4. Move to the `Declare Blockers` phase and try to block any creature with `Kozilek's Sentinel`.
5. `Kozilek's Sentinel` is not able to block any creature.

**Expected behavior**
`Kozilek's Sentinel` is now a `4/4` and should be able to block even though it was a `1/4` when `Immobilizer Eldrazi`'s ability was activated.

**Desktop**
 - OS: MacOs
 - Browser: chrome (not sure why this matters)
 - Version: mtg forge 1.6.59

**Additional context**
I assume there are many ways to hit this issue, I just found it during the puzzle.

**Comment by tool4ever** [comment]
It's interesting that you mention this exact puzzle because it should actually have a crash on loading I've been meaning to fix

**Comment by fgoncalves** [comment]
@tool4ever oh! It does load fine for me and the terminal from where I've launched forge doesn't really output any stacktrace. I know you've said crash. The program is not crashing but sometimes when there's an exception the stack trace is output to the terminal but not here either.

Any other details I could provide? Java version, OS version, any other thing?

**Comment by Hanmac** [comment]
@tool4ever in general we need to remove the use of HiddenKeywords there
