### ISSUE TITLE
Order of target legality checking with dependency restriction has unwanted influence

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#3893]
The way ``hasFizzled`` removes illegal targets sequentially could cause some weird results.

Example:
- Cast _Blatant Thievery_ on Opps A Creature X + Opps B Creature Y
- Before resolve have A gain control of Y
- You will now only gain control of X or Y (whichever you targeted last is kept)

The ruling on it:
> If a permanent changes controller after being targeted but before this spell resolves, you won't gain control of that permanent.

Means it should always be X that is kept?

_Chaos Mutation_ is worded differently:
> The phrase “target creatures controlled by different players” means that no two targets may be controlled by the same player.

Means it should always fizzle?

**Comment by Hanmac** [comment]
isn't that issue a duplicate? hasFizzled needs to be reworked by me anyway inside the MagicStack thing

**Comment by tool4ever** [comment]
You mean #1179?

well it is a related topic but for this it's more about keeping the wrong target which might mean `SpellAbility.canTarget` also needs better logic

but maybe both can fixed together

**Comment by tool4ever** [comment]
@Hanmac
Once your PR is merged the example above will worsen such that you won't gain control of either creature

However I think we're probably still taking a step in the right direction and need to think of something else to cover these kind of situations?

**Comment by tool4ever** [comment]
We need to consider LKI there too 🤔 
> If one of the two target creatures becomes an illegal target, Run Away Together can still determine its controller only to check whether the other creature is a legal target. If the illegal target has left the battlefield, use its last known information. If the other creature is still a legal target, it's returned to its owner's hand.
