### ISSUE TITLE
Jetfire, Ingenious Scientist Not converting after using Mana ability

### ISSUE THREAD

**Issue by magusnebula** [Card-Forge/forge#3909]
**Describe the bug**
Jetfire, Ingenious Scientist Not converting after using Mana ability

**To Reproduce**
1. Cast **Jetfire, Ingenious Scientist**
2. Use ability to remove counters, targeting yourself for player to gain mana
3. **Jetfire, Ingenious Scientist** does not convert to  **Jetfire, Air Guardian**

After using **Jetfire, Ingenious Scientist**  Mana ability, the card would not transform. **Jetfire, Ingenious Scientist**  activated ability was missing code to call his sub ability.

**Forge Gui**
Tested on Windows, Android, MacOS M1

**Additional context**
Adding commit #3908

**Comment by kevlahnota** [comment]
- #3908
