### ISSUE TITLE
The Locust God

### ISSUE THREAD

**Issue by Sylopidae** [Card-Forge/forge#3925]
When The Locust God dies, it is supposed to go back to your hand which avoids commander tax. In Forge, instead of going back to your hand, it goes back to the command zone which incurs commander tax and does not reflect realistic gameplay. This bug also affects the cards The Scorpion God, and The Scarab God.

To reproduce this, I have a deck called 'TLG5' which I'm willing to make available to play. Alternatively, The Locust God and The Scarab God are both decks which appear as automated decks and can be played by the system.

Links to relevant cards:
https://scryfall.com/card/hou/146/the-scorpion-god
https://scryfall.com/card/hou/139/the-locust-god
https://scryfall.com/card/2xm/216/the-scarab-god

**Comment by kevlahnota** [comment]
The card works fine, you have the option to move the commander or not to command zone... watch video for sample. I'll close this and mark as invalid and this is user error..

https://github.com/Card-Forge/forge/assets/9781539/b38a3d62-650d-48a0-9080-5f5ae3492512
