### ISSUE TITLE
WHO Face a Villainous Choice

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#3926]
> 701.53. [Face a Villainous Choice](https://mtg.fandom.com/wiki/Face_a_villainous_choice)
        701.53a “[A player] faces a villainous choice — [option A], or [option B]” means “[A player] chooses [option A] or [option B]. Then all actions in the chosen option are performed.”
        701.53b While facing a villainous choice, a player may choose an option that is illegal or impossible. In that case, they perform as much of the action as is possible. This is an exception to rule 608.2d.
        701.53c A replacement effect may replace an instruction to face a villainous choice with an instruction to face that choice some number of additional times. In that case, the entire process described in rule 701.53a is performed for that player the appropriate number of times one at a time.
        701.53d If more than one player is instructed to face a villainous choice, the entire process described in rule 701.53a is performed for each of those players one at a time in APNAP order. This is an exception to rule 608.2e.

similar to GenericChoice , but because of the exceptions, (and replacement effects)

 The Valeyard has this:
> If an opponent would face a villainous choice, they face that choice an additional time.

**Comment by Hanmac** [comment]
Current Logic to implement the Effect:

```
(for Player p : Defined Players) {
  Replace VillainousChoice N=1
  for (i = 0; i < N; i++) {
    SpellAbility choice = p getController Choice from List
    choice.add Remember (p)
    Ability resolve (choice)
    choice.remove Remember (p)
  }
}
```

**Comment by Hanmac** [comment]
@tool4ever do you want to checkout the Effect for this? or should i try this?

**Comment by tool4ever** [comment]
I'm mostly busy with reviews and other stuff
