### ISSUE TITLE
AI incorrectly uses 2 Reflection of Kiki-Jiki

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3938]
**Describe the bug**
AI copies one Reflection of Kiki-Jiki with another and so on for as long as AI has mana. The AI ends up with no mana and with one untapped Reflection of Kiki-Jiki.

**To Reproduce**
1. AI casts 2 Fable of the Mirror-Breaker
2. Both Fable of the Mirror-Breaker return to the battlefield transformed
3. AI uses all mana to copy Reflection of Kiki-Jiki with another Reflection of Kiki-Jiki.

**Expected behavior**
AI shouldn't copy one Reflection of Kiki-Jiki with another one (unless the opponent is trying to destroy/exile another Reflection of Kiki-Jiki).

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-10.19

**Screenshots**
![kiki1](https://github.com/Card-Forge/forge/assets/115870280/8c47274f-412e-486b-8867-33442036cc0b)
![kiki2](https://github.com/Card-Forge/forge/assets/115870280/acae0937-a5ec-43da-8789-34c139e6184f)

**Comment by MorihiroS** [comment]
@Hanmac, AI label pls

**Comment by Hanmac** [comment]
this is a valid play, and was the plan for one of standard decks

the difference is that it was done in opponents end step, so you have many untapped Mirrors on your turn

AI just need to use the Ability at the right timing
