### ISSUE TITLE
RE execution needs better lookahead

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#3939]
Judges say Devouring a counter replacer should still modify the ETB counters:

https://www.reddit.com/r/mtgrules/comments/q41up2/winding_constrictor_corpsejack_menace_and_devour/

**Comment by tool4ever** [comment]
@Hanmac

might be tricky? I can make it work by adding AddCounter type here but it would break `testETBCounterMowu`:

https://github.com/Card-Forge/forge/blob/8332b7604ea699bdce8700fffb777964dce6f8ae/forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java#L129

**Comment by Hanmac** [comment]
Etb Counter need to interact inside Moved type

So I would need to merge them into one thing

See #2481
