### ISSUE TITLE
AI uses abilities of two Roiling Vortex at the same time

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3948]
**Describe the bug**
AI uses the abilities of two Roiling Vortex at the same time, though it is enough to use the ability of one

**To Reproduce**
1. AI casts 2 Roiling Vortex
2. Player uses, for example, Bubbling Cauldron
3. AI uses abilities of two Roiling Vortex 

**Expected behavior**
AI should only use the ability of one of the Roiling Vortex

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-10.19

**Screenshots**

![vortex](https://github.com/Card-Forge/forge/assets/115870280/d2c1a15f-a2cd-4f1c-94f5-e4117c7ba2d0)

**Comment by Agetian** [comment]
Can't reproduce in the latest snapshot (23.10), the AI only uses one Roiling Vortex in this instance. Please retry in the latest version, and if it's still an issue, please dump the game state (using the Dev panel "Save Game State" feature), if possible.

**Comment by MorihiroS** [comment]
@Agetian, tried it on the latest version - you're right, it works as it should.
