### ISSUE TITLE
AI doesn't use Roiling Vortex ability in response of using the second ability of Bubbling Cauldron

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3955]
**Describe the bug**
AI doesn't use Roiling Vortex ability in response of using the second ability of Bubbling Cauldron, although it heals player. But AI uses Roiling Vortex ability in response of using the first ability of Bubbling Cauldron

**To Reproduce**
1. AI casts Roiling Vortex
2. Player casts Bubbling Cauldron and Festering Newt
3. Player activates the second ability of Bubbling Cauldron
4. AI doesn't use Roiling Vortex

**Expected behavior**
AI uses Roiling Vortex ability in response of using the second ability of Bubbling Cauldron

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-10.23

**Screenshots**

![vortex](https://github.com/Card-Forge/forge/assets/115870280/65ab95d6-154b-4ee5-9eec-536cfbde1b8e)

**Comment by Agetian** [comment]
Will be fixed by #3952
