### ISSUE TITLE
Cybership creates Cybermen under control of damaged player

### ISSUE THREAD

**Issue by Glorax** [Card-Forge/forge#3956]
**Describe the bug**
When Cybership damages a player, the Cybermen are created under the control of the damaged player.

**To Reproduce**
1. Attack with Cybership.
2. Cybership damages the attacked player.

**Expected behavior**
The Cybermen should be created under the control of the owner of Cybership.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version: 1.6.59-SNAPSHOT-10.19

**Comment by Simisays** [comment]
@tool4ever I think the gaincontrol param isn't wired up for DigEffect ?
