### ISSUE TITLE
"Blink" saga not working properly; triggering first effect as Chapter II

### ISSUE THREAD

**Issue by Glorax** [Card-Forge/forge#3957]
**Describe the bug**
The Blink saga triggers its first effect as Chapter II, shuffling a creature into the library and creating a clue token under control of the same player. The effect triggers three times in a row in total. The effect that creates the Alien Angel token only occurs once, as Chapter IV.

**To Reproduce**
1. Play "Blink".
2. Allow chapters I through IV to trigger.

**Expected behavior**
The effects should alternate. I and III shuffle a creature into the library and create a clue. II and IV create an Alien Angel token.

**Desktop (please complete the following information):**
- OS: macOS Monterey Version 12.5.1
- Browser: Chrome
- Version: 1.6.59-SNAPSHOT-10.19

**Additional context**
Perhaps the way sagas are currently coded is not equipped to handle repeated Chapters that are "out of order". I checked the script for the card, and it seems like it should be working properly, yet it does not.

**Comment by Hanmac** [comment]
@tool4ever can you check this? it should only have been a visual issue?

**Comment by tool4ever** [comment]
yea I didn't expect that either but the report is correct
I should probably wait for your refactor for a fix?
