### ISSUE TITLE
AI will readily sacrifice Ashad to his own ability for no benefit whatsoever

### ISSUE THREAD

**Issue by Glorax** [Card-Forge/forge#3961]
**Describe the bug**
The AI will consistently sacrifice Ashad to his own ability if there are no other eligible creatures in play. It consistently does this even if he is the commander, and the artifact it is trying to duplicate is a cheap artifact creature or mana rock. Even worse, since Ashad's removal from play causes the cast artifact to lose Casualty, it's not even duplicated. The AI, in effect, is consistently willing to remove its own commander for no reason.

**To Reproduce**
1. Make a deck with Ashad in it. Make him the commander for the guarantee of him being cast. Ensure the deck has lots of cheap artifacts in it.
2. Put the AI in charge of the deck.
3. Continue playing against the AI until it casts an artifact spell while Ashad is the only creature it has in play.

**Expected behavior**
The AI should never treat any creature that grants Casualty to cast spells as eligible fuel for its own ability. It'd be a waste even if the spell were actually copied. (The spell not being copied because of the sacrifice of the Casualty-granting creature is in line with the rules as intended.)

**Desktop (please complete the following information):**
- OS: macOS Monterey Version 12.5.1
- Browser: Chrome
- Version: 1.6.59-SNAPSHOT-10.19

**Additional context**
I suspect the only reason why Anhelo doesn't have the same problem is that, while he also grants Casualty 2, Anhelo's power is 1. I haven't tested Anhelo, but it'd be interesting to see if he'd have the same issue when accompanied by some kind of non-creature anthem.

**Comment by Hanmac** [comment]
@Agetian for this we probably need better logic for Additional Cost like Causality

so we could mark this Creature to not sacrifice for Causality

**Comment by Hanmac** [comment]
yeah i think i need to first update how AI handles Optional Cost anyway for Effects

i think it would be nice if you could mark the Card with a "Don't Sacrifice Me" if it can be prevented

**Comment by Agetian** [comment]
Yeah, currently, the only way to do this preemptively that I see would be to rig ComputerUtilCost.canPayCost in order to bail early before CostPayment.canPayAdditionalCosts is called (in order to avoid dropping AI code into game engine). I'll think about what to do here, but if worst comes to worst, maybe I'll just mark it with a DontSac hint of some sort :)

**Comment by Hanmac** [comment]
@Agetian you probably need to checkout chooseSacrificeType for now
