### ISSUE TITLE
Reimplement UI_CLONE_MODE_SOURCE

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#3983]
I think it should be inline on the card art preference as a global settings, but it seems it's lacking some views (like if the player only want earlier cards to be shown to persist, etc) when it was refactored by @leriomaggio

_Originally posted by @kevlahnota in https://github.com/Card-Forge/forge/pull/3982#discussion_r1372848274_

**Comment by Hanmac** [comment]
i think we should flip the logic

We only need to have the Token be a different image for some special cases, and for this Special cases, we could give the Clone Command an Extra Image flag?
