### ISSUE TITLE
AI always chooses to put counters on the Aether Vial each turn

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3989]
**Describe the bug**
AI puts сounters on all of its Aether Vial every turn, even if it has no creatures with that mana cost. Consequently, Aether Vial stops making sense after a couple of turns.

**To Reproduce**
1. AI casts Aether Vial
2. Each upkeep AI chooses to put сounter on the Aether Vial.
3. It goes on ad infinitum

**Expected behavior**
Difficult, I can see several ways:
1) AI takes into account the cost of creatures in its hand
2) AI stops putting сounters on Aether Vial when it reaches a number equal to the maximum mana cost of creatures in its deck
3) Both options together

And an important point, AI will achieve a different number of сounters on Aether Vial by having 2 or more Aether Vial on the battlefield.

**Desktop (please complete the following information):**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-10.26

**Screenshots**

![vial1](https://github.com/Card-Forge/forge/assets/115870280/a60b7979-feff-4109-aa8d-7a5e726d4315)
![vial2](https://github.com/Card-Forge/forge/assets/115870280/9195713c-f232-4aea-a8e2-916fb2d1531b)

**Comment by Glorax** [comment]
I believe Ratchet Bomb has a similar problem.

**Comment by Hanmac** [comment]
i thought Aether Vial already had a logic to not put more counters on it than Max Cmc of its creatures?

I don't know if we need also some logic for Proliferate.  for this we might need some AI Flags

**Comment by MorihiroS** [comment]
> i thought Aether Vial already had a logic to not put more counters on it than Max Cmc of its creatures?
In that Merfolks deck from the screenshots above, the maximum cmc of creatures is 3

**Comment by Hanmac** [comment]
i think the Card had logic before, but i right now i can't see anything about it

@Agetian @tool4ever i think we need Card Specific Flag at what point a Counter that was previously good, would become a bad counter. (so that its more flexible?)

for the Merfolk Deck, should it goes up to 3 cmc? or should it stay at 2 where it probably has the most creatures for this?

**Comment by MorihiroS** [comment]
> for the Merfolk Deck, should it goes up to 3 cmc? or should it stay at 2 where it probably has the most creatures for this?

@Hanmac, its need 1 and 2 counters, third counter just for very-very few situations

**Comment by Hanmac** [comment]
AI should check its own deck, and decide for which CMC it has the most Creature Cards

**Comment by MorihiroS** [comment]
> I believe Ratchet Bomb has a similar problem. The AI will keep putting counters on it, by tapping it or via proliferate, until it's no longer useful to remove most things.

@Glorax, you should create separate issue about Ratchet Bomb
