### ISSUE TITLE
Menu Interface stuck in corner on boot

### ISSUE THREAD

**Issue by Zavael** [Card-Forge/forge#3990]
**Describe the bug**
When booting the app on android, the initial splash screen loads correctly. Then when the menu screen loads it rotates to attempt landscape mode and squishes the screen and pushes it into the lower right corner. Clearing cache sometimes allows the next boot to load properly, but it reverts by the next boot. 

**To Reproduce**
1. Load app
2. Wait for menu load

**Expected behavior**
App should boot to menu in full stretched landscape mode that fills screen

**Screenshots**
![Screenshot_20231025-150708](https://github.com/Card-Forge/forge/assets/121262295/4c988393-0f12-45fe-be74-9d45ac59bd47)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: Android 14
 - Browser: Chrome
 - Version: Current daily snapshot 10/26/23

**Additional context**

**Comment by kevlahnota** [comment]
Forge version? Are you using latest snapshot? I don't encounter this in a long time except earlier release versions..

**Comment by Zavael** [comment]
Forge version 1.6.59-SNAPSHOT-10.26
I have enough control to be able to download updates from the menu but that's all.  I've also updated my pixel tablet to Android 14 and haven't experienced the same issue, so it may be the phone more than the OS.
    On Friday, October 27, 2023 at 02:30:35 AM PDT, kevlahnota ***@***.***> wrote:  
 
 


Forge version? Are you using latest snapshot? I don't encounter this in a long time except earlier release versions..

**Comment by kevlahnota** [comment]
Just tested multiple times in this video, seems your issue is hard to reproduce or maybe its device specific..

https://github.com/Card-Forge/forge/assets/9781539/ddeea30d-9aa1-4972-9723-4075ee7cffa1

**Comment by Zavael** [comment]
I agree it's likely device specific. I'll just keep updating and hope it gets fixed on that side down the road. 
    On Friday, October 27, 2023 at 02:39:00 AM PDT, kevlahnota ***@***.***> wrote:  
 
 


Just tested multiple times in this video, seems your issue is hard to reproduce or maybe its device specific..

https://github.com/Card-Forge/forge/assets/9781539/ddeea30d-9aa1-4972-9723-4075ee7cffa1

**Comment by Zavael** [comment]
Just a final note if it helps.  If I clear the cache and force stop the app it will load correctly the next time.  But then revert back to the bugged load state on the next start up.  I can use this as a workaround to play for now, so feel free to close the issue if needed.  Thank you!
