### ISSUE TITLE
AI casts Veil of Summer in its draw step for no reason

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3993]
**Describe the bug**
AI casts Veil of Summer in its draw step for no reason. It doesn't do anything else in the same turn.

**To Reproduce**
1. AI takes Veil of Summer
2. AI casts Veil of Summer in its draw step without reason

**Expected behavior**
AI casts Veil of Summer only in response to black/blue spells, that targets it or its spells and permanent/ Or in response to black/blue spells just for draw (in very few situations).

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-10.26

**Screenshots**

![veil](https://github.com/Card-Forge/forge/assets/115870280/d977067c-ffe5-4f45-a418-866b60c31be5)

**Comment by MorihiroS** [comment]
@Agetian, is it real to fix?

**Comment by Agetian** [comment]
Should be, I'll take a look soon :)
