### ISSUE TITLE
AI never casts Searing Blaze

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#3997]
**Describe the bug**
AI never casts Searing Blaze, just holds it in his hand.

**To Reproduce**
1. AI draw Searing Blaze
2. AI always holds it in hand and never casts it

**Expected behavior**
AI should casts Searing Blaze.

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-10.26

**Screenshots**

![blaze1](https://github.com/Card-Forge/forge/assets/115870280/cf1191d1-243a-4080-b269-523791f695b9)
![blaze2](https://github.com/Card-Forge/forge/assets/115870280/a7657ff0-c6f6-4d58-b970-07a2757b3db7)

**Comment by Agetian** [comment]
Umm, it does use it, it's just rather hesitant to use it - it will, for example, use it against a Wild Elephant when the Player is at 5-7 life or so. This can be tweaked, will look into it a bit later so that it'll use it more eagerly when viable :)

**Comment by MorihiroS** [comment]
> Umm, it does use it, it's just rather hesitant to use it - it will, for example, use it against a Wild Elephant when the Player is at 5-7 life or so. This can be tweaked, will look into it a bit later so that it'll use it more eagerly when viable :)

It's gonna be great!

**Comment by MorihiroS** [comment]
@Hanmac, need keep label, pls

**Comment by MorihiroS** [comment]
@Agetian, you haven't looked at it yet? AI doesn't play a Burn deck properly literally because of that one card.

**Comment by Agetian** [comment]
Not yet, sadly, will see if I can take a look tomorrow
