### ISSUE TITLE
AI prefers to block creatures with lesser power

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4004]
**Describe the bug**
AI prefers to block Lord of Atlantis (2/2) with his Spellskite rather than block Tide Shaper with kicker (3/3)

**To Reproduce**
1. Player casts Tide Shaper with kicker and Lord of Atlantis
2. AI casts Spellskite
3. Player attacks with Lord of Atlantis and Tide Shaper
4. Lord of Atlantis is blocked by Spellskite

**Expected behavior**
AI should block a creature with the maximum power its creature can survive

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-10.27

**Screenshots**

![spellskite](https://github.com/Card-Forge/forge/assets/115870280/00da8e0f-2f23-4aa9-b853-531742fc51c3)

**Comment by Agetian** [comment]
I don't thjink Tide Shaper can be blocked in this instance because, you know, Islandwalk and stuff?

**Comment by MorihiroS** [comment]
> I don't think Tide Shaper can be blocked in this instance because, you know, Islandwalk and stuff?

@Agetian, I agree, I don't read cards, my mistake XD
