### ISSUE TITLE
AI repeatedly tries artifact abilities that cannot be activated.

### ISSUE THREAD

**Issue by stormcat664** [Card-Forge/forge#4015]
**Describe the bug**
When a card like Stony Silence is in play, AI tries every time priority shifts to activate an artifact's ability that cannot be activated. 
The game does not progress smoothly.

**To Reproduce**
1. play Stony Silence or similar card.
2. Passing priority to AI.
3. Showing "Result: Stony Silence ~ " 
4. Press OK several times to proceed with the game.

**Expected behavior**
I don't want anything to happen.

**Screenshots**
![2023-10-29 041122](https://github.com/Card-Forge/forge/assets/52299273/8c36781b-8e0a-48eb-b1ba-a9d47164ba1d)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 10.28

**Comment by MorihiroS** [comment]
It's not the AI, it's a notification error. I tried to activate the Powerstone's ability when the AI had Karn, the Great Creator on the battlefield. After that, I got a notification after any action I took.

![karn](https://github.com/Card-Forge/forge/assets/115870280/7ffb52ba-1988-47b1-969a-d0a2f06edca2)

**Comment by kevlahnota** [comment]
hmm forgot to remove the info dialog on snaps on can't cast/can't play when I was trying to give info on player... i wonder why  would the AI would give that info on human player? this should be fixed on upcoming snapshot and this is not part of main release, gonna close this.
