### ISSUE TITLE
Completed Weeping Angel script

### ISSUE THREAD

**Issue by Glorax** [Card-Forge/forge#4016]
I completed the script for Weeping Angel myself and tested it. I have 95% confidence that there are no issues with it. I would have created a proper branch but I have very limited time and no idea how to do that, so I'm putting it here.
[weeping_angel.txt](https://github.com/Card-Forge/forge/files/13196654/weeping_angel.txt)

Apologies for this crude and flagrant violation of proper protocol.

**Comment by Simisays** [comment]
Thanks for your work. I'll create a pull request for you, the card seems to work fine from my testing as well. 

Also feel free to ask around on Github for help concerning Github pull requests 👍
