### ISSUE TITLE
Coward // Killer not correctly damaging all creatures

### ISSUE THREAD

**Issue by Glorax** [Card-Forge/forge#4018]
**Describe the bug**
The "Killer" half of "Coward // Killer" leaves some creatures that share a creature type with the target undamaged.

**To Reproduce**

1. Have a multiplayer game state where multiple players have creatures in play that share creature types. For example, "Time Lord", "Doctor", "Alien", "Soldier", or Detective".
2. Target one of those creatures with "Killer".
3. Some of the creatures that share a creature type with the target won't be damaged.

**Expected behavior**
"Killer" deals 3 damage to each creature that shares any creature type with the targeted creature.

**Desktop (please complete the following information):**
- OS: macOS Monterey Version 12.5.1
- Browser: Chrome
- Version: 1.6.59-SNAPSHOT-10.19

**Additional context**
It isn't clear to me if the issue is that "Killer" is only damaging creatures controlled by a single player, or if "Killer" is only damaging creatures that have exactly the combination of creature types that the targeted creature has. (This would be the difference between targeting a creature with Changeling and damaging everything, or doing the same and damaging nothing but other Changelings.)

**Comment by Northmoc** [comment]
> "Killer" is only damaging creatures controlled by a single player

Was able to target both my own creature and opponent creature and observed creatures controlled by other player also getting damaged in both scenarios.

> "Killer" is only damaging creatures that have exactly the combination of creature types that the targeted creature has

Put out types A, B, C, A+B, and card with Changeling (randomly between two players)
Targeted AB -> all but C were damaged

Put out types A, B, C, AB, and card with Changeling (randomly between two players)
Targeted Changeling -> all were damaged

**Comment by Northmoc** [comment]
3 players test:

P1 Changeling + Grizzly Bears
P2 2nd Doctor
P3 5th Doctor

Targeted one of the Doctors... everything but Grizzly Bears got hit

Sorry, can't reproduce this 😞
