### ISSUE TITLE
Using enter to advance the steps leads to Pre-Combat Mainphase beeing skipped.

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4067]
See title.

**Comment by Nymra** [comment]
UPDATE:
it seems in some sessions the pre-combat main phase is skipped completely o_O, no matter how I get to it.

**Comment by TheLastNarwhal** [comment]
See my reply in this post about what I think is most likely your issue: https://github.com/Card-Forge/forge/issues/4064#issuecomment-1789057274.

**Comment by Nymra** [comment]
this is not user error... I tried to advance with enter or with mouse, the pre-combat phase was always skipped during that session, even on a new game.
But go on when you dont believe there is a bug...
