### ISSUE TITLE
I cannot activate abilities or cast instant spells when I am attacked 

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4071]
For example, I have no idea when I would be able to use "Radiant Arch Angels" Ability to tap another creature with flying to gain protectin from a color.
Same for Maze of Ith... I somehow always lose my creatures before I can do anything. Is there some hidden option for it or do I understand the paper rules in a wrong way?

**Comment by TheLastNarwhal** [comment]
You are probably misunderstanding the rules, **or** you don't have your phase stops set up correctly. 

For the former, the rules are pretty simple actually. Once the attackers have been declared you have a window to respond with spells/abilities, and the same is true once the defenders have been declared. After you move past these windows it's too late to activate or cast anything. 

As for the latter, I already explained how to fix that issue in another of your posts.
