### ISSUE TITLE
Cannot sacrifice burnished hart in reaction to beeing forced to sac it?!?

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4075]
So an effect forces me to sacrifice burnished hart but I have no way to sacrifice it in response??!
how does this work?

this kind of problem I am facing very often. I have an ability but I cannot use it in response to another :(
makes the whole thing quite pointless because I cannot really play magic this way.

I noticed I stopped using certain cards because of this limitation, but that cannot be how its supposed to be?

**Comment by kevlahnota** [comment]
When you have priority and you can activate the card, just click it and it will work as it should..


https://github.com/Card-Forge/forge/assets/9781539/c28cddb4-1ae8-46ef-8315-b5c3bcde85fc
