### ISSUE TITLE
Camel can block any trampler and absorb all damage

### ISSUE THREAD

**Issue by jumpinjackie** [Card-Forge/forge#4081]
**Describe the bug**

Bumped into a weird duel in Adventure mode where I was about to deal the finishing blow with a [Blightsteel Colossus](https://scryfall.com/card/2xm/235/blightsteel-colossus) and the opponent chump blocks with a [Camel](https://scryfall.com/card/arn/3/camel), only for that Camel to die and **absorb all excess combat damage**

I re-tried this same encounter with various tramplers and they all seem to have the same result, the blocking Camel dies absorbing all excess combat damage that would've gone to the opponent.

**To Reproduce**

Play against an opponent with [Camel](https://scryfall.com/card/arn/3/camel) and get it to block your attacking trampler

**Expected behavior**

Expect: Get the trample prompt dialog to assign excess damage

Get: Camel dies and absorbs all excess damage. Opponent receives 0 trample damage

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

 - Version 1.6.59-SNAPSHOT-11.01

**Additional context**

**Comment by tool4ever** [comment]
> 702.22j. During the combat damage step, if an attacking creature is being blocked by a creature with banding, or by both a [quality] creature with "bands with other [quality]" and another [quality] creature, the defending player (rather than the active player) chooses how the attacking creature's damage is assigned.

**Comment by jumpinjackie** [comment]
Wow! Shows how much I know about banding (not much)! Ok disregard 😄
