### ISSUE TITLE
"Flickered" (exiled) Creature enters the battlefield tapped

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4083]
Card involved was "Disorder in the courd", flickered creature was "Sigarda, Font of Blessings" that i noted it. She entered tapped at the endstep.

**Comment by kevlahnota** [comment]
What's wrong with it? When the card says it should enter tapped? 
![image](https://github.com/Card-Forge/forge/assets/9781539/4e8de2ee-86c1-491e-b2da-a7c457567588)

**Comment by tool4ever** [comment]
This user is clearly not putting in the minimal effort of reading.

**Comment by Nymra** [comment]
fair enough, I missread the card, twice ^^ :(
