### ISSUE TITLE
Mana Overlay improved Visibility?

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4084]
I noticed that the mana overlays are a very bad read... would it be possible to add a black border around the mana symbols to make them stand out better? especially in front of the card illustrations they sometimes almost vanish...

If there is already a way to do it: sorry for bothering you, I looked in the settings and did not find it. So please consider this feature or enlighten me when it comes to understanding the settings better, thx :D

(size is not the issue here. they COULD be bigger, but that would not fix the issue here)

**Comment by kevlahnota** [comment]
You can create your custom skin including the mana symbols with your choice of colored borders and use your custom skin to override the default ones.

**Comment by Nymra** [comment]
wow, ok, that is a cool option. I knew I could change the card pics, but yeah, ofc all the graphics are there. 
thank you
