### ISSUE TITLE
Add Cards to existing decks? Change set of the card? How?

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4089]
I am trying this for a day now but I have not found the option to add new cards to my saved decks in Forge OR change the set of the cards already in.
I can add basic lands and I can remove cards, but that is it...

So either this fundamental feature just does not exist (deck BUILDer?) or I am too stupid to find it (in which case it might be hidden too well... so hence the feature request to add it or improve it. thx)

- google search did not find a thing
- there is no guide that I found that explains this
- there is no discord server that is open to people that I can use... :( 

If there is a maintained forum or other chat anywhere, feel free to show me.

**Comment by Northmoc** [comment]
Check this out – https://www.slightlymagic.net/forum/viewforum.php?f=26&sid=3a0f69a63cab1dfbf4c6f04a13520124

**Comment by tehdiplomat** [comment]
The forum isn't really maintained anymore but we're extremely active on Discord. Its literally in the first few lines on the README of this repo.

**Comment by paulsnoops** [comment]
How are you adding basic lands if you can't add any other cards? A screenshot of what you think is missing would help.

**Comment by TheLastNarwhal** [comment]
> The forum isn't really maintained anymore but we're extremely active on Discord. Its literally in the first few lines on the README of this repo.

Well, to be fair to this poster about the discord thing, not everyone has a cellphone, a cellphone number that discord likes, or wants to give discord their cellphone number, so... mentioning you're active on discord, and/or directing people to discord isn't helpful.

I understand the reasoning behind requiring a cellphone number, though I do question it somewhat.

----------

As for the other issue, to me it sounds like they haven't clicked on the card catalog section again after they've chosen their deck.

**Comment by Nymra** [comment]
> How are you adding basic lands if you can't add any other cards? A screenshot of what you think is missing would help.

I have 

> The forum isn't really maintained anymore but we're extremely active on Discord. Its literally in the first few lines on the README of this repo.

I do not want to give my Cellphone number to discord. 
While understanding the Discord Admins in that regard, I do not support any site or forum that forces me to disclose personal information. Even thinking about shutting down my patreon because of that....

Email, ok, but CellPhone is a different level of involement on an app that is run by whom exactly anyways? :(

**Comment by Nymra** [comment]
> How are you adding basic lands if you can't add any other cards? A screenshot of what you think is missing would help.

See screenshot above. I can remove a card, 4 cards and I can add basic lands o_O 
that is all

**Comment by TheLastNarwhal** [comment]
> Where exactly is the "Card Catalog Section"? I cannot find it :(
> 
> > > The forum isn't really maintained anymore but we're extremely active on Discord. Its literally in the first few lines on the README of this repo.
> > 
> > 
> > Well, to be fair to this poster about the discord thing, not everyone has a cellphone, a cellphone number that discord likes, or wants to give discord their cellphone number, so... mentioning you're active on discord, and/or directing people to discord isn't helpful.
> > I understand the reasoning behind requiring a cellphone number, though I do question it somewhat.
> > As for the other issue, to me it sounds like they haven't clicked on the card catalog section again after they've chosen their deck.
> 
> ![2023-11-03 15_30_04-Greenshot](https://user-images.githubusercontent.com/43454517/280310292-74df84c6-dae6-45ac-84d4-eb96e7344c9d.jpg)

Look at the top left of your screenshot.

**Comment by paulsnoops** [comment]
Ok but this issue isn't about any reasoning for Discord requirements. The option is there; it's up to people whether they agree and use it or not.

Click the tab at the top left that says card catalog. There you can add cards

**Comment by Nymra** [comment]
> Ok but this issue isn't about any reasoning for Discord requirements. The option is there; it's up to people whether they agree and use it or not.
> 
> Click the tab at the top left that says card catalog. There you can add cards

oooooh, now I see it. 
damn be me, I did not think its where the formats are... 
my bad here, no doubt, but honestly I also dont understand what it is doing in there with the formats ^^
