### ISSUE TITLE
AI fails to properly cast Spiteful Banditry and it deals 0 damage no matter the X choice

### ISSUE THREAD

**Issue by Agetian** [Card-Forge/forge#4102]
**Describe the bug**
Each time the AI tries to cast Spiteful Banditry, it correctly chooses and announces the X value, but the card deals 0 damage.
The problem is that once the card enters the battlefield, the information about the X payment is lost to the AI, and the game assumes that 0 was chosen.

**To Reproduce**
1. Give the AI Spiteful Banditry and some mana to cast it, and give yourself a few 1/1s or 2/2s or whatever.
2. Wait for the AI to cast Spiteful Banditry.

**Expected behavior**
The spell should deal the expected amount of damage when the AI casts it.

I tried debugging this and I can clearly see that it's precisely because the X information is lost between casting the spell and the resolution of the ETB trigger, but I'm not sure what a good approach would be to fixing this... Any ideas, @tool4ever @Hanmac ?

**Comment by tool4ever** [comment]
@Agetian here:
https://github.com/Card-Forge/forge/blob/780d1a7ced7a84d397168a20900dfd28bd7464ee/forge-ai/src/main/java/forge/ai/ability/DamageAllAi.java#L280

you need to check if there is any trigger that would allow AI to pay it there and then adjust accordingly

**Comment by Agetian** [comment]
Yeah, I also thought rigging stuff around that line, but the problem is that by the time the ETB trigger resolves, the AI already has the mana tapped and paid for X... So, how it works is:
1. The AI checks if it can pay X for the spell. Let's say it has 4 mana to pay for X.
2. It sets X=4 at that line above and pays the mana , casting the spell. It resolves with X=4.
3. The trigger goes on stack, which assumes that the card should still remember that X was 4 when the spell was originally cast.
4. Sadly, at this point, X is reset to 0 at this point by somewhere in the AI code, and the game engine deals 0 damage.

Is there an extra forced reset for X somewhere in the AI code

**Comment by Agetian** [comment]
Ok, it looks like checking for trigger does the job, but I'm not sure if that's the real fix... I mean, it might break for things where you pay X at the moment of trigger resolution? (I'm not sure if any DamageAll cards like that exist, I don't think so though)

**Comment by Agetian** [comment]
Hmm, it's weird though, I mean, it's called inside doTriggerAINoCost, so it was meant to set the X inside the trigger code... Not sure what to do so far :/

**Comment by Agetian** [comment]
Maybe checking the pay cost for X is better?
