### ISSUE TITLE
AI kills itself with Street Wraith

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4128]
**Describe the bug**
AI cycles Street Wraith with low health and die

**To Reproduce**
1. AI has 1-2 lifes
2. AI cycles Street Wraith

**Expected behavior**
AI shouldn't cycle Street Wraith with low health

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-11.03

**Screenshots**

![street](https://github.com/Card-Forge/forge/assets/115870280/07071b04-4ec8-4fef-a741-da2d6e5cd284)

**Comment by Hanmac** [comment]
normally the logic for Pay Life Effects is that AI should not pay that amount of Life if the Life would drop into the Danger Zone (0-5)

@Agetian can you look into this?

**Comment by Agetian** [comment]
Hmm, must be something contextual, I tested a few board states and for me the AI never tries to cycle a Street Wraith when it has lower than 5 life or so :/ I'll dive deeper into the logic soon and see where exactly there may be a loophole where the AI stops thinking that it's a bad idea to cycle it at that point.

**Comment by MorihiroS** [comment]
> Hmm, must be something contextual, I tested a few board states and for me the AI never tries to cycle a Street Wraith when it has lower than 5 life or so :/ I'll dive deeper into the logic soon and see where exactly there may be a loophole where the AI stops thinking that it's a bad idea to cycle it at that point.

@Agetian, Forge Version: 1.6.59-SNAPSHOT-11.0X:

![street](https://github.com/Card-Forge/forge/assets/115870280/74d90ebb-ecad-4bef-8f5e-b05d33217128)
![street2](https://github.com/Card-Forge/forge/assets/115870280/fd38004c-5b55-472b-90a8-99b444355e77)

**Comment by Agetian** [comment]
I recreated the battlefield state and the AI doesn't cycle Street Wraith for me... Not sure what's causing it for you since I can't recreate it yet. Since it seems to reproduce quite consistently and easily for you, can you save a game state for me once it happens? (e.g. enable Dev mode, wait until this happens (the trigger goes on stack), and then click "Save Game State" and upload the resulting file here)

**Comment by MorihiroS** [comment]
@Agetian, I gave AI 4 life aaaand:
![street2](https://github.com/Card-Forge/forge/assets/115870280/19811c85-3611-4cd6-aa4b-2f2f83b5b18a)
[state.txt](https://github.com/Card-Forge/forge/files/13275906/state.txt)
