### ISSUE TITLE
Feral Encounter doesn't reveal the cards

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4142]
**Describe the bug**
As the title says, Feral Encounter doesn't reveal the top 5 cards to you if there is no creature among them.

**Expected behavior**
For Forge to reveal the top 5 cards of your deck to you, so you can have that information, even if you just end up putting them on the bottom of your deck in a random order.

**Comment by Hanmac** [comment]
it says:
> Look at the top five cards of your library. You may exile a creature card from among them. Put the rest on the bottom of your library in a random order. You may cast the exiled card this turn. At the beginning of the next combat phase this turn, target creature you control deals damage equal to its power to up to one target creature you don’t control.

it doesn't say "reveal" for other players.

@tool4ever but the player should still be able to see them

**Comment by TheLastNarwhal** [comment]
> it says:
> 
> > Look at the top five cards of your library. You may exile a creature card from among them. Put the rest on the bottom of your library in a random order. You may cast the exiled card this turn. At the beginning of the next combat phase this turn, target creature you control deals damage equal to its power to up to one target creature you don’t control.
> 
> it doesn't say "reveal" for other players.

Yes, apologies for the poor word choice. I was using "reveal" in the sense that Forge would show you (the caster) the top 5 cards, not in the "reveal to the table" sense.
