### ISSUE TITLE
 The program crashes when Ivy, Gleeful Spellthief's ability copies Grove's Bounty and adds it to itself

### ISSUE THREAD

**Issue by coolboy0961** [Card-Forge/forge#4160]
**Describe the bug**
Using Grove's Bounty to add +1/+1 indicators to creatures, the program crashes when Ivy, Gleeful Spellthief's ability copies Grove's Bounty and adds it to itself.

**To Reproduce**.
1. Ensure there is a creature and Ivy, Gleeful Spellthief on the battlefield.
2. Use Grove's Bounty to add +1/+1 indicators to creatures.
3. Ivy, Gleeful Spellthief's ability copies Grove's Bounty and adds it to itself.

**Expected behavior**
The program doesn't crash and the +1/+1 indicator for the specified number of Grove's Bounty is added to Ivy, Gleeful Spellthief.

**Screenshots**
![PXL_20231114_030540055.jpg](https://github.com/Card-Forge/forge/assets/12973893/d8222904-f0b9-4b11-b8f9-db8da28b2bf3)

![PXL_20231114_030741162.jpg](https://github.com/Card-Forge/forge/assets/12973893/5e50ad39-5043-4388-9814-81a8f6a8687c)

**Desktop (please complete the following information):**
 - OS: Steam Deck Desktop mode
 - Version v.1.6.59-SNAPSHOT-11.0x

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 14
 - Version v.1.6.59-SNAPSHOT-11.0x

**Additional context**
None

**Comment by Hanmac** [comment]
@tool4ever can you look into this? probably the Divided Values isn't updated correctly when the Target is set to `Defined$ Self`?
