### ISSUE TITLE
Game crashes when player kills AI's planeswalker

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4213]
**Describe the bug**
Game crashes when player attacks/kills  (I haven't tracked exactly what causes the game to crash, just the damage or the death of the Grist, the Hunger Tide). I've attached the log file.

**To Reproduce**
1. AI casts Grist, the Hunger Tide
2. Player attacks Grist, the Hunger Tide
3. Grist, the Hunger Tide is dead
4. Game crashes

**Expected behavior**
Game shouldn't crash

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-11.24

**Screenshots**

![grist](https://github.com/Card-Forge/forge/assets/115870280/8a651f37-c4df-43f1-8381-95e085e80bfd)

[2023-11-25-00.txt](https://github.com/Card-Forge/forge/files/13464682/2023-11-25-00.txt)

**Comment by MorihiroS** [comment]
@Hanmac, @Agetian, it's not only with Grist, its with other planeswalkers (here - Teferi, Time Raveler)

![teferi](https://github.com/Card-Forge/forge/assets/115870280/533a2698-e145-403e-87da-859b4c3e57b9)

**Comment by MorihiroS** [comment]
@tool4ever, @Agetian, it's like the reason in Sigarda, Font of Blessings:

![kill](https://github.com/Card-Forge/forge/assets/115870280/7cdaa9d3-ab87-4913-9a1b-d816cc0d6f99)

Without her all is normal:

![not](https://github.com/Card-Forge/forge/assets/115870280/7636409a-d12c-4808-a272-f9db11f4b30c)
![not2](https://github.com/Card-Forge/forge/assets/115870280/d5a1b385-b258-48d0-aa93-d036cbea0d0f)

**Comment by MorihiroS** [comment]
It's not Sigarda, Font of Blessings

![planes](https://github.com/Card-Forge/forge/assets/115870280/ae3d09a0-44d0-4555-8002-326f8e9e6d60)

**Comment by Northmoc** [comment]
Hmm, can't reproduce 🤷 

These crashes are happening in a stringbuilder in CCombat that hasn't been touched in years... my guess is something goofy on that individual Forge install as opposed to a universal bug, or more users would be definitely be reporting this problem.

**Comment by MorihiroS** [comment]
@Northmoc, what should I do with Forge install? I deleted the folder and unzipped the new version and again. It's not every time but often:

[2023-12-08-00.txt](https://github.com/Card-Forge/forge/files/13619704/2023-12-08-00.txt)

**Comment by MorihiroS** [comment]
@Northmoc, may be you need game stat before game's crash?

[2023-12-09-00.txt](https://github.com/Card-Forge/forge/files/13623083/2023-12-09-00.txt)
[state.txt](https://github.com/Card-Forge/forge/files/13623084/state.txt)

![bug](https://github.com/Card-Forge/forge/assets/115870280/1ee864a8-1b32-471a-9bc6-2118d4b3cd94)

**Comment by Northmoc** [comment]
> @Northmoc, may be you need game stat before game's crash?
> 
> [2023-12-09-00.txt](https://github.com/Card-Forge/forge/files/13623083/2023-12-09-00.txt) [state.txt](https://github.com/Card-Forge/forge/files/13623084/state.txt)
> 
> ![bug](https://private-user-images.githubusercontent.com/115870280/289243277-1ee864a8-1b32-471a-9bc6-2118d4b3cd94.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTcxOTMsIm5iZiI6MTcwMjE1Njg5MywicGF0aCI6Ii8xMTU4NzAyODAvMjg5MjQzMjc3LTFlZTg2NGE4LTFiMzItNDcxYS05YmM2LTIxMThkNGIzY2Q5NC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQyMTIxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGUyNzU0NGE2MGUyZGM5ZDBjNWVkYzRkN2FlNWI4Y2Y3ZWE4YmM1ZGVjYThlNDY1NjJhYTNhYzEzZjJlMTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kYaLN-l7OtoH-hQzJKd1W7AAXEG_0EnJ-S0ZGybrSOs)

Can't hurt – I can try to reproduce

An NPE in a StringBuilder shouldn't be too hard to fix if it can be nailed down

**Comment by MorihiroS** [comment]
Apparently something changed, can't reproduce this error anymore. I close the query now, but will reopen it if the error returns
