### ISSUE TITLE
Doubling season/parallel lives not doubling copy effects that create tokens

### ISSUE THREAD

**Issue by CapybaraEater** [Card-Forge/forge#4223]
**Describe the bug**
Doubling season and parallel lives do not copy the ability of Magus lucea kane as she creates a token copy.

**To Reproduce**
1. Place doubling season/parallel lives and another copy effect
2. Use copy effect of a creature, for example magus lucea kane
3. They do not see the copy effect as an effect that makes a token and therefore do not copy it

**Expected behavior**
Magus copies permanent spells with x in cost, the copy is a token, from my knowledge of rules this should mean that the abilities of doubling season and parallel lives should create a second copy (with all counters on) as it would doubles the effect that would make the token.

**Desktop (please complete the following information):**
Desktop
 windows
1.6.59-snapshot 11-23

Apolgies for if my understanding of the rules is incorrect, i've also had this confirmed by multiple other people who play and some rough google searches, thanks!

**Comment by tool4ever** [comment]
Nope:
> 111.12. A copy of a permanent spell becomes a token as it resolves. The token has the characteristics of the spell that became that token. The token is not "created" for the purposes of any replacement effects or triggered abilities that refer to creating a token.
