### ISSUE TITLE
AI doesn't cast Seek the Beast if it has green mana

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4226]
**Describe the bug**
AI doesn't cast Seek the Beast, only Questing Druid

**To Reproduce**
1. AI has a lot of mana
2. AI casts Questing Druid, not Seek the Beast

**Expected behavior**
AI should cast Seek the Beast sometimes

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-11.25

**Screenshots**

![druid](https://github.com/Card-Forge/forge/assets/115870280/bb5c7dcf-ba55-494f-8dee-bc1cb6364166)

**Comment by MorihiroS** [comment]
@Agetian, AI casts Seek the Beast only if it hasn't green mana (Forge Version: 1.6.60-SNAPSHOT-12.08):

![seek](https://github.com/Card-Forge/forge/assets/115870280/58dfe5f3-8854-4733-a6e6-050f07b36eea)

So, AI doesn't cast Seek the Beast if it has untapped land with green.

**Comment by Hanmac** [comment]
@Agetian @tool4ever same there, AI should prefer Adventure Spell if able

**Comment by MorihiroS** [comment]
Merged with #4352
