### ISSUE TITLE
AI doesn't cycling Eagles of the North

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4227]
**Describe the bug**
AI doesn't plainscycling Eagles of the North even if it doesn't have Plains

**To Reproduce**
1. AI has only Field of Ruin/Demolition Field on the battlefield
2. AI has Eagles of the North and some cards with white symbols in mana symbols
3. AI doesn't plainscycling Eagles of the North

**Expected behavior**
AI should plainscycling Eagles of the North in early game

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-11.25

**Screenshots**

![eagles](https://github.com/Card-Forge/forge/assets/115870280/5f0b2f50-944d-42cd-96e9-5b0bb167ed7b)
![eagles2](https://github.com/Card-Forge/forge/assets/115870280/2faffe10-8947-48ea-87b8-c8e92f3d00e4)

**Comment by MorihiroS** [comment]
@Hanmac, need keep label and assign Agetian, pls

**Comment by Hanmac** [comment]
I noticed the AI doesn't used Mountain cycling too

**Comment by MorihiroS** [comment]
> I noticed the AI doesn't used Mountain cycling too

@Hanmac, AI can do it:

![olip](https://github.com/Card-Forge/forge/assets/115870280/4c7486fa-f131-4ad4-9551-c6e81d4e539a)

**Comment by MorihiroS** [comment]
@Hanmac, need keep label, please!

**Comment by MorihiroS** [comment]
Ok, AI did it!

![1](https://github.com/Card-Forge/forge/assets/115870280/153be3c6-6676-48e6-a8d3-cb32caca3df0)
