### ISSUE TITLE
Incorrect image for Braids, Conjurer Adept Avatar.

### ISSUE THREAD

**Issue by myyk** [Card-Forge/forge#4241]
**Describe the bug**
The text on the image does not match what the card script does. The card *script does matches* the official behavior. (https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/b/braids_conjurer_adept_avatar.txt)

**To Reproduce**
1. Play a Vanguard match in Forgotten Realms against Braids, Conjurer Adept (Vanguard) to the bottom left.
2. Observe when the art loads that it has a "5" for the last ability cost when it should be a "4"

**Expected behavior**
To display the correct card image.

**Screenshots**
![Screenshot_20231129-034611](https://github.com/Card-Forge/forge/assets/2080820/c655a668-7261-41df-be52-7e35df939d82)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 14

**Comment by Northmoc** [comment]
Huh where do these images even come from?
https://scryfall.com/card/pmoa/66/braids-conjurer-adept-avatar doesn't look anything like this
Frankly I like the gray style here better than the purple but obviously the incorrect bit needs to be fixed
@paulsnoops seems like this might be a quick fix?

**Comment by paulsnoops** [comment]
I think the ftp has custom images made by @kevlahnota not sure why they would be wrong though

**Comment by paulsnoops** [comment]
Should be fixed on the ftp now, shoddy photoshop but better than nothing. @myyk try deleting your image and re-downloading

**Comment by myyk** [comment]
Looks good now, thanks!

![Screenshot_20231129-234120](https://github.com/Card-Forge/forge/assets/2080820/6e1d3586-3e33-4188-a2cd-453d6f3f1934)
