### ISSUE TITLE
Crashing Tide transform copies into "card" when returning in the hand

### ISSUE THREAD

**Issue by Nemesis666first** [Card-Forge/forge#4253]
I had a copy of Platinum Angel (Copied with Sculpting Steel) on the board, Crushing Tide returned it into my hand... as Platinum Angel !

Since my original Platinum Angel were exiled, I have now 2 Platinum Angel's xD !!!

https://www.dropbox.com/scl/fi/pja1p0rx1koujogd09mzr/Crashing-Tide-and-Token-or-Copy.png?rlkey=6qr7c9d4lcnt42c4ia4d7kxga&dl=0

**Comment by Nemesis666first** [comment]
I realized the card became a Sculpting Steel next turn, it was probably just a showing issue, but I cant be sure.

**Comment by Hanmac** [comment]
@Northmoc probably need to cleanup view?

**Comment by Northmoc** [comment]
Can't reproduce – possibly old Forge version?
