### ISSUE TITLE
Horizon Stone doesnt convert unspend mana from Mishra's Workshop

### ISSUE THREAD

**Issue by Nemesis666first** [Card-Forge/forge#4254]
Hi,

For every particular mana, like from Powerstone, Horizon Stone is working well, but when it's about Mishra's Workshop, it seems Horizon Stone is not working :

https://www.dropbox.com/scl/fi/c708sdimcjbz3c6e5lrvc/Horizon-Stone-and-Mishras-Workshop.png?rlkey=d9856jqeamt7d6epbu9op40wc&dl=0

It seems it doesnt convert the mana.

**Comment by tool4ever** [comment]
Check card rulings before opening issues:
> If unspent mana you have has any restrictions or riders associated with it (for example, if it was produced by Jeweled Lotus), those restrictions or riders remain associated with that mana when it becomes colorless.

**Comment by Nemesis666first** [comment]
So, there is an other issue : if I produce mana from Powerstone, if I change of phase, this mana can be spent for anything else, like sorcery or instant, there is not any limitation about artifact anymore.

**Comment by tool4ever** [comment]
Can't reproduce
show your board for that?
