### ISSUE TITLE
Saw in Half / Lord of Lineage bug (+Possible bug with all TDFCs)

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4291]
**Describe the bug**
I target my Lord of Lineage with Saw in Half, destroying it and getting two copies of Bloodline Keeper with a p/t of 3/3. They are both able to transform, as per the new rules, and when they do transform into Lord of Lineage they each keep the set base p/t of 3/3.

I'm 90% sure that I shouldn't get two copies of Bloodline Keeper when destroying Lord of Lineage with Saw in Half. I should get two copies of what I actually destroyed, which was Lord of Lineage.

I'm a little less sure, maybe 65-70%, that if I ***did*** have a copy of Bloodline Keeper from Saw in Half that it shouldn't retain the halved p/t when it transforms, because while it isn't a new card, it does have a whole new set of characteristics and Saw in Half only affects the base p/t of the visible side.

**To Reproduce**
1. Have Lord of Lineage on the field.
2. Destroy it with Saw in Half.
3. Gain two copies of Bloodline Keeper.
4. Transform them to see that they retain the set p/t and don't gain the new stats. (Assuming that this part is an actual mistake.)

**Expected behavior**
When I destroy Lord of Lineage with Saw in Half, I expect to have two copies of Lord of Lineage.

If I have two copies of Bloodline Keeper from Saw in Half, I expect them to "lose" the halved p/t and fully become Lord of Lineage when I transform them. (Again, assuming that this bit is actually a mistake.)

**Desktop (please complete the following information):**
 - Version: forge-gui-desktop-1.6.59-SNAPSHOT-12-02

**Additional context**
I don't know if this bug is specific to Saw in Half, but it's quite possible that all TDFCs will have this happen with a card that destroys and makes a token. Though I suppose that Saw in Half might be the only card that both destroys and creates a token... I haven't checked.

**Comment by Klisz** [comment]
You are correct that you should have created Lords of Lineage, not Bloodline Keepers: "If the token is a copy of a transforming permanent with its back face up, the token enters the battlefield with its back face up." (707.8a) However, you are incorrect about the p/t: "The characteristics of each face are determined by the copiable values of the same face of the permanent it is a copy of, as modified by any other copy effects that apply to that permanent." (also 707.8a)

**Comment by TheLastNarwhal** [comment]
Gotcha. I wasn't super sure about the p/t part. It felt wrong, but if you say it's correct, then that's good enough for me.

**Comment by MorihiroS** [comment]
@Hanmac, need keep label, pls

**Comment by Icehawk78** [comment]
Adding to this, this also affects creatures that have mutated. It seems like the base action of Saw in Half should be "make a copy of a permanent" rather than whatever it is doing?

**Comment by Hanmac** [comment]
@tool4ever can you look into this?
