### ISSUE TITLE
Opponents sometimes ignore The Second Doctor card draw restriction

### ISSUE THREAD

**Issue by zlyfire** [Card-Forge/forge#4294]
**Describe the bug**
During your end step, The Second Doctor lets everyone draw an additional card. If they do, they cannot attack you or permanents you control until your next end step. Sometimes, opponents will take the card draw but not the restriction, thus letting them attack me anyway.

**To Reproduce**
1. Play The Second Doctor
2. Keep playing and pay attention to when opponents draw cards and when they gain the "Can't attack [player]" emblem Forge uses to track the effect
3. Occasionally, an opponent won't get the restriction

**Expected behavior**
Opponents will always gain the effect in their command zone and prevent them from attacking the player when they accept the card draw (seemingly the always take the card draw)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1.6.59-SNAPSHOT-12-04

**Additional context**
Relatedly, AI seem to always take the card draw. It might be that, when they don't want to take the card draw, they get the cards anyway but not the emblem.

**Comment by tool4ever** [comment]
not enough info to reproduce
