### ISSUE TITLE
Relic of Progenitus's first ability is incorrectly displayed on the stack

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4318]
**Describe the bug**
The first ability of Relic of Progenitus shows that player "player returns a card from their graveyard into their exile."

**To Reproduce**
1. AI/player casts Relic of Progenitus.
2. AI/player activates first ability of Relic of Progenitus.
3. See wrong figure.

**Expected behavior**
"Player exiles a card from their graveyard."

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.60-SNAPSHOT-12.06

**Screenshots**

![relic](https://github.com/Card-Forge/forge/assets/115870280/71983ee9-ad45-4708-87f6-34acf3399891)

**Comment by Northmoc** [comment]
> @Northmoc i think you once broke it?

Probably 😅 
Should be easy fix
