### ISSUE TITLE
AI can target player with hexproof

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4323]
**Describe the bug**
AI targets player with hexproof by first ability of Relic of Progenitus. Ability of Relic of Progenitus fizzles, but AI shouldn't even have to target a player with hexproof.

**To Reproduce**
1. AI casts Relic of Progenitus.
2. Player has Shalai, Voice of Plenty
3. AI activates first ability of Relic of Progenitus and targets player
4. First ability of Relic of Progenitus fizzles.

**Expected behavior**
AI can't targets player with hexproof.

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.60-SNAPSHOT-12.06

**Screenshots**

![relic](https://github.com/Card-Forge/forge/assets/115870280/50672827-822e-445d-9fd1-d3a0649db466)

**Comment by Hanmac** [comment]
@tool4ever could you reproduce it?
