### ISSUE TITLE
The Skullspore Nexus trigger uses wrong power

### ISSUE THREAD

**Issue by pfirpfel** [Card-Forge/forge#4335]
**Describe the bug**
With the The Skullspore Nexus on the battlefield, I had a creature, with base p/t 4/4 with 3 +1/+1 counters and the power double effect of the nexus making it a 14/7, dying. 

I expected to get a 14/14 token, but got a 4/4.

It shoul use the last known information about the dying creature's power and not the one it would have in the graveyard.

Ruling:
> Use the power of the nontoken creatures that died as they last existed on the battlefield to determine the base power and toughness of the token created by the middle ability. [(2023-11-10)](https://scryfall.com/card/lci/212/the-skullspore-nexus#rulings)

This was on Android 1.6.59-SNAPSHOT-12-03

**Comment by tool4ever** [comment]
yea it's ChangesZoneAll
should we try to pass it LastStateBattlefield for checks?

**Comment by Hanmac** [comment]
> yea it's ChangesZoneAll should we try to pass it LastStateBattlefield for checks?

yeah lets try that

**Comment by tool4ever** [comment]
_Tormod, the Desecrator_ also shouldn't trigger when it ETB
but I'm not sure yet if it can/should be fixed together
