### ISSUE TITLE
Question about the naming convention for the Army tokens

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4344]
**Describe the bug**
Noticed recently that after the amass change with the LTR set the army tokens no longer show up with an image, nor does Forge download a new image. Just wondering what the new naming rule for the tokens is, so I can manually update them.

**Comment by Klisz** [comment]
It's simply `b_0_0_army` - the current version of Forge doesn't distinguish, for token prototype (and thus filename) purposes, between the different armies created by different "amass [creature type]" effects (some testing confirms that this issue applies to the original Zombie Armies and to CMM's Sliver Army as well). Perhaps as a stopgap, the token art database could rename the Zombie Armies to just `b_0_0_army_war` and so on for each relevant set, with the Orc Army becoming `b_0_0_army_ltc` and maybe the Sliver Army being `b_0_0_army_cmm` (though that last one is complicated by the fact that CMM's tokens also include a Zombie Army for use with some reprints of the WAR amass cards as well)?

**Comment by TheLastNarwhal** [comment]
Ah, okay. It would be cool if the database could be updated to re-download the art for the new token name, but until then I'll just rename them using the set code.

Making a sliver deck and I definitely want that really cool sliver army art, so that's where this question came from. I'll just hope that no bot uses a card from CMM that makes nonsliver army tokens.

**Comment by Hanmac** [comment]
@kevlahnota we need to update the army token list in the token images
