### ISSUE TITLE
Defining a RewardData with "colors": ["white", "colorless"]

### ISSUE THREAD

**Issue by Jorilx** [Card-Forge/forge#4354]
Hello,
I'm trying to build a "pile" starter deck that replicates one of those from Shandalar (1997). This deck should contain 7 cards that are "a white enchantment or an artifact", so I tried this:
```

{
"name":"White",
  "mainDeck": [
    {
      "count":7,
      "colors": ["white", "colorless"],
      "cardTypes": ["Enchantment", "Artifact"]
    }
 ]
}

```

This doesn't work though, I always get 7 white enchantments. I think this is because of this line:

https://github.com/Card-Forge/forge/blob/63f05d0c7c7f98f6e074abdcae7f87ada15ae1d2/forge-gui-mobile/src/forge/adventure/util/CardUtil.java#L90

Since my "colorless" inside `this.colors` gets lost (the COLORLESS constant is 0), I think that the condition "white or colorless" cannot be handled correctly.
Am I right? Did I miss something?
I'm not sure how I could try to fix this.
Thanks for your help!

**Comment by jjayers99** [comment]
While it's not as clean to read, what you're looking for here can be accomplished with a Union node.


{
"name":"White",
  "mainDeck": [
    {
      "count":7,
      "type": "Union",
      "cardUnion": [
        {
          "colors": ["white"],
          "cardTypes": ["Enchantment", "Artifact"]
        },
        {
          "cardTypes": ["Enchantment", "Artifact"],
          "colorType": "Colorless"
        }
      ],
    }
 ]
}

**Comment by Jorilx** [comment]
I hadn't thought of that, thanks!
