### ISSUE TITLE
AI targets its own creatures by triggers of Valakut, the Molten Pinnacle 

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#4357]
**Describe the bug**
If a player and his creatures have protection from lands, AI targets its own creatures by triggers of Valakut, the Molten Pinnacle. But there is a word "may" in the text of Valakut, the Molten Pinnacle, which AI ignores.

**To Reproduce**
1. Player has Serra's Emissary with protection from lands
2. AI has Valakut, the Molten Pinnacle, 4+ lands and some creatures
3. AI casts Primeval Titan
4. AI finds 2 lands and targets its creatures by triggers of Valakut, the Molten Pinnacle

**Expected behavior**
AI shouldn't target its own creatures or itself by triggers of Valakut, the Molten Pinnacle.

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.60-SNAPSHOT-12.08

**Screenshots**

![valakut](https://github.com/Card-Forge/forge/assets/115870280/4fb98bb1-da9d-46ae-a961-4f0e51e397cf)

**Comment by Hanmac** [comment]
for the Rules, AI need to target its own creatures, but it should choose not to deal damage to them

> You target a permanent or player when the ability triggers. You decide whether to have Valakut deal damage to that permanent or player as the ability resolves.

**Comment by Hanmac** [comment]
@tool4ever @Agetian we need to look at when the Optional Trigger resolves, if it REALLY still wants to keep resolving

**Comment by MorihiroS** [comment]
Merged with #4392
