### ISSUE TITLE
The War Doctor receives multiple triggers from ReplaceDying effects

### ISSUE THREAD

**Issue by Klisz** [Card-Forge/forge#4375]
**Describe the bug**
When a permanent dealt damage by an effect with ReplaceDying would die, and the resulting replacement effect exiles that creature, The War Doctor's ChangesZoneAll ability triggers twice rather than once. If several permanents are exiled simultaneously (such as via Anger of the Gods), there will be one correct "[Amount: X]" trigger (where X is the number of permanents exiled this way) and a separate "[Amount: 1]" for each permanent, as though the ability was triggering once as a ChangesZoneAll and then again as a ChangesZone.

**To Reproduce**
1. Have The War Doctor in play, along with a creature with toughness less than or equal to the number of time counters on The War Doctor
2. Attack with The War Doctor, targeting the other creature with the attack trigger
3. When the attack trigger resolves and the other creature is exiled, The War Doctor's ChangesZoneAll ability triggers twice rather than once

**Expected behavior**
The War Doctor should trigger only once when one or more permanents are exiled from the battlefield.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.60-SNAPSHOT-12-13

**Additional context**
Neither Ranar the Ever-Watchful nor Hero of Bretagard (the only other two cards I'm aware of that have ChangesZoneAll triggers with Destination$ Exile and with battlefield as a possible origin zone) have this issue. After some testing, this appears to be linked with their ValidCause$ SpellAbility.YouCtrl clause (rather than the other difference, that their triggers both have battlefield as the only origin zone rather than any for The War Doctor).

**Comment by tool4ever** [comment]
Hmn this is tricky to fix fully but I think I can check all those trigger places in the engine, if the old card doesn't receive a new zone skipping it should be better
that should help with such corner cases for now

**Comment by tool4ever** [comment]
Fixed the duplicate already: #4458
