### ISSUE TITLE
Bug with Stand or Fall

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4404]
**Describe the bug**
When the A.I. chooses the piles for my creatures I am never informed which creatures go in which pile, nor am I prompted to select a pile. This basically means that I can never block.

**Expected behavior**
To know which creatures in which pile and to be able to select a pile.

**Screenshots**
Normally I'd include a screen, but can't really show being unable to block with a still.

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.60-SNAPSHOT-12-17

**Comment by MorihiroS** [comment]
@Hanmac, need keep label
