### ISSUE TITLE
Kutzil's Flanker - Can only select one mode

### ISSUE THREAD

**Issue by yoshimario40** [Card-Forge/forge#4405]
**Describe the bug**
When Kutzil's Flanker enters the battlefield, I can only select "Gain 2 Life, Scry 2"

**To Reproduce**
1. Play Kutzil's Flanker 

**Expected behavior**
I should be able to select from his three modes:
* Put +1/+1 counter per killed creature
* Gain 2 life, scry 2
* Exile target player's graveyard.

Instead, only the second one comes up

**Screenshots**
https://imgur.com/RMPo0WZ

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Forge 1.6.59

**Comment by tool4ever** [comment]
already fixed by #4322
