### ISSUE TITLE
Aragorn, the Uniter green ability

### ISSUE THREAD

**Issue by dmanofthenorth** [Card-Forge/forge#4416]
**Describe the bug**
Unable to select a valid choice for green spell +4/+4 selection. All creatures are said to be not a valid choice to be targeted. Can't also back out of selection, causing to have to end the game. 

**To Reproduce**
1. Have Aragorn, the Uniter in play. 
2. Play a green spell
3. Select green ability onto stack
4. try and select any creature you have on the battlefield
5. see error

**Expected behavior**
should be able to select any creature I have on the battlefield, including Aragorn himself, and give +4/+4 until end of turn. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version forge 1.6.60

**Comment by tool4ever** [comment]
Your steps don't work
please show your board or provide gamestate
