### ISSUE TITLE
Card with optional effect handled as mandatory

### ISSUE THREAD

**Issue by wesleyer** [Card-Forge/forge#4421]
**Describe the bug**
War Priest of Thune text says "When War Priest of Thune enters the battlefield, you may destroy target enchantment".  However, Forge is making "destroy target enchantment" mandatory, and not optional (as the text says).

**To Reproduce**
Cast War Priest of Thune in a game with at least one enchantment in play
Forge requires a target to be selected, and game can't progress without this.

**Expected behavior**
The card can enter the game without destroying an enchantment, if the player wants.

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Forge 1.6.59

**Comment by wesleyer** [comment]
Forge forces you to choose a target, but then later you can choose to skip the effect. So it's just confusing (having to actually choose a target to just be ignored).

**Comment by tool4ever** [comment]
that's just how the rules are...
