### ISSUE TITLE
"Slicer, Hired Muscle" is acting strange

### ISSUE THREAD

**Issue by Nemesis666first** [Card-Forge/forge#4422]
https://www.dropbox.com/scl/fi/ky9k46ioxe1846e7ey5cu/Slicer-Hired-Muscle-bug.png?rlkey=9yimxympx4huqa59y4qz3jyo9&dl=0

Something strange appears on my game.

"Linda" declared an attack on me, I blocked with a token. Butcher of Malakir Trigger, Slicer survive for no reason.
At my upkeep, Slicer trigger, she gave me Slicer, then... I cant attack her, this give me an error message "invalid blabla something".

**Comment by tool4ever** [comment]
Nothing strange if you read the rules:
> 701.38b. Goaded is a designation a permanent can have. A goaded creature attacks each combat if able and attacks a player other than the controller of the permanent, spell, or ability that caused it to be goaded if able.

**Comment by Nemesis666first** [comment]
Indeed, okay and she was not able to sacrifice it because it was not her card, I understood, thank you.
