### ISSUE TITLE
Roaming Throne does not seem to be able to respond Reflexive Triggered Ability.

### ISSUE THREAD

**Issue by stormcat664** [Card-Forge/forge#4428]
**Describe the bug**
Roaming Throne should respond to any triggered ability, but it does not seem to respond to Reflexive Triggered Ability.

**To Reproduce**
1. Playing Roaming Throne.
2. Triggering an ability with Reflexive Triggered Ability.
3. Fulfill the required conditions and induce Reflexive Triggered Ability.
4. It is triggered only once.

**Expected behavior**
Triggered twice.

**Screenshots**
![スクリーンショット 2023-12-23 175923](https://github.com/Card-Forge/forge/assets/52299273/21fd6288-9e23-45cf-8ac8-1a55a32af4f3)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version forge-gui-desktop-1.6.60-SNAPSHOT-12-21

**Comment by Hanmac** [comment]
@stormcat664 

Roaming Throne:
> If a triggered ability **of another creature you control** of the chosen type triggers, it triggers an additional time.

Rules:
> 603.2d An ability may state that a triggered ability triggers additional times. In this case, rather than simply determining that such an ability has triggered, determine how many times it should trigger, then that ability triggers that many times. An effect that states that an ability triggers additional times doesn’t invoke itself repeatedly and doesn’t apply to other effects that affect how many times an ability triggers.
> 603.2e Some effects refer to a triggered ability of an object. Such effects refer only to triggered abilities the object has, not any **delayed triggered abilities (see rule 603.7) that may be created by abilities the object has.**

also not any reflexive triggers too
