### ISSUE TITLE
Cards exiled with Lagrella, the Magpie don't return

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4452]
**Describe the bug**
As the title says, the cards that Lagrella exiles aren't returning when she leaves the battlefield.

**Expected behavior**
Any card that is exiled with Lagrella to return once she leaves the field, no matter how she leaves the field.

**Comment by tool4ever** [comment]
Can't reproduce, need details

**Comment by TheLastNarwhal** [comment]
Hmm. I don't know how much I can give you then... I know that the second time it happened I checked the field for anything that would prevent exiled cards from returning and there wasn't anything like that.

The first situation, I don't really remember how Lagrella was removed, I think... by combat, but the cards never came back. This puzzled me, so the next time I was extra observant to make sure I knew why it happened.

The second situation was the A.I. cast Lagrella (their commander), and exiled four creatures, two of which belonged to the same A.I., but I think that bit of cheating is a well documented issue. I then waited a few turns for my suspended Mystic Confluence to be cast and selected the bounce targeting Lagrella. Lagrella was returned to the command zone, but all the exiled cards remained exiled.

**Comment by TheLastNarwhal** [comment]
I don't think this will be too helpfull, but this is the only bit of info recorded in the log for that game. Rose Tyler was one of my commanders that was exiled and not allowed to return.

`[AI Preferences] AI profile Cautious was chosen for the lobby player Sebastian.
[AI Preferences] AI profile Cautious was chosen for the lobby player Martin.
[AI Preferences] AI profile Reckless was chosen for the lobby player Sarah.
Overriding AI confirmAction decision for ChangeZoneToAltDestination, defaulting to true.
Overriding AI confirmAction decision for ChangeZoneToAltDestination, defaulting to true.
Rose Tyler Did not have activator set in SpellAbilityRestriction.canPlay()
Overriding AI confirmAction decision for ChangeZoneToAltDestination, defaulting to true.`

**Comment by tool4ever** [comment]
Right, the important thing here is you caused a replacement effect (hand + commander)
This is not easy to fix and probably requires just doing #1733

**Comment by TheLastNarwhal** [comment]
So, this is happening because Lagrella was the commander? The first time this happened the card of mine that was exile was Jhoira of the Ghitu and she isn't my commander.
