### ISSUE TITLE
Ability does not activate on exile ( remove from game )

### ISSUE THREAD

**Issue by jarodium** [Card-Forge/forge#4453]
**Describe the bug**
After Gemstone Caverns is deployed and I choose Simian Spirit Guide to remove from game, Simian's ability does not trigger.

**To Reproduce**
Create a 7 card deck with Gemstone Caverns and Simian Spirit Guide on it. The rest does not matter for this issue.
Select Draw if you win the toss.
Activate Caverns
Choose Simian Spirit to exile ( remove from game )

**Expected behavior**
Red mana does not get added to pool.

**Screenshots**
![image](https://github.com/Card-Forge/forge/assets/1470446/20cbca2e-3984-432e-aa40-2d34e79afa71)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser brave
 - Version - does it matter?

**Smartphone (please complete the following information):**
 - Device: using only desktop.

**Additional context**
Attempting to get Zero Turn achievement

**Comment by tool4ever** [comment]
That doesn't make sense.
_Simian Spirit Guide_ has an activated ability, not a trigger:
If you're exiling it for the _Gemstone Caverns_ you can't also use it to produce red mana

**Comment by jarodium** [comment]
@tool4ever thank you for the reply. after some research I confirmed that you are correct. 

Therefore, I submit that it's impossible to win at turn 0 since all researched solutions for this achievement depend on Spirit Guides + Cavern combo. Even with Leylines I can't just put something when it's not my turn ( I am assuming Turn 0 is when it's before the opponent's main phase ).

Thank you for your time
Best regards
jarodium
