### ISSUE TITLE
War Doctor triggering twice on exiling creature

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4458]
**Describe the bug**
I attacked with The War Doctor and killed Merfolk Assassin with his ability, but instead of a single trigger, he triggered twice as you can see in the log.

I *think* this (triggering twice on exile) was one of the issues mentioned in something that's being worked on, but just in case it isn't I wanted to let you guys know about it.

**Screenshots**
![Screenshot_20231231_191907 cleaned](https://github.com/Card-Forge/forge/assets/92389638/55857678-e19b-457a-bc6c-7ea8231b95e9)

**Comment by Hanmac** [comment]
same problem as #1733 i think
