### ISSUE TITLE
Minor issue? with Rift Elemental

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4459]
**Describe the bug**
Rift Elemental's ability appears to be listed twice while in a game.

Although... now that I've stopped to actually read them, I see that the one ability is split into two for the choices. Hmm... I'm not sure if this qualifies as a bug anymore now, but I'll still post this, because maybe the ability should be changed to where it asks you which mode you want to use instead of listing them separately.

**Screenshots**
![Screenshot_20231231_202711 cleaned](https://github.com/Card-Forge/forge/assets/92389638/0e8f6a6b-33b1-4355-b001-ade51e592c4d)

**Comment by Hanmac** [comment]
yes, it should be a smaller bug, because for some cases where cards gain abilities, some say "only activate once per turn"
so it would make a difference if they are two abilities

@tool4ever can you check if the abilities can be merged? probably need some tweaking with the cost?
