### ISSUE TITLE
Issue with suspend and MDFC lands

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4460]
**Describe the bug**
I could be wrong about this, but I don't think you're supposed to be able to play the land side of a suspended MDFC card. Currently, for example, when the last time counter is removed from Sea Gate Restoration you are asked which side to play and can play the land side.

**To Reproduce**
1. Have Jhoira of the Ghitu on the field and Sea Gate Restoration in hand.
2. Suspend Sea Gate with Jhoira.
3. Remove the time counters with something like Clockspinning, or wait 4 turns.
4. Play it as a land when prompted.

**Expected behavior**
Suspend says "cast" not "play," so I would expect to only be able to cast the spell side of an MDFC land.

**Comment by tool4ever** [comment]
> 702.62a. Suspend is a keyword that represents three abilities. The first is a static ability that functions while the card with suspend is in a player's hand. The second and third are triggered abilities that function in the exile zone. "Suspend N--[cost]" means "If you could begin to cast this card by putting it onto the stack from your hand, you may pay [cost] and exile it with N time counters on it. This action doesn't use the stack," and "At the beginning of your upkeep, if this card is suspended, remove a time counter from it," and "When the last time counter is removed from this card, if it's exiled, play it without paying its mana cost if able. If you can't, it remains exiled. If you cast a creature spell this way, it gains haste until you lose control of the spell or the permanent it becomes."

I will update our reminder text.

**Comment by TheLastNarwhal** [comment]
> > 702.62a. Suspend is a keyword that represents three abilities. The first is a static ability that functions while the card with suspend is in a player's hand. The second and third are triggered abilities that function in the exile zone. "Suspend N--[cost]" means "If you could begin to cast this card by putting it onto the stack from your hand, you may pay [cost] and exile it with N time counters on it. This action doesn't use the stack," and "At the beginning of your upkeep, if this card is suspended, remove a time counter from it," and "When the last time counter is removed from this card, if it's exiled, play it without paying its mana cost if able. If you can't, it remains exiled. If you cast a creature spell this way, it gains haste until you lose control of the spell or the permanent it becomes."
> 
> I will update our reminder text.

Oh, so even though it mentions mana cost here you can still play a land due to the word "play?"

**When the last time counter is removed from this card, if it's exiled, play it without paying its mana cost if able.***
