### ISSUE TITLE
When targeting a permanent with an effect that is duplicated by another card, you cannot unselect the card

### ISSUE THREAD

**Issue by aaronmell** [Card-Forge/forge#4469]
**Describe the bug**
I had [Naban, Dean of Iteration](https://gatherer.wizards.com/pages/Card/Details.aspx?multiverseid=442946) in my hand.
I played a creature that allowed me to return a creature to my opponents hand.

1. There was no way to select a different creature for either the first or second trigger.
2. It allowed me to select the same card twice

**To Reproduce**
1.  Play the card I specified in the description
2. Make sure opponent has 2 creatures on the board
3. Play a card like [Aether+Adept](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=380241&part=Aether+Adept)

**Expected behavior**
I would expect to be able to change my selection between each invocation of the cards effect

Smartphone (please complete the following information):

Device: Samsung
OS: Android 14
Browser Latest Chrome
Version 12-26-23 Snapshot

**Comment by tool4ever** [comment]
This works fine, but maybe you tapped too fast

**Comment by aaronmell** [comment]
Just had the situation happen again, double checked, I qas unable to
deselect the selected card

**Comment by aaronmell** [comment]
I believe this was because the UI covers up the card in portrait mode on the phone.
