### ISSUE TITLE
Game gets  stuck after winning any oponent on duel !

### ISSUE THREAD

**Issue by ozgur1318** [Card-Forge/forge#4470]
**Describe the bug**
on the quest mode when i play a duel  after wining 3  games in a row  (cuz playing best of 5), and defeating the oponent the game gots stuck just after the last prompt to which gives me credits . i click ok and then nothing happens ?  
It was supposed to show me a mini window showing 3  diffrent booster names which i had to choose  i.e. earn  for winning the opponent ! but it never shows it :S . 

i have no idea why this happened all of a sudden . please help . 

**Desktop (please complete the following information):**
 - OS:  windows 11
 
[forge0.log](https://github.com/Card-Forge/forge/files/13812747/forge0.log)

 - Version [1.6.53 )

**Comment by tehdiplomat** [comment]
@ozgur1318 It's trying to award you a booster, but none are defined; 

EDT > java.lang.RuntimeException: choice required from empty list
	at forge.gui.GuiChoose.getChoices(GuiChoose.java:148)
	at forge.gui.GuiChoose.getChoices(GuiChoose.java:141)
	at forge.GuiDesktop.getChoices(GuiDesktop.java:181)
	at forge.gui.util.SGuiChoose.getChoices(SGuiChoose.java:158)
	at forge.gamemodes.quest.QuestWinLoseController.awardBooster(QuestWinLoseController.java:537)
	at forge.gamemodes.quest.QuestWinLoseController.access$1400(QuestWinLoseController.java:50)
	
How did you create your quest?

**Comment by ozgur1318** [comment]
it was probably a quest that i started on some other verisons of the forge which i started way before like years ago maybe even 10 years ago i really dont remember  ! . and everything was working well since the last week or so i guess.. btw i dont know if this is related or the reason but i also  mistakenly tried  to open the game via the "forge-fava8.exe" file instead of the "forge java.exe" file once and weirdly enough none of my 10 quests can be seen there? when i click the load quest there are zero quests there . so i closed that one i remembered i generally play on the forge.exe file and there i can see my quests but the weird problem that i had written on my previous post appered there..  im still very suprised why did it happen in the first place..

**Comment by ozgur1318** [comment]
any help ?_

**Comment by ozgur1318** [comment]
??=
