### ISSUE TITLE
Triggers should only be checked once (preferably very close after the event)

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#4471]
When you target yourself with _Goblin Festival_ and control _Auntie Blyte_ you only get her trigger if you win the flip (but obviously it should happen in both cases).

It fails because even though the trigger is collected correctly after the damage is dealt (while you still control the Enchantment), the trigger gets tested again when the stack unfreezes for it.

But why? We have **already confirmed the event was correct** at the point between effect X and Y and that should be the final result.

So I think checking `canRunTrigger` twice is not only redundant but even wrong rules wise.

Luckily my proposed fix is minimal by changing the logic here
https://github.com/Card-Forge/forge/blob/13cf0810460741f36b9f25f4e31ad8db5f9e259d/forge-game/src/main/java/forge/game/trigger/TriggerHandler.java#L360
into `(wt.getTriggers() != null || canRunTrigger(t, mode, runParams)`

@Hanmac 
your opinion?

(It is a bit like #1157 but not the same!)

**Comment by Hanmac** [comment]
We still need to think about a way to store the Trigger Controller inside the Waiting Trigger List at the time the Trigger is collected
