### ISSUE TITLE
Music doesn't stop playing after exit

### ISSUE THREAD

**Issue by Gevaarlijk** [Card-Forge/forge#4485]
When I exit Forge the music continues playing until I manually kill Java in task manager

Windows 10. 

1.6.60-SNAPSHOT-01-0

**Comment by MorihiroS** [comment]
I don't know, for me music stops as it should. It only continues to play if the game crashes

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.60-SNAPSHOT-01.05
