### ISSUE TITLE
Blast-Furnace Hellkite has no option to be played without sacrificing and artifact

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4529]
Blast-Furnace Hellkite has no option to be played without sacrificing and artifact.

It has artifact offering

Artifact offering (You may cast this card any time you could cast an instant by sacrificing a artifact and paying the difference in mana costs between this and the sacrificed artifact. Mana cost includes color.)

But I cannot play it without sacrificing an artifact even in my mainphase.

**Comment by TheLastNarwhal** [comment]
I don't know what you had on your field at the time, nor do I know if there happened to be another spell on the stack when you tried to cast Blast-Furnace Hellkite (which would mean you would be attempting to cast it at flash speed, hence the forced artifact offering.)  So, more information would be needed to figure out why you can't cast it without artifact offering.

That being said, I just tested this card and there isn't an issue with it as far as I can see. When you click on the card while in the main phase, and with no spells on the stack, you are given the option of which way to cast it. You can cast it normally, or you can cast it with artifact offering.

![Screenshot_20240118_114756](https://github.com/Card-Forge/forge/assets/92389638/e30ef858-b9cc-401e-aefb-ff27f8b6ff9f)

Though unlikely, it's also possible that there was a bug with this card before and it's fixed now. I'm on the latest snapshot and it works correctly.
