### ISSUE TITLE
Not all cards shown of a set when searching in Deck Editor.

### ISSUE THREAD

**Issue by chinaaa555** [Card-Forge/forge#4530]
**Describe the bug**
Not all cards are showing in deck editor of a set.

**To Reproduce**
1. Go to 'Deck Editor'
2. Search for cards in LCI set
3. Shows only 22 cards when filtered on LCI set

**Expected behavior**
All cards visible especially when searching for a specific card like Tishana's Tidebringer

**Screenshots**
![image](https://github.com/Card-Forge/forge/assets/130354502/360457e2-5030-44c4-ace5-22f600da9dc7)
![image](https://github.com/Card-Forge/forge/assets/130354502/04e8c2b7-d401-4bdd-a8c6-f0219f7b375b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.60-SNAPSHOT

**Additional context**
Tried:
- Reinstalling
- Content Downloaders
- Resetting configuration
- Audit card and image data does not show any missing cards from LCI
- Also applicable for other new sets like REX etc.

**Comment by TheLastNarwhal** [comment]
I very, very occasionally run into this issue and if I'm remembering correctly I've resoved it in the past by reseting the search filters, or just exiting and restarting the program.

I don't know what version you're using or if you've correctly extracted it, but I'm on the latest snapshot (forge-gui-desktop-1.6.60-SNAPSHOT-01-17) and if you filter by the LCI set you see 291 or 415 cards, depending on whether or not you have "unique cards only" checked.

**Filtering by LCI set:**
![Screenshot_20240118_120950](https://github.com/Card-Forge/forge/assets/92389638/75747310-ded1-4d31-9496-ee383875dd5c)

**Filtering by "tisha":**
![Screenshot_20240118_121009](https://github.com/Card-Forge/forge/assets/92389638/676115f0-1360-49da-9079-d60728aae9e0)
