### ISSUE TITLE
MKM: Disguise and Cloak

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#4532]
* Disguise is similar to Morph, with the difference that the Face-Down card has Ward 2. But it doesn't count as Morph.
* Cloak is similar to Manifest, also with Ward 2 there too.

Qarsi Deceiver and MorphOrManifest needs an update.
`Spend this mana only to cast a face-down creature spell, pay a mana cost to turn a manifested creature face up, or pay a morph cost.`
* you can't use the Mana to turn a Disguised card face up.
* but you can use it when the card was manifested, then you can use the Disguise Ability.
* Card.java has `public boolean turnFaceUp(boolean manifestPaid, boolean runTriggers, SpellAbility cause) {` which should be removed or updated? especially the `manifestPaid` check, shouldn't that be done in the SetStateEffect instead?
* isManifestUp probably needs to be removed?
* Qarsi Deceiver probably should use isValid checks instead of Special String

**Comment by Hanmac** [comment]
@tehdiplomat i think I'm going to try this one at the Weekend

its mostly a copy of Morph and Manifest (with extra steps)

**Comment by tehdiplomat** [comment]
Sounds good. It'd be nice if we can spend some time as some point making these things a bit more generic so they can be more easily updated in these cases.

**Comment by Hanmac** [comment]
@tehdiplomat i want to cleanup `meetsManaRestrictions` if able and only use `SpellAbility.isValid`

i wonder if i can make this better? should this check for ApiType ?
`pay a mana cost to turn a manifested creature face up`

can this be used on other stuff too like Activated Abilities? like ones that Target?
for example Ixidor, Reality Sculptor?
