### ISSUE TITLE
MKM: Suspected

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#4533]
imo Suspected should be a flag on the Creature card and no extra effect?

* A suspected creature has menace and can't block for as long as it remains suspected.
* Once suspected, a creature remains suspected until it leaves the battlefield or another effect causes it to no longer be suspected.

There are some cards that say:
* "You may have it become no longer Suspected"
* And Airtight Alibi says: "If it’s suspected, it’s no longer suspected." and "can’t become suspected"

AI wise, Suspecting is both offensive and also defensive:
* Giving your creatures menace is cool.
* Giving your opponent creatures "can't block" also has benefits.

might need some tweaking on when to use on your vs your opponents creatures.

**Comment by Agetian** [comment]
Agreed regarding the mechanical implementation, I'd also prefer that it's just a flag on the creature.
Once the mechanics are implemented, I can take a look at the AI side.

**Comment by tehdiplomat** [comment]
Maybe one day we'll convert all of these properties into a bitflag. So we can just add it in a single place and everything else just works.

**Comment by Hanmac** [comment]
This Issue could benefit from this MR #4553 one

we just need to branch the AI logic for this later
