### ISSUE TITLE
MKM: Case

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#4534]
Case has new Enchantment Type

> Individual Cases each have three abilities. The top ability is always active. The middle ability, preceded by "to solve," sets out the conditions under which you can solve the Case. At the beginning of your end step, if the Case is unsolved and if you've met the condition described in the middle ability, the Case becomes solved.
> Now that the Case is solved, the middle ability won't trigger again. Additionally, the last ability, preceded by "solved," becomes active. If that ability is an activated ability, it can now be activated. If it's a triggered ability, it can now trigger. If it's a static ability, that ability now functions.

imo the middle ability should just be a normal trigger without extra Code-Keyword?

Making a Case Solved should be an Extra SpellAbilityEffect

The third Ability just needs a StaticAbility with a Condition to give itself the other Abilities (check out Class Level)

**Comment by tehdiplomat** [comment]
https://github.com/Card-Forge/forge/pull/4553
