### ISSUE TITLE
MKM: Collect Evidence

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#4535]
> Each time you're asked to collect evidence, exile any number of cards from your graveyard with total mana value of the indicated number or greater. For example, to collect evidence 6, you could exile a single card with mana value 6 from your graveyard, cards with mana values 1 plus 2 plus 2 plus 1. Or even 1 plus 1 plus 2 plus 2 plus 1 plus … **The point is, any number of cards, even extra ones if you really want to.** If you're given a choice to collect evidence but can't cover the full amount, you can't collect evidence at all and you can't exile any cards from your graveyard.

Tricky for this one is that you can overpay if you really want to?

- [ ] Add Trigger for "Whenever you collect evidence"
- [ ] Handle "Collect Evidence X" Cost _(To collect evidence X, exile cards with total mana value X or greater from your graveyard.),_
  - [ ] Urgent Necropsy `where X is the total mana value of the permanents this spell targets.`
  - [ ] Incinerator of the Guilty `When you do, Incinerator of the Guilty deals X damage to each creature and each planeswalker that player controls.`

**Comment by tehdiplomat** [comment]
The overpay is something we already do for Crew. So shouldn't be too bad. The thing we did poorly with Crew is tracking how much is currently paid for in the input dialog, so we should try to do that better.

**Comment by tehdiplomat** [comment]
https://github.com/Card-Forge/forge/pull/4561

**Comment by Hanmac** [comment]
@tehdiplomat i added some extra stuff needed like the Trigger, and special note on the two cases of "collect evidence X"

**Comment by tehdiplomat** [comment]
I'm not doing any more work here. There should be enough built up for people to add those for the specific cards that require it.

**Comment by Hanmac** [comment]
yeah, no problem, me or someone else like @tool4ever should be enough to add the trigger

and for the X cards, might a bit of testing but i think they should still work

**Comment by tehdiplomat** [comment]
Yep, I expect the X cards to just work since we're already doing CalculateAmount. Just needs to be defined properly as an Announce or a Target. Adding the trigger should be pretty straightforward when that one card gets added.

**Comment by tehdiplomat** [comment]
Yep, it just lets you select some things and then if your value is less than the required it says you didn't do it right.
