### ISSUE TITLE
Add a "Pack Wars" mode

### ISSUE THREAD

**Issue by JimmBuck** [Card-Forge/forge#4538]
Given that forge can simulate packs for draft, would it be possible to add a Pack Wars mode using the official WotC rules - all that Forge would have to do is generate a pack and add 2 of each basic land.

**Comment by tehdiplomat** [comment]
Traditionally, Mini Master (Pack Wars) adds 3 basics to the booster before playing. This probably would need a lot of people requesting, or a developer really interested in adding it before it shows up in Forge. My biggest question mark is what category we'd actually put this in.
