### ISSUE TITLE
AI Removal priorities are totally nuts (and centered towards the Human Player)

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4549]
Yeah, the AI is bad at the game (much better tho than I thought it could be, alot better actually),

but this makes the game really frustrating to play. Its like the board always plays against the player in a 4P commander game.

- AI removes my 2 CMC 0/6 blue wall without even flying while the other 2 AIs have like 6 threats out combined
- next AI then removes my commander (Arcades) which is my last creature, while the other 2 AIs (see above) have half a dozen threats out combined.
I did not even aggro any of these AIs before, if that is taken into account.

This is also a problem with early removals which are spammed by the AIs especially against the players board.
Play a 1 CMC mana elf. REMOVE, while the other AI has a 4/1 lifelink necron out...

I see I m not a pro player and maybe the AI makes pro player decisions, but they are often bad for the game or for themselves, since they sometimes waste their removal early just to die from prime threats later which they cannot act against.

Also they play boardwipes very early, sometimes also just to remove ONE creature or Artifact... 

I tried playing ultra slow and sometimes casting first nonland permanent in turn 4 or 5, but same shit, even when other AIs have stuff out.

If there is an AI setting I did not see yet or that maybe helps with this, please tell me. Thank you :) 

EDIT: I forgot to mention, I set the AI to "cautious".
Not that this had any noticeable difference in AI gameplay to any other setting I trie :(

**Comment by silentiea** [comment]
From my understanding, the AI will often base its decisions about card value solely on mana value. While this isn't perfect (and is often pretty much just bad), it's very low-cost as a strategy. The AI doesn't have to think very hard to decide, and doesn't have to individually check the characteristics of each viable target every time it considers casting a spell.
