### ISSUE TITLE
Flashback spells does not get exiled when returned to hand.

### ISSUE THREAD

**Issue by bountygiver** [Card-Forge/forge#4628]
A spell that is cast from flashback gets returned to hand when an effect do so.

**To Reproduce**
1. Play Krark, The Thumbless
2. Cast a spell with flashback from your graveyard using flashback.
3. Lose the coin flip on Krark
4. The spell gets returned to your hand rather than exiled.

**Expected behavior**
The spell should be exiled regardless of how it leaves the stack.

```702.34a Flashback appears on some instants and sorceries. It represents two static abilities: one that functions while the card is in a player’s graveyard and another that functions while the card is on the stack. “Flashback [cost]” means “You may cast this card from your graveyard if the resulting spell is an instant or sorcery spell by paying [cost] rather than paying its mana cost” and **“If the flashback cost was paid, exile this card instead of putting it anywhere else any time it would leave the stack.”** Casting a spell using its flashback ability follows the rules for paying alternative costs in rules 601.2b and 601.2f–h.```

**Comment by Hanmac** [comment]
Can you check that out? It was working before

**Comment by Hanmac** [comment]
@tool4ever Can you check that out? It was working before
