### ISSUE TITLE
"one or more" triggers that reuse the singular type have become more problematic

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#4633]
By fixing #4471 I introduced another bug:
if two Blood tokens are sacrificed simultaneously _Blood Hypnotist_ will trigger twice.

This happens because it's only using a `Sacrificed` trigger with ActivationLimit.

Since rolling back the fix isn't really desirable I might need to make it more accurate too and write a new type.

`SacrificedOnce`?

and for _Forge, Neverwinter Charlatan_
>one or more players sacrifice one or more creatures

`SacrificedAll?`

**Comment by Hanmac** [comment]
Imo it should still respect the Trigger Limit

But SacrificeOnce might be cleaner
