### ISSUE TITLE
[1.6.59] Missing Doctor Who cards

### ISSUE THREAD

**Issue by Kantharr** [Card-Forge/forge#4645]
The following cards from the Doctor Who Commander set are missing in the Card Catalog:

The Valeyard
Davros, Dalek Creator
Ensared by the Mara
Genesis of the Daleks
Great Intelligence's Plan
Hunted by The Family
Midnight Crusader Shuttle
Missy
Sycorax Commander
The Dalek Emperor
The Master, Gallifrey's End
This Is How It Ends

**Comment by Hanmac** [comment]
because some of them were added after the release and are available via the snapshot

**Comment by Kantharr** [comment]
> because some of them were added after the release and are available via the snapshot

Where would I find this snapshot? I'm not sure which one of versions on this list is the snapshot so I downloaded whatever was the latest:

https://releases.cardforge.org/forge/forge-gui-desktop/

**Comment by paulsnoops** [comment]
https://downloads.cardforge.org/dailysnapshots/
