### ISSUE TITLE
Slow performance on Linux

### ISSUE THREAD

**Issue by thedevnull** [Card-Forge/forge#4667]
The desktop application performs a bit slow during the animations and transitions inside the client.

I'm using Kubuntu 22.04 and Intel graphics card.

I've fixed it by passing these parameters, but we can implement that inside the source code. 

        // activate opengl
        System.setProperty("sun.java2d.opengl", "True");

        // set system look and feel
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

Or we can fix like this inside de bash launcher script: java -Dsun.java2d.opengl=true -jar forge-gui-desktop-1.6.59-jar-with-dependencies.jar

**Comment by kenjitamura** [comment]
Thanks for the idea.  Appearance is better and seems to be a little smoother after adding this to forge.sh SHAREDPARAMS: `-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dsun.java2d.opengl=true`  

On Ubuntu 22.04 however forge still kept freezing even with those options added.  What resolved the freezes for me was disabling sound effects and music.

**Comment by tool4ever** [comment]
Implemented via #4742
