### ISSUE TITLE
Capricious Hellraiser's ETB didn't trigger Prosper

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#4685]
Windows, current snapshot.

I got Capricious Hellraiser [ONE] off of an opponent's Oath of Druids [C16] on my upkeep. It exiled several cards, including Chaos Wand [AFC] which it let me copy and cast for free. However, it didn't trigger my Prosper, Tome Bound [AFC] and I didn't get a treasure!

**Comment by Samthere** [comment]
Never mind, a copy is made directly on the stack I think! Checking that and will close this if so.

**Comment by Samthere** [comment]
Nope I was wrong about being wrong:
707.12. An effect that instructs a player to cast a copy of an object (and not just copy a spell) follows the rules for casting spells, except that the copy is created in the same zone the object is in and then cast while another spell or ability is resolving.

The card is in exile so the copy should be created in exile, and then move to the stack or cease to exist as a state-based action if it doesnt.

**Comment by tool4ever** [comment]
It's been ruled that copies of cards are in fact not cards which matters here because Proper's trigger event specifically checks against this fact (compared to some others with wording like "...cast a spell from exile".

**Comment by Samthere** [comment]
Oh yep, that's the word I was missing :D
