### ISSUE TITLE
Orcish Bowmasters "Ping" Freezes Game

### ISSUE THREAD

**Issue by EricDspeed** [Card-Forge/forge#4691]
Whenever Orcish Bowmasters is cast and enters the battlefield, its ETB trigger, "deal 1 damage to any target" allows you to target something, but after targeting something and allowing the target to resolve it just says "waiting for opponent" forever and the game is frozen. This is with both AI and human vs human

Desktop Windows, Forge 1.6.60 latest snapshots

**Comment by tehdiplomat** [comment]
Without a forge log we can't tell why you crashed.
