### ISSUE TITLE
Transmute Artifact calculates mana difference wrongly if sacrificing artifact copies

### ISSUE THREAD

**Issue by jumpinjackie** [Card-Forge/forge#4721]
**Describe the bug**

When I try to play Transmute Artifact and sacrifice an artifact which is a copy (made by Copy Artifact or Phyrexian Metamorph for example), Transmute Artifact will compute the difference I have to pay based on the mana value of the copying card (Copy Artifact, Phyrexian Metamorph, etc), instead of the mana value of the artifact that it copied.

**To Reproduce**

1. Play Coveted Jewel (mana value: 6)
2. Play an an artifact copier (eg. Copy Artifact, mana value: 2). The copier becomes a copy of (Coveted Jewel)
3. Play Transmute Artifact, choose to sacrifice the *copy* of Coveted Jewel
4. Search for another Coveted Jewel or another mana value 6 artifact to put into play

**Expected behavior**

I expect Transmute Artifact to say I don't have to pay any difference as I sacrificed an artifact with mana value 6, to fetch an artifact with mana value 6. Thus difference is 6 (MV of Jewel) - 6 (MV of sac'd copy) = 0 mana.

Instead, Transmute Artifact wants me to pay the difference of 4 mana because it thinks the MV of the *copy* is the MV of Copy Artifact instead of the MV of the artifact it copied (Coveted Jewel). It thinks 6 (MV of Jewel) - 2 (MV of Copy Artifact) = I have to pay 4 mana difference.

This also happens with Phyrexian Metamorph (mana value: 4) where it wants me to pay a difference of 2 mana under the same scenario. It thinks 6 (MV of Jewel) - 4 (MV of Metamorph) = I have to pay 2 mana difference.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: 1.6.60-SNAPSHOT-02-20

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Hanmac** [comment]
@tool4ever use Sacrificed LKI if able

**Comment by Hanmac** [comment]
@tool4ever can you check this?
