### ISSUE TITLE
Creatures being granted Blitz through Henzie can't be cast from the graveyard or Exile even though an ability allows you to do so

### ISSUE THREAD

**Issue by nighthawkFX** [Card-Forge/forge#4725]
**Describe the bug**
If you have Henzie "Toolbox" Torre on the field and an ability or effect allows you to cast a creature from your grave or exile, you can't cast that spell for it's Blitz cost. (creature with cmc 4 or More) 

**To Reproduce**
1. Henzie on the field
2. An abilitiy allowing you to cast a creature from graveyard or Exile. For example Chainer, Nightmare Adept. 
3. Try casting a creature spell with cmc 4 or more from the graveyard or Exile. 
4. You are only given the option to cast the creature for its normal cost, Not its Blitz cost

**Expected behavior**
You should be able to cast the creature for its Blitz cost from the grave/Exile. 
This was possible in an earlier Version. 

**Smartphone (please complete the following information):**
 - Device: Honor View20
 - OS: Android 10
 - Forge Version forge-android-1.6.60-SNAPSHOT-02-18

**Additional context**
Tested on Android.
Tested with Chainer, Nightmare Adept and Commune with Lava.

**Comment by Hanmac** [comment]
See #4696

**Comment by tool4ever** [comment]
@Hanmac 
adding
``alternatives.addAll(getMayPlaySpellOptions(iSa, source, activator, altCostOnly));``
here https://github.com/Card-Forge/forge/blob/600da3e80bbba868881e25b45affe776a0a00475/forge-game/src/main/java/forge/game/GameActionUtil.java#L247
will now let you Blitz your commander

but I'm not sure if the logic should still be cleaned up more before this gets patched
