### ISSUE TITLE
Outpost Siege loses track of "can be cast" when casting fails

### ISSUE THREAD

**Issue by Samthere** [Card-Forge/forge#4745]
Windows, current snapshot.

I have `Outpost Siege` [FRF] in Khans mode, which puts a card into exile and allows it to be played that turn. I started casting the exiled card, then cancelled. I'm no longer able to cast the card.

Presumably this is some tracking effect/element which is removed at the start of casting, instead of the end.

**Comment by tool4ever** [comment]
I want to do a big refactor to check all ExileOnMoved usage but that's something for my backlog

**Comment by PTheocharis** [comment]
Hello, I am a beginner in coding and I want to start improving. My class has a project to contribute to an Open source project, do you think I can try to handle this task?

**Comment by tool4ever** [comment]
Always happy for help
you need more details?

**Comment by tehdiplomat** [comment]
I wonder if this is resolved with the undo restore experimental functionality that was recently added.

**Comment by harshitissm** [comment]
Hi, I am starting my open-source contribution journey and came across this issue which was market as good for newcomers.

Would anyone explain me this issue?

**Comment by tool4ever** [comment]
We have multiple params for effect cleanup, the logic is defined here:
https://github.com/Card-Forge/forge/blob/2042aaa03393b243c5b84f868aaa0c50d3f5f124/forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java#L228-L235

ExileOnMoved$ might be a bit quicker but is only for single affected cards and causes problems with our standard way of doing stack rollback

So basically all effects that involve some kind of play permission should avoid it. Depending on the amount it might even make sense to implement heuristics for auto-detection 🤔

**Comment by pachecoberlin** [comment]
I made a puzzle starting at untap phase with Outpost Siege [FRF] on battlefield, so i can choose Khans. I can confirm that addExileOnMovedTrigger is called, while resolving in upkeep.
I have one card in library, which is exiled and can be cast and canceled several times in both main phases. 
So i cannot reproduce. Any other ideas or steps on how to test/reproduce would be greatly appreciated.

**Comment by tool4ever** [comment]
@dracontes 
I'm trying to document these params usage in the related wiki section

Can you help search if there's a card where `ExileOnMoved$` is required instead of `ForgetOnMoved$`?
so probably something that's limited to a single use (ideally nothing with stack as that complicates things)

**Comment by dracontes** [comment]
> Can you help search if there's a card where `ExileOnMoved$` is required instead of `ForgetOnMoved$`?

Apologies for the late reply. I do hope it is timely still. 

Surveying the usage of `ExileOnMoved$` there's a lot of effects outside of play/cast permissions that use it. usually associated with a specific permanent (damage prevention, can't/must attack/block, setting up triggers/replacement effects, etc.), but I'm not sure that any specifically _require_ `ExileOnMoved$`, if, as I understood from the discussion, the only difference between `ExileOnMoved$` and  `ForgetOnMoved$` is that the former is stricter about aborted spell casting. 
I checked and not even something like the trigger on an [Attuned Hunter](https://scryfall.com/card/tdm/135/attuned-hunter) is strict about it when faced with [Yawgmoth's Will](https://scryfall.com/card/usg/171/yawgmoths-will). Moving to the stack to start the casting of a spell seems to be mostly ignored outside of the casting process itself, except by static effects that track numbers of cards in a zone (Lhurgoyf, all the threshold cards).
