### ISSUE TITLE
CantLose and CantWin as StaticAbilities/CantHappen

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#4757]
Cases:

- [ ]  "You can't win the game." → StaticAbility
- [ ]  "You can't lose the game." → GameLoss Replacement + `GameLossReason` parameter
  - [ ]  "You don't lose the game for having 0 or less life."
  - [ ]  "You don't lose the game for drawing from an empty library."

Similar to other #3307, "CantLose" and "CantWin" should be via StaticAbilities instead of keywords
CantHappen Replacement would be fine too

Also @tool4ever "Your opponents can't win the game." keyword probably doesn't exist

https://github.com/Card-Forge/forge/blob/511ccd697c7b1d7dea8933715a5b7973be8ea141/forge-gui/res/cardsfolder/c/courageous_resolve.txt#L8

**Comment by tool4ever** [comment]
Hmn, GameLoss Replacement already exists there

**Comment by Hanmac** [comment]
> Hmn, GameLoss Replacement already exists there

CantHappen is fine too i think

i need to make a Meta ticket for the `Player.hasKeyword("string")` stuff to be changed into Static or CantHappen
