### ISSUE TITLE
Zephyr Singer gives Player flying counters

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#4761]
@tool4ever can you debug this?

My Version is 05-02-2024, but the code doesn't seems to have changed since then

**Comment by tool4ever** [comment]
caused by #2710
since CounterPut* uses `getDefinedEntities` Players will be matching that too
I'd prefer to roll back that change, adding more exceptions into `getDefinedPlayers` for every DefinedCards possibility feels ugly...?

**Comment by Hanmac** [comment]
> caused by #2710 since CountersPut uses `getDefinedEntities` Players will be matching that too I'd prefer to roll back that change, adding more exceptions into `getDefinedPlayers` for every DefinedCards possibility feels ugly...?

`Defined$ Something` is more clean than `Valid$ Stuff.Something`

so i think its better to just fix DefinedPlayers ... i will do that later
