### ISSUE TITLE
AI does not know what Commander damage is (does not block my Commander to save itself)

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#4762]
In Commander matches vs AI (I test my decks playing vs. 3 AI commanders)

the AI:

- does not block with creatures when my Commander would kill it with commander damage even when it could (has valid blockers, even useless tokens, still does not even try)
- virtually as long as my commander does not deal letal damage (AI gets 0 or negative life) it will never block it when it would lose a creature for it

Using the latest Version of FORGE

**Comment by tool4ever** [comment]
No, your observation is incorrect, the AI is well aware of it as can be reproduced quite easily:
![grafik](https://github.com/Card-Forge/forge/assets/8506892/593d0b3a-7319-4879-9be2-4ae15d4a8c50)

Now in complex boardstates there can be an infinite number of reasons for why the AI might miscalculate, but you should provide specific and reasonable examples rather than making such general claims...

**Comment by Nymra** [comment]
are you mad/in denial? If this is how feedback and bugs are treated in here there is no wonder the AI of Forge is so freaking bad.
"Invalid" is your attitude. 

I attack with my 23/23 Licia with Firstrike to an opponent with 50 life and he has like 1 million blockers including 1/1 tokens but does not block but dies instantly to the commander damage.

**Comment by Nymra** [comment]
ok then, ignore this. ridiciulous.

**Comment by Nymra** [comment]
> No, your observation is incorrect, the AI is well aware of it as can be reproduced quite easily: ![grafik](https://private-user-images.githubusercontent.com/8506892/309286443-593d0b3a-7319-4879-9be2-4ae15d4a8c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjM4MDYsIm5iZiI6MTcwOTMyMzUwNiwicGF0aCI6Ii84NTA2ODkyLzMwOTI4NjQ0My01OTNkMGIzYS03MzE5LTQ4NzktOWJlMi00YWUxNWQ0YThjNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAwNTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzc4ODU4MjgxNTA3ZmU1MGFhM2ZiNDEzZmZmYjU2Y2RhMjU1ZGZmOGMxYjA4ZWRmZGU0MDBjNTYzMmUzMjE0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a2ZU76RTu9OlI0zMZPn7y9_RU0yyUuWnxwa65oSeSE0)
> 
> Now in complex boardstates there can be an infinite number of reasons for why the AI might miscalculate, but you should provide specific and reasonable examples rather than making such general claims...

this is not invalid. remove the tag. 
why is there no report function for this kind of behavior?
