### ISSUE TITLE
Can't play the Cards stolen with Outrageous Robbery

### ISSUE THREAD

**Issue by AncientGrief** [Card-Forge/forge#4793]
**Describe the bug**
Outrageous Robbery forces the AI to exile cards from the library. I see them face down in the exile window, on hover I can see the front of the card in the preview, but can't do anything with it.

**Expected behavior**
Being able to click on one of the exiled cards and play them? 

**Screenshots**
![image](https://github.com/Card-Forge/forge/assets/7722670/2d3a37fe-be1e-4c47-914c-0493a9d2517a)

**Desktop (please complete the following information):**
Windows 10

**Comment by GPistre** [comment]
How did you figure it out? It seems I have a similar problem.
