### ISSUE TITLE
Gyox, Brutal Carnivora crashes game

### ISSUE THREAD

**Issue by pfirpfel** [Card-Forge/forge#4812]
**Describe the bug**
Gyox, Brutal Carnivora

> At the beginning of your end step, put an oil counter on up to one target creature.
> 
> Whenever a nontoken creature you control with one or more oil counters on it dies, conjure X duplicates of it into exile, where X is the number of oil counters on it. Those duplicates perpetually get +X/+X. Then shuffle those duplicates into your library.

**To Reproduce**
1. Have Gyox, Brutal Carnivora in play
2. Put an oil counter on another creature
3. Let that creature die
4. Game crashes, see error below

**Screenshots**
![Screenshot_20240309-112905](https://github.com/Card-Forge/forge/assets/621371/21624ada-15f9-4c4a-8113-dc7e60820ab4)

![Screenshot_20240309-112855](https://github.com/Card-Forge/forge/assets/621371/4c940c2c-3a8b-4cac-a71f-4a7fef4c1940)

Version:
Android 1.6.60-SNAPSHOT-03-08

**Comment by tool4ever** [comment]
I feel like it might be best if we just got rid of the timestamp check in `canExiledBy`.
For effects that need it they should already do it themselves and technically costs shouldn't have access to LKI anyway.
