### ISSUE TITLE
Possible cheating with Cryptic Spires

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#4817]
**Describe the bug**
The A.I. cast Ray of Dissolution which is a 3cmc spell, but it only tapped a single Plains and Cryptic Spires. I wonder if it's somehow generating two mana from Cryptic Spires instead of having two colors to choose from?

**Screenshots**
![Screenshot_20240313_014807](https://github.com/Card-Forge/forge/assets/92389638/5c54309b-5e41-44d0-8c83-ad9df162cb69)
![Screenshot_20240313_014823](https://github.com/Card-Forge/forge/assets/92389638/6dcaeb07-5399-4cb2-95d1-3aee875f6367)

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.61-SNAPSHOT-03-10

**Comment by Hanmac** [comment]
i think the main problem is this: #4817

**Comment by Hanmac** [comment]
Closes in favor for #3652
