### ISSUE TITLE
Question on Braid of Fire and Upkeep

### ISSUE THREAD

**Issue by kenjitamura** [Card-Forge/forge#4834]
**Describe the bug**
This is more a question than a bug but I couldn't find any reference in issues or the wiki.  I thought the mana generated by [Braid of Fire](https://scryfall.com/card/csp/78/braid-of-fire) could be used for instants or activated abilities during the upkeep but in Forge it doesn't seem possible in any way I've found.  

If you try to trigger an instant or activated ability before resolving braid of fire it will tap a land.  
When you press resolve it immediately prompts 
"Add: ![Red](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/MTG_%28R%29.svg/32px-MTG_%28R%29.svg.png)?" 
When it's prompting it's not possible to trigger an ability or instant.  
Then as soon as you click "Yes" it proceeds to DR followed by M1.
Never at any point does there seem to be a pause where the red mana is populated in the pool.

**To Reproduce**
Attempt to use an instant or activated ability with the mana from Braid of Fire during the Upkeep step.

**Expected behavior**
After selecting "Yes" a way to spend the mana from Braid of Fire on an instant spell or activated ability.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Java: openjdk 17.0.10

Attribution:
<a href="https://commons.wikimedia.org/wiki/File:MTG_(R).svg">RekonDog</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>, via Wikimedia Commons

**Comment by TheLastNarwhal** [comment]
*If you try to trigger an instant or activated ability before resolving braid of fire it will tap a land.*

Of course it would as you have yet to add the mana from Braid of Fire to your pool, so the only mana source you've got are your lands.

-------
*When you press resolve it immediately prompts
"Add: Red?"
When it's prompting it's not possible to trigger an ability or instant.*

It's not possible to cast spells or activate abilities while you are resolving a spell or ability.

------
*Never at any point does there seem to be a pause where the red mana is populated in the pool.*

You've got to set a stop to be able to cast spells or use abilities during upkeep and it sounds like you've got the upkeep step set to "skip." Once you've told Forge to stop on the upkeep step you can then do all the things you want to do.

**Comment by kenjitamura** [comment]
Thank you!  I missed that the steps could be toggled by clicking.  I was wondering why the game seemed to start pausing on the draw step as I believe I clicked on that one but not upkeep while attempting to use the mana.
