### ISSUE TITLE
MagicStack needs to handle invalid Targets separate

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#4843]
https://github.com/Card-Forge/forge/blob/93a52a4263538910543ad222f20d056a2bcfb388/forge-game/src/main/java/forge/game/zone/MagicStack.java#L653-L684

for cards like "Target Player and Target Card they Control" they become invalid when the Player gets Hexproof because the second part about "they control" get messed up

we need to collect the invalid targets in the loop and then remove all of invalid targets together

(Effects that currently check for "canTarget" should be removed, because the MagicStack already does the stuff)

**Comment by tool4ever** [comment]
Agreed, see #3893

**Comment by Hanmac** [comment]
Ah i knew there was an issue for this, but i didn't found #1179

**Comment by Hanmac** [comment]
i think the main problem there is this part:
https://github.com/Card-Forge/forge/blob/93a52a4263538910543ad222f20d056a2bcfb388/forge-game/src/main/java/forge/game/zone/MagicStack.java#L697-L704

in simple code it does this:
> Check Targets (and Remove invalid)
> Check Sub Ability Targets (and there lies the Problem, because Parent Target might be removed)

what probably should be better would be:
> Check Targets
> Check Sub Ability Targets
> Remove Invalid (and/or have old Targets still in a second Property)

if that's cleaned up, maybe we could remove cases like _The Fall of Kroog_ and `RememberOriginalTargets$`
