### ISSUE TITLE
Canceling Blast Zone Ability Still Adds Charge Counters

### ISSUE THREAD

**Issue by zachbarber** [Card-Forge/forge#4867]
When paying XX to put charge counters on Blast Zone, if the ability is canceled after mana is paid for the XX cost, lands are untapped but the charge counters remain on Blast Zone.

**Steps to Reproduce:**
1. Play Blast Zone
2. Pay XX for "Put X charge counters on Blast Zone."
3. Cancel the ability after mana has been paid for XX
4. Observe that the charge counter amount chosen has been added to Blast Zone, but no mana was spent.

**Expected Behavior:**
Charge counters should not be added to Blast Zone when canceling the ability from the stack.

**Desktop Information:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Desktop Release 1.6.60

**Comment by tool4ever** [comment]
can't reproduce, how are you canceling it when the ability is on the stack?

**Comment by zachbarber** [comment]
Sorry I meant canceling after choosing an amount for XX, but before paying mana and putting it on the stack. Now I can't reproduce this either.
