### ISSUE TITLE
When I open forge, I can't see the window and can only hear the background music

### ISSUE THREAD

**Issue by g-zhima** [Card-Forge/forge#4868]
**Describe the bug**
When I open forge, I can't see the window and can only hear the background music

**Additional context**
logs file：
Forge v.1.6.60 (forge.GuiDesktop@5e600dd5)
Windows 10 (10.0 amd64)
Java Version - 1.0.22_0
Language 'zh-CN' loaded successfully.
(ThreadUtil first call): Running on a machine with 16 cpu core(s)
Read cards: 27644 archived files in 1171 ms (25 parts) using thread pool
Upcoming set Bloomburrow (BLB) dated in the future. All unaccounted cards will be added to this set with unknown rarity.
Upcoming set Bloomburrow (BLB) dated in the future. All unaccounted cards will be added to this set with unknown rarity.
Read cards: 650 files in 30 ms (6 parts) using thread pool
An unsupported card was requested: "Bloodsworn Steward" from "SLD". 

We're sorry, but this card is not supported yet.
An unsupported card was requested: "Boompile" from "SLD". 

We're sorry, but this card is not supported yet.
An unsupported card was requested: "Buried Ruin" from "SLD". 

We're sorry, but this card is not supported yet.
An unsupported card was requested: "Cascade Bluffs" from "SLD". 

We're sorry, but this card is not supported yet.
An unsupported card was requested: "Chance Encounter" from "SLD". 
...

**Comment by tehdiplomat** [comment]
I think this was a specific issue with this release. Please redownload latest.
