### ISSUE TITLE
Retrieve should return both targets simultaneously

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#4962]
Also an issue for:
 - Aether Tradewinds
 - Churning Eddy
 - Crop Sigil
 - probably more

> @tool4ever @Northmoc we probably need to reutrn the cards at the same time?

_Originally posted by @Hanmac in https://github.com/Card-Forge/forge/pull/4947#discussion_r1552051980_

**Comment by tool4ever** [comment]
imo closeable as duplicate of #1182 :P
