### ISSUE TITLE
Quest "prices" are unbalanced

### ISSUE THREAD

**Issue by Serrasmurf** [Card-Forge/forge#4973]
A lot of the prices for quest are currently unbalanced. E.g. you can do a beta quest draft for the standard price of 1777. After the draft you sell your cards for 100000+. In the shop some packs are correctly priced with the input from real world prices, others are too cheap too. 

I played Forge a lot from almost the beginning until a few years ago. I now started again, great it is still out there and being updated and improved! Then it had correct pricing for drafts and all shop items which made quest balanced and challenging. What has changed?

**Comment by paulsnoops** [comment]
I update the card prices quite regularly (using a script; Arena cards without a real world price are estimated) but I have no idea when the last time any other prices were updated for things like boosters, boxes and drafts etc. as they would take manually updating which is something none of the devs have looked at for a while (or really have time for these days) so things may be unbalanced when using real life prices.
