### ISSUE TITLE
OTJ Rules Updates

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5003]
> If the top card of the player’s library changes while a player is taking a special action (see rule 116, “Special Actions”), the new card won’t be revealed and can’t be looked at until the player has finished taking that special action.

This is for Ploting from Library with `Fblthp, Lost on the Range` #4743

>500.10. Some effects add a step after a particular phase. In that case, that effect first creates the phase which normally contains that step directly after the specified phase. Any other steps that phase would normally have are skipped (see rule 500.11).
>Example: Obeka, Splitter of Seconds says, in part, “Whenever Obeka, Splitter of Seconds deals combat damage to a player, you get that many additional upkeep steps after this phase.” After that ability resolves, its controller adds that many beginning phases after this phase. Those new beginning phases have only an upkeep step. The untap steps and draw steps of those phases are skipped.
>**500.10a If an effect that says “you get” an additional step or phase would add a step or phase to a turn other than its controller’s, no steps or phases are added.**

This is for `Obeka, Splitter of Seconds` somehow deals combat damage to opponent while on another turn

@tehdiplomat @tool4ever this is what we need!

>500.12. No game events can occur between steps, phases, or turns.

i wonder what it means

----

> 702.171c A creature “saddles” a permanent as it’s tapped to pay the cost to activate a permanent’s saddle ability.

We need to check if that happens while Activating the Ability, not when the Ability resolves.

See `Crewed` Trigger for the place

----

> 700.2h Some modal spells use plus signs (+) rather than bullet points, with each plus sign followed by a cost. This indicates that each mode has an additional cost that must be paid as the spell is cast if that mode is chosen. If more than one such mode is chosen, all additional costs must be paid to cast that spell. Paying these costs follows the rules for paying additional costs in rules 601.2b and 601.2f–h.

this is not depending on Spree. might be interesting?

> 702.172a Spree is a static ability found on some modal spells (see rule 700.2) that applies while the spell on the stack. Spree means “Choose one or more modes. As an additional cost to cast this spell, pay the costs associated with those modes.”
> 702.172b Cards with the spree ability have a plus sign icon in the upper right corner of the card. This symbol is a visual reminder that this card requires an additional cost to be cast. This icon has no rules meaning.

so it means still only for Spree?

**Comment by dracontes** [comment]
> > 500.12. No game events can occur between steps, phases, or turns.
> 
> i wonder what it means

I think that's chiefly calling back to [late 1990s shenanigans](https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/252330-end-of-turn?comment=6) as people abused loopholes in the game's evolving rule system.

**Comment by Hanmac** [comment]
@tool4ever @Northmoc we need to move the Saddle Trigger to place where Crew does trigger?

> Whenever Stubborn Burrowfiend becomes saddled for the first time each turn, mill two cards, then Stubborn Burrowfiend gets +X/+X until end of turn, where X is the number of creature cards in your graveyard.

from the Rules i think it should be like Crewed?
> 702.171c A creature “saddles” a permanent as it’s tapped to pay the cost to activate a permanent’s saddle ability.

**Comment by tool4ever** [comment]
no
that's for "crews" (payers) which happens on activation
but then "becoming crewed/saddled" is a different trigger (source) - happens on resolution

maybe they did not put that into an extra rule again because the definition of saddling includes it

**Comment by Hanmac** [comment]
@tool4ever i think we completed all of this and this can be closed?
