### ISSUE TITLE
Activated Ability This Turn

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5007]
* Similar to "Cast This Turn", store the Abilities that got activated this turn
* This can help for cleanup of `CycledThisTurn` & `EquippedThisTurn`
* Remove more getParam Checks for `Cycling$ True` and `Equip$ True` and check for their Keywords instead.
* `isCycling` should check for `TypeCycling` Keyword too
* `AlternativeCost.Cycling` can be removed too, 

Then we can use this ActivatedThisTurn List to check for the conditions of the CyclingForZero cards or the ones that does EquipForZero but only on the First Time

**Comment by tool4ever** [comment]
Hmn I guess it can't be avoided
_Tezzeret, Betrayer of Flesh_ will also like it

I wonder if it makes sense to reuse `ActivationTable` for it?
Like I did with DamageHistory, just store the references to all  `Card.numberTurnActivations` globally 🤔

**Comment by Hanmac** [comment]
i don't think ActivationTable would be for something like this
i would want to fill it with LKI information like the Cast List on player.

but i will think about it
