### ISSUE TITLE
MayPlay AltCost defined as {X} shard are calculated too early

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#5044]
Hmn, we do need to transform that statics result better so the {X} is always part of the total cost 🤔 
otherwise you can't use "Spend this mana only on costs that contain {X}." abilities for it...
as also discussed in https://www.reddit.com/r/mtgrules/comments/n9pe1d/kentaro_the_smiling_cat_and_alternate_costs/

_Originally posted by @tool4ever in https://github.com/Card-Forge/forge/issues/5037#issuecomment-2054100044_

**Comment by Hanmac** [comment]
My Solution would be that Kentaro uses `Cost$ X`, but then defines X as CardManaCost

i asked Judges and they told me, that it just sets X=ManaValue, so no tricks with X-Creatures (also Their X should be 0)

**Comment by tool4ever** [comment]
is it always safe if we `setSVar(X)` even on the new SA only or is there risk of SVar collision...?
cast trigger like _Hydroid Krasis_ are probably unaffected, since they would only check the host? 🤔

**Comment by Hanmac** [comment]
> is it always safe if we `setSVar(X)` even on the new SA only or is there risk of SVar collision...? cast trigger like _Hydroid Krasis_ are probably unaffected, since they would only check the host? 🤔

sa.setSVar should be safe i think ...

Rules wise, Kentaro would overwrite the X in the ManaCost with its own Special X ... (for _Hydroid Krasis_ = 2)
but that should also cause the other abilities of _Hydroid Krasis_ to not find the right X value, so for its own abilities, X = 0

**Comment by tool4ever** [comment]
We'll need to look into this again for Combat costs...
CantAttack/BlockUnless static also converts X into generic amount too early

There are two problem cases:

_War Tax_ - this has two different {X} usage but can probably be done with some support param
_Nils, Discipline Enforcer_ this has {X} based on affected attacker, I don't think we have a nice way to pass the value along (currently I need it in HumanPlay for when it builds the final `ManaCostBeingPaid`)

Now if both are in play the attack cost would get merged to {X}{X}? But each shard could have a different value 🤔 ughhh....
