### ISSUE TITLE
Can't finish "Event: Booster Draft" in Adventure Mode

### ISSUE THREAD

**Issue by MRCLVC** [Card-Forge/forge#5052]
**Describe the bug**
In Adventure Mode after the end of a "Draft Mode" round an exception is thrown.

**To Reproduce**
- Go to any city
- Go to the inn
- Start any Event (happened 3 times in different Booster Drafts and 1 time in Jumpstart tournament)
- Note that I have used the starting gold coin to get access to the event
- Draft, complete deck and finish 1 round of tournament
- this exception is thrown:

`EDT > java.lang.NullPointerException: Cannot invoke "forge.adventure.data.AdventureEventData$AdventureEventParticipant.getDeck()" because "this.eventData.nextOpponent" is null
        at forge.adventure.scene.DuelScene.enter(DuelScene.java:309)
        at forge.Forge.switchToLast(Forge.java:1074)
        at forge.adventure.scene.DuelScene.lambda$afterGameEnd$1(DuelScene.java:163)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at forge.app.Main.main(Main.java:134)`

**Expected behavior**
Another round of Draft should happen with the winning opponent from other pairings.

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Using the right arrow button on the bracket table show no second round pairings when you start the Tournament.

**Comment by tehdiplomat** [comment]
@MRCLVC What version of Forge are you on?

**Comment by MRCLVC** [comment]
> @MRCLVC What version of Forge are you on?

Forge v.1.6.62-SNAPSHOT (forge.GuiDesktop@9597028) downloaded 4/16/24

**Comment by jylee4** [comment]
I've seen this before, also on latest snapshots. It doesn't seem reliably reproducible.
