### ISSUE TITLE
Dust Animus condition check seems to be wrong.

### ISSUE THREAD

**Issue by stormcat664** [Card-Forge/forge#5078]
**Describe the bug**
Dust Animus is triggered with five untapped lands, but when cast by AI it was triggered even though AI did not control five or more lands.

**To Reproduce**
1. AI cast Dust Animus
2. See error

**Expected behavior**
Triggered when there are five or more untapped lands.

**Screenshots**
![image](https://github.com/Card-Forge/forge/assets/52299273/cc62dc9d-3d2d-494c-9e93-1df76306e945)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version forge-gui-desktop-1.6.62-SNAPSHOT-04-19

**Comment by dracontes** [comment]
Much appreciated for the report. Turns out it didn't work for the human player either which would be expected since for the most part the scripts work the same for both.
