### ISSUE TITLE
Optional Variable Cost should only be copied from Spell

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5099]
Optional Variable Costs from Keywords:
* Casualty (variable for X)
* Conspire
* Replicate (n-times)
* Squad (n-times, on a permanent)

Currently, they set the values inside their own triggers because if the card has multiple of the same keyword, they should each trigger independently

Also while on the stack, they should be copied when the Spell is copied.
Most of them shouldn't be a problem, because they are Cast triggers, so they don't apply when getting copied on the stack.

but the Problem now is for Squad (its an ETB Trigger)
when something copies the Card with Squad on the Battlefield, the Trigger is copied with the old values too (but it shouldn't).

My idea right now i need to think about more:
* instead of inside the Trigger (and their Ability), 
store the value inside CastSA inside a `KewordInterface => Map<String Key, String Value)` map
and then have the Trigger and their ability get their values from there
* My Current Problem i see with the idea is copySpellHost again, the one time when they should be copied
the copied card gets new Keyword Instances form this too
And right now there is no good way to connect the new Keywords with the old ones (or vice versa)
for it to look into CastSA again

**Comment by tool4ever** [comment]
Since Squad is only done as intrinsic checking for `isUnlinkedFromCastSA` might be good enough

**Comment by Hanmac** [comment]
> Since Squad is only done as intrinsic checking for `isUnlinkedFromCastSA` might be good enough

that fixes it

as for other rewrites, please look at _Chorus of the Conclave_
