### ISSUE TITLE
AI:RemoveDeck:Monocolored or DeckNeeds$Multicolor

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#51]
**Is your feature request related to a problem? Please describe.**
All cards that benefit from multicolored spells currently use `AI:RemoveDeck:All` or `:Random`

**Describe the solution you'd like**
`AI:RemoveDeck:Monocolored`

**Describe alternatives you've considered**
Leave everything as is

**Additional context**
n/a

**Comment by Northmoc** [comment]
@Agetian thought you might have some thoughts here 😉

**Comment by Agetian** [comment]
Can you please provide a couple examples of cards you have in mind?

**Comment by Northmoc** [comment]
_Widespread Thieving_ was one card that sparked this... only one color required to cast it, but it's dead weight if your deck is monocolored unless there are other methods to make. That's when I searched "Whenever you cast a multicolored spell," and saw other cards that have `AI:RemoveDeck:Random` but might get supported more specifically by this:

There are almost surely other cards that care in various ways about multicolored decks beyond this specific trigger type, but even this is an interesting start.

**Monocolored/colorless**
_Tome of the Guildpact
Aurora/Entropic/Enigma/Sandstorm/Verdant Eidolon
Rampaging Monument
Hero of Precinct One
Pyroconvergence
Lobber Crew_ this one has no RemoveDeck - very interesting card

**Multicolored**
_General Ferrous Rokiric_ this one has `RemoveDeck:Random` but may need that since its identity is RW
_Gloryscale Viashino_ this one has no RemoveDeck

**New wrinkles**
_Paragon of Modernity_ and _Meeting of the Five_ really want a three (or more) color deck, though that may be a different issue. Meeting of the Five may just be a `RemoveDeck:All` though... probably just a bad card 😆

**Comment by tehdiplomat** [comment]
Maybe DeckNeeds:Multicolor?
