### ISSUE TITLE
Sheoldred Apocalypse combo with Necropotence doesn't work

### ISSUE THREAD

**Issue by Blood-sun** [Card-Forge/forge#5166]
**Describe the bug**
When Sheoldred apocalypse on board, when Resolving the triggers of necropotence to draw card, we don't gain 2 Life (minus 1) each draw made. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tool4ever** [comment]
_Necropotence_ does not make you draw any cards. So there is no trigger event for _Sheoldred_.
