### ISSUE TITLE
card name errors

### ISSUE THREAD

**Issue by y12345e** [Card-Forge/forge#5173]
card name errors:

forge card name                             mtg card name
Wibbly-Wobbly, Timey-Wimey       Wibbly-wobbly, Timey-wimey
Stormcaller                                      Stormcaller's Boon
Pillage The Bog                               Pillage the Bog
Mageta                                            Mageta's Boon
Historian                                          Historian's Boon
Gryff                                                Gryff's Boon
Coming in Hot                                Coming In Hot
Calix, Guided By Fate                      Calix, Guided by Fate

For example
![image](https://github.com/Card-Forge/forge/assets/6188425/6141cd3a-05e3-4c57-aa4c-5f3397c6f9ec)

**Comment by tool4ever** [comment]
I've updated the scripts except for those "Boon" ones
I don't see what's wrong with them?

**Comment by y12345e** [comment]
> I've updated the scripts except for those "Boon" ones I don't see what's wrong with them?
language is zh-CN
![Uploading A0BD24BB-6DD9-4817-8BC5-D45CFAD80396.png…]()
