### ISSUE TITLE
Vexyr, Ich-Tekik's Heir triggering from inside the deck.

### ISSUE THREAD

**Issue by corwin72** [Card-Forge/forge#5192]
**Describe the bug**
Vexyr, Ich-Tekik's Heir triggering from inside the deck.

**To Reproduce**
Include Vexyr, Ich-Tekik's Heir in your deck. Not on the battlefield. 
Play a card that uses the function seek.
A 3/3 colorless Phyrexian Golem will be created.

**Expected behavior**
Vexyr, Ich-Tekik's Heir should only trigger while on the battlefield.

**Additional context**
Issue found in:
forge-gui-desktop-1.6.63-SNAPSHOT-04-29

**Comment by dracontes** [comment]
Much obliged for the bug report 👍 It's fixed.
