### ISSUE TITLE
Cannot order multiple Captured by the Consulate triggers

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5235]
**Describe the bug**
I am unable to properly order the triggers when I control multiple Captured by the Consulate. They just get added to the stack automatically.

**Ruling:** *If there is more than one Captured by the Consulate on the battlefield, the triggered ability of each one will change the target if able. The last one to resolve determines what that spell finally targets. If one player controls more than one Capture by the Consulate, they choose the order in which they resolve. If multiple players control those Auras, the first player among them in turn order (starting with the player whose turn it is now) is the one whose triggered ability resolves last.*

**Expected behavior**
When you control multiple Captured by the Consulate and they trigger, you are able to order them on the stack as you please.

**Screenshots**
Doesn't really show much beyond the triggers being on the stack, but I never got a prompt for their order.
![Screenshot_20240513_164551 cleaned](https://github.com/Card-Forge/forge/assets/92389638/006a328f-f839-467a-8b3f-fead3fa8599d)

**Desktop (please complete the following information):**
 - Version: forge-gui-desktop-1.6.63-SNAPSHOT-05-12

**Comment by TheLastNarwhal** [comment]
Okay, so now that I have four copies I am suddenly able to order them.

 Maybe the issue occured because I had each of the auras targeting a creature controlled by a separate opponent, but now that I have two Captured by the Consulate(s) targeting creatures the same opponent controls it recognizes that I can order them?

![Screenshot_20240513_170409 cleaned](https://github.com/Card-Forge/forge/assets/92389638/495cc282-e33a-47ef-92dc-9852afb1d1e2)

**Comment by Hanmac** [comment]
I think there is an option that it doesn't ask the Player to order Triggers when all of them are the same Description

check the Game Settings

**Comment by TheLastNarwhal** [comment]
> I think there is an option that it doesn't ask the Player to order Triggers when all of them are the same Description
> 
> check the Game Settings

I don't believe that this setting exists. The only thing that seems similar, and might be what you're thinking of, is: 
**Preselect Last Order of Abilities:** *When enabled, preselects the last defined simultaneous ability order in the ordering dialog.*

This should still open the ordering dialoge for you every time though. The only difference will be that they will be auto ordered and already on the right-hand side, so you just click okay if you don't want to change anything.
