### ISSUE TITLE
Doubling Season with Double Major failure

### ISSUE THREAD

**Issue by JohnyDL** [Card-Forge/forge#5264]
**Describe the bug**
Used Double Major to make a non-legendary Token copy of a creature, Doubling Season didn't trigger it's replacement effect

**To Reproduce**
Play Double Major, then play a Legendary Creature, and while it's still on the stack play Double Major. See 1 token created

**Expected behavior**
2 Tokens should have entered the battle field not 1

**Desktop (please complete the following information):**
Desktop, Windows 10, 1.6.62

**Additional context**
Don't know if it matters but the Legendary Card I played was Vorinclex, Monstrous Raider no cards that the opponents played interact with enchantments or tokens.
Given this is a replacement effect that triggers on Tokens it might be related to #5176

**Comment by tool4ever** [comment]
Nah that's not how it works - this is also what the ruling on such cards tries to clarify:
> The token that a resolving copy of a spell becomes isn’t said to have been “created.”
