### ISSUE TITLE
Bruenor Battlehammer's 'First Equip ability costs 0' ability not working.

### ISSUE THREAD

**Issue by Ronanob** [Card-Forge/forge#5275]
**Describe the bug**
Hey there,
Bruenor Battlehammer's ability "You may pay 0 rather than pay the equip cost of the first equip ability you activate each turn." does not work currently.

**To Reproduce**
1. Have Bruenor and an equipment down on the battlefield.
2. Click on the equipment to start the equip ability.
3. Notice that it automatically asks to pay mana, rather than give the popup to use Bruenor's ability.

**Expected behavior**
A small popup window should appear when clicking on the equipment and list Bruenor's ability as a possibility.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by tool4ever** [comment]
already fixed by #5223
