### ISSUE TITLE
Bug with cards granting other cards alternate cast options (for lack of a better term)

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5293]
**Describe the bug**
I have Haakon, Stromgald Scourge + Ashes of the Fallen (on knight) + Six (which gives permanents in my graveyard retrace) on the field. I'm trying to cast Ayara, First of Locthwain from my graveyard using Haakon, but no matter which choice I select, even the one that specifically says "by Haakon," it forces me to use retrace.

**To Reproduce**
1. Haakon, Stromgald Scourge + Ashes of the Fallen (on knight) + Six on the field
2. Any creature in the graveyard (I assume it's not only Ayara)
3. Attempt to cast using Haakon

**Expected behavior**
To be able to pick and choose which alternate cast method I use.

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.63-SNAPSHOT-05-23

**Comment by tool4ever** [comment]
It is not supposed to work:
https://www.reddit.com/r/EDH/comments/xy3yr8/psa_ashes_of_the_fallen_does_not_work_with_haakon/

**Comment by TheLastNarwhal** [comment]
Oh, appologies. I wasn't aware of that distinction.
