### ISSUE TITLE
Issue with Scapeshift placing lands sequentially not simultaneously

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5299]
**Describe the bug**
It seems as though Scapeshift is placing the lands on the field in order of how you selected them, instead of all at the same time and for some cards this kind of "breaks" them. 

An example of this would be where I selected five lands in this order: **Lake of the Dead, Windswept Heath, Urborg, Tomb of Yawgmoth, Underground Mortuary, Field of the Dead**. In theory I should've been able to select any of the lands to sacrifice to Lake of the Dead due to Urborg, but in case that's wrong, at the very least I should've been able to select Underground Mortuary. However what happens is that Lake of the Dead just goes straight to the graveyard, because it enters first when no other lands are on the field due to Scapeshift placing the lands sequentially and not simultaneously.

The odd thing is that Field of the Dead works correctly even if it's chosen last. So if you sacrifice 7 lands and have Field of the Dead enter last, you still get 7 triggers.

**Expected behavior**
For the lands to enter at the same time.

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.63-SNAPSHOT-05-23

**Comment by tool4ever** [comment]
Indeed the lands ETB simultaneously but you're wrong to assume this means they'll all be available as a sacrifice.
Rather since the ability of _Lake of the Dead_ is a replacement effect it will be processed before any have entered.
So for the order you proposed Forge already behaves correctly.

However this is tricky to get right and if you switch the order to select other candidates first you'd be able to (illegally) keep it in play.

@Hanmac
Can't we just fix this by using LastStateBattlefield here?

**Comment by TheLastNarwhal** [comment]
> Rather since the ability of Lake of the Dead is a replacement effect it will be processed before any have entered.

So, this means that Lake of the Dead will always go to the graveyard if there isn't already a swamp on the field for it to sacrifice? If that's the case, then I guess there's another issue, because if have 4 (example number) lands, sacrifice all of them to Scapeshift and then select Swamp, Lake of the Dead, Land, Land as the order. I will be able to sacrifice the Swamp to Lake of the Dead since it enters first.

**Comment by Hanmac** [comment]
@tool4ever the Replacement Effect of _Lake of the Dead_ should need to use LastStateBattlefield to check which Lands can be sacrificed.

so you should not be able to sacrifice lands that enter at the same time as _Lake of the Dead_ (that's the thing that is probably broken right now)

what we also need to change (i don't know if that works yet), is that you probably can't sacrifice lands that weren't Swamps before _Urborg, Tomb of Yawgmoth_ entered the battlefield.
