### ISSUE TITLE
Bug with Synth Eradicator

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5351]
**Describe the bug**
When you attack with Synth Eradicator and decline to receive the energy counters you are unable to play the exiled card.

**Expected behavior**
When you attack with Synth Eradicator, exile the top of your library, and then decline the energy counters you should be able to play the exiled card.

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.63-SNAPSHOT-05-31

**Comment by tool4ever** [comment]
"You **may** get {E}{E} (two energy counters). **If you don't**"

?
