### ISSUE TITLE
Creating Named Token by Card Name

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5416]
> 111.11. If an effect instructs a player to create a token by name, **doesn’t define any other characteristics for that token**, and the name is not one of the types in the list of predefined tokens above, that player uses the card with that name in the Oracle card reference to determine the characteristics of that token.
> Example: Disa the Restless has the ability “Whenever one or more creatures you control deal combat damage to a player, create a Tarmogoyf token.” As that ability resolves, its controller creates a token with the same characteristics as the card named Tarmogoyf, as determined by the Oracle card reference.

For now, we could keep our Token Scripts, but that is the difference between:
* Create a Tarmagoyf token. (has mana cost)
* Create a 1/1 white Kithkin Soldier creature token named Goldmeadow Harrier. It has "{W}, Tap: Tap target creature." (has no mana cost)

Also, Tarmagoyf token should not be affected by Card Text Changes. So they should be marked with `LockTokenScript`

**Comment by tehdiplomat** [comment]
We're chatting in discord. There probably isn't really anything to do here except utilize existing script syntax;

`CopyPermanent | DefinedName$`

**Comment by Hanmac** [comment]
We still might need to update CopyPermanentEffect that we don't need ValidSupportedCopy when using DefinedName

that code piece is a leftover from `Momir Vig, Simic Visionary Avatar`
