### ISSUE TITLE
This app needs jumpstart mode

### ISSUE THREAD

**Issue by JustNaggy** [Card-Forge/forge#5445]
I know in adventure mode it starts with a jumpstart pack of our choice but i usualy play in normal mode. I want a quick jumpstart play mode that gave me and opponent 2 completely random boosters from jumpstart set of our choice and let us play. That set designed this way. Please

**Comment by tehdiplomat** [comment]
You can do this already in Sealed Deck.

**Comment by JustNaggy** [comment]
> You can do this already in Sealed Deck.

No, it doesnt work on android version latest snapshot
