### ISSUE TITLE
Game crashes when rendering some card in the adventure mode deck editor.

### ISSUE THREAD

**Issue by Galadorn** [Card-Forge/forge#5459]
**Describe the bug**
Rendering a certain card (I don't know exactly which card). Causes the deck editor to crash in adventure mode.
Since I don't know the exact card causing it I can't check if the problem exists on other deck editor views.
I have narrowed it down to a multicolor creature card.

**To Reproduce**
1. Load the attached adventure mode save file.
[quick_save.zip](https://github.com/user-attachments/files/15945119/quick_save.zip)
3. Open the deck editor.
4. Then scroll down until the card is to be rendered.
5. Program crashes with attached crash log.
[forge0.log](https://github.com/user-attachments/files/15945121/forge0.log)

Alternatively:
1. Load the attached adventure mode save file.
[quick_save.zip](https://github.com/user-attachments/files/15945119/quick_save.zip)
2. Open the deck editor.
3. Disable display of multicolor cards. So you don't accidentally render the card causing the crash while disabling other filters.
4. Disable display of all other cards.
6. Activate multicolor cards
7. Activate creatures
8. Program crashes with attached crash log.
[forge0.log](https://github.com/user-attachments/files/15945121/forge0.log)

**Expected behavior**
The card should be rendered properly and not crash the program.

**Desktop:**
 - OS: Windows 11
 - Forge Version: Forge 1.6.63-SNAPSHOT-06-22 22-Jun-2024 18:38 

Thanks for your hard work. :)

**Comment by Hanmac** [comment]
> EDT > java.lang.RuntimeException: Element Discard not found in ReplacementType enum
	at forge.game.replacement.ReplacementType.smartValueOf(ReplacementType.java:64)
	at forge.game.replacement.ReplacementHandler.parseReplacement(ReplacementHandler.java:843)
	at forge.game.replacement.ReplacementHandler.parseReplacement(ReplacementHandler.java:828)
	at forge.game.card.CardFactory.readCardFace(CardFactory.java:367)


3 months ago, Replace Discard was removed (#4833)

you still have cards in your cardscripts referring to this

that probably happens when you don't update your cards correctly

**Comment by Galadorn** [comment]
Thanks for the response, I'll see if I can fix it otherwise I'll just make a clean install and start a new save.

**Comment by Hanmac** [comment]
@Galadorn I don't know the save file structure for adventure, but I don't think it saves the whole card script in them

so if you do a fresh Installation from the game, you should be able to load your save file

**Comment by Galadorn** [comment]
@Hanmac There was something wrong with my installation. After a clean reinstall everything works  as it should.
