### ISSUE TITLE
Ordering the top of player's library  sometimes works incorrectly

### ISSUE THREAD

**Issue by dusan-madzarevic** [Card-Forge/forge#5466]
**Describe the bug**
When using effects which allow you to order the top X cards of your library, after the screen where you sort them starting with "closest to top", the cards will sometimes be in incorrect order. This seems to happen consistently with Brainstorm and Brainsurge

**To Reproduce**
Here is my most recent example

1. Cast Brainsurge from hand
2. Choose Echo of Eons and Heliod's Intervention to put back
3. On the order screen, order so that Echo of Eons is "Closest to top"
4. Activate Elminster's -3 ability, exiling Heliod's Intervention 

**Expected behavior**
The expected behaviour is to have the card I selected as "Closest to top" be the one actually on top of the library

**Screenshots**
![Screenshot_2024-06-26-11-39-57-425_forge.app.jpg](https://github.com/Card-Forge/forge/assets/43146662/88d7d688-e652-4c13-b4fd-0853591dd010)

![Screenshot_2024-06-26-11-39-35-579_forge.app.jpg](https://github.com/Card-Forge/forge/assets/43146662/b9008998-3708-45ef-959a-7a33abbc6794)

![Screenshot_2024-06-26-11-40-14-808_forge.app.jpg](https://github.com/Card-Forge/forge/assets/43146662/c6705bf2-6dd1-4c82-90bc-818469bee383)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 12 pro 
 - OS: Android 11
 - Version: 1.6.63-SNAPSHOT-06-15

**Additional context**
This might be intended behavior, but in that case I think it's unintuitive for the card that you selected as "Closest to top" to not actually end up being closest to top

**Comment by Jetz72** [comment]
Not able to verify right now but at a glance, looks like ChangeZoneEffect [doesn't reverse the list](https://github.com/Card-Forge/forge/blob/5fc6d3895409e1f63a7f4d1473c3978883e64ef1/forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java#L522) before putting the cards into the library, whereas other effects that move lots of cards to the library usually do? (e.g. [ChangeZoneAllEffect](https://github.com/Card-Forge/forge/blob/5fc6d3895409e1f63a7f4d1473c3978883e64ef1/forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java#L96), [ReorderTopOfLibraryEffect](https://github.com/Card-Forge/forge/blob/5fc6d3895409e1f63a7f4d1473c3978883e64ef1/forge-game/src/main/java/forge/game/ability/effects/RearrangeTopOfLibraryEffect.java#L110))?
