### ISSUE TITLE
Combo thespian's stage and dark depths not working

### ISSUE THREAD

**Issue by marnixnaber** [Card-Forge/forge#5502]
Combo of thespian's stage and dark depths is not working.

1. Play commander against AI with the cards [[dark depths]] and [[thespian's stage]] and 2 [[wastes]] in my draw hand. 
2. I first played the wastes in turn one and two.
3. I then played [[dark depths]] in the third turn and [[thespian's stage]] in the fourth turn. 
4. Then I activated the ability of [[thespian's stage]] by paying to and it became a copy of [[dark depths]]. 
5. Then I had to sacrifice [[dark depths]] (not the copy of [[thespian's stage]])
6. Then I was left with the copy of [[thespian's stage]], but it still had the 10 ice counters on it. BUG: the counters should not be copied when a copy is made from a permanent (this is a famous combo that is currently not working in forge).

Desktop, java forge, windows 

LOG:
Match result: Rismak: 1 Marnix: 0 
Game outcome: Marnix has conceded
Game outcome: Rismak has won because all opponents have lost
Game outcome: Turn 6
Player control: Rismak is controlled by Rismak
Player control: Marnix is controlled by Marnix
Phase: Marnix's Beginning of Combat Step
Resolve stack: When Dark Depths has no ice counters on it, sacrifice it. If you do, create Marit Lage, a legendary 20/20 black Avatar creature token with flying and indestructible.
Add to stack: Marnix triggered Dark Depths (20)
Resolve stack: Dark Depths (20) - Dark Depths (20) becomes a copy of Dark Depths (74).
Add to stack: Marnix activated Thespian's Stage (20) targeting [Dark Depths (74)][Dark Depths (74)]
Mana: Wastes (14) - {T}: Add {C}.
Mana: Reliquary Tower (26) - {T}: Add {C}.
Land: Marnix played Urza's Cave (24)
Replacement Effect: You may have Echoing Deeps enter the battlefield tapped as a copy of any land card in a graveyard, except it's a Cave in addition to its other types.
Phase: Marnix's Main phase, precombat
Phase: Marnix's Draw step
Phase: Marnix's Upkeep step
Phase: Marnix's Untap step
Turn: Turn 12 (Marnix)
Phase: Rismak's Cleanup step
Phase: Rismak's End step
Resolve stack: Endless Atlas
Add to stack: Rismak cast Endless Atlas (128)
Mana: Swamp (181) - {T}: Add {B}.
Mana: Polluted Mire (125) - {T}: Add {B}.
Resolve stack: Phalanx Commander — When Royal Warden enters the battlefield, create two tapped 2/2 black Necron Warrior artifact creature tokens. [Zone Changer: Royal Warden (197)]
Add to stack: Rismak triggered Royal Warden (197)
Resolve stack: Royal Warden - Creature 3 / 2
Add to stack: Rismak cast Royal Warden (197)
Mana: Barren Moor (131) - {T}: Add {B}.
Mana: Swamp (180) - {T}: Add {B}.
Mana: Arcane Signet (150) - {T}: Add one mana of any color in your commander's color identity.
Land: Arcane Signet effect's value for Arcane Signet (150) is Rismak picked B
Mana: Swamp (160) - {T}: Add {B}.
Mana: Swamp (167) - {T}: Add {B}.
Phase: Rismak's Main phase, postcombat
Phase: Rismak's End of Combat Step
Damage: Szarekh, the Silent King (201) deals 3 combat damage to Marnix.
Phase: Rismak's Combat Damage Step
Phase: Rismak's First Strike Damage Step
Combat: Marnix didn't block Szarekh, the Silent King (201).
Phase: Rismak's Declare Blockers Step
Resolve stack: My Will Be Done — Whenever Szarekh, the Silent King attacks, mill three cards. You may put an artifact creature card or Vehicle card from among the cards milled this way into your hand. [Attacker: Szarekh, the Silent King (201)]
Zone Change: Rismak milled Imotekh the Stormlord (127), Swamp (159) and Swamp (161).
Add to stack: Rismak triggered Szarekh, the Silent King (201)
Combat: Rismak assigned Szarekh, the Silent King (201) to attack Marnix.
Phase: Rismak's Declare Attackers Step
Phase: Rismak's Beginning of Combat Step
Land: Rismak played Swamp (181)
Phase: Rismak's Main phase, precombat
Phase: Rismak's Draw step
Phase: Rismak's Upkeep step
Phase: Rismak's Untap step
Turn: Turn 11 (Rismak)
Phase: Marnix's Cleanup step
Phase: Marnix's End step
Phase: Marnix's Main phase, postcombat
Phase: Marnix's End of Combat Step
Phase: Marnix's Combat Damage Step
Phase: Marnix's First Strike Damage Step
Phase: Marnix's Declare Blockers Step
Combat: Marnix didn't attack this turn.
Phase: Marnix's Declare Attackers Step
Phase: Marnix's Beginning of Combat Step
Resolve stack: Urza's Cave (23) - Marnix searches their library for a land card, puts it onto the battlefield tapped, then shuffles.
Replacement Effect: Dark Depths enters the battlefield with ten ice counters on it.
Add to stack: Marnix activated Urza's Cave (23)
Mana: Thespian's Stage (20) - {T}: Add {C}.
Mana: Wastes (14) - {T}: Add {C}.
Mana: Reliquary Tower (26) - {T}: Add {C}.
Phase: Marnix's Main phase, precombat
Phase: Marnix's Draw step
Phase: Marnix's Upkeep step
Phase: Marnix's Untap step
Turn: Turn 10 (Marnix)
Phase: Rismak's Cleanup step
Phase: Rismak's End step
Land: Rismak played Polluted Mire (125)
Replacement Effect: Polluted Mire enters the battlefield tapped.
Phase: Rismak's Main phase, postcombat
Phase: Rismak's End of Combat Step
Damage: Szarekh, the Silent King (201) deals 3 combat damage to Marnix.
Phase: Rismak's Combat Damage Step
Phase: Rismak's First Strike Damage Step
Combat: Marnix didn't block Szarekh, the Silent King (201).
Phase: Rismak's Declare Blockers Step
Resolve stack: My Will Be Done — Whenever Szarekh, the Silent King attacks, mill three cards. You may put an artifact creature card or Vehicle card from among the cards milled this way into your hand. [Attacker: Szarekh, the Silent King (201)]
Zone Change: Rismak milled Cryptothrall (112), Swamp (155) and Necron Overlord (144).
Add to stack: Rismak triggered Szarekh, the Silent King (201)
Combat: Rismak assigned Szarekh, the Silent King (201) to attack Marnix.
Phase: Rismak's Declare Attackers Step
Phase: Rismak's Beginning of Combat Step
Phase: Rismak's Main phase, precombat
Resolve stack: Lychguard (109) -  Return all legendary creature cards from your graveyard to your hand.
Add to stack: Rismak activated Lychguard (109)
Mana: Swamp (180) - {T}: Add {B}.
Mana: Arcane Signet (150) - {T}: Add one mana of any color in your commander's color identity.
Land: Arcane Signet effect's value for Arcane Signet (150) is Rismak picked B
Mana: Swamp (160) - {T}: Add {B}.
Mana: Swamp (167) - {T}: Add {B}.
Phase: Rismak's Draw step
Phase: Rismak's Upkeep step
Phase: Rismak's Untap step
Turn: Turn 9 (Rismak)
Phase: Marnix's Cleanup step
Phase: Marnix's End step
Phase: Marnix's Main phase, postcombat
Phase: Marnix's End of Combat Step
Phase: Marnix's Combat Damage Step
Phase: Marnix's First Strike Damage Step
Phase: Marnix's Declare Blockers Step
Combat: Marnix didn't attack this turn.
Phase: Marnix's Declare Attackers Step
Phase: Marnix's Beginning of Combat Step
Resolve stack: Urza's Cave (50) - Marnix searches their library for a land card, puts it onto the battlefield tapped, then shuffles.
Add to stack: Marnix activated Urza's Cave (50)
Mana: Urza's Cave (23) - {T}: Add {C}.
Mana: Wastes (14) - {T}: Add {C}.
Mana: Reliquary Tower (26) - {T}: Add {C}.
Land: Marnix played Wastes (14)
Phase: Marnix's Main phase, precombat
Phase: Marnix's Draw step
Phase: Marnix's Upkeep step
Phase: Marnix's Untap step
Turn: Turn 8 (Marnix)
Phase: Rismak's Cleanup step
Phase: Rismak's End step
Resolve stack: Lychguard - Creature 2 / 3
Add to stack: Rismak cast Lychguard (109)
Mana: Arcane Signet (150) - {T}: Add one mana of any color in your commander's color identity.
Land: Arcane Signet effect's value for Arcane Signet (150) is Rismak picked B
Mana: Swamp (160) - {T}: Add {B}.
Mana: Swamp (167) - {T}: Add {B}.
Land: Rismak played Barren Moor (131)
Replacement Effect: Barren Moor enters the battlefield tapped.
Phase: Rismak's Main phase, postcombat
Phase: Rismak's End of Combat Step
Damage: Szarekh, the Silent King (201) deals 3 combat damage to Marnix.
Phase: Rismak's Combat Damage Step
Phase: Rismak's First Strike Damage Step
Combat: Marnix didn't block Szarekh, the Silent King (201).
Phase: Rismak's Declare Blockers Step
Resolve stack: My Will Be Done — Whenever Szarekh, the Silent King attacks, mill three cards. You may put an artifact creature card or Vehicle card from among the cards milled this way into your hand. [Attacker: Szarekh, the Silent King (201)]
Zone Change: Rismak milled Swamp (158), Sol Ring (138) and Royal Warden (197).
Add to stack: Rismak triggered Szarekh, the Silent King (201)
Combat: Rismak assigned Szarekh, the Silent King (201) to attack Marnix.
Phase: Rismak's Declare Attackers Step
Phase: Rismak's Beginning of Combat Step
Phase: Rismak's Main phase, precombat
Phase: Rismak's Draw step
Phase: Rismak's Upkeep step
Phase: Rismak's Untap step
Turn: Turn 7 (Rismak)
Phase: Marnix's Cleanup step
Phase: Marnix's End step
Phase: Marnix's Main phase, postcombat
Phase: Marnix's End of Combat Step
Phase: Marnix's Combat Damage Step
Phase: Marnix's First Strike Damage Step
Phase: Marnix's Declare Blockers Step
Combat: Marnix didn't attack this turn.
Phase: Marnix's Declare Attackers Step
Phase: Marnix's Beginning of Combat Step
Land: Marnix played Urza's Cave (50)
Replacement Effect: You may have Vesuva enter the battlefield tapped as a copy of any land on the battlefield.
Phase: Marnix's Main phase, precombat
Phase: Marnix's Draw step
Phase: Marnix's Upkeep step
Phase: Marnix's Untap step
Turn: Turn 6 (Marnix)
Phase: Rismak's Cleanup step
Phase: Rismak's End step
Resolve stack: Szarekh, the Silent King - Creature 3 / 4
Add to stack: Rismak cast Szarekh, the Silent King (201)
Mana: Swamp (180) - {T}: Add {B}.
Mana: Arcane Signet (150) - {T}: Add one mana of any color in your commander's color identity.
Land: Arcane Signet effect's value for Arcane Signet (150) is Rismak picked B
Mana: Swamp (160) - {T}: Add {B}.
Mana: Swamp (167) - {T}: Add {B}.
Phase: Rismak's Main phase, postcombat
Phase: Rismak's End of Combat Step
Phase: Rismak's Combat Damage Step
Phase: Rismak's First Strike Damage Step
Phase: Rismak's Declare Blockers Step
Combat: Rismak didn't attack this turn.
Phase: Rismak's Declare Attackers Step
Phase: Rismak's Beginning of Combat Step
Land: Rismak played Swamp (180)
Phase: Rismak's Main phase, precombat
Phase: Rismak's Draw step
Phase: Rismak's Upkeep step
Phase: Rismak's Untap step
Turn: Turn 5 (Rismak)
Phase: Marnix's Cleanup step
Phase: Marnix's End step
Phase: Marnix's Main phase, postcombat
Phase: Marnix's End of Combat Step
Phase: Marnix's Combat Damage Step
Phase: Marnix's First Strike Damage Step
Phase: Marnix's Declare Blockers Step
Combat: Marnix didn't attack this turn.
Phase: Marnix's Declare Attackers Step
Phase: Marnix's Beginning of Combat Step
Land: Marnix played Reliquary Tower (26)
Phase: Marnix's Main phase, precombat
Phase: Marnix's Draw step
Phase: Marnix's Upkeep step
Phase: Marnix's Untap step
Turn: Turn 4 (Marnix)
Phase: Rismak's Cleanup step
Phase: Rismak's End step
Resolve stack: Arcane Signet
Add to stack: Rismak cast Arcane Signet (150)
Mana: Swamp (160) - {T}: Add {B}.
Mana: Swamp (167) - {T}: Add {B}.
Phase: Rismak's Main phase, postcombat
Phase: Rismak's End of Combat Step
Phase: Rismak's Combat Damage Step
Phase: Rismak's First Strike Damage Step
Phase: Rismak's Declare Blockers Step
Combat: Rismak didn't attack this turn.
Phase: Rismak's Declare Attackers Step
Phase: Rismak's Beginning of Combat Step
Land: Rismak played Swamp (160)
Phase: Rismak's Main phase, precombat
Phase: Rismak's Draw step
Phase: Rismak's Upkeep step
Phase: Rismak's Untap step
Turn: Turn 3 (Rismak)
Phase: Marnix's Cleanup step
Phase: Marnix's End step
Phase: Marnix's Main phase, postcombat
Phase: Marnix's End of Combat Step
Phase: Marnix's Combat Damage Step
Phase: Marnix's First Strike Damage Step
Phase: Marnix's Declare Blockers Step
Combat: Marnix didn't attack this turn.
Phase: Marnix's Declare Attackers Step
Phase: Marnix's Beginning of Combat Step
Land: Marnix played Urza's Cave (23)
Phase: Marnix's Main phase, precombat
Phase: Marnix's Draw step
Phase: Marnix's Upkeep step
Phase: Marnix's Untap step
Turn: Turn 2 (Marnix)
Phase: Rismak's Cleanup step
Phase: Rismak's End step
Phase: Rismak's Main phase, postcombat
Phase: Rismak's End of Combat Step
Phase: Rismak's Combat Damage Step
Phase: Rismak's First Strike Damage Step
Phase: Rismak's Declare Blockers Step
Combat: Rismak didn't attack this turn.
Phase: Rismak's Declare Attackers Step
Phase: Rismak's Beginning of Combat Step
Land: Rismak played Swamp (167)
Phase: Rismak's Main phase, precombat
Phase: Rismak's Draw step
Phase: Rismak's Upkeep step
Phase: Rismak's Untap step
Turn: Turn 1 (Rismak)
Mulligan: Marnix has kept a hand of 6 cards
Mulligan: Rismak has kept a hand of 7 cards
Mulligan: Marnix has mulliganed down to 6 cards.

**Comment by TheLastNarwhal** [comment]
@marnixnaber

I'm using *forge-gui-desktop-1.6.64-SNAPSHOT-06-28* and the combo works perfectly fine. I'm guessing that you accidentally clicked the original Dark Depths when asked which one you wanted to stay on the field.

**Comment by marnixnaber** [comment]
Oh shit, I think you are totally right! I am sorry for letting you check this false bug.
