### ISSUE TITLE
Tarmogoyf was not destroyed properly

### ISSUE THREAD

**Issue by leebailey88** [Card-Forge/forge#5537]
**Describe the bug**
I had a 2/3 Tarmogoyf due to a creature and sorcery being in the graveyards. The AI targeted it with Incinerate. I did not interact with the stack further and ended turn. Tarmogoyf was not destroyed as the Incinerate seemed to go to the graveyard before the lethal damage check.

**To Reproduce**
1. Load a deck with Tarmogoyf
2. Get it to 2/3 with no instants in the GY
3. Target it with a 3 damage instant, 
4. See that Tarmogoyf survives

**Expected behavior**
Tarmogoyf should die.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Forge-1.6.63

**Comment by TheLastNarwhal** [comment]
So, I'll give you a pass here and assume you're newish to the game, because that's an infamous Tarmogoyf interaction. 

What happened is that you had a sorcery and creature in the graveyard, making Tarmogoyf a 2/3, then when Incinerate resolved an instant was added to the graveyard. Tarmogoyf was then a 3/4 with 3 damage marked on it.

>**Ruling:** *If an instant or sorcery spell deals damage to Tarmogoyf or lowers its toughness, that spell is put into its owner's graveyard before state-based actions are performed. If that card is the first of its type to enter a graveyard, it will raise Tarmogoyf's toughness before the game checks to see if Tarmogoyf dies. (2021-03-19)*

@leebailey88

**Comment by leebailey88** [comment]
Interesting, I thought that may be the case. I suppose ChatGPT is wrong then:

Is lethal damage checked before the instant goes to the graveyard?

> ChatGPT
> In Magic: The Gathering, state-based actions, including the check for lethal damage, occur immediately after a spell or ability resolves, but before any player receives priority. The sequence of events is crucial to understanding how damage and graveyard state interact with Tarmogoyf's power and toughness.
> 
> Sequence of Events in Detail
> Casting Incinerate: Your opponent casts Incinerate, targeting Tarmogoyf.
> Incinerate Resolves: Incinerate deals 3 damage to Tarmogoyf.
> State-Based Actions: State-based actions are checked immediately after Incinerate resolves but before Incinerate goes to the graveyard.
> Important Points
> Tarmogoyf's Toughness Calculation: Tarmogoyf's toughness is determined by the number of card types in all graveyards. At the moment Incinerate deals damage, it hasn't gone to the graveyard yet, so the number of card types remains unchanged.
> Damage Application: Tarmogoyf will have 3 damage marked on it from Incinerate.
> State-Based Actions: After Incinerate resolves and before it goes to the graveyard, state-based actions check for lethal damage. Tarmogoyf, with 3 damage marked and a toughness of 3, will be destroyed due to lethal damage.
> Final Sequence
> Incinerate targets Tarmogoyf and resolves.
> 3 damage is marked on Tarmogoyf.
> State-based actions check for lethal damage: Tarmogoyf is a 2/3 with 3 damage marked on it.
> Tarmogoyf is destroyed due to lethal damage.
> Incinerate is put into the graveyard.
> Conclusion
> Tarmogoyf's toughness is checked for lethal damage before Incinerate goes to the graveyard. Therefore, at the time state-based actions are checked, Tarmogoyf remains a 2/3 (since Incinerate is not yet in the graveyard to add another card type), and it will indeed die from the 3 damage dealt by Incinerate.
>

**Comment by TheLastNarwhal** [comment]
> I suppose ChatGPT is wrong then:

Yeah, don't ask any sort of A.I. about anything that you wish to know. They routinely hallucinate and will give wrong answers. If you want to know rulings you're better off looking it up on getherer/scryfall or just doing a plain google search.
