### ISSUE TITLE
Aura Shards is forcing players to select a target although the triggered ability is a 'may'

### ISSUE THREAD

**Issue by ikzy1980** [Card-Forge/forge#5538]
**Describe the bug**
With Aura Shards in play and valid targets on the field (enchantment/artifact), players are forced to select a target eventhough the triggered ability is a 'may'

**To Reproduce**
1. Open MTG Forge Desktop
2. Cast Aura Shards
3. Cast any creatures with valid target for Aura Shards in the field
4. Forced to choose a valid target

**Expected behavior**
Since the triggered ability of Aura Shards is '**may**' based on the Oracle text below, MTG Forge should not be forcing me to select a valid target. The expected behavior is for players to have the option not to select a target

![MF2](https://github.com/Card-Forge/forge/assets/96282152/e41b0e21-a543-42e8-94de-d0746a877b1d)

**Screenshots**
![MF1](https://github.com/Card-Forge/forge/assets/96282152/1cec3837-c572-4295-bb8d-0819f6400120)

**Desktop (please complete the following information):**
 - OS : Windows 10
 - Browser : Chrome
 - Version 126.0.6478.63 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by Hanmac** [comment]
Ruleswise the Target is not optional (it would need to say "target up to one")

That means you need to target something, and trigger effects that care about targeting. 
And then On Resolving you can decline the Effect
