### ISSUE TITLE
Expend Trigger

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5554]
> Whenever you expend 4, you gain 3 life. (You expend 4 as you spend your fourth total mana to cast spells during a turn.)
> Whenever you expend 8, exile the top two cards of your library. Until the end of your next turn, you may play those cards.

Rules:
> An ability like that can trigger only once each turn. It's looking specifically for the fourth mana, not every fourth mana.

**Comment by tool4ever** [comment]
It probably needs to some extra logic so it doesn't count mana from Assist

**Comment by Hanmac** [comment]
Expend only applies to Spells (and we might ignore Assist for now?)

The Expend values that exist on BLB and BLC:
* 4 (BLB)
* 6 (BLC)
* 8 (BLB + BLC)

so would it be better for us if we "hard-code" them for now?
