### ISSUE TITLE
Battle Box gameplay option in classic mode. 

### ISSUE THREAD

**Issue by NullpointerWorks** [Card-Forge/forge#5569]
I've been exploring a few new formats that I can easily set up and play with a friend. I like draft and Cube, but since it usually requires more than two players, it's can be inconvinient at times. Battle Box is a solution. A two player game that feels a lot like draft using a singleton deck both players draw from.

The basic construction is as follows;
- A shared library both players draw from and search.
- An option for a shared or individual graveyard.
- An option for a shared or individual exile zone.
- Individual battlefield and command zone.
- A set of cards players may cast from outside the game(or usually the command zone). This often contains 10 lands.
- A starting hand of 4 (usually).
- Cards that refer to the "owner" now refer to the player that initially casts/played/obtained that instance of the card.

An introduction:
[https://luckypaper.co/articles/a-guide-to-battle-box/](url)

I understand that this may be tricky to implement, because the set-up of Battle Box differs from regular play with individual decks. It would, however, be really neat if this features gets implemented. I'd love it, and I think more people will. Not to mention if multiplayer becomes more stable. This would be awesome.

Thank you in advance.

**Comment by tehdiplomat** [comment]
Seems cool, but also very problematic to write into the engine.
