### ISSUE TITLE
Bello, Bard of the Bramble

### ISSUE THREAD

**Issue by b-pollett** [Card-Forge/forge#5574]
Bello, Bard of the Bramble doesn't make the 4 Mana Value Enchantment or Artifacts, 4/4 Elemental Creatures, just gives them indestructible and haste.

**To Reproduce**
Have Bello, Bard of the Bramble on the field
 Have on the field or cast a 4+ Mana Value Enchantment or Artifact

**Expected behavior**
The Enchantment or Artifact should become a 4/4 Elemental Creature with Haste and Indestructible.

**Comment by b-pollett** [comment]
Upon further inspection, it is making them the Elemental and 4/4, but is adding creature to the subtype not the supertype

**Comment by b-pollett** [comment]
![Screenshot_20240711_185243_Forge](https://github.com/user-attachments/assets/f16a8974-8ff4-4f72-9aa2-6f37981e734d)
![Screenshot_20240711_185248_Forge](https://github.com/user-attachments/assets/95eaa9e5-c479-46fb-9f30-70cc8950496a)

**Comment by b-pollett** [comment]
So they are still not considered a creature and not able to attack

**Comment by dracontes** [comment]
Much obliged for the thorough report: fixed 👍
