### ISSUE TITLE
Moonstone Harbinger

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5579]
"Whenever you gain or lose life" needs to be its own trigger because "Triggers only once each turn"

**Comment by tool4ever** [comment]
I wonder if we should try to support `List<TriggerType>` to write it in single line and clean up more cards with it? 🤔

(as long as the Valid params are compatible, e.g. on _Aetherwind Basker_:
`T:Mode$ ChangesZone,Attacks ...`)

**Comment by Hanmac** [comment]
i think making one Trigger have Multiple Modes is a bigger can of worms we probably shouldn't do

**Comment by tool4ever** [comment]
@Hanmac 
I think I'd like to remove the extra `LifeChanged` triggertype because it feels like a weird exception now that it's supported more naturally thanks to #9094

your opinion?

**Comment by Hanmac** [comment]
> [@Hanmac](https://github.com/Hanmac) I think I'd like to remove the extra `LifeChanged` triggertype because it feels like a weird exception now that it's supported more naturally thanks to [#9094](https://github.com/Card-Forge/forge/pull/9094)
> 
> your opinion?

Yeah, go for it

There also could be a corner case where you gain life, but "you life total" doesn't change
