### ISSUE TITLE
AI Sideboarding mode "Human for AI" is broken 

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#5606]
**Describe the bug**
AI Sideboarding mode "Human for AI" doesn't work after starting the program. Only after you select a different mode and return this one it will work.

**To Reproduce**
1. Start MTG Forge with already selected AI Sideboarding mode "Human for AI"
2. Start match with AI
3. Concede match
4. You see only your sideboarding menu, not AI

**Expected behavior**
Already selected AI Sideboarding mode "Human for AI" should work after starting the program.

**Additional context**
This problem has been dragging on for many versions

**Desktop**
 - OS: Windows 10
 - Java Version: 1.8.0_202-b08
 - Forge Version: 1.6.64-SNAPSHOT-07-13

**Screenshots**

![sb](https://github.com/user-attachments/assets/bead9505-4f47-42ad-a4f1-04c5a317c414)

**Comment by tehdiplomat** [comment]
@Agetian Can you check this out? I see you made some changes in this area semi-recently, I wonder if it broke the loading of this preference from file.

**Comment by Agetian** [comment]
@tehdiplomat Oh, interesting, either it was never hooked up to the loading process and no one noticed before (can't remember tbh), or maybe it got somehow changed/removed over time, hehe :) At any rate, a patch PR is submitted, seems to work fine.

**Comment by MorihiroS** [comment]
@Agetian, it worked many versions ago, as recently as this year, and then it broke.
