### ISSUE TITLE
Kudo does not effect cards properly

### ISSUE THREAD

**Issue by Jvess** [Card-Forge/forge#5611]
**Describe the bug**
Kudo, King among bears, should cause all other creatures to be 2/2 bears, once it has entered the battlefield. 
Currently it does not effect your own creatures.

**To Reproduce**
1. Have creatures on yours, and opponents board.
2. Cast Kudo
3. Note that opponent creatures are effected, but your own do not get updated.

**Expected behavior**
When Kudo is on the battlefield, All other creatures should become base 2/2 Bear creatures.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
- Version 1,6,63

**Comment by tool4ever** [comment]
Please provide a screenshot of your boardstate while hovering over one of your creatures.

**Comment by dracontes** [comment]
> Please provide a screenshot of your boardstate while hovering over one of your creatures.

Not OP, but this works as expected on `1.6.64-SNAPSHOT-06-28`. 

![image](https://github.com/user-attachments/assets/d6c7516b-6fa0-430f-acf1-f055be64159b)
