### ISSUE TITLE
Brawl decks cannot have more than 59 cards

### ISSUE THREAD

**Issue by Quantumdit** [Card-Forge/forge#5628]
**Describe the bug**
I'm unable to start a new Brawl game, as Forge tells me my Brawl deck can have no more than 59 cards.

**To Reproduce**
1. Go to "New Game"
2. Select "Brawl" as the Variant
3. Select a 100 card deck for yourself and any deck (tested with random and pregenerated commander deck) for your AI opponent

**Expected behavior**
Brawl to be playable with a normal 100 card (99 cards + commander) deck.

**Screenshots**
![Screenshot from 2024-07-16 12-16-59](https://github.com/user-attachments/assets/3ad74486-1a05-456c-8882-381991e027b9)

**Desktop (please complete the following information):**
 - OS: Fedora 40 (Linux)
 - Browser: Firefox (version 128.0)
 - Version: 1.6.63 (Modern Horizons 3)

**Additional context**
Trying to use a Brawl deck with exactly 59 cards will result in the same error. Trying to use a Brawl deck with less than 59 cards will result in "Human deck should have at least 59 cards" as the error:

![Screenshot from 2024-07-16 12-35-40](https://github.com/user-attachments/assets/2d98ceea-64c0-4ace-8a13-d42149342c7f)

**Comment by Jetz72** [comment]
That sounds like correct behavior?
>903.12. [Brawl Option](https://mtg.fandom.com/wiki/Brawl_option)
>...
>903.12d A player’s deck must contain exactly 60 cards, including its commander. In other words, the minimum deck size and the maximum deck size are both 60.

**Comment by Quantumdit** [comment]
Ah, I see. When I saw the "Brawl" option I was thinking of the [Brawl on MTG Arena](https://magic.wizards.com/en/formats/brawl), which uses 100 card decks and uses Historic cards. I didn't know there was another Brawl format with 60 cards and Standard cards.

Before I close this, is there any desire to rename "Brawl" to "Standard Brawl" so that it matches the terminology used in MTG Arena?

**Comment by tehdiplomat** [comment]
We're not super interested in following Arena's bad terminology. They already cause us too many headaches.
