### ISSUE TITLE
Possible bug with Massacre Girl, Known Killer not triggering off of Toxrill

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5667]
**Describe the bug**
I have both Massacre Girl, Known Killer and Toxrill, the Corrosive on the field. When Toxrill reduces my opponent's creature's toughness to below 1 it dies, of course, but Massacre Girl doesn't trigger. Is this right? She's always triggered when I've used her before with things like wither or Toxic Deluge.

**Expected behavior**
To draw a card with Massacre Girl, Known Killer when Toxrill reduces a creature's toughness to less than 1.

**Screenshots**
*Toxrill effect on the stack*
![Screenshot_20240721_052703](https://github.com/user-attachments/assets/c2513da3-c88c-4d17-ad36-ec2ee4ee528f)

*Toxrill and Harvester of Souls effect on the stack after above effect resolves, but no Massacre Girl.*
![Screenshot_20240721_052719](https://github.com/user-attachments/assets/12b201cb-7230-41df-acae-47efab7f7dee)

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.64-SNAPSHOT-07-20

**Comment by tool4ever** [comment]
when did you cast her?
are you sure you flashed her in during your opponents turn?

**Comment by TheLastNarwhal** [comment]
> when did you cast her? are you sure you flashed her in during your opponents turn?

She was on the board before the Toxrill trigger happened. Also, no flash in this deck.

**Comment by tool4ever** [comment]
then read her text again
why do you think she can trigger after any turn you cast her?

**Comment by TheLastNarwhal** [comment]
**Massacre Girl, Known Killer:**
*Menace*

*Creatures you control have wither.*

*Whenever a creature an opponent controls dies, if its toughness was less than 1, draw a card.*

**Comment by TheLastNarwhal** [comment]
You're thinking of the wrong Massacre Girl.

@tool4ever

**Comment by tool4ever** [comment]
indeed my bad, I was going by the screenshots too much and missed you're talking about her other appearance
I'll see if I can reproduce
