### ISSUE TITLE
Unable to add card.

### ISSUE THREAD

**Issue by RecurveRanger** [Card-Forge/forge#5669]
**Describe the bug**
When adding cards abrade was not possible

**To Reproduce**
Add click on abrade in catalog. Card highlights in green but unlike other cards there is no pop up to add it to the deck

**Expected behavior**
Popup to add to deck should appear.

**Screenshots**
![Screenshot_20240721_094647_Forge](https://github.com/user-attachments/assets/c21e294a-36fa-42b0-9cbc-4ddeb9315fb4)

**smartphonr (please complete the following information):**
 - OS: [Android samsung galaxy 23 ultra]
 - Browser [e.g. chrome, ]
 - Version [1.6.64.snapshot.7.20]

**Additional context**

**Comment by Jetz72** [comment]
Did other cards exhibit this issue after Abrade did? Is it possible Abrade was already in the deck?
