### ISSUE TITLE
Text change doesn't work on cards with replacing contrary choice ETB

### ISSUE THREAD

**Issue by tool4ever** [Card-Forge/forge#5672]
The "Siege" cards Animate themselves for their abilities.

So far it only seems to matter for creature type in _Mirrodin Besieged_ ?

**Comment by Hanmac** [comment]
@tool4ever the Anchor Words should be some kind of Linked:
> 614.12b Some replacement effects cause a permanent to enter the battlefield with its controller’s choice of one of two abilities, each marked with an anchor word and preceded by a bullet point. “[Anchor word] — [ability]” means **“As long as [anchor word] was chosen as this permanent entered the battlefield, this permanent has [ability].”** The abilities preceded by anchor words are each linked to the ability that causes a player to choose between them. See rule 607, “Linked Abilities.”

with a Static Ability giving the Card the other Abilities
Also Linked
