### ISSUE TITLE
Camellia, the Seedmiser

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5674]
Needs "SacrificedOnce" trigger

Because the trigger cares about "You" sacrificing stuff, it should collect the LKI and trigger per Player.

Most sacrifice stuff already applies to a List, or is already in a for each player loop

**Comment by Hanmac** [comment]
@tool4ever can you try this SacrificeOnce Trigger per player?

**Comment by tool4ever** [comment]
Maybe but I just checked and it looks like there'd be 9 places where this needs to get called :/
Ideally I can also refactor with some helper that gets that number down somewhat...

**Comment by Hanmac** [comment]
Maybe Optimize it to a Game Action Function that takes a List/CardCollection if cards to be sacrificed?
