### ISSUE TITLE
Heirloom Epic

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5675]
> {4}, {T}: Draw a card. For each mana in this ability’s activation cost, you may tap an untapped creature you control rather than pay that mana.

@tool4ever wouldn't this work with Announce with an TapXType + ReduceCost/ReduceAmount?

While thinking more about it, it probably needs to be inside CostAdjustment with an optional SwitchCost Logic

**Comment by tool4ever** [comment]
The problem is the cost needs to be adjusted before:
> You can't tap more creatures than the amount of mana in the cost of Heirloom Epic's ability. Effects that increase or reduce the activation cost of Heirloom Epic's ability apply before costs are paid and will increase or decrease the total number of creatures you can tap.

**Comment by Hanmac** [comment]
> The problem is the cost needs to be adjusted before:
> 
> > You can't tap more creatures than the amount of mana in the cost of Heirloom Epic's ability. Effects that increase or reduce the activation cost of Heirloom Epic's ability apply before costs are paid and will increase or decrease the total number of creatures you can tap.

Isn't that what "AnnounceMax" is for?

**Comment by Hanmac** [comment]
While thinking more about it, it probably needs to be inside CostAdjustment with an optional SwitchCost Logic

**Comment by Hanmac** [comment]
@tool4ever for this to work, the RaiseCost needs to be After all the Other Raise Cost, so it can use the maximum of ManaCost can be used:

> 601.2f The player determines the total cost of the spell. Usually this is just the mana cost. Some spells have additional or alternative costs. Some effects may increase or reduce the cost to pay, or may provide other alternative costs. Costs may include paying mana, tapping permanents, sacrificing permanents, discarding cards, and so on. The total cost is the mana cost or alternative cost (as determined in rule 601.2b), plus all additional costs and cost increases, and minus all cost reductions. **If multiple cost reductions apply, the player may apply them in any order.** If the mana component of the total cost is reduced to nothing by cost reduction effects, it is considered to be {0}. It can’t be reduced to less than {0}. Once the total cost is determined, any effects that directly affect the total cost are applied. Then the resulting total cost becomes “locked in.” If effects would change the total cost after this time, they have no effect.

the current rule only says about that you can choose the order they apply for cost reductions

> 118.7. What a player actually needs to do to pay a cost may be changed or reduced by effects.

I think effects like "Heirloom Epic" are more like Changing Cost than Raising/Reducing it 🤔

**Comment by tool4ever** [comment]
not enough time right now

**Comment by tool4ever** [comment]
I think first iteration might just share logic with Convoke?
(since there are not cost increases that would add colored mana to the activation cost?)

**Comment by Hanmac** [comment]
@tool4ever thinking about it, yes it might be "Convoke" adjacent

That might help with the implement?


Otherwise, i would have probably added it somewhere before this line in CostAdjustment:
https://github.com/Card-Forge/forge/blob/3b29804568255b246522ca67380ac0bc28bdc790/forge-game/src/main/java/forge/game/cost/CostAdjustment.java#L237-L241
