### ISSUE TITLE
Bug with Kassandra, Eagle Bearer

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5687]
**Describe the bug**
Kassandra's draw ability is triggering on any creature dealing damage, but it should only trigger on creatures that are equipped with legendary equipment. 

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.64-SNAPSHOT-07-24

**Comment by Hanmac** [comment]
@TheLastNarwhal should already be fixed with #5685, so it should be in SNAPSHOT-07-25

**Comment by TheLastNarwhal** [comment]
Oh, my mistake. I didn't notice that the fix was already done.
