### ISSUE TITLE
Something wrong with the "Season of ..." cards in Bloomburrow

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5734]
**Describe the bug**
When scrolling past the Season of ... cards from Bloomburrow Forge becomes semi-unresponsive. It doesn't crash for me, but until I scroll far enough past those cards the card catalog appears to be frozen.

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.64-SNAPSHOT-07-30

**Comment by Hanmac** [comment]
fixed by #5732
