### ISSUE TITLE
Arthur, Marigold Knight return to hand ability is not working. 

### ISSUE THREAD

**Issue by RancidRance** [Card-Forge/forge#5876]
**Describe the bug**
Arthur, Marigold Knight's triggered ability of returning the creature to it's owners hand it not functioning. While the log shows the ability going onto the stack, the creature is never actually return to the hand, and will remain on the field for the rest of the game. 

**To Reproduce**
1. Create a deck with Arthur, Marigold Knight.
2. Attack with Arthur and another creature, triggering Arthur's ability.
3. Select a creature to put into play.
4. Finish combat
5. Observe the creature stays on the field. 

**Expected behavior**
A creature put into play with Arthur's ability should return to it's owners hand after combat.

**Desktop (please complete the following information):**
OS: Windows
Build: forge-gui-desktop-1.6.64-SNAPSHOT-08-07

**Comment by Sehrsiebte** [comment]
This issue still exist in my snapshot version (2024-10-07)

**Comment by Hanmac** [comment]
@tool4ever can your look into this?
