### ISSUE TITLE
AI doesn't cast Shatterskull Smashing

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#5899]
**Describe the bug**
AI doesn't cast Shatterskull Smashing even if it have enough lands and player has 2+ creatures

**To Reproduce**
1. AI has untapped 8+ lands on the battlefield and 2 Shatterskull Smashing in hands
2. Player has 2 dorks and Baneslayer Angel
3. AI doesn't cast Shatterskull Smashing

**Expected behavior**
AI should cast Shatterskull Smashing

**Additional context**
AI casts Spikefield Hazard and Bala Ged Recovery

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.64-SNAPSHOT-08.04

**Screenshots**

![shatt](https://github.com/user-attachments/assets/69722e64-e079-4786-b609-2b1a0cd43f30)
![shatt2](https://github.com/user-attachments/assets/13492c76-bfdd-4d46-ab24-cd03e914cfbf)

**Comment by MorihiroS** [comment]
@Hanmac, need AI label, keep label and assign someone, please

**Comment by MorihiroS** [comment]
@Hanmac, need AI label, keep label and assign someone, please

**Comment by Agetian** [comment]
Hmm, this is a rather serious issue that I may need some help with. It looks like all the spells similar to Shatterskull Smashing may be affected, e.g. the AI no longer casts Fireball (even though it could a while ago), something must have broken it. Can you please help looking at this one, @Hanmac?

**Comment by Hanmac** [comment]
@Agetian i need to see what i can find. Maybe @tool4ever can help me pinpoint the problem?
