### ISSUE TITLE
AI doesn't cast Strike It Rich

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#5900]
**Describe the bug**
AI doesn't cast Strike It Rich at all

**To Reproduce**
1. AI has 1+ untapped Mountain
2. AI has only Strike It Rich in hands
3. AI doesn't cast Strike It Rich

**Expected behavior**
AI should cast Strike It Rich

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.64-SNAPSHOT-08.04

**Screenshots**

![strike](https://github.com/user-attachments/assets/25f749ce-aaf8-42d0-913c-7555f4ff97f4)

**Comment by MorihiroS** [comment]
@Hanmac, need AI label, keep label and assign someone, please

**Comment by Hanmac** [comment]
@Agetian this looks like a timing problem? does it try to make the Treasure Token at instant speed?
