### ISSUE TITLE
Somehow I could just play an 10  CMC spell for nothing when I pressed "cancel"

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#5917]
Log attached.

I wanted to cast Storm Herd but the "Auto" mana could not manage the Boros Signet (this is also an very old and odd issue), so I had to cancel to first tap the boros signet first manually, paying the 1. Then Storm Herd resolved but all my other lands remained untapped and I had even 2 mana still in the pool. 

So somehow I could play Storm Herd for 0 after I pressed "cancel" when casting it first time. Had no time to try and reproduce it, but I attach the log.

![2024-08-12 22_49_57-Greenshot](https://github.com/user-attachments/assets/7c685582-75ac-4054-af65-c5cac8a2ca99)

[forge.log](https://github.com/user-attachments/files/16591788/forge.log)

**Comment by tehdiplomat** [comment]
Are you still using experimental restore?

**Comment by Nymra** [comment]
> Are you still using experimental restore?

I disabled the feature in the settings after the last conversation, so no.
