### ISSUE TITLE
Kozilek's Command, which was cast by AI, couldn't add to stack, failed to target

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#5954]
**Describe the bug**
AI casts Kozilek's Command and this spell doesn't resolved

**To Reproduce**
1. AI casts Kozilek's Command
2. Kozilek's Command doesn't resolved, log text: "Сouldn't add to stack, failed to target"

**Expected behavior**
Kozilek's Command, which was cast by AI, must be resolved

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.64-SNAPSHOT-08-15

**Screenshots**

![koz](https://github.com/user-attachments/assets/c4fec776-6d47-4d12-878e-01d15f9f558b)

**Comment by Agetian** [comment]
Looking into this at the moment, can't quite figure out which part of the ability is targeted incorrectly :/ It feels like it could be the token creation one, but it's a bit tricky to debug :( Easy to reproduce though, e.g.:
[AI_bug_KozileksCommand.txt](https://github.com/user-attachments/files/16708665/AI_bug_KozileksCommand.txt)
