### ISSUE TITLE
bloomburrow quest draft - cant collect prizes and buy boosters

### ISSUE THREAD

**Issue by Serrasmurf** [Card-Forge/forge#5957]
**Describe the bug**
I've played a bloomburrow draft in quest mode and won.
If I press the "collect prizes"button nothing happens. The tournament is stuck (and my draft cards are subsequently not added to my quest pool)

interestingly enough every time i press the button the winning credits are added to my quest credits. 

In the quest card shop i cant buy a bloomburrow booster pack. Its there but nothing happens when I buy it,

**Desktop (please complete the following information):**
 - OS: windows 11
 - forge-gui-desktop-1.6.65-SNAPSHOT-08-20

**Comment by tehdiplomat** [comment]
Ya this was fixed in this PR: https://github.com/Card-Forge/forge/pull/5953 I think it should be in the upcoming snapshot
