### ISSUE TITLE
Hydra Omnivores ability somehow does not seem to work when the AI controls it.

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#5962]
Had this happen twice in the past games now...

AI cast Hydra Omivore, attacks other AI, deals damage, but no other AI or me, the Player receive damage.

When I steal the Omnivore with Insurrection and attack, it works as intended, dealing damage to every AI opponent with its ability.

Log attached.

[forge.log](https://github.com/user-attachments/files/16701064/forge.log)

**Comment by dracontes** [comment]
Tested it on `1.6.64-SNAPSHOT-08-05` and it's working fine: 
![image](https://github.com/user-attachments/assets/3a751109-ac7d-4677-84e1-ba15a581f0d5)
