### ISSUE TITLE
Moonstone Harbinger has typo in keyword

### ISSUE THREAD

**Issue by tjtillman** [Card-Forge/forge#5964]
**Describe the bug**
Moonstone Harbinger's card text says:
SVar:TrigPump:DB$ PumpAll | ValidCards$ Bat.YouCtrl | KW$ Deathouch | NumAtt$ +1

Deathtouch is missing the "t", should be

SVar:TrigPump:DB$ PumpAll | ValidCards$ Bat.YouCtrl | KW$ Deathtouch | NumAtt$ +1

**Desktop (please complete the following information):**
 - Version 1.6.65-snapshot-08-21

**Comment by dracontes** [comment]
Much obliged for the report. It's fixed 👍
