### ISSUE TITLE
card data not translation 

### ISSUE THREAD

**Issue by y12345e** [Card-Forge/forge#5967]
![image](https://github.com/user-attachments/assets/dd644398-c374-4018-8bed-425417aa9a2d)

![image](https://github.com/user-attachments/assets/41fd6baf-a899-4b36-b5a2-40a4652b351a)
Regarding "Garbage Elemental", the card names in res/languages/cardnames*.txt cannot distinguish the following situations
![image](https://github.com/user-attachments/assets/5a1e8e9c-bb15-40ab-a353-d4348202205a)

**Comment by kevlahnota** [comment]
@Hanmac upon checking, it seems the original file doesn't have any chinese translations so this report is a modded cardname file which doesn't match with the unfinity edition file.. removing **$** from the set edition or adding it in the modded cardname translation should fix it
![image](https://github.com/user-attachments/assets/d6dff6bc-c13d-4906-93c4-8576bc5423f0)

**Comment by y12345e** [comment]
This is the translation file I modified. How should I name Garbage Elemental?
Garbage Elemental $A doesn't work either
![image](https://github.com/user-attachments/assets/38a094ab-61c6-4e4b-b1ea-88d5d1d96537)

You can merge this file into Forge
[Uploading cardnames-zh-CN.txt…]()

**Comment by kevlahnota** [comment]
> This is the translation file I modified. How should I name Garbage Elemental? Garbage Elemental $A doesn't work either ![image](https://private-user-images.githubusercontent.com/6188425/361092722-38a094ab-61c6-4e4b-b1ea-88d5d1d96537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NjU4NTEsIm5iZiI6MTcyNDQ2NTU1MSwicGF0aCI6Ii82MTg4NDI1LzM2MTA5MjcyMi0zOGEwOTRhYi02MWM2LTRlNGItYjFlYS04OGQ1ZDFkOTY1MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjRUMDIxMjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI2MzFiNjZiNWZkOTA0YTY4OTUzMjU4NTc0OWIyMmI0ODBlNGM2ZGI1MzNlOWVlZDkxOGVmMDBiMmI0ZTFmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RRGpEIDmz-hIW44NbbRzBEynFOINfeUlBS3WoJNOIQE)
> 
> You can merge this file into Forge Uploading cardnames-zh-CN.txt…

did you try to remove the **$** in the translation file and in the edition file?

**Comment by y12345e** [comment]
> > This is the translation file I modified. How should I name Garbage Elemental? Garbage Elemental $A doesn't work either ![image](https://private-user-images.githubusercontent.com/6188425/361092722-38a094ab-61c6-4e4b-b1ea-88d5d1d96537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NjU4NTEsIm5iZiI6MTcyNDQ2NTU1MSwicGF0aCI6Ii82MTg4NDI1LzM2MTA5MjcyMi0zOGEwOTRhYi02MWM2LTRlNGItYjFlYS04OGQ1ZDFkOTY1MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjRUMDIxMjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI2MzFiNjZiNWZkOTA0YTY4OTUzMjU4NTc0OWIyMmI0ODBlNGM2ZGI1MzNlOWVlZDkxOGVmMDBiMmI0ZTFmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RRGpEIDmz-hIW44NbbRzBEynFOINfeUlBS3WoJNOIQE)
> > You can merge this file into Forge Uploading cardnames-zh-CN.txt…
> 
> did you try to remove the **$** in the translation file and in the edition file?
Related to this submission https://github.com/Card-Forge/forge/commit/8c8c8a779bb6b765b42b2ddcebd7c88d00d6f9f9

**Comment by Jetz72** [comment]
The letters disambiguating the different prints of "Garbage Elemental" were removed from the card names when functional variant support was added. The translation lookups aren't currently aware of these variants. I can look into adding them. Not sure what syntax makes most sense for the translation file though. Could stick with the `Garbage Elemental $A` design since the dollar sign is probably distinct enough an entity to look for.

**Comment by Jetz72** [comment]
Should be possible to translate these now. As noted in the PR, the syntax is:
```
Garbage Elemental $A|Garbage Elemental|Creature — Elemental|Frenzy 2...
Garbage Elemental $B|Garbage Elemental|Creature — Elemental|When Garbage Elemental...
```
Feel free to ping me if any issues crop up in the wake of this; it involved a fair bit of reorganization of the translation logic and there's always a chance something didn't get wired up right.
