### ISSUE TITLE
Insatiable Frugivore does not ask to pay optional costs

### ISSUE THREAD

**Issue by bountygiver** [Card-Forge/forge#5977]
**Describe the bug**
Insatiable Frugivore's triggered ability never asks you to exile cards from graveyard to repeat the process.

**To Reproduce**
1. Have cards in graveyard
2. Play Insatiable Frugivore
3. It creates only 1 food
4. Resolution of the triggered ability ends without asking you to pay optional costs of exiling cards from graveyard to repeat the process.

**Expected behavior**
The triggered ability should ask you whether you want to exile 3 cards from your graveyard to repeat the process of creating more food tokens.

Version forge-adventure-1.6.65-SNAPSHOT

**Comment by kevlahnota** [comment]
fixed by 3bfef56d516c7b308fbcc5817d17d6a5ffad2bf4
