### ISSUE TITLE
Colorless Damage Source as StaticAbility

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5994]
- [ ] Remove hidden Keyword `Colorless Damage Source`, it is only used for `Ghostly Flame`
- [ ] update `nonRed` in the Valid Properties to `!Red` for easier checks? `nonred` should still exist in Descriptions

**Comment by Hanmac** [comment]
@tool4ever your Opinion on `nonRed` → `!Red` to simplify the Code?

**Comment by tool4ever** [comment]
Well in this case nonRed is closer to the templating than the other stuff that was cleaned up, so I don't think that refactor would help that much

**Comment by Hanmac** [comment]
it would help up the code if we could just use the negation instead of the "non" parts
