### ISSUE TITLE
Ward Trigger Not Functioning When Unpaid (Adventure Mode)

### ISSUE THREAD

**Issue by 8BitAvenger** [Card-Forge/forge#6068]
**Describe the bug**
MKM Draft
AI Opponent has a Disguised creature from MKM, I target it with a spell, Ward (2) triggers and pops up, I click cancel (instead of paying 2), the ward trigger goes away and then my spell on the stack resolves as normal. I did not pay the 2 for Ward.

**To Reproduce**
1. Play vs AI in adventure mode in MKM draft or otherwise with them having Disguised creatures
2. Cast a spell targeting the Disguised creature
3. Hit Cancel on the ward trigger resolution
4. Profit

**Expected behavior**
When I cancel paying the Ward (2) trigger, my spell on the stack that triggered it should be countered.

**Desktop (please complete the following information):**
- OS: Win 11
- Version 1.6.65-SNAPSHOT-08-28

**Comment by tool4ever** [comment]
Can't reproduce
Need more details about boardstate

**Comment by Jetz72** [comment]
The spell in question would also be helpful to know. Could it have been any of these?

https://scryfall.com/search?q=set%3Amkm+o%3A%22can%27t+be+countered%22&unique=cards&as=grid&order=name

**Comment by 8BitAvenger** [comment]
> The spell in question would also be helpful to know. Could it have been any of these?
> 
> https://scryfall.com/search?q=set%3Amkm+o%3A%22can%27t+be+countered%22&unique=cards&as=grid&order=name

I had Murder and Slice From the Shadows in the deck, it's possible I only tried/noticed slice doing it which is uncountable. I can try again to reproduce vs regular AI out of adventure but it very well may be I only hit cancel on the uncounterable spell. I didn't notice that part of the text!
