### ISSUE TITLE
Editor breaking bug with Kirtar's Wrath

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#6097]
**Describe the bug**
While building a Selesnya deck I noticed that the editor would freeze up while scrolling through the sorceries section and after some investigating I narrowed it down to Kirtar's Wrath. I assume something is wrong with the Threshold keyword on this particular card?

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Forge Version: forge-gui-desktop-1.6.65-SNAPSHOT-09-05

**Comment by tool4ever** [comment]
Already fixed by https://github.com/Card-Forge/forge/commit/1049f9
