### ISSUE TITLE
Boggart Trawler and Malakir Rebirth frizzes out AI

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#6106]
**Describe the bug**
AI freezes when it has 2 lands on the battlefield and Boggart Trawler and Malakir Rebirth in hands

**To Reproduce**
1. AI has 2 lands on the battlefield
2. AI has Boggart Trawler and Malakir Rebirth in hands
3. AI takes its third turn
4. AI freezes at first main phase

**Expected behavior**
AI shouldn't freeze when it has 2 lands on the battlefield and with Boggart Trawler and Malakir Rebirth in hands

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.65-SNAPSHOT-09-06

**Screenshots**

![fr1](https://github.com/user-attachments/assets/15a7c65e-c88f-406c-8646-e412d48f10ff)
![fr2](https://github.com/user-attachments/assets/4ad4640f-a30f-4292-b4fb-57b6aedb4c1f)
![fr3](https://github.com/user-attachments/assets/18dd22cb-df2b-4383-85ab-8cccaea415ed)

**Comment by tool4ever** [comment]
Doesn't look like it's this specific card...
please provide a crash log

**Comment by MorihiroS** [comment]
> Doesn't look like it's this specific card... please provide a crash log

@tool4ever, I can't drop the crash log because the game doesn't crash, AI just freezes. But I can give game states and game layouts before the turn pass and after the freeze.

And yes, the problem is not one card, but two. The problem is not one card, but a combination of two, Boggart Trawler and Malakir Rebirth.

[state.txt](https://github.com/user-attachments/files/16948130/state.txt)
[state (after).txt](https://github.com/user-attachments/files/16948127/state.after.txt)
[layouts.zip](https://github.com/user-attachments/files/16948144/layouts.zip)

![444](https://github.com/user-attachments/assets/a604b7ab-c8cf-4364-bc7f-e883764edbd3)
