### ISSUE TITLE
Ghalta Presence in Adventure Mode: extra 2 cost to "cast" spells

### ISSUE THREAD

**Issue by thranur** [Card-Forge/forge#6124]
**Describe the bug**
When fighting Ghalta in Adventure Mode, its card says something like "non-creature, non-battle spells cast by your opponent cost 2 more". I played an Apex Devastator and, for each non-creature card in Cascade, it asked me to pay 2 mana. However, when cascade takes place, spells are not cast, they enter the battlefield. If I put an Apex Devastator this way, for instance, its Cascade won't trigger because it requires that the spell be cast.

**To Reproduce**
1. Fight Ghalta
2. Cast an Apex Devastator 
3. Try to put a non-creature card

**Expected behavior**
The 2 mana cost should not be required.

**Screenshots**
Cannot take them (phone out of memory)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 3 
 - OS: Android 13
 - Version 1.6.65

**Comment by Klisz** [comment]
> However, when cascade takes place, spells are not cast, they enter the battlefield.

This is incorrect. Cascade does indeed cast spells, rather than put them directly onto the battlefield (if it did put them onto the battlefield, it wouldn't work with instants or sorceries). Quoting rule 702.85a (emphasis mine):

> "Cascade" means "When you cast this spell, exile cards from the top of your library until you exile a nonland card whose mana value is less than this spell's mana value. You may **cast** that card without paying its mana cost if the resulting spell's mana value is less than this spell's mana value. Then put all cards exiled this way that weren't cast on the bottom of your library in a random order."
