### ISSUE TITLE
Undercity (Throne of the Dead Three) and Forgotten Ancient Bugged (30 +1/+1 counters instead of 3!)

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#6164]
As the title said...

rare occasion tho...

I put Forgotten Ancient into play with the Throne of the Dead Three room of the Undercity and it entered the game with 30 +1/+1 counters instead of just three. 

I dont have any multi triggers or stuff like that on the field...

**Comment by tool4ever** [comment]
Can't reproduce that either
