### ISSUE TITLE
Puzzle #01 Bypass Operation - Vedalken Mastermind bug

### ISSUE THREAD

**Issue by Ayora29** [Card-Forge/forge#6189]
**Describe the bug**
In branh "master". In Puzzle "Forge Puzzle 01 Bypass Operation", the abilty of Vedalken Mastermind is not going on the stack during Main phase 1. Instead we need to pass M1 and the ability goes suddenly on the stack in BC phase. 
Bug not reproduced in branch 1.6.64.

**To Reproduce**
1. Go to Puzzle "Forge Puzzle 01 Bypass Operation";
2. Click on "Vedalken Mastermind" to enable his ability.
3. Choose "Crumbling vestige" as a target
4. Pay 1 blue mana cost
5. The ability is not going on the stack.
6. Pass M1 phase.
7. The ability appear on the stack.

**Expected behavior**
1. Go to Puzzle "Forge Puzzle 01 Bypass Operation";
2. Click on "Vedalken Mastermind" to enable is ability.
3. Choose "Crumbling vestige" as a target
4. Pay 1 blue mana cost
5. The ability is going on the stack.

**Screenshots**
![{13E74AE6-05EB-44EE-BB04-7851C6D4034A}](https://github.com/user-attachments/assets/1738a8bb-a5da-4300-8969-7a85a3fd7982)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Master branch (last commit 11a7f7b2719b109a995cb54bdeba8af378101429)

**Comment by kevlahnota** [comment]
@tool4ever just encountered the bug but I can't reproduce again. Just played a land and activate to animate it and the trigger goes to the stack only after proceeding to next phase. Anyway, I wonder what is the cause of it.

**Comment by Ayora29** [comment]
@tool4ever fixed the bug in #6213 I have tested after his commit and the bug can't be reproduced now.
