### ISSUE TITLE
Asking to target before paying the cost to target

### ISSUE THREAD

**Issue by KingNin64** [Card-Forge/forge#620]
I noticed this bug when playing Yasova Dragonclaw. She states, "At the beginning of combat on your turn, you may pay {cost}. If you do, gain control of target creature..."

You should have the choice of whether or not to pay the cost before you choose the target, but in Forge, you are asked to choose a target before you pay the cost. This leads to some interesting things happening:

For example, I run Willbreaker, which says "Whenever a creature an opponent controls becomes the target of a spell or ability, gain control of it." This bug allows Yasova to choose a target before a pay her cost, thus triggering Willbreaker and allowing me to gain control of the creature for free. This shouldn't be the case.

Another example is one that is negative for me, and has ruined some games for me. When playing against Draconic Domination, I ran across Scalelord Reckoner, which states, "If a Dragon you control becomes the target of a spell or ability an opponent controls, destroy target nonland permanent that player controls." Yasova triggers, I don't get the choice of not paying her cost like I should, I have to choose a target (despite me not wanting to), then my opponent gets to destroy something of mine.

I've noticed that this bug seems to happen with other abilities that function similarly to Yasova, where they ask you to pay a cost, then target something. This also happens with casting spells that target things too. For example, if I cast Shock, I choose the target, then pay. I haven't checked if that causes "if this is targeted" triggers, however. 

I believe this is just an issue that exists within how things like this are handled, and might be a difficult change, so I understand. I think targets and such should be considered after paying the cost to cast a card or to activate an ability that would result in you targeting something.

Image shows Scalelord Reckoner triggering before I choose to pay Yasova's "gain control" cost:
![unknown](https://user-images.githubusercontent.com/80501165/172034104-fa750d65-da80-488b-8294-28b619e4fd5f.png)

**Comment by tool4ever** [comment]
Only "when you do" is a reflexive trigger (see CR 603.12).
But Yasova ability says "if you do" which is handled by CR 118.12.
So Forge does it correctly.
