### ISSUE TITLE
Second Main Phase cards interaction with cards that generate extra Main Phases

### ISSUE THREAD

**Issue by BigCrunch22** [Card-Forge/forge#6215]
I'm not really sure if I should put this to Bug Report or Feature Request, so I'll just choose the latter.

There was a functionality change a while ago that the Second Main Phase will only occur once. Any further main phases beyond it will be 3rd, 4th, etc.

In the case that you have a card that triggers on the Second Main Phase and you can get additional Main Phases beyond the second one (like Aggravated Assault), those Main Phases will not trigger said cards.

It looks like the cards that trigger on the Second Main Phase can still trigger from extra main phases generated by Aggravated Assault. This should not be the case.

I tested this on Cautious Survivor, but I think the other cards with similar effects also do the same thing.

Also, World at War received a change from **"First Postcombat Main Phase"** to **"Second Main Phase"**. So I think it should also receive a similar functionality change.

https://www.reddit.com/r/magicTCG/comments/1e9wb5w/fyi_the_change_in_templating_from_postcombat_main/?share_id=s9s2uIA-oR4I54b6f5_RO&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1
![image](https://github.com/user-attachments/assets/c73c67d2-341a-44b3-b44e-07d9f54c6750)

**Comment by TheLastNarwhal** [comment]
@tool4ever

I just want to mention, in case it wasn't known, that WotC confirmed that there are 11 cards that used the term "postcombat main phase" that would **not** be affected by this change to "second main phase" terminology and that they would continue to function as they always have.

https://www.reddit.com/r/magicTCG/comments/1ec0st5/nehebpostcombat_main_phases_update_tldr_will/?rdt=56563

So, I think it's safe to say that the cards on this scryfall list are the ones mentioned that won't be affected.
https://scryfall.com/search?q=%28oracle%3A%22postcombat+main+phase%22%29+%28game%3Apaper%29&unique=cards&as=grid&order=name

**Comment by tool4ever** [comment]
thanks, I do believe my PR respects that
but feel free to test :)
