### ISSUE TITLE
Engine does not activate Illusionary Mask correctly

### ISSUE THREAD

**Issue by brederic** [Card-Forge/forge#6217]
**Describe the bug**
Illusionary Mask does not bring creature to the battlefield as expected

**To Reproduce**
1. Illusionary Mask in play with creature card in hand with Mana Cost 3, during main phase
2. Click on Illusionary Mask, choose X=3, tap 3 mana matching the mana cost of the creature in hand.
3. Click on creature card in hand 
4. Nothing happens.

**Expected behavior**
The creature should be placed in play face down as a 2/2 creature.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.64

**Comment by Jetz72** [comment]
What was the creature and what mana did you use to pay X? Illusionary Mask doesn't just care about numeric mana value, it has to use the same kinds of mana that could actually pay the creature's cost.

**Comment by brederic** [comment]
It happened several times.  Here is one that I specifically remember.  I had Earth Elemental in hand, Mana Cost 3RR. I had three forests and two mountains untapped.  After activating Illusionary Mask all my mana was tapped but no creature appeared on the battlefield in any form.
