### ISSUE TITLE
Forge crash after game exit

### ISSUE THREAD

**Issue by HassanSky81** [Card-Forge/forge#6241]
Isue present in 1.6.64 or the latest soruces from 7th of October 2024

Play the game then exit the game.
Message: "A problem caused the program to stop working correctly. Please close the program."
![Game exit](https://github.com/user-attachments/assets/9cf11168-0362-47ed-bf10-cd533275ff53)

**Comment by HassanSky81** [comment]
does anyone experience same issue?

**Comment by Jetz72** [comment]
Does it still happen with the 2.0.0 snapshot? The latest update jumped the game ahead several Java versions.

**Comment by HassanSky81** [comment]
yes. still the same with 2.0.0
Do you have this problem also?

**Comment by Jetz72** [comment]
I do not. Unless someone else has experienced it or you can post your `forge.log` file and something there indicates the cause, there isn't much to go on here. Is this with the Desktop UI or the Adventure/Mobile UI?
