### ISSUE TITLE
Selecting a deck at random from custom user decks with the "Random Deck" button takes too long  

### ISSUE THREAD

**Issue by keineahnungking** [Card-Forge/forge#626]
**Describe the bug**
Since a few snapshots ago the process of selecting a random user deck takes way too long.

**To Reproduce**
1. Go to the deck selection.
2. Click on "Random Deck" button

**Expected behavior**
This should select a random deck instantly as it does on the latest stable build. Even though I have 6000 decks in my folder the algorithm should be very quick.

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: Android 11
 - Version SNAPSHOT June 08 01:25:47 AM

**Comment by kevlahnota** [comment]
disable Automatic AI Deck Selection: 
![image](https://user-images.githubusercontent.com/9781539/172601344-58260b67-c2fc-489d-bc5a-f97ad7363958.png)
