### ISSUE TITLE
SubAbility not found for certain cards

### ISSUE THREAD

**Issue by BigCrunch22** [Card-Forge/forge#6264]
### List of Cards
- SubAbility 'DBBounce' not found for: Disappear
- SubAbility 'DBChangeZone' not found for: The Five Doctors
- SubAbility 'DBGainLife' not found for: Cryptex
- SubAbility 'DBPEffect' not found for: Ruhan of the Fomori
- SubAbility 'DBUntapAll' not found for: Twist Allegiance
- SubAbility 'SacAllOthers' not found for: Keldon Firebombers

**Comment by tool4ever** [comment]
thanks :)
