### ISSUE TITLE
Horrific Assault (MH3) missing

### ISSUE THREAD

**Issue by Luarien** [Card-Forge/forge#6273]
Helped a friend import a deck and Horrific Assault (a common from MH3) appears not to be in the card list anywhere. I checked the card list in the project merges and Horrific Assault isn't on either MH3 or MH3 commander lists, it appears to have been forgotten.

**Comment by paulsnoops** [comment]
https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/h/horrific_assault.txt

https://github.com/Card-Forge/forge/blob/b6cfbe3fae065b47894fa27f64b3cc9141ec2b56/forge-gui/res/editions/Modern%20Horizons%203.txt#L207

I don't know where you're looking in our project merges but that card is in both the scripts and edition files
