### ISSUE TITLE
Castle Garenbrig passes phase on OK to cast

### ISSUE THREAD

**Issue by nwg5817** [Card-Forge/forge#6277]
**Describe the bug**
When I use the ability on Castle Garenbrig, hit auto to tap mana, when I hit OK it ends the phase and doesn't cast.

**To Reproduce**
Have Castle in play, attempt to use ability to ramp 4 mana into 6 for creatures.
Press castle -> 4 mana to get 6 for creatures -> Hit Auto or tap mana to cast -> Press OK -> M1 Phase is Passed

**Expected behavior**
Castle should auto 4 mana from other sources with auto, Tap on OK and provide Mana.

**Desktop (please complete the following information):**
 - OS: Windows
 - Adventure Mode latest snapshot.

**Comment by tool4ever** [comment]
This isn't really clear to me.
Pressing "OK" usually means pass priority.
Mb record a video of what you're doing?
