### ISSUE TITLE
Adventnure mode: Not getting cards from Jumpstart, no matter placing.

### ISSUE THREAD

**Issue by RyushoYosei** [Card-Forge/forge#6286]
**Describe the bug**
Playing the jumpstart tournaments in the INn, but it doesn't give the untradable copies of the cards in the deck..

**To Reproduce**
1. Go to an inn that is playing jumpstart.
2. Enter the tournament, Mana or coin, I haven't tried paid.
3. Play matches if you wish, just get to the end of the tournament.
4. Check your inventory after getting the "Tournametn rewards."  And it sshould just be the starting cards you had, none of the jumpstart cards.

**Expected behavior**
I should have the copies of the jumpstart cards from the decks I used.

**Additional context**
Tried this several times, I believe I was using the current Release version, as I downloaded it a couple days ago.

**Comment by kevlahnota** [comment]
@RyushoYosei Did you check your inventory and open the card packs? It should be there..

**Comment by RyushoYosei** [comment]
Oh, I thought they would be just added to yourr cards, not a "Card pack" that was in your inventory, that explains it >.<
