### ISSUE TITLE
Duskmourn Enchantment Staff Roombugged

### ISSUE THREAD

**Issue by JustiinJS** [Card-Forge/forge#6374]
**Describe the bug**
I played the Jump Scare! deck from duskmourn and when the faced down creature (with Staff Room) under it died the Staff Room was still active and gave creatures +1/+1 counters. Even in a new game, new deck and a fresh instal of Forge this issue was still stuck when Staff Room is included in the deck. 

**To Reproduce**
Jump Scare! Deck
Play Staff Room faced down
Let the Faced down creature die
Ta-da! Stuck card.

Is this a cache related thing?

**Comment by tool4ever** [comment]
already fixed by 8f7b782
