### ISSUE TITLE
AI casts spells with X in cost, paying X as 0

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#6390]
**Describe the bug**
AI casts some spells with X in cost, paying X as 0, and takes nothing:

- [ ] Kozilek's Command
- [x] Portent of Calamity

**To Reproduce**
1. AI has 2 colorless mana
2. AI has Kozilek's Command
3. AI casts Kozilek's Command for 2 colorless mana, X=0

and

1. AI has 1 blue mana and some other lands
2. AI has Portent of Calamity in hands
3. AI casts Portent of Calamity for one blue mana, X=0

**Expected behavior**
AI casts some spells with X in cost, paying X as 1 or more

**Additional context**
AI may cast Electrodominance with X=0 if it has at least spells with 0 cmc in its hands (look #4118).

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.66-SNAPSHOT-10-17

**Screenshots**

![x2](https://github.com/user-attachments/assets/b9bed946-dd74-4b94-a28a-3a93ba325e26)
![x3](https://github.com/user-attachments/assets/d3276fe1-a348-4a8e-aff5-2b4dd1d34d89)
![x4](https://github.com/user-attachments/assets/ec2b35d2-e43f-4473-a0f4-a06219290136)

**Comment by MorihiroS** [comment]
Now Kozilek's Command is worked well, but AI still casts Portent of Calamity for 1 blue mana

![calam1](https://github.com/user-attachments/assets/29bbb891-9e11-4128-8952-9c8cf7ee3b65)
![comm1](https://github.com/user-attachments/assets/cb9f7017-c7cd-4193-9bac-e3a3a55f7b2c)
![comm2](https://github.com/user-attachments/assets/56d683e1-9233-45d8-853a-6769b8ec1e9b)

**Comment by MorihiroS** [comment]
Closed by #6410

**Comment by MorihiroS** [comment]
@Agetian, AI did it again with Kozilek's Command(

2.0.00-SNAPSHOT-10.31

![koz1](https://github.com/user-attachments/assets/7478a18d-d4df-40e7-9103-5aad7b53b261)

**Comment by Agetian** [comment]
Tried to improve this with #6506, but can't promise it's going to fully do the job. If it happens to you after this MR is merged, it would help if you provided a game state and not just a screenshot.
