### ISSUE TITLE
Forge jar installer QoL

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#6395]
**Is your feature request related to a problem? Please describe.**
Okay, so, first things first. I do prefer the tar.bz2 way of installing, but that's a thing of the past and that's fine. It _was_ simpler since it was only a single extract and then good to go, but things change.

Anyway, this jar installer does work and it could work just as well as the tar.bz2 if a few things were changed.

1. First, it would be nice if the jar itself was executable by default, so I don't have to manually change that every update.
2. Secondly, and exactly like the first issue, it would be nice if the forge.sh was executable by default, so I don't have to manually change that every update as well.
3. Last one I don't know if it could be "fixed" but I may as well list it anyway. When using the installer and changing the default directory location the file name is erased and then I have to add it back manually. It would be nice if that didn't happen.

**Additional context**
I fully admit that these are all small things, but when compared to the single click of the last way to install it starts to become a thing over time. Three or four steps that you have to go through now.

**On a separate note**
Congratulations on the 2.0 update! As a daily user for many years it's so nice to see how far this has come and see such an amazing milestone reached. Keep up the good work. You all are the absolute best and are basically the only reason my passion for this game has been able to be sustained.

**Comment by Hanmac** [comment]
We might still add the tar.bz2 again, we just need to brainstorm about it

**Comment by kevlahnota** [comment]
How come it isn't executable? After it was created, double clicking should open it ( just tested on windows and it's working fine). Also forge.sh works too when double clicking on windows. If you're on a different platform and needs additional things, custom action can be added though it may be a dev with the same platform you use.

**Comment by kevlahnota** [comment]
@TheLastNarwhal I updated the installer and marked the scripts as executable but I don't know if it will work upon installation since the docs on izpack is hard to understand and there's no latest information or examples to do it. 
![IMG20241021205458](https://github.com/user-attachments/assets/8d4b3405-779c-45f1-a340-362cd03d8780)

**Comment by TheLastNarwhal** [comment]
I'll see if anything is fixed once the new snapshot comes out later this afternoon.
