### ISSUE TITLE
Adeline Resplendent Cathar token issue

### ISSUE THREAD

**Issue by bkapvt** [Card-Forge/forge#6406]
**Describe the bug**
As the card text states, 3 1/1 tokens are created tapped and attacking with Adeline. When playing against AI, if it decides to assign blockers to the tokens, it is somehow able to block all of the tokens with one creature. When damage is assigned it was as if only one token did damage. All of the tokens will die after blockers are assigned. Interestingly enough any death triggers from the tokens will still count. i.e. three death triggers would occur

**To Reproduce**
Attack with Adeline Resplendent Cathar, it should not matter what the circumstances are as long as the ai assigns a blocker to the token.

**Expected behavior**

**Screenshots**
Sorry no screenshot but. when the AI assigns the blocker I hear the "blocker" noise 3 times but only see the one arrow showing the assigned blocker

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A?
 - Version 1.6.65

**Additional context**

**Comment by tool4ever** [comment]
sounds like user error
only seeing one arrow is normal unless you arranged it to see all 4 battlefield at the same time....

**Comment by bkapvt** [comment]
Not sure I understand… the issue here is that my opponent is able to block all of the tokens with one creature. That shouldn’t be possible…

**Comment by tool4ever** [comment]
I'm saying you're probably confusing what you're seeing
are you even aware there are two other opponents that can also block?
Please provide screenshots of your boardstate including log and combat tab during declare blockers
