### ISSUE TITLE
Forge can't be updated by Check for Updates

### ISSUE THREAD

**Issue by MorihiroS** [Card-Forge/forge#6408]
**Describe the bug**
Forge can't be updated by Check for Updates

**To Reproduce**
1. Go to Preferences -> Check for Updates
2. Choose "Update now"
3. Click "Start" 
4. See text with "0 Download the new version.. extracted"

**Expected behavior**
Forge can be updated by Check for Updates

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 2.0.00-SNAPSHOT-10-21

**Screenshots**

![download 1](https://github.com/user-attachments/assets/54394c8d-1fff-4d68-b303-b0bb6fd7b530)
![download 2](https://github.com/user-attachments/assets/f326458a-99ae-4ef4-b1c8-5aa638c8605b)

**Comment by kevlahnota** [comment]
I really thought that the desktop updater is disabled since it doesn't work correctly @tehdiplomat

**Comment by tehdiplomat** [comment]
No it was turned back on when we standardized the upload format (via github actions). Maybe the updater is still referencing an old version reference?

**Comment by tehdiplomat** [comment]
Also, how can you be on Java 1.8? Forge 2.0 doesn't support that.

**Comment by kevlahnota** [comment]
Java 8 support is dropped. I think There is something wrong with your installation, I suggest redownload a new snapshot and clean install to new folder.

**Comment by MorihiroS** [comment]
@tehdiplomat done!

**Comment by tehdiplomat** [comment]
@kevlahnota So looks like the AutoUpdater is using https://github.com/Card-Forge/forge/blob/master/forge-gui/src/main/java/forge/download/AutoUpdater.java#L52

Which seems to not be grabbing the date subversion. Is there a dfiferent string we should be using for that?

**Comment by kevlahnota** [comment]
> @kevlahnota So looks like the AutoUpdater is using https://github.com/Card-Forge/forge/blob/master/forge-gui/src/main/java/forge/download/AutoUpdater.java#L52
> 
> Which seems to not be grabbing the date subversion. Is there a dfiferent string we should be using for that?

On my local copy I implement the Atom/RSS parsing since github links can be parsed as atom feeds and process the xml tags and get the exact data to compare with the app version or by build date. I think that's the better method and we can get more info like commits by date range. Still on testing phase though
