### ISSUE TITLE
Fatal error in Java Runtime Environment when using forge-adventure.sh

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#6415]
**Describe the bug**
Title pretty much says it all.

I don't normally use the adventure version, but I thought I should check up on the differences between the mobile and desktop versions of Forge. When I tried to open it I got the error below.

The regular desktop version is fine.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Forge Version: forge-gui-mobile-dev-2.0.00-SNAPSHOT-jar-with-dependencies

**Error Log**
[hs_err_pid385697.log](https://github.com/user-attachments/files/17481077/hs_err_pid385697.log)

**Comment by kevlahnota** [comment]
Found similar problem here for libc
https://forums.developer.nvidia.com/t/opsu-crashes-on-nvidia-535-86-10/264553

Try to update your graphics driver.

**Comment by TheLastNarwhal** [comment]
@kevlahnota
Yeah... I only have an integrated graphics card and those drivers taken care of by my distro. I don't think I should go poking around for other drivers.

> Also add this:
__GL_THREADED_OPTIMIZATIONS=0 env variable set.

Add this where?

**Comment by kevlahnota** [comment]
> @kevlahnota Yeah... I only have an integrated graphics card and those drivers are taken care of by my distro. I don't think I should go poking around for other drivers.
> 
> > Also add this:
> > __GL_THREADED_OPTIMIZATIONS=0 env variable set.
> 
> Add this where?

Well it's for nvidia only, I don't know what graphics driver you use but most sigsegv (segmentation fault) errors are likely fixed by graphics driver update.

**Comment by TheLastNarwhal** [comment]
Honestly, I'm not super knowledgeable in this area. Based on some google searches I _think_ my drivers are OpenGL 4.2 or Mesa something. I don't know. That's what pops up when I run the `glxinfo -B` command in the terminal that this site: https://linuxconfig.org/graphics-driver-check-on-ubuntu-22-04 says is used to check drivers.

**Comment by TheLastNarwhal** [comment]
I was able to run the mobile version in the past, so it's a bit weird that it's having this issue now, but, eh, I suppose I'll just stick to the regular version of Forge. I do prefer the desktop layout to the mobile one and Adventure mode seems like you'd need nostalgia for the old Shandalar to really enjoy it.

I just hope that the desktop version doesn't start to have this issue...

**Comment by kevlahnota** [comment]
> I was able to run the mobile version in the past, so it's a bit weird that it's having this issue now, but, eh, I suppose I'll just stick to the regular version of Forge. I do prefer the desktop layout to the mobile one and Adventure mode seems like you'd need nostalgia for the old Shandalar to really enjoy it.
> 
> I just hope that the desktop version doesn't start to have this issue...

No it will not, the mobile build uses updated engine hence the LibGDX team may incorporate new methods or Graphics update that maybe conflicts on older driver. The Desktop does use plain graphics so most likely it will never have that issue since it doesn't use LibGDX.
