### ISSUE TITLE
Fatal error trying to start adventure mode on linux desktop

### ISSUE THREAD

**Issue by jmelesky** [Card-Forge/forge#6417]
**Describe the bug**
When running `forge-adventure.sh` from the command line, the splash animation appears, a blank window appears, and then the program crashes with a SIGSEGV:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000077b954697ef4, pid=354450, tid=354451
#
# JRE version: Java(TM) SE Runtime Environment (21.0.5+9) (build 21.0.5+9-LTS-239)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (21.0.5+9-LTS-239, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x97ef4]  pthread_mutex_lock+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /mnt/drive2/Games/Forge/core.354450)
#
# An error report file with more information is saved as:
# /mnt/drive2/Games/Forge/hs_err_pid354450.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```
(here is the error report file: [hs_err_pid354450.log](https://github.com/user-attachments/files/17485220/hs_err_pid354450.log))

I tried this with dailysnapshots from 10.22 and 10.23. I tried this with both Oracle JRE 21.0.5 and OpenJDK JRE 1.21.0. Non-adventure mode starts up without a problem.

All drivers are up-to-date. Graphics are Intel Mesa integrated, nothing fancy.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Version: 2.0.00-SNAPSHOT-10.23 daily snapshot

**Additional context**
Happy to try other JRE versions or different java launch configurations if you'd like.

**Comment by kevlahnota** [comment]
@jemelesky can you try to redownload 10.23 snaps or the next snaps if the issue persists on your end?

**Comment by jmelesky** [comment]
Tried with the 10.24 snap, and it got further (displayed the "Welcome to Forge" splash screen), but still segfaulted:

```
Skin not found. Defaulting to fallback_skin.
(ThreadUtil first call): Running on a machine with 8 cpu core(s)
Forge v.2.0.00-SNAPSHOT (forge.GuiMobile@c15cae8)
Linux (6.9.3-76060903-generic amd64)
Oracle Corporation (Java 21.0.5+9-LTS-239, Java HotSpot(TM) 64-Bit Server VM)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000712502e97ef4, pid=481088, tid=481089
#
# JRE version: Java(TM) SE Runtime Environment (21.0.5+9) (build 21.0.5+9-LTS-239)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (21.0.5+9-LTS-239, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x97ef4]  pthread_mutex_lock+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /mnt/drive2/Games/Forge/core.481088)
#
# An error report file with more information is saved as:
# /mnt/drive2/Games/Forge/hs_err_pid481088.log
Language 'en-US' loaded successfully.
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

(yes, the `Language 'en-US'` line appeared in the middle of the JRE fatal error message)

The error report: 
[hs_err_pid481088.log](https://github.com/user-attachments/files/17512549/hs_err_pid481088.log)

**Comment by kevlahnota** [comment]
> Tried with the 10.24 snap, and it got further (displayed the "Welcome to Forge" splash screen), but still segfaulted:
> 
> ```
> Skin not found. Defaulting to fallback_skin.
> (ThreadUtil first call): Running on a machine with 8 cpu core(s)
> Forge v.2.0.00-SNAPSHOT (forge.GuiMobile@c15cae8)
> Linux (6.9.3-76060903-generic amd64)
> Oracle Corporation (Java 21.0.5+9-LTS-239, Java HotSpot(TM) 64-Bit Server VM)
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x0000712502e97ef4, pid=481088, tid=481089
> #
> # JRE version: Java(TM) SE Runtime Environment (21.0.5+9) (build 21.0.5+9-LTS-239)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (21.0.5+9-LTS-239, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
> # Problematic frame:
> # C  [libc.so.6+0x97ef4]  pthread_mutex_lock+0x4
> #
> # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /mnt/drive2/Games/Forge/core.481088)
> #
> # An error report file with more information is saved as:
> # /mnt/drive2/Games/Forge/hs_err_pid481088.log
> Language 'en-US' loaded successfully.
> #
> # If you would like to submit a bug report, please visit:
> #   https://bugreport.java.com/bugreport/crash.jsp
> #
> Aborted (core dumped)
> ```
> 
> (yes, the `Language 'en-US'` line appeared in the middle of the JRE fatal error message)
> 
> The error report: [hs_err_pid481088.log](https://github.com/user-attachments/files/17512549/hs_err_pid481088.log)

anyway how do you run the app? do you use java -jar command or the forge-adventure.sh?

**Comment by jmelesky** [comment]
I use the provided `forge-adventure.sh`. I'm happy to try other ways of launching if you'd like.

**Comment by kevlahnota** [comment]
> I use the provided `forge-adventure.sh`. I'm happy to try other ways of launching if you'd like.

Can you try to update your drivers? Are you using MESA drivers?

**Comment by jmelesky** [comment]
I'm using the drivers provided with stock Pop!_OS 22.04 LTS, which I believe are MESA. I've been updating daily in case that fixes things, but no luck so far.

**Comment by kevlahnota** [comment]
> I'm using the drivers provided with stock Pop!_OS 22.04 LTS, which I believe are MESA. I've been updating daily in case that fixes things, but no luck so far.

Ok I think I found the issue, the natives are not updated for the mobile build but I'm not really sure if those will fix your issue since they work on windows.

**Comment by jmelesky** [comment]
I'll give it a try when the next daily snapshot comes out.

**Comment by jmelesky** [comment]
It didn't get as far this time:

```
Skin not found. Defaulting to fallback_skin.
(ThreadUtil first call): Running on a machine with 8 cpu core(s)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007c29c9097ef4, pid=530116, tid=530117
#
# JRE version: Java(TM) SE Runtime Environment (21.0.5+9) (build 21.0.5+9-LTS-239)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (21.0.5+9-LTS-239, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x97ef4]  pthread_mutex_lock+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /mnt/drive2/Games/Forge/core.530116)
#
# An error report file with more information is saved as:
# /mnt/drive2/Games/Forge/hs_err_pid530116.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

[hs_err_pid530116.log](https://github.com/user-attachments/files/17524918/hs_err_pid530116.log)

**Comment by kevlahnota** [comment]
Does the release 1.6.65 version works on your end? If thats the case then it should be something on the newer libgdx engine.

**Comment by jmelesky** [comment]
Good idea. The instructions say to go with the snapshots for Adventure mode, so I hadn't tried it. But just downloaded it and it gets to the menu screen without a problem.

**Comment by kevlahnota** [comment]
> Good idea. The instructions say to go with the snapshots for Adventure mode, so I hadn't tried it. But just downloaded it and it gets to the menu screen without a problem.

Ok maybe the small splashscrreen crashes on your end since I found this single issue similar with yours..
 - # https://github.com/libgdx/libgdx/issues/5208

**Comment by TheLastNarwhal** [comment]
Just want to say that this is the exact same issue I had here: https://github.com/Card-Forge/forge/issues/6415.
