### ISSUE TITLE
Images no longer downloading after last build update

### ISSUE THREAD

**Issue by RodrigoChetto14** [Card-Forge/forge#6429]
**Describe the bug**
Card's Images no longer downloading after last build update

**To Reproduce**
1. Create a new adventure game
2. Check settings.
3. Dowload missing card art should be checked
4. Enter deck editor. Images no longer download.

**Expected behavior**
As worked in yesterday's build it should download the missing images.

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi a2
 - OS: Android 12 SKQ1.210908.001
 - Browser Chrome (but the problem is with the app. Not sure if this is relevant).
 - Version 
  Forge: 2.0.00-SNAPSHOT-10.25
  Chrome: 13.0.6723.73

**Comment by kevlahnota** [comment]
Try to turn off permission, run forge and then when it asks for permission, turn on again..
![Screenshot_20241026-041745_Permission controller](https://github.com/user-attachments/assets/e5d70d42-27c6-4df1-be50-86b51cede4ad)

https://github.com/user-attachments/assets/3683acdc-8f0e-4f76-913e-8ba6f592a5a1

**Comment by kevlahnota** [comment]
- fixed by #6431
