### ISSUE TITLE
Adventure mode not working

### ISSUE THREAD

**Issue by EthanTGOL** [Card-Forge/forge#6430]
Card images not showing up, game freezes when getting items from defeated enemies, books on ground being grabbed without giving rewards, gold and mana shards not picking up, shops cannot be entered, mine quest not continuing, severe lag, input delay, and clipping indoors

**To Reproduce**
1. Go to adventure mode
2. Enter any shop, defeat enemy, attempt to see card image, or go into dungeon and attempt to pick up item
3. Card image will not display, enemy will not drop loot or game will freeze, image will not display, cards will not go into inventory

Sometimes when I'm in a town, cave, or dungeon, the controls will be unresponsive, and my FPS will drop to 8, but will eventually slingshot me forwards an extreme distance, often clipping through walls in the process. I don't know how to replicate that one.

Expected behavior:
Card images display, enemies drop loot, interacting with gold piles, mana shards, etc will add the items, shops can be entered, and the Landscape Sketchbook will be usable in some capacity 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A25 5G
 - OS: Android 14
 - Browser: I think Chrome? I'm using the app.
 - Version v.2.0.00-SNAPSHOT-10.25

**Additional context**

**Comment by kevlahnota** [comment]
Duplicate #6429

**Comment by kevlahnota** [comment]
- fixed by #6431
