### ISSUE TITLE
Artwork for 4/4 Elemental Token not showing

### ISSUE THREAD

**Issue by Capamerica805** [Card-Forge/forge#6432]
Using Zaffai the Thunder Conductor i can't seem to get the token artwork to show. 

![image](https://github.com/user-attachments/assets/4fc4bbf8-1165-4aa9-88b2-a45ec178023c)

**Comment by paulsnoops** [comment]
The token for Zaffai doesn't exist so there's no artwork to show. See here for C21 tokens: https://scryfall.com/sets/tc21

**Comment by Capamerica805** [comment]
> The token for Zaffai doesn't exist so there's no artwork to show. See here for C21 tokens: https://scryfall.com/sets/tc21 You could use the one from CMM though: https://scryfall.com/card/tcmm/37/elemental Name it: ur_4_4_elemental_c21

Thank you.  That worked perfectly!
