### ISSUE TITLE
Tameshi didn't trigger

### ISSUE THREAD

**Issue by dwetuski** [Card-Forge/forge#6441]
**Describe the bug**
Tameshi, Reality Architect didn't trigger a card draw in response to Echo Tracer returning the AI's Warden of the Woods to hand.  The only other action taken that turn was me playing an Island.

**To Reproduce**
1. Have Tameshi, Reality Architect and a face-down Echo Tracer in your battlefield and a Warden of the Woods in the opponent's.
2. Use Echo Tracer's morph to turn it face up.
3. Target Warden of the Woods with Echo Tracer's triggered ability.
4. Resolve Warden's and Tracer's triggered abilities.
5. Tameshi's ability doesn't trigger.

**Expected behavior**
5. Tameshi's ability does trigger.

**Version Info**
Forge v.1.6.64 (forge.GuiDesktop@10163d6)
Linux (6.5.0-valve22-1-neptune-65-g9a338ed8a75e amd64)
Oracle Corporation (Java 1.8.0_421-b09, Java HotSpot(TM) 64-Bit Server VM)

**Comment by tool4ever** [comment]
Why do you think Tameshi should trigger from a creature when the event is limited to nonCreature only?

**Comment by dwetuski** [comment]
I don't; I just somehow missed that detail even after rereading the ability text multiple times to make sure I wasn't overlooking anything.  I guess I was a lot more tired than I realized.  Thanks for clearing up my misunderstanding, and I'm sorry for wasting your time.
