### ISSUE TITLE
Android - Adventure mode - data restore error

### ISSUE THREAD

**Issue by daddy32** [Card-Forge/forge#6465]
**Describe the bug**
Error message displayed when trying to restore the data previously backed up data after device reset.

**To Reproduce**
1. Export Adventure data
2. Reinstall whole phone and the app
3. Try to import the data

**Expected behavior**
Save games imported successfully OR details of the error given.

**Screenshots**
![Screenshot_2024-10-29-19-36-16-996_forge app](https://github.com/user-attachments/assets/7e5ead88-0f9d-4b0e-bbc2-de45a6140a38)

**Smartphone (please complete the following information):**
 - Device: Xiaomi 14
 - OS: HyperOS by Xiaomi.eu - Android 14
 - Version v2.0 snapshot 10.29

**Additional context**
I'm attaching the file in question.
[forge.zip](https://github.com/user-attachments/files/17561686/forge.zip)

**Comment by kevlahnota** [comment]
on your phone settings, try to enable all file access for forge

**Comment by daddy32** [comment]
I have tried to allow all storage related permissions I have found in the settings - see screenshots - but the error persists :(
![IMG_20241030_114041](https://github.com/user-attachments/assets/26e019e6-f932-471a-bb5f-584faa8f7203)
![Screenshot_2024-10-30-09-38-51-767_com miui securitycenter](https://github.com/user-attachments/assets/15b5bbf1-7e19-471a-8ee9-192b1f680634)
![Screenshot_2024-10-30-09-23-07-583_com miui securitycenter-edit](https://github.com/user-attachments/assets/9f92572f-af3b-4bbd-bfc6-9ddd3c5b6d28)

**Comment by daddy32** [comment]
But you are probably right and this is a permission issue - i found this in system logs: 
![Screenshot_2024-10-30-11-54-20-079_scd lcex-edit](https://github.com/user-attachments/assets/6f356f44-a640-4dd4-9cc6-be7eeab1664e)

But I managed to import the file in the end by:
- exporting the data first
- replacing the exported file with my previous backup
- importing the data

So, my problem is resolved, but there may be deeper permission issue in the implementation.

**Comment by kevlahnota** [comment]
@daddy32 something like this:
![Screenshot_2024-10-30-21-59-15-08_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/cd264af9-3a78-499e-9e5e-d2692a323ac2)

**Comment by daddy32** [comment]
Looks like that works!
Thank you for your help.

**Comment by Rhisun** [comment]
> @daddy32 something like this: 


I have this same issue but all permissions are enabled. I've had the issue repeat twice now in different saves- there is a different issue that causes my app to hang/crash, and then the save will no longer load again once it happens

**Comment by Rhisun** [comment]
It triggers for me when entering locations from the overworld

**Comment by kevlahnota** [comment]
> It triggers for me when entering locations from the overworld

I don't think your issue is related to storage permission. Better to open a new issue and try to give more details so the dev that updates adventure mode can see it.
