### ISSUE TITLE
Stuck in Emrakul's castle

### ISSUE THREAD

**Issue by Rhisun** [Card-Forge/forge#6485]
After entering Emrakul's castle, player is unable to go anywhere else. Leaving reloads the same location. Exiting to world map reloads the same location.  Reloading the save reloads the same location. After app is restarted, leaving the current town loads Emrakul's castle again. 

**To Reproduce**

**Expected behavior**
Player should be able to leave 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy A71 5g
 - OS: android 10
![Screenshot_20241031_113252_Forge](https://github.com/user-attachments/assets/5dd7fb6a-3e8a-4662-8a90-7dedb39072b2)

**Comment by kevlahnota** [comment]
hmmm can you share the save file? also if you have depeleted your health it doesn't go back in the center of worldstage?
