### ISSUE TITLE
Arena "Jump in" Packs added for JUmpstart tourrnament variety or start variety

### ISSUE THREAD

**Issue by RyushoYosei** [Card-Forge/forge#6505]
Just thinking, that To add more jumpstart variety, should add the various custom "JUmp in" ones that are from Arena, which are basically just jumpstart packs, but also, maybe could see about adding a way to people to add custom Jumpstart  cube/sets, if they wish so they could add more variety for such.

**Comment by Agetian** [comment]
Is there a detailed definition for the contents of these packs available anywhere? I checked some sources and only found vague-ish descriptions that describe which rares can be found in them and also the overall description of the theme, but not which cards belong to each theme.

**Comment by RyushoYosei** [comment]
I'm sure I had seen lists somewhere, and people who potentially have put them out on Tabletop simulator for some of its groupings, but Let me check a bit more,

**Comment by RyushoYosei** [comment]
I did find this, which is for the Bloomburrow added Jump in packs it says, https://magic.wizards.com/en/news/mtg-arena/jump-in-packets-update-for-bloomburrow

**Comment by RyushoYosei** [comment]
Also looks like they have done that for most of them I see it for some others too. Looking at it, It's thee 12 cards, not counting the 8 lands that it would add, and then the special cards are the chances that One of each pairring might be replacing another card in the pack from what i get from that, but looking for more information.

**Comment by RyushoYosei** [comment]
There was No reply from those in charge abvout this, t hats why it was stale, Re-opening for the sake of checking

**Comment by RyushoYosei** [comment]
> Is there a detailed definition for the contents of these packs available anywhere? I checked some sources and only found vague-ish descriptions that describe which rares can be found in them and also the overall description of the theme, but not which cards belong to each theme.

I linked such, but seems it closed the issue.
