### ISSUE TITLE
Unable to Load save

### ISSUE THREAD

**Issue by Rhisun** [Card-Forge/forge#6518]
**Describe the bug**
The game stalls infinitely when entering some locations. After restarting,  save will no longer load from menu (loops back to main menu). Selecting any load or continue option produces the same result, as well as new game +. Only new games will load to world map. If a new game is started, issue reproduces within first 50 locations traveled to. 

**To Reproduce**
1. Go to any location that causes the game to freeze from world map

**Expected behavior**
Should be able to continue previous saves

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy a71 5G
 - OS: android 10
![Screenshot_20241102_140730_Forge](https://github.com/user-attachments/assets/181efe7c-d529-4065-bfdb-f3197988de3b)

**Comment by kevlahnota** [comment]
@Rhisun  can you share your save? or click data, backup then after it finishes, attach the forge.adv from your downloads directory here.

**Comment by Rhisun** [comment]
[Uploading forge.zip…]()

**Comment by Rhisun** [comment]
[forge.zip](https://github.com/user-attachments/files/17608875/forge.zip)

**Comment by kevlahnota** [comment]
@Rhisun  Ok I tested your save and it seems your auto save is corrupted (EOF Exception, it didn't save properly) upon loading it. However your Save slot 1 and Save slot 2 loads fine. Do you know which location crashes? do you have screenshot of location? Just indicate if its on save 1 or save 2 file, I want to reproduce the crash. 

https://github.com/user-attachments/assets/1b6ddd06-0653-4bdb-931c-33c1606e5af0

**Comment by Rhisun** [comment]
They're increments of the same save file- I think the last time was in swamp biome. But the save fork exists because I had the issue twice in separate playthroughs today.  I've reproduced the issue about 6 different times in the last week though, and I'm not sure if it existed before the snapshot update around then. 

Anyway I'd try the second
