### ISSUE TITLE
AI: add Logic for ClassLevelUp

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#6531]
AI need logic / flags for when it should use the Mana for this

For Example: `Caretaker's Talent`
```
{W}: Level 2

When this Class becomes level 2, create a token that’s a copy of target token you control.

{3}{W}: Level 3

Creature tokens you control get +2/+2.
```

AI need to first check for Trigger, like `When this Class becomes level` and see if it would be beneficial (if it controls tokens)

Then it might need some Other AI Flags, like don't update to Level 3 if it doesn't control any creatures

**Comment by Agetian** [comment]
Hmm, an interesting, though not a very straightforward/easy thing to do :) I'll see if I can figure it out closer to the weekend unless someone is faster :)

**Comment by Hanmac** [comment]
yeah, i will see what kind of AI parameters i could add to this
