### ISSUE TITLE
Rev, Tithe Extractor's ability is not working.

### ISSUE THREAD

**Issue by stormcat664** [Card-Forge/forge#6571]
**Describe the bug**
Cards exiled by Rev's ability cannot be cast.

**To Reproduce**
1. Triggered Rev's ability and exile cards.
2. Click the exiled card
3. I can't cast it.

**Expected behavior**
I can cast it.

**Comment by Hanmac** [comment]
Did you disable "performance mode"?

**Comment by stormcat664** [comment]
I restarted forge and it worked.
