### ISSUE TITLE
Strange interaction when cloning XX cost card

### ISSUE THREAD

**Issue by P-rus** [Card-Forge/forge#6573]
A rare occurrence as there is only 1 x cost clone spell, but if you clone any XX creature using Altered Ego and you add X to the cost, the creature enters with double the +1/+1 counters.  I have done this twice with Sporocyst and Altered Ego.

-Have Sporocyst (XXG) in play
-Cast Altered Ego (X2UG) FOR 4
-Result eight +1/+1 counters

**Comment by Hanmac** [comment]
@tool4ever the problem seems to be the `Ravenous` Keyword
