### ISSUE TITLE
Bottom part of screen covered by navigation buttons on Android 15

### ISSUE THREAD

**Issue by chrismacr** [Card-Forge/forge#6581]
The nav bar at the bottom of the screen is covering part of the game ui. It also happens when I switch the nav bar to gesture mode.

This did not happen on Android 14.

**Screenshots**
![Screenshot_20241115-165648](https://github.com/user-attachments/assets/85e4dd97-16c5-46c5-a409-9ae6de760e8a)

![Screenshot_20241115-165817](https://github.com/user-attachments/assets/cd48042e-49b9-478b-bc4f-d950cc9fbc80)

 - Device: Pixel 7a
 - OS: Android 15
 - Version: version 2.0.00-SNAPSHOT-11.15

Thanks.

**Comment by kevlahnota** [comment]
Should be fixed on 11.17, can you redownload @chrismacr

**Comment by chrismacr** [comment]
I can confirm the issue is fixed.

Thank you for taking the time to look into this!
