### ISSUE TITLE
Room abilities trigger without room being on battlefield.

### ISSUE THREAD

**Issue by biggzlar** [Card-Forge/forge#6582]
**Describe the bug**
It appears some room abilities are active without the room being on the battlefield.

**To Reproduce**
Can quickly be reproduced by playing against the "Jump Scare!" precon in commander mode. As soon as a face-down creature deals damage to a player, the room ability of "Staff Room" will trigger.

**Expected behavior**
Room abilities should of course only trigger when the room is actually on the battlefield and unlocked.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 15.1

**Comment by tool4ever** [comment]
Already fixed by 8f7b782
