### ISSUE TITLE
Possible fix? for Adventure mode and Linux crashes

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#6584]
**Describe the bug**
So, I saw @kevlahnota's suggestion in the Forge discord about deleting the **SplashScreen-Image:** line in the MANIFEST.MF file and it _seems_ to have worked. I am now able to succesfully run the `forge-adventure.sh` and have it load all the way to the main menu. It did go a bit slow, but it loaded without crashing, so I count that as a win.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Forge Version: forge-installer-2.0.00-SNAPSHOT-11.14

**Comment by kevlahnota** [comment]
@TheLastNarwhal before you edit the manifest.mf does the crash occurs before the splash screen or after the splash screen is closed?

**Comment by TheLastNarwhal** [comment]
@kevlahnota

It would crash at different times. The first time I reported the issue it would crash shortly after the splash screen appeared, now on the latest snapshot it crashes on the "Finishing startup" section of the loading. So, it does get past the the splash, but it will still crash with: 

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000071b6dc497ef4, pid=25745, tid=25746
#
# JRE version: OpenJDK Runtime Environment (17.0.13+11) (build 17.0.13+11-Ubuntu-2ubuntu122.04)
# Java VM: OpenJDK 64-Bit Server VM (17.0.13+11-Ubuntu-2ubuntu122.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x97ef4]  pthread_mutex_lock+0x4
```

However, if I make the change you suggested it will skip the splash screen and load all the way through the "Finishing startup" and into the main menu.

**Comment by TheLastNarwhal** [comment]
If it helps at all, when running it through the terminal it seems to crash at the **ui/vs.png** everytime.

```
(ThreadUtil first call): Running on a machine with 8 cpu core(s)
Forge v.2.0.00-SNAPSHOT-11.17 (forge.GuiMobile@2a6e774)
Linux (6.8.0-48-generic amd64)
Ubuntu (Java 17.0.13+11-Ubuntu-2ubuntu122.04, OpenJDK 64-Bit Server VM)
Language 'en-US' loaded successfully.
Read cards: 29635 archived files in 1323 ms (25 parts) using thread pool
Upcoming set Aetherdrift (DFT) dated in the future. All unaccounted cards will be added to this set with unknown rarity.
Upcoming set Aetherdrift (DFT) dated in the future. All unaccounted cards will be added to this set with unknown rarity.
Read cards: 723 files in 14 ms (7 parts) using thread pool
Looking for resource ui/transition.png... Found!
Looking for resource ui/title_bg.png... Found!
Looking for resource ui/vs.png... Found!
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000072caf3297ef4, pid=24891, tid=24892

```

**Comment by kevlahnota** [comment]
I think I'll disable closing the splash screen on linux, I wonder why it works on windows though...
