### ISSUE TITLE
Unable to change directory.

### ISSUE THREAD

**Issue by SlayerV546** [Card-Forge/forge#6586]
**Describe the bug**
Hello, I'm trying to get the ForgeData out of my AppData/C Drive but no matter what I'm trying it is not working.
I followed the instructions in the forge.profile.properties file but it still does not work.
(https://github.com/riking/mtg-forge/blob/master/forge-gui/forge.profile.properties.example)

**To Reproduce**
Open forge.profile.properties
Edit any path, for example change "userDir=" to "userDir=D:/ForgeData" save and close forge.profile.properties.
Launch forge.exe
Forge still uses the default AppData directory.

**Expected behavior**
I expected forge to use the "userDir=D:/ForgeData" path as set it the file. The path "userDir=D:/ForgeData" is the example given in the file, it should work.

**Screenshots**
I'll attach a screenshot of my  forge.profile.properties file

![Forge001](https://github.com/user-attachments/assets/ee59cdeb-e969-4a5e-ab4b-ecbeb69a2af7)

**Desktop (please complete the following information):**
-Win10
-Mullvad
-latest

**Comment by niceandgoodonline** [comment]
does `D:/ForgeData` exist?

does your current user have read/write permissions for `D:\ForgeData`? 

have you tried other settings overrides to make sure this file is being used by forge?

**Comment by SlayerV546** [comment]
Hello and thank you for your reply.

Yes, D:/ForgeData does exist. I also tried C:/ForgeData and E:/ForgeData, no luck.

My PC has only one user and that's the admin user. So I guess, I have permission to read/write stuff.

I have no idea, how to even test if this file is used by Forge. I tried other settings but nothing did anything.
I don't know why something like this has to be so cryptic, the first thing Forge should ask is where to store all the files.

**Comment by SlayerV546** [comment]
> does `D:/ForgeData` exist?
> 
> does your current user have read/write permissions for `D:\ForgeData`?
> 
> have you tried other settings overrides to make sure this file is being used by forge?

Jesus Christ, I fixed it, it's working now and I feel so stupid.

In the windows 10 folder settings,  there's an option for "Hide extensions for known file types" and if that box is checked "forge.profile.properties.example" shows up as "forge.profile.properties" in the folder.

I downloaded to latest version, unpacked it and was like "why is the properties file already renamed???" but it was just because the .example was hidden..
