### ISSUE TITLE
X cannot be paid from graveyard when a card gains flashback

### ISSUE THREAD

**Issue by P-rus** [Card-Forge/forge#6597]
As written.  Just use Snapcaster Mage or something similar to grant anything with X in the cost (e. g. Commander's Insight) flashback.

Alternative costs cannot be paid with flashback, but X costs can.

**Comment by tool4ever** [comment]
@Hanmac
can you reproduce it?

**Comment by Hanmac** [comment]
@tool4ever i haven't tested it yet, i just assigned the Issue
