### ISSUE TITLE
"Error in keyword" exception for cards with Miracle (Forge v2.0)

### ISSUE THREAD

**Issue by humra** [Card-Forge/forge#6676]
**Describe the bug**
Happens for cards that have a Miracle keyword (for example Metamorphosis Fanatic or Devastation tide).
When the card is trying to be found or played the following error appears:
java.lang.RuntimeException: Error in Keyword Miracle:1 B for card <card name>

The bug appears when the card is drawn from the deck while playing.
Furthermore, if the card is searched for in deck editor or card browser, forge will throw the exception mentioned above. The browser will also break on trying to show the card, causing general UI issues.

**To Reproduce**
1. Go to 'Card Catalog'
2. In search type in a card with miracle keyword (for example Devastation Tide)
3. Scroll down to where the card should appear (sorcery section in my example)
5. Open forge.log to find full error details

**Expected behavior**
A card with miracle keyword appears and is usable in card catalog, deck, and similar.

**Screenshots**
Won't let me scroll below or above the following parts:
![javaw_XJvF0SXCBu](https://github.com/user-attachments/assets/7df443b5-5bf6-4634-aab6-079f2b3f0fb5)
![javaw_ZIFWqjpeKH](https://github.com/user-attachments/assets/f269f449-d196-4fa1-8a3f-c8bf48b3a568)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 11

**Comment by Hanmac** [comment]
You need to update to Snapshot

the bug was introduced in https://github.com/Card-Forge/forge/commit/212f14063e0f93e386bbec5d09eb145e72ca8c74
but fixed in https://github.com/Card-Forge/forge/commit/3e5a728646b7bd55aa7c37e12fc8ebdd2423d97b
