### ISSUE TITLE
Recent ETB Changes causes problems with LKI

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#668]
This Section there by #663 causes problems:

https://github.com/Card-Forge/forge/blob/master/forge-game/src/main/java/forge/game/ability/AbilityUtils.java#L223-L225

Without the setting for LKI the test fails, but in game it works as it should
With the setting for LKI the tests pass, but in game it becomes broken

Can one of you guys check what should be done there? @Agetian  @tool4ever @Northmoc 
somehow fix the tests?

**Comment by tool4ever** [comment]
This one is also caused by the same PR but not fixed by that line:

![image](https://user-images.githubusercontent.com/8506892/173248330-e5b0035b-5461-43ac-8efe-ad055a9b4168.png)

**Comment by Hanmac** [comment]
the trigger is probably something else to be fixed too, it should only indirect related to this issue

**Comment by kevlahnota** [comment]
> This one is also caused by the same PR but not fixed by that line:
> 
> ![image](https://user-images.githubusercontent.com/8506892/173248330-e5b0035b-5461-43ac-8efe-ad055a9b4168.png)

I pushed 613 snaps that reverts #663 on my branch, so users will stop spamming the etb issue on discord. Gonna update future snaps until this is resolved.

**Comment by Hanmac** [comment]
i also need to check if this part is still valid, and if it is maybe it can be done better:

```
if (toBattlefield && !copied.getEtbCounters().isEmpty()) {
    for (final ReplacementEffect re : copied.getReplacementEffects()) {
       re.setSuppressed(true);
    }
}
```

**Comment by Hanmac** [comment]
fixed the bugs for now

but there might be some corner cases when there is something like Grumgully that does additional +1/+1 counters
and then two Corpsejack Menace (what replaces the amount of counters are put onto it) enter at the same time.

the corner case there would be that they only be affected by themselves (i think) and not the other Corpsejack Menace.

**Comment by Hanmac** [comment]
> i also need to check if this part is still valid, and if it is maybe it can be done better:
> 
> ```java
> if (toBattlefield && !copied.getEtbCounters().isEmpty()) {
>     for (final ReplacementEffect re : copied.getReplacementEffects()) {
>        re.setSuppressed(true);
>     }
> }
> ```
> 
> i tested it with this line enabled or disabled, it doesn't seems to have a difference

I finally found the corner case i have been looking for, because i was only testing it with Mowu, Loyal Companion:
> Mowu, Loyal Companion
> Because Mowu’s replacement effect affects only Mowu, it will apply if Mowu somehow enters the battlefield with one or more +1/+1 counters on it and give Mowu an additional +1/+1 counter. 

This one should apply

> Conclave Mentor
> Conclave Mentor’s first ability doesn’t apply to itself if it’s somehow entering the battlefield with a +1/+1 counter on it. 

This should not

> Winding Constrictor
> Winding Constrictor’s effect can’t apply to itself as it’s entering the battlefield or to any other permanent entering the battlefield at the same time as it.

This also not

for this, the PutCounter Replacement needs to check if it is ETB Counters, and then needs to check lastStateBattlefield stuff

**Comment by tool4ever** [comment]
@Hanmac 
can this be closed?

**Comment by Hanmac** [comment]
closed for now
