### ISSUE TITLE
ulamog the defiler issue.

### ISSUE THREAD

**Issue by Siegeglasgow** [Card-Forge/forge#6705]
**Describe the bug**
When ulamog the defiler is cast from exile he should see himself and get 10 1+1 counters but currently is not seeing himself.
**To Reproduce**

**Expected behavior**
he should see the cmc card of himself if nothing is bigger than him and get 10 counters. 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image (2)](https://github.com/user-attachments/assets/a09bdb1e-d8a3-4d7d-a263-844db950d200)
![image (3)](https://github.com/user-attachments/assets/02d57951-3681-4ed8-bf9b-2488448591ff)

**Comment by tool4ever** [comment]
That's not how it works:
when you cast him he enters from stack.

**Comment by Siegeglasgow** [comment]
![image (4)](https://github.com/user-attachments/assets/098ca374-c471-4a14-a238-ecdaf976c1a8)

scryfall says that if he enters from exile he will see himself. please dont close my thread when it says so
