### ISSUE TITLE
Doubling season + Serrated arrows issue. 

### ISSUE THREAD

**Issue by leeterry** [Card-Forge/forge#6708]
![screenshot](https://github.com/user-attachments/assets/733f0112-4672-4686-846d-0d434965e1ab)
I was playing against AI and I had doubling season out. AI played Serrated arrows with my doubling season out, but it only got 3 tokens. Doubling season should have doubled it and the negative counters it provides (I will myself now, but thought should send this 1st just in case). In the screenshot you will clearly see a log on the top left and the top of that without scrolling up (you can not do anyway) is when he casts the artifact. The AI uses it right away as you can see, but that only removes 1 counter and so that can not be the issue and I took the screenshot in the beginning of my turn (after the AI finished). The only logical thing I can think of based on how many counters the card has currently after only being used once is the program forgetting Doubling season works for any tokens/counters regardless who played/owned the card if/when it is in play.

**Comment by tool4ever** [comment]
The replacement effect of _Doubling Season_ is clearly restricted to "a permanent you control".
Nothing seems broken here.
