### ISSUE TITLE
HBG Specialize mechanic

### ISSUE THREAD

**Issue by paulsnoops** [Card-Forge/forge#763]

**Comment by Hanmac** [comment]
i Would try to make it via Clone States that this sets new copyable values

i just need to check that it doesn't mess with ColorIdentity

**Comment by Hanmac** [comment]
Specialize + Brawl Commander:
![Specialize_commander_color_Brawl_MTGA](https://user-images.githubusercontent.com/225553/179496789-95ba4b5f-323a-4133-8677-4f14d7b23058.png)

**Comment by paulsnoops** [comment]
Closed by #1330
