### ISSUE TITLE
YCLB Boon mechanic

### ISSUE THREAD

**Issue by paulsnoops** [Card-Forge/forge#765]

**Comment by Hanmac** [comment]
Boon shouldn't be needed, we just keep our delayed trigger that aren't visable

**Comment by paulsnoops** [comment]
Agreed. Made this issue for those more knowlegable to decide. Will close.

**Comment by Northmoc** [comment]
Uh oh, I didn't see this and worked up a draft

**Comment by Northmoc** [comment]
Might be nice to have it in the command zone with other effects / emblems

**Comment by Hanmac** [comment]
> Might be nice to have it in the command zone with other effects / emblems

I don't like that, command zone is already over boarded
