### ISSUE TITLE
android build

### ISSUE THREAD

**Issue by CCTV-1** [Card-Forge/forge#80]
After tags `1.6.49`,I can‘t build `forge-gui-android`. error message:
```
[INFO] --- android-maven-plugin:4.6.0:d8 (default-d8) @ forge-gui-android ---
[INFO] Convert classes to Dex : /home/CCTV-1/forge/forge-gui-android/target
[INFO] Error: Unable to access jarfile /home/CCTV-1/Android/Sdk/build-tools/26.0.1/lib/d8.jar
```

have undocumented changes for android build requirement?

**Comment by kevlahnota** [comment]
use build-tools 30.0.3, then edit d8.jar to add the manifest header or compile android maven plugin 4.6.1.SNAPSHOT and use it to compile without problems

**Comment by CCTV-1** [comment]
> use build-tools 30.0.3, then edit d8.jar to add the manifest header or compile android maven plugin 4.6.1.SNAPSHOT and use it to compile without problems

install build-tools 30.0,can build. I think we should update android build doc in readme and wiki.
