### ISSUE TITLE
Bane, Lord of Darkness

### ISSUE THREAD

**Issue by paulsnoops** [Card-Forge/forge#812]

**Comment by xaviermd** [comment]
Just in case anyone is eyeing this one: I have already written and tested a script for it. :) I'm not a contributor yet, but, as soon as I'm added, I will gladly assign myself this ticket, upload my card script for review, and hopefully eventually merge it.

**Comment by xaviermd** [comment]
Just in case anyone is eyeing this one: I have already written and tested a script for it. :) I'm not a contributor yet, but, as soon as I'm added, I will gladly assign myself this ticket, upload my card script for review, and hopefully eventually merge it.
