### ISSUE TITLE
Myrkul, Lord Of Bones Doesn't Trigger on Animated Planeswalkers

### ISSUE THREAD

**Issue by xion1992** [Card-Forge/forge#982]
**Describe the bug**
When a planeswalker is animated as a creature and dies (Discovered it with Kaya the Inexorable animated with Luxior) Myrkul does not trigger.

**To Reproduce**
1. Have Myrkul on the field
2. Have a Planeswalker on the field (In this case Kaya the Inexorable)
3. Have a sac outlet on the field (In this case Phyrexian Altar)
4. Have Luxior, Giada's Gift on the field and attached to Planeswalker
5. Sacrifice Planeswalker

**Expected behavior**
Myrkul triggers, allowing you to exile the animated planeswalker and create a token copy that is an enchatment and loses all other card types. It does not enter with any loyalty counters on it but can still activate loyalty abilities to add counters.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.54-SNAPSHOT 22-Jun-2022 13:24

**Comment by tool4ever** [comment]
Hmn, the problem seems to be that CostSacrifice reuses LastState

So if you Equip and then sac directly after it's not refreshed (yet) - or rather `copyLastState` is called when `resolveStack()` finishes but the Luxior static wasn't applied at that point already
