### ISSUE TITLE
Blitz again

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#990]
Jess messed up some of the rules, and now the Blitz Static is linked to the Permanent being cast with that specific Blitz Cost.

My Current Problem there:
* i added `CardTraitBase#keyword` this value is set when an ability is added to the Keyword.
* Also CardProperty gets `castWithKeyword` that checks if `CastSA.keyword == staticAbility.keyword`
* My Problem now is that for Toolbox, the CastSA comes from a Keyword which was added to an LKI before the Card was put on the Stack.
* for this to fix: i would probably need to manipulate `Card.storedKeywords` so when the Card is moved to the Stack, i add this specific Keyword to the storage.
* So when Toolbox tries to add the Keyword again, it doesn't create a new KeywordInstance

**Comment by tool4ever** [comment]
Closed by #1001
