### ISSUE TITLE
Strixhaven 371 displayed as 370 and 373 displayed as 372

### ISSUE THREAD

**Issue by chesse20** [Card-Forge/forge#991]
![image](https://user-images.githubusercontent.com/9161779/175493393-0ec533b2-e0cb-4616-8a2b-907c557504bc.png)
![image](https://user-images.githubusercontent.com/9161779/175493441-148ae345-528f-40be-8a07-bdc9dbfc342c.png)
game is downloading the wrong images for both of these cards and idk

**Comment by paulsnoops** [comment]
The user would need to delete the images and retry downloading. The images on the FTP and on Scryfall are in the correct order. The edition file is also correct. Closing this. Please re-open if the issues persists.
